### ISSUE TITLE
Add .kpf extension to Open File dialog

### ISSUE THREAD

**Issue by XaserAcheron** [sirjuddington/SLADE#1001]
**SLADE Version**: 3.1.4
**Operating System**: Any

**Issue Details**:
Got a small feature request: Kex (Kaiser's engine that powers Turok, Forsaken Remastered, et.al) uses zip/pk3 as its data file format, only with the extension ".kpf" (for "Kex Pack File," I believe). Would y'all mind adding .kpf to the list of known filetypes to the Open File dialog? Right now it's a bit tricky to open them since the files don't appear in the Browse dialog.

**Comment by sirjuddington** [comment]
Ok that is simple enough. If you can't wait until 3.1.5 is released it's a pretty simple change to `config/archive_formats.cfg` in slade.pk3: https://github.com/sirjuddington/SLADE/commit/2148841c692b5d32516b08162fb0288dde6158d5

**Comment by XaserAcheron** [comment]
Cool, thanks! Didn't even think to open up slade.pk3 for things -- though that'd be a bit like hacking gzdoom.pk3 to add an IWAD. :P
