### ISSUE TITLE
Issues displaying Path if it is too long

### ISSUE THREAD

**Issue by Frozsoul2019** [sirjuddington/SLADE#1015]
**SLADE Version**: (3.1.4)
**Operating System**: (Windows)

**Issue Details**:
If the Path of a particular folder is too long, the Path text will display beyond the "up one folder" button, which makes it difficult to tell what the current folder is (it will be obscured by this button) and also makes using this button much more difficult (have to place the mouse cursor at the very top or bottom of the button in order to use it).  Recommend that if displaying the full path of a particular folder will overlap with the "up one folder" button, then the starting characters of the path are replaced as necessary with an ellipsis "..."

The following is an example that demonstrates this issue:
![image](https://user-images.githubusercontent.com/41276432/50724615-96b84480-10be-11e9-9ab2-d588aec6b5a2.png)

In this case, if the Path for this particular folder was instead displayed as:
.../SPRITES/WEAPONS/Slot 1/Chainsaw/BackAttack

This would resolve the issue.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/60312856-93da3600-9922-11e9-836a-54dc5a41a2d1.png)
I was just about to report this same issue with 3.1.5.
