### ISSUE TITLE
Editing PNAMES in SLADE then Saving causes PNAMES to be "Unknown Type"

### ISSUE THREAD

**Issue by busybeaverhp** [sirjuddington/SLADE#1017]
**SLADE Version**: (3.1.4)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
![image](https://user-images.githubusercontent.com/23037996/50743075-1f6ed780-11c8-11e9-970d-cba826240b6a.png)
I deleted a row in PNAMES, and saved the change...

![image](https://user-images.githubusercontent.com/23037996/50743083-3a414c00-11c8-11e9-8246-0d78e5e90252.png)
... and now PNAMES is not recognized.

Futher discussion on DWF: https://www.doomworld.com/forum/topic/103809-editing-pnames-in-slade-then-saving-causes-pnames-to-be-unknown-type/?tab=comments#comment-1951967

**Comment by Gaerzi** [comment]
I'll add that there should probably be a warning about direct PNAMES modifications and a recommendation to go through the texture editor unless you really know what you're doing.
