### ISSUE TITLE
Tabs won't save to archive if multiple SLADE apps are open

### ISSUE THREAD

**Issue by paynworth** [sirjuddington/SLADE#1023]
**SLADE Version**: (3.1.4)
**Operating System**: (Linux)

When I click the save button on a text lump opened in another tab, it won't save to the parent archive if there are multiple SLADE apps open.

**Comment by paynworth** [comment]
Edit: It seems to happen occasionally, but not always.

**Comment by sirjuddington** [comment]
I can't reproduce this one, what save button do you mean, the one for the entry or the one to save the archive in the main toolbar?

Also note that having multiple instances of SLADE open can cause issues so it's not really recommended

**Comment by paynworth** [comment]
I haven't used Slade in a while, but I think it was just confusion from me having multiple entries open and forgetting to save the individual tabs before saving the main archive.
