### ISSUE TITLE
Support for Descent Data files

### ISSUE THREAD

**Issue by Marcaek** [sirjuddington/SLADE#1026]
Tools for accessing Descent resources contained in HOG and PIG files are limited to DTX, which only works on ancient versions of Windows, and XWE which doesn't seem to work at all. It would be helpful for those seeking to extract assets from the game if SLADE replaced these tools.

**Comment by sirjuddington** [comment]
Descent archives (Hog etc.) and resources should already be supported as far as I know, unless something broke since they were implemented.
