### ISSUE TITLE
Color Remap Window Sizing On 1344x768 Resolution

### ISSUE THREAD

**Issue by BLOODWOLF333** [sirjuddington/SLADE#1031]
**Environment**
Slade 3.1.4
Windows 8.1 64-bit

**Issue Details**
![image](https://user-images.githubusercontent.com/16950832/53305535-36d15500-3848-11e9-9697-075ef45ba6bf.png)

With my laptop that has a 1344x768 resolution the color remap pop-up window starting size is too large and cannot rescale it since the top is off the screen and bottom is behind the taskbar.  I know I might just have a funky resolution because I encounter this a lot with other programs like Doom Builder but, still.

**Comment by Gaerzi** [comment]
One way I could see of addressing that would be to optionally split off the "Resulting Palette" and "Preview" widgets to a separate, non-modal window.

**Comment by sirjuddington** [comment]
SLADE really isn't designed for such a small effective resolution (it doesn't help that your DPI is set above 100%), though that dialog could be rearranged a bit I guess, it is by far the largest in terms of minimum size.

Another option might be to make the 'resulting palette' the same width/height as the other palettes above, and the preview image smaller.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/55280955-e6dc2700-52fa-11e9-8638-e6c6b72afc1d.png)
Googled it and then set my DPI to 100% and that is much better.  I don't know why this Windows 8.1 laptop was default at 125% but, that fixed my issue.  Thank you guys and I really enjoy this program and have been using it every night for the past two weeks getting XV117's Monster Expansion pack to work with Brutal Doom v21rc8.

**Comment by Gaerzi** [comment]
> Another option might be to make the 'resulting palette' the same width/height as the other palettes above, and the preview image smaller.

I often wished I could zoom on it, so a resizable non-modal window seems a better approach.

**Comment by BLOODWOLF333** [comment]
this has been resolved, user DPI setting was too high
