### ISSUE TITLE
Mac OS 10.14 in Dark Mode makes Slade interface very hard to read

### ISSUE THREAD

**Issue by objorling** [sirjuddington/SLADE#1032]
**SLADE Version**: 3.1.3 (There is no 3.1.4 download for macOS!)
**Operating System**: MacOS 10.14.3

**Issue Details**:
In MacOS "Dark Mode", text is white on a dark gray. Slade obeys the system text color in this mode but not the window background color, leading to white text on a very bright gray which is hard to read.

**Comment by sirjuddington** [comment]
This is an issue with wxWidgets that is fixed in wx3.1.2, however there are some other issues with that version of wx that prevent me from updating to it currently, so it will need to wait until wx 3.1.3 or 3.2.0 is released unfortunately

**Comment by dpkonofa** [comment]
Has there been any update on this? I just downloaded SLADE and it's still nearly impossible to use with the white text on light grey.

**Comment by floverdevel** [comment]
Hi 👋🏻 

I just find out that Apple provides a way to opt out of dark mode.

https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app

> **Opt Out of Dark Mode**
> The system automatically opts in any app linked against the macOS 10.14 or later SDK to both light and dark appearances. If you need extra time to work on your app's Dark Mode support, you can temporarily opt out by including the NSRequiresAquaSystemAppearance key (with a value of true) in your app’s Info.plist file. Setting this key to true causes the system to ignore the user's preference and always apply a light appearance to your app.

In the meantime I found an article that explain how a user can manually opt out of dark mode for any specific app.

https://webtrickz.com/disable-dark-mode-for-specific-app-on-mac

Just by running this command :
`defaults write com.slade NSRequiresAquaSystemAppearance -bool Yes`
