### ISSUE TITLE
double crash

### ISSUE THREAD

**Issue by joshthenesnerd** [sirjuddington/SLADE#1037]
**SLADE Version**: (3.something.err.other. need to go to bed, not opening again tonight)
**Operating System**: (Windows 7)

**Issue Details**:
left the program open in the background for a few hours. and then it crashed while i tried to close it. and then the crash reporter crashed.
![sladecrash](https://user-images.githubusercontent.com/48535253/54319344-a58c0d80-45bf-11e9-854a-c6a5fa2d7617.png)

**Comment by sirjuddington** [comment]
Does this happen with the latest version (3.1.4 currently)?

**Comment by sirjuddington** [comment]
Closing, feel free to repoen if it still happens
