### ISSUE TITLE
SLADE exhibits non-deterministic behavior when exporting assets

### ISSUE THREAD

**Issue by busybeaverhp** [sirjuddington/SLADE#1041]
**SLADE Version**: 3.1.4
**Operating System**: Windows 10

**Issue Details**:
SLADE exhibits non-deterministic behavior when exporting assets

Example: exporting 500 PNG's doesn't always output 500, it's more like 490, 498... only 500 exported 25% of the time.
Something is causing SLADE to skip entries when exporting.
![image](https://user-images.githubusercontent.com/23037996/56107983-18a9dc00-5efe-11e9-9b3c-3a5e0c028f90.png)

**Comment by sirjuddington** [comment]
Hmm I can't reproduce this one, are there any messages in the console log when it happens?

**Comment by sirjuddington** [comment]
Closing this, feel free to reopen if it still happens
