### ISSUE TITLE
Remove unused textures feature not working...?

### ISSUE THREAD

**Issue by PeterMoro** [sirjuddington/SLADE#1044]
**SLADE Version**: (3.14)
**Operating System**: (Windows)

**Issue Details**:
 After clicking remove unused textures, nothing seems to happen. Same for Flats.
Using multiple texture packs for a Doom wad. With all the unused textures included, the wad file is huge. Wad format is UDMF / Doom2. All textures / flats are in PNG format.

**Comment by Gaerzi** [comment]
I think the feature is not implemented yet for UDMF maps, since they are parsed differently from the binary formats.

**Comment by PeterMoro** [comment]
Got it. Well that's a bummer. Thanks for the post.
