### ISSUE TITLE
Interface is broken

### ISSUE THREAD

**Issue by AkitotheHedgy** [sirjuddington/SLADE#1046]
**SLADE Version**: 3.1.4
**Operating System**: Windows

**Issue Details**:
When I open up slade, the starting photo doesn't appear. i thought that was ok, since I didn't use it for a long time, but when it got to the interface, it did not show anything thats supposed to be on the start screen.
this is how it looks.
![SLADE_07Y39b8GSG](https://user-images.githubusercontent.com/50081890/56867631-48a0b700-69b5-11e9-841d-dbbf7107c26e.png)
can somebody explain to me what is going on?

**Comment by sirjuddington** [comment]
(was resolved in discord)
