### ISSUE TITLE
Where are the dev builds?

### ISSUE THREAD

**Issue by igdegoo** [sirjuddington/SLADE#1047]
This isn't a bug in the program but i don't know where to ask

The only devbuilds i can find (http://slade.mancubus.net/dev/build/ and https://devbuilds.drdteam.org/slade/) are very outdated, (april and novemeber 2018 respectively)

are there any up to date ones, and where are they?

**Comment by sirjuddington** [comment]
Those are the latest for now. Not a lot has been done since then until just recently, and I plan on releasing 3.1.5 fairly soon once i've looked at / fixed a few more things

**Comment by igdegoo** [comment]
huh, ok. I thought the devbuilds were made for each commit, guess not
