### ISSUE TITLE
3d edit mode spinns rapidly non stop.

### ISSUE THREAD

**Issue by Erikir** [sirjuddington/SLADE#1048]
SLADE Version: 3.1.3
Operating System: OSX
Issue Details:
The speed changes depending on where i move my mouse. I have tried to put Slade3 in low resolution mode but nothing changes.
What do i do?

**Comment by JadingTsunami** [comment]
Try going to System Preferences -> Security & Privacy -> Accessibility. Click the Lock in the lower left corner to make changes. Find SLADE in the list on the right side that says "Allow the apps below to control your computer", and check the box next to SLADE (if it is checked, uncheck it, click the lock icon, then unlock and re-check it, then click the lock again).

**Comment by matatk** [comment]
I was experiencing this issue with 3.1.9 but since trying 3.1.11 I can't get any version to run on the Mac.

I had tried the low resolution fix when I was using 3.1.9, but it had no effect. I've not yet been able to try the accessibility suggestion.

**Comment by sirjuddington** [comment]
This should hopefully be fixed with #1301
