### ISSUE TITLE
Installed Slade 3.1.5 on OSX High Sierra, reports as version 3.1.3

### ISSUE THREAD

**Issue by jkh0208** [sirjuddington/SLADE#1050]
**SLADE Version**: (3.1.5)
**Operating System**: (OSX)

**Issue Details**:
I installed Slade version 3.1.5 on OSX High Sierra.  Upon opening Slade, it shows that version 3.1.3 is running, and clicking "About Slade" confirms I am running version 3.1.3.  I never installed version 3.1.3 prior to this.
<img width="909" alt="image" src="https://user-images.githubusercontent.com/46360615/58809350-9e7a0780-85d0-11e9-92a0-9e9525f9a236.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/46360615/58809540-ff094480-85d0-11e9-9a5d-09fa6707b51a.png">

**Comment by TolgaDaSilva** [comment]
Same Issue !!
Besides, I can't use it in dark mode.
![grafik](https://user-images.githubusercontent.com/33528315/60462108-b9c84900-9c48-11e9-94ff-5e7566225c0f.png)

**Comment by Calinou** [comment]
I noticed that the [`3.1.5`](https://github.com/sirjuddington/SLADE/tree/3.1.5) tag is still identified as 3.1.4 in the source code. The version number was bumped in the `master` branch though.

**Comment by sirjuddington** [comment]
Unfortunately currently I can't build the macos version, so it's stuck at 3.1.3 until I (or someone else) can. Dark mode support is entirely waiting on wxwidgets 3.1.3, and who knows when that will be released

**Comment by sirjuddington** [comment]
I've removed the macos version from the main download table on the site and put a link to 3.1.3 below for now
