### ISSUE TITLE
Textures are broken on linux at current master

### ISSUE THREAD

**Issue by iirelu** [sirjuddington/SLADE#1059]
![Screenshot from 2019-08-06 08-25-24](https://user-images.githubusercontent.com/3432543/62515843-c3cf0000-b823-11e9-9f92-ede3e461bc01.png)

Not much to show. Anything that's supposed to have a texture is instead just black. Ctrl+T still works.

![image](https://user-images.githubusercontent.com/3432543/62515871-d34e4900-b823-11e9-99c5-d7309b7fcbc3.png)

I tried to bisect down to the commit that introduced this but 95% of the commits on this project don't build on Linux. I've narrowed things down to the 50 commits between ac246f2 (bad) and 2def7b2 (good). No idea how to narrow things down from there.

**Comment by sirjuddington** [comment]
I have no idea what that would be, I can't reproduce it anywhere and really don't know where to even start. Maybe try changing some of the OpenGL options in preferences?

**Comment by sirjuddington** [comment]
Ok, upon further investigation this looks like an issue with UDMF maps, 'lightcolor' is defaulting to black instead of white like it should
