### ISSUE TITLE
Pk4 Support 

### ISSUE THREAD

**Issue by goldenmobster72** [sirjuddington/SLADE#1060]
Will Slade have Pk4 support at some point?

**Comment by Gaerzi** [comment]
What are those?

**Comment by goldenmobster72** [comment]
> What are those?

https://fileinfo.com/extension/pk4

Doom 3 , Quake 4 [IV] , and much more or other games use that as a file type

**Comment by OrdinaryMagician** [comment]
pk4 is just zip with a different extension. it's exactly the same as pk3.

**Comment by Gaerzi** [comment]
So, already supported then. The only thing that might have to be done here would be to add the extension to the already-long list of zip-synonyms.
