### ISSUE TITLE
Color Palettes

### ISSUE THREAD

**Issue by ghost** [sirjuddington/SLADE#1062]
Will the Following Color Palettes be added to Slade later in the future ?
Just curious

Powerslave/Exhumed 
Witchaven [I & II]
Fate 
Legend of the 7 Paladins 
Corridor 8 : Galatic Wars 
Super Noah's Ark 3D

**Comment by Gaerzi** [comment]
They could be. It's a pretty simple pull request to make, if you have these games' palettes in format SLADE uses.
