### ISSUE TITLE
Autocomplete crashes SLADE 3.1.6 64-bit

### ISSUE THREAD

**Issue by SanyaWaffles** [sirjuddington/SLADE#1064]
**SLADE Version**: 3.1.6 64-bit
**Operating System**: Windows

**Issue Details**:
Using shift+enter in Zscript to pull up autocomplete causes the editor to crash. Works fine in SLADE 3.1.5 32-bit

**Comment by Xane123** [comment]
For me, it crashes on 32-bit version. At first, it just made the text insertion cursor disappear (sirjuddington, please fix both bugs), but after a few tries, now it crashes SLADE consistently.

Crash log:
>Version: 3.1.6
>No current action
>
>Operating System: Windows 10 (build 18362), 64-bit edition
>Graphics Vendor: OpenGL not initialised
>Graphics Hardware: OpenGL not initialised
>OpenGL Version: OpenGL not initialised
>
>Stack Trace:
>0: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\stc\PlatWX.cpp:2498) >ListBoxImpl::Select
>1: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\stc\scintilla>\src\ScintillaBase.cxx:317) ScintillaBase::AutoCompleteStart
>2: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\stc\scintilla\src\ScintillaBase.cxx:1087) ScintillaBase::WndProc
>3: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\stc\ScintillaWX.cpp:873) >ScintillaWX::WndProc
>4: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\stc\stc.cpp:1338) wxStyledTextCtrl::AutoCompShow
>5: (H:\Dev\SLADE\Build\src\TextEditor\UI\TextEditorCtrl.cpp:1332) TextEditorCtrl::onKeyDown
>6: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\appbase.cpp:658) >wxAppConsoleBase::HandleEvent
>7: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\appbase.cpp:669) >wxAppConsoleBase::CallEventHandler
>8: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\event.cpp:1398) >wxEvtHandler::ProcessEventIfMatchesId
>9: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\event.cpp:1868) >wxEvtHandler::SearchDynamicEventTable
>10: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\include\wx\event.h:3892) >wxEvtHandler::TryBeforeAndHere
>11: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\event.cpp:1499) >wxEvtHandler::ProcessEvent
>12: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\event.cpp:1627) >wxEvtHandler::SafelyProcessEvent
>13: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\window.cpp:3196) >wxWindow::MSWHandleMessage
>14: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\window.cpp:3823) >wxWindow::MSWWindowProc
>15: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\window.cpp:2910) >wxWndProc
>16: [unknown location] AddClipboardFormatListener
>17: [unknown location] CallWindowProcW
>18: [unknown location] DispatchMessageW
>19: [unknown location] IsDialogMessageW
>20: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\window.cpp:2658) >wxWindow::MSWProcessMessage
>21: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\evtloop.cpp:145) >wxGUIEventLoop::PreProcessMessage
>22: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\evtloop.cpp:163) >wxGUIEventLoop::ProcessMessage
>23: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\evtloop.cpp:230) >wxGUIEventLoop::Dispatch
>24: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\evtloopcmn.cpp:242) >wxEventLoopManual::ProcessEvents
>25: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\evtloopcmn.cpp:283) >wxEventLoopManual::DoRun
>26: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\evtloopcmn.cpp:90) >wxEventLoopBase::Run
>27: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\appbase.cpp:380) >wxAppConsoleBase::MainLoop
>28: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\common\init.cpp:507) >wxEntryReal
>29: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\main.cpp:184) wxEntry
>30: (H:\Dev\vcpkg2\buildtrees\wxwidgets\src\v3.1.2-38b1831b23\src\msw\main.cpp:305) wxEntry
>31: (H:\Dev\SLADE\Build\src\Application\SLADEWxApp.cpp:477) WinMain
>32: (d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288) >__scrt_common_main_seh
>33: [unknown location] BaseThreadInitThunk
>34: [unknown location] RtlGetAppContainerNamedObjectPath
>35: [unknown location] RtlGetAppContainerNamedObjectPath
>
>Last Log Messages:
>Checking for updates...
>Latest stable release: v3.1.6
>Latest beta release: v3.1.2 beta 5
>Already up-to-date
>Opening archive D:\Games\Mary's Magical Adventure\MaryMagicalAdventure.ipk3
>Opening took 2026 ms
>Opening archive D:\Games\Mary's Magical Adventure\MaryMagicalAdventure2.pk3
>Opening took 1383 ms
>Opening archive D:\Games\Mary's Magical Adventure\MaryMagicalAdventure3.pk3
>Opening took 1420 ms

**Comment by DoomKrawa** [comment]
Same problem with ACS scripts here.
