### ISSUE TITLE
Timidity setting does not persist

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#1068]
**SLADE Version**: 3.1.6
**Operating System**: Linux

**Issue Details**:
Setting the MIDI player to Timidity then restarting SLADE makes it revert to using Fluidsynth instead. After some investigation it seems that this is due to some cvar naming discrepancy between the code that saves the setting and the one that reads it (`snd_midi_use_timidity` vs `snd_midi_player`).

**Comment by sirjuddington** [comment]
Are you switching between master and 3.1.6? Those cvars are from different versions but shouldn't be mixed up in either, and I can't reproduce it in either version on linux

**Comment by OrdinaryMagician** [comment]
Not really. I'm in 3.1.7 now and it still happens.
