### ISSUE TITLE
Text Editor Fonts & Colors Behavior

### ISSUE THREAD

**Issue by BLOODWOLF333** [sirjuddington/SLADE#1073]
**SLADE Version**: 3.1.6
**Operating System**: Windows 8.1

**Issue Details**:
The text colors are misbehaving and sometimes not coloring the whole file.  Can also verify the disappearing cursor and calltips bug as well with this version.
![image](https://user-images.githubusercontent.com/16950832/65382811-1aa87000-dcd2-11e9-9982-a5ae64ab06fd.png)

**Comment by sirjuddington** [comment]
Is this still happening in 3.1.7? I know there can still be issues with block comment colouring but functions etc should all be fine

**Comment by BLOODWOLF333** [comment]
I will update right now and check, I've been putting it off lately.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/68266115-af152a80-0013-11ea-805c-a59a8cf8c13c.png)
Tooltips are fixed, cursor disappearing is fixed but, yeah the Text Language coloring still misbehaves compared to 3.1.5.

**Comment by sirjuddington** [comment]
That's weird then, since there haven't been any changes to the text editor/lexer between 3.1.5 and 3.1.7 that would cause it. Does it happen when you edit the text or is it like that when you just open it?

**Comment by sirjuddington** [comment]
Can you try the latest dev build from here: https://slade.mancubus.net/files/?sort_by=mod&sort_as=desc&dir=devbuild and see if it works with that?

**Comment by BLOODWOLF333** [comment]
The way I am reproducing it is the files Im editing are saved as text files and not included in DECORATE since my thing is just a patch for Brutal Doom and that method allows them to overwrite the original BD files.  So, when I change the text language from text to ZDoom Decorate is when the program fails to color the, usually the beginning, of the whole decorate file.  Downloading the Dev build now....

**Comment by BLOODWOLF333** [comment]
The coloring issues is fixed in the dev release, thanks.
