### ISSUE TITLE
Can't access most folders on System

### ISSUE THREAD

**Issue by TMittag-CIT18** [sirjuddington/SLADE#1075]
**SLADE Version**: (3.1.6)
**Operating System**: (Linux Mint 19.1)

**Issue Details**:
Can't access most folders on the System.
I can't choose the Doom port I have installed, like LZDoom, because of this.
I also can't access any wads/pk3s on another drive.

Note: I am new to Linux, so this might be a Linux issue.

**Comment by Gaerzi** [comment]
Open the console log (Ctrl-2) and copy/paste the access error messages.

**Comment by TMittag-CIT18** [comment]
Here:
`SLADE - It's a Doom Editor
Version 3.1.6
Written by Simon Judd, 2008-2019
Compiled with wxWidgets 3.1.2 and SFML 2.5.1
--------------------------------
Loading configuration
Loading resources
Loading icons
Loading entry types
Loading text languages
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
Read game configuration "doom2" + "zdoom"
Opening archive /media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
Error: can't open file '/media/tobias/C Drive/Users/User/Desktop/Games n' Modding/Doom/WADS/Text to Doom.wad' (error 2: No such file or directory)
SLADE Initialisation OK`

**Comment by TMittag-CIT18** [comment]
I somehow fixed it by reinstalling.
But instead of using the flathub package, I used the one hosted on the DRD Team Package Repository.
I can now access those folders.
