### ISSUE TITLE
[Slade 3.1.6] - Crash while hover on a special action then pressing ctrl+spacebar plus midi issue

### ISSUE THREAD

**Issue by Ozymandias81** [sirjuddington/SLADE#1076]
**SLADE Version**: 3.1.6 64bit
**Operating System**: Windows 7 64bit

**Issue Details**:

- I have last release of Slade straight from github, and in order to use less memory I unzip the slade.pk3 and add the content inside a folder called res. It looks that this issue might be related to #1064 

- I never had a problem until this version, what happens is if I try to open any pk3, wad or folder then hover over a special action from decorate and press ctrl+spacebar, the app crashes.

- I have a Palit GeForce GT 610 1024mb, with last possible drivers updated, an AMD FX-6300 3.5ghz 14mb cache Black Edition Unlocked and 4gb of ram ddr3 1333mhz. I never had this issue until this version, I always install Slade as portable, so simply update via zip file without any install

- As a second note, midi songs doesn't play even if I have configured the plugin properly
![image](https://user-images.githubusercontent.com/11136108/66044040-f5610080-e520-11e9-852a-83e8760a330c.png)

- **Stack trace**:

Version: 3.1.6
No current action

Operating System: Windows 7 (build 7601, Service Pack 1), 64-bit edition
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: [unknown location] [unknown:1081796985]
1: [unknown location] [unknown:1082961193]
2: [unknown location] [unknown:1082042820]
3: [unknown location] [unknown:1082045696]
4: [unknown location] [unknown:1081751831]
5: [unknown location] [unknown:1077612431]
6: [unknown location] [unknown:1078479108]
7: [unknown location] [unknown:1078679777]
8: [unknown location] [unknown:1078682699]
9: [unknown location] [unknown:1078683487]
10: [unknown location] [unknown:1078679540]
11: [unknown location] [unknown:1078682563]
12: [unknown location] [unknown:1079703752]
13: [unknown location] [unknown:1079717256]
14: [unknown location] [unknown:1079739660]
15: [unknown location] TranslateMessageEx
16: [unknown location] TranslateMessage
17: [unknown location] IsDialogMessageW
18: [unknown location] [unknown:1079714769]
19: [unknown location] [unknown:1080751327]
20: [unknown location] [unknown:1080751410]
21: [unknown location] [unknown:1080749748]
22: [unknown location] [unknown:1079020341]
23: [unknown location] [unknown:1079019920]
24: [unknown location] [unknown:1079020563]
25: [unknown location] [unknown:1078484753]
26: [unknown location] [unknown:1079064951]
27: [unknown location] [unknown:1078670312]
28: [unknown location] [unknown:1083039654]
29: [unknown location] BaseThreadInitThunk
30: [unknown location] RtlUserThreadStart

Last Log Messages:
Loading entry types
Loading text languages
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
Read game configuration "doom2" + "zdoom"
Opening archive C:\Games\DoomZone\GZDoom\BLOOM_ozy.pk3
SLADE Initialisation OK

**Comment by sirjuddington** [comment]
The text editor crash is a known issue with wxWidgets 3.1.2. I'll revert to wx3.1.1 for the next release of SLADE which should fix that.

The MIDI playback isn't working because fluidsynth isn't supported in the 64bit build (note it's greyed out in that picture)

**Comment by Ozymandias81** [comment]
Alright then, probably I'll revert to 32bit of 3.1.5 :+1:
