### ISSUE TITLE
Slade 3.1.6 won't let me set items as friendly or doors as Repeatable.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [sirjuddington/SLADE#1081]
**SLADE Version**: 3.1.6
**Operating System**: (Windows/Linux/OSX)
Linux

**Issue Details**:
Slade 3.1.6 won't let me set items as friendly or doors as Repeatable in UDMF Maps. This seems not to affect Doom-in-Hexen-Format maps. It's as if the editor is refusing to flag monsters as friendly, unless its written into their Decorate.

**Comment by sirjuddington** [comment]
I'm not sure what you mean here, I can set those flags fine in UDMF maps (friendly is 'Ally' in UDMF, and the 'Repeatable' flag for lines is in the 'Special' tab and not with the regular line flags)
