### ISSUE TITLE
Syntax highlighting can't be changed on the fly anymore

### ISSUE THREAD

**Issue by DoomKrawa** [sirjuddington/SLADE#1086]
**SLADE Version**: (3.1.7)
**Operating System**: (Windows)

**Issue Details**:
Syntax highlighting can't be changed on the fly anymore. That worked before 3.1.7.
How to test it:
- Select TEST (Text) of [script_test.zip](https://github.com/sirjuddington/SLADE/files/3816514/script_test.zip). It should be shown as Text Language: None (because of unknown text type).
- Change to ACS (ZDoom). Syntax highlighting will not change.
- Select something else e.g. Entry LOADACS.
- Go back to TEST (Text) and syntax highlighting will be there.

It's the same with any kind of highlighting. Only reopening changes the highlighting.

**Comment by sirjuddington** [comment]
Can you try the latest dev build from here: https://slade.mancubus.net/files/?sort_by=mod&sort_as=desc&dir=devbuild and see if it works with that?

**Comment by DoomKrawa** [comment]
Tested with slade_3.1.7_30ad114_20191107 and it works.
Thanks!
Issue closed.
