### ISSUE TITLE
Crash on New/Open Wad

### ISSUE THREAD

**Issue by Zyzyx** [sirjuddington/SLADE#1097]
**SLADE Version**: 3.1.8
**Operating System**: Linux

**Issue Details**:
Slade crashes with a traceback when I try to create a new wad or open one. It's repeatable. I tried the version that is packaged with the distro (Void) and compiling myself on the stable branch; I get the same issue.

The "OpenGL not initialised" makes me a little suspicious but I'm just guessing. I'm running wayland on intel drivers. I can run (g)zdoom fine.

I'm eager to get this working so let me know what else you need. :)

Traceback:

> Version: 3.1.8
> No current action
> 
> Operating System: Linux 5.3.18_1 x86_64
> Graphics Vendor: OpenGL not initialised
> Graphics Hardware: OpenGL not initialised
> OpenGL Version: OpenGL not initialised
> 
> Stack Trace:
> 0: [unknown location] [unknown:913930992]
> 1: [unknown location] [unknown:886178080]
> 2: [unknown location] XQueryExtension
> 3: [unknown location] [unknown:805175043]
> 4: [unknown location] glXQueryVersion
> 5: [unknown location] wxGLCanvasX11::GetGLXVersion()
> 6: [unknown location] wxGLCanvasX11::ConvertWXAttrsToGL(int const*, int*, unsigned long)
> 7: [unknown location] wxGLCanvasX11::InitXVisualInfo(int const*, __GLXFBConfigRec***, XVisualInfo**)
> 8: [unknown location] wxGLCanvas::Create(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&, int const*, wxPalette const&)
> 9: [unknown location] wxGLCanvas::wxGLCanvas(wxWindow*, int, int const*, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&)
> 10: [unknown location] OGLCanvas::OGLCanvas(wxWindow*, int, bool, int)
> 11: [unknown location] GfxCanvas::GfxCanvas(wxWindow*, int)
> 12: [unknown location] GfxEntryPanel::GfxEntryPanel(wxWindow*)
> 13: [unknown location] ArchivePanel::ArchivePanel(wxWindow*, Archive*)
> 14: [unknown location] ArchiveManagerPanel::openTab(Archive*) const
> 15: [unknown location] ArchiveManagerPanel::createNewArchive(wxString) const
> 16: [unknown location] ArchiveManagerPanel::handleAction(wxString)
> 17: [unknown location] SActionHandler::doAction(wxString)
> 18: [unknown location] SToolBarButton::onMouseEvent(wxMouseEvent&)
> 19: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
> 20: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
> 21: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
> 22: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
> 23: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
> 24: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
> 25: [unknown location] [unknown:922130570]
> 26: [unknown location] [unknown:895076635]
> 27: [unknown location] g_closure_invoke
> 28: [unknown location] [unknown:882948756]
> 29: [unknown location] g_signal_emit_valist
> 30: [unknown location] g_signal_emit
> 31: [unknown location] [unknown:894732114]
> 32: [unknown location] [unknown:893422072]
> 33: [unknown location] gtk_main_do_event
> 34: [unknown location] [unknown:883439573]
> 35: [unknown location] [unknown:883819618]
> 36: [unknown location] g_main_context_dispatch
> 37: [unknown location] [unknown:877382224]
> 38: [unknown location] g_main_loop_run
> 39: [unknown location] gtk_main
> 40: [unknown location] wxGUIEventLoop::DoRun()
> 41: [unknown location] wxEventLoopBase::Run()
> 42: [unknown location] wxAppConsoleBase::MainLoop()
> 43: [unknown location] wxEntry(int&, wchar_t**)
> 44: [unknown location] main
> 45: [unknown location] __libc_start_main
> 46: [unknown location] _start
> 
> Last Log Messages:
> Loading text style sets
> Loading colour configuration
> Error: can't open file '/home/jgreguske/.slade3/executables.cfg' (error 2: No such file or directory)
> MemChunk::importFile: Unable to open file /home/jgreguske/.slade3/executables.cfg
> Error: can't open file '/home/jgreguske/.slade3/mainwindow.layout' (error 2: No such file or directory)
> Tokenizer::openFile: Unable to open file /home/jgreguske/.slade3/mainwindow.layout
> Loading base resource
> Base resource loaded
> Loading game configurations
> SLADE Initialisation OK
>

**Comment by sirjuddington** [comment]
Currently wxGLCanvas doesn't work on Wayland (see https://trac.wxwidgets.org/ticket/17702), for now you'll either need to switch back to X11 or run SLADE with `GDK_BACKEND=x11` as suggested at that link

**Comment by Zyzyx** [comment]
That appeared to do the trick, thank you for the tip! This issue is resolved from my standpoint.

For what it's worth, the flatpak works ok too.
