### ISSUE TITLE
Text > Find + Replace > "Replace With" Field Covers Up Part of The GUI

### ISSUE THREAD

**Issue by BLOODWOLF333** [sirjuddington/SLADE#1098]
**SLADE Version**: 3.1.8
**Operating System**: Windows 10

**Issue Details**:
The Replace With: text field partially covers-up the various options below it in the Find + Replace dialog.

![image](https://user-images.githubusercontent.com/16950832/71500753-f0fc6900-282b-11ea-8235-62a16f058993.png)

**Comment by Gaerzi** [comment]
My first thought was a DPI issue like in #1031 but since I don't suppose you'd have changed the DPI setting back, it must be something else.

I don't get this issue, though.

**Comment by sirjuddington** [comment]
This was fixed in 3.1.10
