### ISSUE TITLE
Fix HiDPI support

### ISSUE THREAD

**Issue by MarkJeronimus** [sirjuddington/SLADE#1100]
**SLADE Version**: (v3.1.7)
**Operating System**: (Ubuntu 18.04 with Unity)

**Issue Details**:
When using a High DPI (HiDPI) setting in the OS (200% in my case) the 3D scene of the map editor is rendered in the lower-left corner of the viewport. This isn't a bug in Slade per-se because I see the _exact_ same problem in another program, KiCAD. The problem in KiCAD can be worked around by disabling anti-aliasing.

However, there's no way (I found) to disable anti-aliasing in the map editor.

https://youtu.be/NGrIPmQM9pw

**Comment by matatk** [comment]
Hi, I believe I'm experiencing the same issue on macOS, using a MacBook Pro from several years back. When running on the internal display, I get exactly the same problem as above. When running on an external monitor (in non-HIDPI mode), SLADE's editor looks as expected. SLADE looks pretty awesome; looking forward to using it :-).
