### ISSUE TITLE
lua table functions

### ISSUE THREAD

**Issue by kfpopeye** [sirjuddington/SLADE#1102]
**SLADE Version**: (3.1.8)
**Operating System**: (Windows 10)

**Issue Details**:
Cant seem to access the table.sort() and table.insert() in the lua scripts. Get error: attempt to index a nil value (global 'table')

**Comment by sirjuddington** [comment]
Yeah currently they aren't available to scripts, they will be available in 3.1.9+

**Comment by sirjuddington** [comment]
3.1.9 is now available which should allow enable the table library (and others) in scripts
