### ISSUE TITLE
Syntax highlighting does not work

### ISSUE THREAD

**Issue by Talon1024** [sirjuddington/SLADE#1109]
**SLADE Version**: (3.1.9)
**Operating System**: Kubuntu 18.04 (Linux)

**Issue Details**:
The text editor does not show syntax highlighting at all for me. None of the text in the text editor is displayed in colour.

I found via git bisect that [this commit](https://github.com/sirjuddington/SLADE/commit/6f0c8a361d6e04ddabdcbaaac995fbf63c98b81b) introduced the issue.

**Comment by sirjuddington** [comment]
Hmm, works fine in windows for me, what version of wxWidgets are you compiling with?

**Comment by Talon1024** [comment]
3.0.4, according to my package manager. But, if new features were added that depend on newer versions of wxWidgets, I don't think SLADE would compile at all.

**Comment by OrdinaryMagician** [comment]
Oh, I just updated from 3.1.8 and syntax highlighting is also gone on my end too.

**Comment by Talon1024** [comment]
[It's fixed now!](https://github.com/sirjuddington/SLADE/commit/44bf0e29a5d5c17dd904c47eac5c08694c8fbeb2). Thank you.
