### ISSUE TITLE
Unable to use Mac Version

### ISSUE THREAD

**Issue by VGBoy** [sirjuddington/SLADE#1112]
**SLADE Version**: (3.1.10 (Reads as 3.1.9-4-ga5927973 on the dmg itself)
**Operating System**: (OSX Version 10.14.6)

**Issue Details**:
When I try to open up SLADE, It displays this message and forces me to delete it if I copy it to Applications or eject the disk image while it's still in the dmg.
<img width="415" alt="Screen Shot 2020-02-24 at 10 28 24 PM" src="https://user-images.githubusercontent.com/18492821/75212503-21da1b00-5755-11ea-875c-0d6e61ceabc1.png">
I don't know if it is just the download being corrupted or there is actually something wrong with the Mac version specifically.

**Comment by gernotresch** [comment]
having the issue as well. copying the binary out of the image doesn´t solve the problem.
macOS 10.15.3 here.

**Comment by sirjuddington** [comment]
No idea what is wrong with it, does 3.1.9 work?

**Comment by VGBoy** [comment]
The old 3.1.9 download works with no issue.

**Comment by gernotresch** [comment]
for me as well.

**Comment by sirjuddington** [comment]
I made a build for [3.1.11](https://github.com/sirjuddington/SLADE/releases/tag/3.1.11), does that work?

**Comment by VGBoy** [comment]
I've tried opening the 3.1.11 build. It still says the app is damaged and can't be opened.

**Comment by sirjuddington** [comment]
Hmm well that's annoying. Unfortunately I have no idea what could be wrong with it and don't really have the mac expertise to figure it out

**Comment by gernotresch** [comment]
ah that´s sad. but nevertheless, thanks for your efforts!

**Comment by alexey-lysiuk** [comment]
Running `pkgutil --check-signature /Volumes/SLADE-3.1.11/SLADE.app` in Terminal outputs `Status: package is invalid (checksum did not verify)`
Most likely, it wasn't singed with the certificate trusted by Apple.

**Comment by matatk** [comment]
I've been unable to use 3.1.11 for the same reasons and, oddly, I thought I'd got my copy of 3.1.9 from the GitHub Releases page, but it doesn't work for the same reason.

I installed wxWidgets and tried to compile (both `master` and `stable`) but get this error, which I've not been able to resolve so far...

```
Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
wxWidgets_INCLUDE_DIRS) (Required is at least version "3.0.4")
```

(I used Homebrew to install wxWidgets and might be able to fix it by tweaking some include path perhaps.)

**Comment by matatk** [comment]
Given that the previously-working 3.1.9 is no longer working for me, I wonder if it's something to do with a mismatched version number somewhere in the build process (as @VGBoy mentioned) that caused the app to be seen as damaged, and that result's been cached somewhere? Or maybe there's a certificate related to the signing that @alexey-lysiuk mentioned, and it just happened to expire?

Maybe it's helpful to state the help info macOS gives when clicking the '?' button in the "SLADE is damaged" dialog...

> The app has been modified, and its code does not match the original signed code. The app may be broken or corrupted, or it may have been tampered with. If you think that an app has been damaged or tampered with, you should delete it by dragging it to the Trash.

@sirjuddington do you know of anything in the build process/certificate that relates to signing and might've changed recently?

I'll keep having a go at compiling it, time permitting, but, in case this info is of use to anyone...

I found [an article on the subject of code signing](https://eclecticlight.co/2019/10/25/how-to-check-signatures-on-apps-installers-and-packages/), and ran `codesign -dvvv /Volumes/SLADE-3.1.9/SLADE.app` and `codesign -dvvv /Volumes/SLADE-3.1.11/SLADE.app`. I don't understand it in great detail, but the following things seem to be of note.

* The app is 'adhoc' signed.
* The CodeDirectory has changed from "system" to "embedded" from 3.1.9 to 3.1.11.
* The app's Identifier has changed between 3.1.9 and 3.1.11.
* The "sealed resources" and Info.plist have also changed.
* `codesign` doesn't report any problems.

**Comment by clobber** [comment]
To get SLADE 3.1.11 to open run the following in Terminal:
`codesign --remove-signature --deep --verbose=4 /path/to/SLADE.app`

Then right click on the SLADE app bundle > select Open.

<img width="721" alt="Screen Shot 2020-03-25 at 11 24 01 PM" src="https://user-images.githubusercontent.com/1303132/77613321-0c8d1380-6ef0-11ea-87eb-49c12c48de3f.png">

The dark mode theming isn't very good though :\

**Comment by mentaluproar** [comment]
Clobber, that worked for me, though I had to try opening twice after issuing the terminal command.  This is a strange issue.  If it can't find a signature, I should get a warning about security, not a warning about corruption.  It's acting like the signature was tampered with.

**Comment by VGBoy** [comment]
> To get SLADE 3.1.11 to open run the following in Terminal:
> `codesign --remove-signature --deep --verbose=4 /path/to/SLADE.app`
This fixed the issue.
