### ISSUE TITLE
Extend/Mixins not parsing functions properly

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#1113]
**SLADE Version**: (3.1.10)
**Operating System**: Windows 10

**Issue Details**:
Slade does not parse functions which forces me to have to bookmark my mixin/extend file(s) in order to double check my function parameters. A minor issue, but still heavily annoying.

**Comment by Gaerzi** [comment]
Makes sense, mixins didn't exist when the ZScript parser was coded.

**Comment by MajorCooke** [comment]
Aye, but extends was in there far longer.
