### ISSUE TITLE
Recent Files

### ISSUE THREAD

**Issue by DoomKrawa** [sirjuddington/SLADE#1114]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
Is there a reason why Recent Files is in Save area?
For me it would make more sense to place it after Open Directory, because you just can open recent files and not save anything.
Very minor issue of course :)

![Recent Files](https://user-images.githubusercontent.com/22943155/76012423-8ac05080-5f16-11ea-8c0f-359bd9b67d85.png)

**Comment by sirjuddington** [comment]
Hmm, I barely use that menu to open recent files so didn't notice :P I'm sure it was originally up with the 'Open' items, not sure when it moved but yeah it's not meant to be there.
