### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Swatchel** [sirjuddington/SLADE#1117]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
(remove this line and enter details here)
url http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe is unreachable now.
Please fix this url in your code

**Comment by sirjuddington** [comment]
Some kind of spam bot?

**Comment by Gaerzi** [comment]
Nah, not a spambot; it's about the value of msi20_url in one of the installer scripts:
https://github.com/sirjuddington/SLADE/blob/3128c0f66642a90d0bf5e303322fcfed8d23550d/win_installer/scripts/products/msi20.iss

**Comment by sirjuddington** [comment]
I'm not sure that is even needed, but for now I'm just going to leave it as is (don't really want to touch the installer stuff while it's still working :P)
