### ISSUE TITLE
"Open with DB2" option nonfunctional (UDMP map, GZDB)

### ISSUE THREAD

**Issue by Leo40Git** [sirjuddington/SLADE#1118]
**SLADE Version**: 3.1.11
**Operating System**: Windows 10

**Issue Details**:
The option to open WAD files with Doom Builder 2 does not work. At all. As in, I click it and literally nothing happens. There are no errors in the console, either.
I have set the DB2 ~~directory~~ EXE path (I'm using GZDoom Builder specifically, but that should work too).
I'm trying to open a UDMP map, if that means anything. Does standard DB2 support it?

**Comment by Gaerzi** [comment]
> I have set the DB2 directory (I'm using GZDoom Builder specifically, but that should work too).
path_db2 should point specifically to the executable, not merely its directory.

**Comment by Leo40Git** [comment]
sorry for the misunderstanding. I have set the DB2 path to my Builder.exe.

**Comment by Leo40Git** [comment]
Sorry for the misunderstanding. I have my DB2 path set to my Builder.exe.

`path_db2` is `C:/<valid directory>/GZDoom Builder/ProgData/Builder.exe`.

**Comment by Gaerzi** [comment]
I assume you solved the problem, if you closed the issue. Could you describe what you did to fix it? It may help other people in the future.

**Comment by Leo40Git** [comment]
I actually wanted to recreate the issue with some additional information, but now that I think about it that's a waste of time.
