### ISSUE TITLE
Add option to 3d camera view to temporarily have all sectors brightly lit

### ISSUE THREAD

**Issue by warrenhead** [sirjuddington/SLADE#1122]
**SLADE Version**: (3.1.11)
**Operating System**: (Linux)

**Issue Details**:
Feature request:
a toggle switch, during 3d camera view, to set the brightness of all sectors to 200+.

This feature is handy when you are in bright room, or outside, while designing dark corridors.
I enjoy using the 3d view for aligning textures, but I cannot always see the textures well when sectors have brightness of 120 or less.
A temporary toggle switch would be really helpful.

**Comment by Gaerzi** [comment]
There is a "fullbright" toggle, it's bound to b by default IIRC. Isn't that what you want?

**Comment by warrenhead** [comment]
Oh, that is it exactly!
Case closed. Thank you.
