### ISSUE TITLE
Will this ever be available for mobile users?

### ISSUE THREAD

**Issue by AdrianShephard** [sirjuddington/SLADE#1123]
I was wondering if this will ever be available to mobile users. Sorry if it's in the wrong place

**Comment by Gaerzi** [comment]
A mobile port of SLADE would have to completely rethink the interface. The main issues are that inputs are designed around keyboard and mouse (there are actions that are hardcoded to right-click and middle-click), and some dialog windows have minimum sizes that are larger than what is commonly found on mobile.

**Comment by AdrianShephard** [comment]
oh. Ok. Sorry if I bothered you. And if the question seemed stupid, I'm really sorry if it was.

**Comment by Gaerzi** [comment]
It's not a bother and it's not a stupid question, don't worry. :) 

I guess I can close it, though.
