### ISSUE TITLE
Infinite loading on Linux with the Flatpak

### ISSUE THREAD

**Issue by Spowmtom** [sirjuddington/SLADE#1124]
**SLADE Version**: 3.1.11 (Flatpak)
**Operating System**: Linux fedora 5.5.10-200.fc31.x86_64 #1 SMP Wed Mar 18 14:21:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Issue Details**:
When running or saving the map, it enters an infinite loading loop for hours and the only way to use SLADE again is to kill the process and relaunch it. 
Steps to reproduce the issue;

1. Launch the application with the line `flatpak run net.mancubus.SLADE`
2. Set my base resource to doom2.wad
3. Load my custom wad _previously edited in Doom Builder_ with "Open Archive"
4. Open the map editor
5. Set the right map, game mode, port, base resource along with its according file and click "ok"
6. Run the archive
7. Set my executable to _chocolate-doom_
8. Use the default _run_ configuration
9. Set the extra parameter `-config /path/to/my/chocolate-doom/config`
10. set the resources to _doom2.wad_

It isn't a problem with my personal configuration, as I can run my doom wad perfectly by myself.
I can also run the doom wad from SLADE without opening the map editor with no trouble.
I did set my node builder to ZenNode accordingly.
While SLADE is bugging out, it only takes around 20% of my CPU.

**Comment by sirjuddington** [comment]
Does it happen if you use a different node builder? If not it might be the same as #653

**Comment by Spowmtom** [comment]
> Does it happen if you use a different node builder? If not it might be the same as #653

It is a duplicate.
