### ISSUE TITLE
Additive color properties

### ISSUE THREAD

**Issue by marrub--** [sirjuddington/SLADE#1126]
**SLADE Version**: Any
**Operating System**: Any

**Issue Details**:
There are properties in GZDoom for additive color blending similar to the gradient color system, [on lines](https://github.com/coelckers/gzdoom/blob/master/specs/udmf_zdoom.txt#L209) and [on sectors](https://github.com/coelckers/gzdoom/blob/master/specs/udmf_zdoom.txt#L291). These would be useful to have editable.

**Comment by Leo40Git** [comment]
For the time being, you can add these properties as custom properties using the "+" button on the Properties pane while selecting a sector/line.
