### ISSUE TITLE
Wrong text color in text editor

### ISSUE THREAD

**Issue by Numnzel** [sirjuddington/SLADE#1131]
**SLADE Version**: 3.1.10
**Operating System**: Windows 10 64bit

**Issue Details**:
Seems like text colors are not being applied correctly when working with a shader text file, a big portion of the text appears as if it were commented.
Screenshot:
https://i.imgur.com/YnFEP4p.png

**Comment by sirjuddington** [comment]
Have you tried updating to 3.1.11? It should be fixed there

**Comment by Numnzel** [comment]
Yes, It is fixed.
