### ISSUE TITLE
Feature request: map items overview for assessing difficulty/playability

### ISSUE THREAD

**Issue by warrenhead** [sirjuddington/SLADE#1132]
**SLADE Version**: 3.1.11
**Operating System**: Linux

**Issue Details**:
While building a level I am loosing track of how many monsters I have placed and whether the ammo I have placed remotely matches how much a player would need. Since I focus on 4 player coop levels, I don't want to cause starvation or uneven division.

Feature idea:
Via the map editor, in menu View, a menuitem Map overview, shows an overview of the playable items placed in the map. (playable as in monsters and items you can pickup).

I would like to get an overview of how many monsters there are of each type, and the same for the items, both displayed simply in columns side by side: 

| monster type | amount | 
|--------------|--------|  
| sarge        |      5 |

| item type     | amount | 
|---------------|--------|  
| box of shells |      5 |

Perhaps a tabpanel is nice way for separating the above into the different skill levels.

And for assessing the difficulty, I would like to see a textual sum total of hitpoints on each tab/skill level, with a textual total of damage points which can be made with the available ammo.

**Comment by sirjuddington** [comment]
This is probably a bit too niche for a general feature, however I can't see any reason this couldn't be done as a [script](http://slade.mancubus.net/docs/scripting/)
