### ISSUE TITLE
Please don't force FluidSynth to use ALSA

### ISSUE THREAD

**Issue by chewi** [sirjuddington/SLADE#1147]
**SLADE Version**: 3.1.12a
**Operating System**: Linux

**Issue Details**:
You have hardcoded FluidSynth to use ALSA because it was apparently preferring JACK in some cases. Please review this decision as ALSA isn't necessarily enabled everywhere. In my case, I see this error.

```
fluidsynth: error: SDL2 not initialized
fluidsynth: error: Couldn't find the requested audio driver 'alsa'.
fluidsynth: Valid drivers are: file, pulseaudio, sdl2
```

**Comment by chewi** [comment]
Okay, I now see that you can change this in `slade3.cfg` but I'm packaging this up for Gentoo and I don't want users to have to do this.

**Comment by hfc2x** [comment]
Wanted to add here that on Fedora 40, SLADE 3.2.6 has horrible sound output when setting the FluidSynth driver to `"alsa"` in slade3.cfg. Music sounds all distorted, slowed down, and completely off-key. Setting the driver to `"pulseaudio"` fixes all problems.
