### ISSUE TITLE
Can't use linedef actions 271/272 in Doom/Boom format maps

### ISSUE THREAD

**Issue by kitchen-ace** [sirjuddington/SLADE#1155]
**SLADE Version**: (3.1.1.2)
**Operating System**: Linux (flatpak)

**Issue Details**:
Even though it's outside of those formats' strict definitions, a lot of ports support linedef actions 271 and 272 (transfer skies) within maps that are otherwise Doom or Boom compatible. In SLADE it appears to be strictly impossible to enter an 'invalid' action number.

**Comment by Gaerzi** [comment]
The MBF specials are already here; I thought they were #included in the Boom config but apparently not.
