### ISSUE TITLE
Copying continuously adds to the clipboard (3.2.0 Beta)

### ISSUE THREAD

**Issue by Frozsoul2019** [sirjuddington/SLADE#1159]
**SLADE Version**: (3.2.0 Beta)
**Operating System**: (Windows)

**Issue Details**:
In previous SLADE versions, if you copy a file, and then copy a second file, the second file overwrites the first file in the clipboard.  However, in SLADE 3.2.0 Beta, these actions incorrectly result in the clipboard containing both the first and the second file (i.e. the clipboard is continuously added with each copying action)

**Comment by sirjuddington** [comment]
This is fixed in 11b70f349adc5726092f1469dbc521866ebc72d6 for the next beta
