### ISSUE TITLE
Copying entries does not clear previously copied entries but adds them to the clipboard instead

### ISSUE THREAD

**Issue by auratoostronk** [sirjuddington/SLADE#1161]
**SLADE Version**: (3.2.0 beta 1)
**Operating System**: Windows 10

**Issue Details**:
Copying any number of entries copies them to the clipboard, but when a set of new entries are copied, they are added to the clipboard instead of replacing them. For example, I was copying some images today and pasted them and it worked as intended. However, when I tried pasting another image that I copied, it pasted both that image and the images I had copied earlier together.

**Comment by sirjuddington** [comment]
This is fixed for the next beta (see #1159)
