### ISSUE TITLE
Crash when opening a graphic in a new tab then closing it

### ISSUE THREAD

**Issue by MrKingMichael** [sirjuddington/SLADE#1186]
**SLADE Version**: (3.2.0 Beta 2)
**Operating System**: (Linux)

**Issue Details**:

I opened a WAD file, searched for a graphic (Indexing took quite some time by the way), opened the graphic in a new tab, closed the tab, and SLADE crashed. I can always reproduce this crash. The WAD has over 1700 graphics, if that helps.

**Comment by FlykeSpice** [comment]
If you can always reproduce this crash you can as well helpfully give us the crash log.

**Comment by MrKingMichael** [comment]
Can't reproduce on latest git version.
