### ISSUE TITLE
Map view on macOS is 1/4th its proper size

### ISSUE THREAD

**Issue by perryprog** [sirjuddington/SLADE#1195]
**SLADE Version**: 3.2.0 (HEAD@[`29c9b9b`](https://github.com/sirjuddington/SLADE/commit/29c9b9bd8142ae95e4ab387424d5056162f88827))
**Operating System**: macOS

**Issue Details**:
On the HEAD version on macOS (after some tweaks to get it to compile, but that's a whole other thing), the map view looks like this:
<img width="1136" alt="Screen Shot 2020-08-15 at 3 53 42 PM" src="https://user-images.githubusercontent.com/12972285/90320441-8198ce00-df0f-11ea-912c-3226de6205e0.png">
Even weirder, the mouse input still behaves as if it took up the full screen, so hovering your mouse in the top right will act as if your mouse is around the center. Hopefully that makes sense, I can make a video demonstrating the video if it doesn't.

This is compiled with commit ae1bcc5 (HEAD as of this issue) of wxWidgets.

**Comment by sirjuddington** [comment]
This should be fixed with #1301
