### ISSUE TITLE
Request - Some DECORATE Action Functions not recognized by SLADE

### ISSUE THREAD

**Issue by Karma1233** [sirjuddington/SLADE#1199]
**SLADE Version**: (3.2.0 beta 2)
**Operating System**: (Windows 10/Linux)

**Issue Details**:
(Low Priority) Just letting you know that certain Functions such as A_SpawnProjectile do not appear to be recognized by SLADE.

**Comment by Da-Spadger** [comment]
A_StartSound is also not recognized.

**Comment by sirjuddington** [comment]
Should be all there with #1312 and #1318
