### ISSUE TITLE
Prevent two linedefs from ever sharing the same sidedef

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#120]
I'm...  not at all sure how I managed this one, but it indeed happened.  The sector check just insisted I toggle the shared sidedef back and forth between the two adjacent sectors ad infinitum, zdoom was very confused, and I had a hell of a time fixing it manually since I can't just invent a new sidedef.

**Comment by sirjuddington** [comment]
Closing this since it's duplicated with a newer issue
