### ISSUE TITLE
Request for SLADE to open files from Windows Explorer in a new tab instead of a new instance/window

### ISSUE THREAD

**Issue by Frozsoul2019** [sirjuddington/SLADE#1205]
**SLADE Version**: (3.2.0 beta 2)
**Operating System**: (Windows)

**Issue Details**:
As an example, if SLADE is already open with a PK3 file, and then you open a second PK3 file from Windows Explorer with SLADE, a new instance/window of SLADE will open, resulting in two active SLADE instances/windows.  Unlike a new tab, files cannot be copied from one instance/window of SLADE to the other.

Even worse is if the second PK3 file you open is the same as the first PK3 file.  There will now have two instances/windows of SLADE open with the same PK3 file which can lead to unintended results when changes are made in one instance/window and not the other, especially if this is not observed by the user.

Recommend that if SLADE is already open with a PK3 file, and any further PK3 files are opened with SLADE (e.g. from Windows Explorer) then SLADE will automatically open the PK3 file in a new tab, and if the same PK3 file is already open, either nothing happens or the user is then prompted with a warning (e.g. "Selected file <file name> is already open.").  This is what currently occurs when a PK3 file is opened from within SLADE.

**Comment by sirjuddington** [comment]
It should already be doing that, at least it does for me. How are you opening the pk3s with SLADE? Do you have pk3 files associated with SLADE or are you using 'send to'?

**Comment by Frozsoul2019** [comment]
For some reason, I can't seem to recreate this issue.  I do have PK3 files associated with SLADE, and I always open PK3 files from Windows Explorer.  My only guess in why this originally occurred is that perhaps I had an older version of SLADE already open, and when I opened a PK3 file from Windows Explorer, it opened the PK3 using the new (associated) version of SLADE, resulting in two active SLADE instances.  If I experience this issue again, I will more closely document and report exactly what causes it to occur.

**Comment by Frozsoul2019** [comment]
I have now successfully reproduced this issue.  A file can be opened twice at the same time in SLADE as follows:
1. Open a file from the "Recent Files" window in SLADE (i.e. double-click on the listed file)
2. Open that same file, either by manually opening the file in SLADE (e.g. using the Open button) or by double-clicking on the file from Windows Explorer (if that file type is associated with SLADE).

The order of above does not matter - either way it results in two instances of the same file being open in SLADE at the same time, creating problems as mentioned in original post.  I tested and this issue is present in at least SLADE versions 3.2.0 beta 2 and 3.1.12 for Windows.

**Comment by Frozsoul2019** [comment]
This issue also occurs if you first open the SLADE editor, and then open a file that is associated with SLADE from Windows Explorer.

It does **not** occur if:
- You open the SLADE editor, and then manually open a file from within SLADE
- You open the SLADE editor, and then open a file from the Recent Files window in SLADE

**Comment by Frozsoul2019** [comment]
As a related bug to the above, SLADE will normally allow only one instance of a file to be open.  For example, if you open a PK3 file from Windows Explorer, and then try to open it again, only one instance will be correctly open.  The same behaviour also happens if you open a PK3 file from the "Recent Files" window within SLADE, and then try to re-open the same file again (again, only one instance will be correctly open).  However, if you open a file from Windows Explorer, and then open that same file from within "Recent Files" window within SLADE, you will now have two instances of the file open as separate tabs within SLADE.
