### ISSUE TITLE
Won't compile on aarch64

### ISSUE THREAD

**Issue by dleslie** [sirjuddington/SLADE#1206]
**SLADE Version**: all
**Operating System**: Anything aarch64

**Issue Details**:

This would _almost_ work on arm/aarch64/etc if not for the `dumb` library and the baked-in `cmake` C flag `-msse`.

As it is, it's impossible to build this on non-pentium CPUs because of the `sse` requirement.

**Comment by Blzut3** [comment]
Fixed with changeset fb10ce9
