### ISSUE TITLE
GCC 10.2.0 error: call of overloaded is ambiguous

### ISSUE THREAD

**Issue by Eonfge** [sirjuddington/SLADE#1209]
**SLADE Version**: 3.1.12.a
**Operating System**: Linux (Flatpak)

**Issue Details**:
```
error: call of overloaded ‘push<const wchar_t*>(lua_State*&, const wchar_t [2], const wchar_t*)’ is ambiguous
```

Discovered it while making the Flatpak build using the new runtime. The new runtime uses GCC 10.2.0 and as such, some previously ignored issues are now enforced.

[log.txt](https://github.com/sirjuddington/SLADE/files/5241005/log.txt)

**Comment by Eonfge** [comment]
@sirjuddington Hey, I'm sorry to @ you, but this issue is now becoming more serious. As the current version of SLADE is still build on an older runtime, I can't update SLADE on Linux until this compiler-issue is resolved.

https://github.com/flathub/net.mancubus.SLADE/pull/27

**Comment by sirjuddington** [comment]
Can you try again with the latest commit to stable? If that doesn't fix it there isn't much else that can be done as it's an issue with the version of sol that is used in 3.1.x

**Comment by Eonfge** [comment]
That's it. Great to see because this might be our way out of this update-impasse. Will you make a new release or should I just deploy the stable branch?

**Comment by sirjuddington** [comment]
Ok that's good,  I've created tag 3.1.13a if you wanted to use that

**Comment by Eonfge** [comment]
Thanks for your help!
