### ISSUE TITLE
VGAGraph support is mostly hard coded

### ISSUE THREAD

**Issue by Blzut3** [sirjuddington/SLADE#121]
It looks like most of the loading is hard coded based on the number of chunks.  This isn't exactly needed as the order is more or less known so it's possible to determine the type by examining the information given.  There are a few catches though.
- The first chunk is the pictable.  The length of this chunk is hard coded so some editors fill in the length with garbage.  However, since the size of the compressed data is known (chunkOfs[1] - chunkOfs[0]) we can rely on the huffman decoder to give us a pointer to the end of the data.  Derive the size from that to determine the number of graphics in the VGAGraph.
  - As an additional sanity check, scan the pictable and truncate if an image is reported as 0x0 or larger than some arbitrary size.  (I use 640x480 as the max size in ECWolf.)
- Following the pictable will be some number of fonts.  Unfortunately the only way to know how many fonts is to go one at a time and check to see if the chunk can be interpreted as a valid font.  (ECWolf does this check in the ECBlake branch.)
- After all the image chunks is the TILE8.  This chunk has no uncompressed length since vanilla just assumed it contained 72 tiles.  This assumption is bad since S3DNA has 106 tiles (IIRC).  For this, pick a max size (I use 256 tiles) and then use the method from before to run the huffman decoder on the compressed buffer.  The end pointer will tell you the size which can be divided by 8*8 to get the number of tiles.
  - With my knowledge limited to Wolf3D engine games, I do not believe there are any VGAGraphs which contain a masked TILE8, TILE16s, or TILE32s.  Allowing these to exist would make things a little more difficult, but from what I can tell they would have to be in that order so you could attempt this method on the chunks following and see if the output size makes sense.
- Following the TILE8 can be either palettes or text screens (ENDOOM).  It looks like they can come in either order, but the size of these would be constants.
- After these is either demos or ASCII text chunks.  I believe the demos are always grouped together, but they could be before, after, or in the middle of the text chunks.

**Comment by sirjuddington** [comment]
I'm assuming this isn't going to be done any time soon? Should probably move it off the 3.1.1 milestone if that's the case

**Comment by sirjuddington** [comment]
Closing - old issue

Feel free to reopen the issue if needed
