### ISSUE TITLE
Image offsets don't apply when using folders

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#1213]
**SLADE Version**: 3.2.0 beta 2
**Operating System**: Linux

**Issue Details**:
Editing images to add offsets APPEARS to work, but once saved and the folder is closed (and also saved, of course), loading again will show that the offsets are at 0,0. This is done on PNGs, which should obviously work. Additionally, the bug does not trigger with WADs or archives, only with folders.

**Comment by biwa** [comment]
I just ran into that, too. It _does_ work when you select multiple files and apply the offset to all of them, though.

**Comment by biwa** [comment]
Here's a video demonstrating the problem. Using 3.2.0 Beta 2.

https://www.youtube.com/watch?v=iytSVMeJZIY

**Comment by ZedekThePlagueDoctor** [comment]
Confirmed issue, 3.2.0 Beta 2.
