### ISSUE TITLE
Request Add Dark/Light Theme to View

### ISSUE THREAD

**Issue by BLOODWOLF333** [sirjuddington/SLADE#1214]
**SLADE Version**: (3.1.12)
**Operating System**: (Windows)

**Feature Request**:
I've had various people (mainly on the Brutal Doom discord) ask me how I enabled the dark theme in Slade when I screenshot things I'm working on and this is a sign that the option is not in an intuitive place.  So, instead of Edit>Preferences>Text Editor> Fonts & Colors could it be moved to View or an option created for it under View?  I think that's where the average user would think to look for dark mode.

**Comment by sirjuddington** [comment]
I've added this in the most recent commit, though not to the 'View' menu because that one isn't dynamic, it's in the 'Text' menu instead
