### ISSUE TITLE
"Caught unhandled unknown exception; terminating" hang when undoing a merge vertex operation

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#1220]
**SLADE Version**: git latest (3.2.0_b2+6+gb247aab8-1 from the AUR)
**Operating System**: Linux (Manjaro)

**Issue Details**:
1. open this very basic example in the map editor: http://vectorpoem.com/doom/crash.wad
2. drag one of the vertices on the invalid (red) line to its nearest neighbor to merge them
3. press ctrl-Z to undo the operation
4. if that doesn't reproduce the bug, try doing it with the vertex on the other invalid line on the other side of the box
5. observe: SLADE hangs, but doesn't crash, and has to be killed

When I run from a terminal, I don't see any particularly useful logging when the hang happens, just "Caught unhandled unknown exception; terminating".

**Comment by runlow** [comment]
Experiencing this issue also, although didn't have the steps to reproduce it. Makes the map editor almost unusuable for me.

**Comment by JPLeBreton** [comment]
Just compiled a Debug build of Slade to see if that turned up any useful info in stdout/stderr. Nothing extra happened at the point of the hang, but it did segfault after logging the exception.

The one line that kept spamming the whole time the program was running was this:
`Debug: ClientToScreen cannot work when toplevel window is not shown`
Not sure if that's related to anything about this hang/crash though.

**Comment by anotak** [comment]
my PR should fix the very particular example that JP mentioned

**Comment by sirjuddington** [comment]
Should be fixed with that PR merged, reopen if it isn't
