### ISSUE TITLE
sol.hpp "compiler is out of heap space" on windows 10

### ISSUE THREAD

**Issue by anotak** [sirjuddington/SLADE#1222]
**SLADE Version**: as of this commit https://github.com/sirjuddington/SLADE/commit/b247aab888afe1127f963f5572d81a8985a55446
**Operating System**: Windows 10

**Issue Details**:
I followed the instructions in compile.md, and then cl.exe uses up all my ram and hangs my machine and says
`fatal error C1060: compiler is out of heap space` for sol.hpp

i can build it if i put `#if 0` + `#endif` pairs around Scripting\Export\Graphics.cpp and Scripting\Export\MapEditor.cpp, as well as commenting out the references to the missing code elsewhere

additionally, i tried building it for x86 and using vcpkg to grab the includes for x86, but it only seems to find the includes for x64, for mysterious reasons.

**Comment by sirjuddington** [comment]
Sol2 is a very template-heavy library so can cause some issues compiling, never seen that one though. Does it still happen now with everything up to date (vcpkg packages, etc.)? If so, what version of MSVC are you using to build?
