### ISSUE TITLE
Conversion from TEXTURE1/2 to TEXTURES is broken.

### ISSUE THREAD

**Issue by sergeirocks100** [sirjuddington/SLADE#1224]
**SLADE Version**: 3.2.0 Beta 2
**Operating System**: Windows 10

**Issue Details**:
Conversion from TEXTURE1/2 to TEXTURES doesn't produce a usable TEXTURES file.

Not only are there two curly brackets at the end of each entry instead of one, but there are no texture definitions assigned to the entries, meaning that you have to open the file in a text editor and manually assign them yourself.

Feel free to close this issue if i'm simply getting something wrong rather than it actually being a bug with the program.

**Comment by sirjuddington** [comment]
Fixed in cbdfd25
