### ISSUE TITLE
Feature request: Ability to view ID3 metadata for MP3 files within SLADE

### ISSUE THREAD

**Issue by Frozsoul2019** [sirjuddington/SLADE#1230]
If feasible, it would be great if ID3 metadata for MP3 files was viewable within SLADE.

**Comment by Gaerzi** [comment]
They should be viewable already. At least it works for me in v3.1.1.2; while all audio metadata info is completely broken in 3.2.0 beta.

![Example](https://i.imgur.com/T2fu6fQ.png)
