### ISSUE TITLE
Texture Editor Creates Invalid TEXTURES Lump

### ISSUE THREAD

**Issue by FoxMcloud5655** [sirjuddington/SLADE#1232]
**SLADE Version**: 3.2.0 beta 2
**Operating System**: Windows 10

**Issue Details**:
When saving the TEXTURES lump from the Texture Editor in SLADE3, it creates two "}" symbols at the end of each definition, which is invalid.  Output is as follows:
```
Sprite "TESTA0", 128, 128
{
	Offset 64, 64
	Patch "SOMEA0", 0, 0
	{
		Blend "#FF0000", 1.0
	}
}}
```

**Comment by sirjuddington** [comment]
Will be fixed in beta 3
