### ISSUE TITLE
FATAL BUG: SLADE overwriting all .exe files to be opened after setting .wad and .pk3 as default through "Open With"

### ISSUE THREAD

**Issue by Meyers07** [sirjuddington/SLADE#1234]
SLADE Version 3.1.1.2 (Last Stable Version, not Beta)
Windows 10 20H2 x64 (Last updated January 2021)

Issue details:
FATAL BUG
SLADE overwriting all .exe files to be opened with after setting .wad and .pk3 as default through "Open With"

While setting .pk3 files to "Open With" as SLADE, i found out that it's overwriting the app to open all .exe files, making me unable to even access CMD, forcing me to reinstall the whole OS. It's almost like ransomware although nothing is changed apart from how Windows recognized exe files to be opened with SLADE after and nothing, not even deleting SLADE fix this.
I'm using the binary version, not the installer version.

**Comment by sirjuddington** [comment]
This doesn't really have anything to do with SLADE itself, nothing in SLADE does anything to do with file associations, they need to be set up manually in Windows
