### ISSUE TITLE
TEXTURES visual editor corrupts textures with 'optional' keyword

### ISSUE THREAD

**Issue by jekyllgrim** [sirjuddington/SLADE#1236]
**SLADE Version**: (3.1.12)
**Operating System**: (Windows)

**Issue Details**:
Upon making any changes in the TEXTURES visual editor, it'll corrupt texture definitions that have **optional** keyword in them, such as this one:
```cs
Texture Optional "BDT_WFA1", 64, 128
{
    NoDecals
    Patch "WFALL1", 0, 0
}
```

They'll turn into this:
```cs
Texture "OPTIONAL", 0, 0
{
}
```

Since there are no alternative visual editors, it's a big problem...

**Comment by sirjuddington** [comment]
Will be fixed in 3.1.13
