### ISSUE TITLE
Slade Crashes upon opening a map in the built in editor. It crashes with a backtrace when any map is open.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [sirjuddington/SLADE#1245]
SLADE 3.2.0b2
Mageia Linux 8.

Slade Crashes opening a Hexen Mod. 
Slade Crashes upon opening a map in the built in editor. It crashes with a backtrace when any map is open.

If I can get a backtrace I will attach it to this bug.

Also, despite compiling from source and compiling Beta 2, Slade says it is compilng Beta 1 at run time.

**Comment by jwoodie** [comment]
This also happens on SLADE 3.2.0b3 on Arch Linux.

I'm also running wayland I don't know if it doesn't happen on X11.

**Comment by FlykeSpice** [comment]
I can't reproduce this on latest commits

**Comment by sirjuddington** [comment]
Closing this as it's likely fixed (I can't reproduce and neither can the last commenter)

**Comment by Zombie-Ryushu** [comment]
I've not tried recently.
