### ISSUE TITLE
Sprite drawing tools are totally busted

### ISSUE THREAD

**Issue by DarkPulse** [sirjuddington/SLADE#1249]
**SLADE Version**: 3.2.0.b2, also tested 3.1.12 with no success
**Operating System**: Windows 7 x64

**Issue Details**:
I'm attempting to draw pixels on a PNG sprite converted into Doom-formatted graphics for a GZDoom game port I'm working on. I'm going to need to do this in order to get proper player palette translations working properly, due to death frames for the player having an explosion graphic that are also shared by the parts of the sprite I would be applying color translation to. (The original game's graphics used a 16-color palette for the sprites, so there is heavy amounts of color sharing.)

I have enough room in the PLAYPAL for additional entries, so the normal solution would be to map the explosion colors into new PLAYPAL entries, create the translated player colors and also put those into the PLAYPAL, and then redraw the explosion colors using their new, exclusive spot on the PLAYPAL that's no longer shared by the player colors. End result: I can translate the parts of the sprite that would denote an individual player into different colors while still retaining properly-colored explosion graphics.

There's just one problem: SLADE isn't responding when I try to click to draw pixels. At all.

I can select a color from the PLAYPAL fine, and it seems like it "wants" to draw, but when I left-click to actually draw a pixel, absolutely nothing happens. I can't draw, I can't erase, I can't translate. Seemingly nothing works.

I figured it might be due to me having DPI scaling to 150% in Windows, but even when I tell Windows to disable DPI scaling for SLADE, it still simply does not draw, effectively rendering the sprite drawing stuff worthless.

Any help or solutions would be greatly appreciated. Thanks in advance.

**Comment by flarn2006** [comment]
I'm on 3.2.0b1 with Arch Linux, and the tool buttons don't even do anything for me; it just keeps the move tool selected.
