### ISSUE TITLE
Undoing and redoing lump creation erases the contents of the lump with no warning

### ISSUE THREAD

**Issue by flarn2006** [sirjuddington/SLADE#1252]
**SLADE Version**: 3.2.0 beta 1
**Operating System**: Linux

**Issue Details**:
I pressed Ctrl+Z to undo a change to a graphic lump's offset, but apparently changing the offset wasn't tracked by the undo mechanism, so it ended up undoing my action of importing the lumps. Which, of course, means it removed them. For some reason I had also invoked the Undo command a second time (I forgot exactly how or why that happened) and ended up doing the same to a text lump, into which I had pasted some text and made a few edits, which Undo apparently also skipped.

Naturally, I hit Ctrl+Y to Redo, and while it did end up re-creating the lumps, it didn't restore their contents, instead leaving them blank. (Even the images I had imported, though at least I can just reimport them.) I think this is a bug that ought to be fixed, because at no point was I warned that Redo wouldn't restore the data.

I was able to reproduce the bug as follows:

1. Create a text lump, and enter some text.
2. Select a different lump, and click Yes when prompted to save. Observe that (as expected) the text lump no longer has a size of 0.
3. Press Ctrl+Z, and observe that the text lump is removed.
4. Press Ctrl+Y. The text lump will reappear, but it will once again be empty.

The ideal solution, I think, would be to preserve lump contents in the undo buffer for as long as it's possible to redo, and restore it if the user does redo. But if for whatever reason that's impractical, there should at least be a warning, e.g.:

> You are about to undo the addition of the following lump(s):
> *[...]*
> This lump/These lumps will be removed, and you will not be able to restore their contents with Redo. Is this okay?
>
> [ Yes ] [ No ]

Of course, the above warning is not necessary if all affected lumps were empty to begin with.

**Comment by sirjuddington** [comment]
I think the issue here is when switching to a different entry, if you select yes to save changes it doesn't create an undo step for the modifications (it creates it as expected if you click the 'save' button before switching to a different entry)
