### ISSUE TITLE
Misidentification of Doom patches with 256 bytes length

### ISSUE THREAD

**Issue by coelckers** [sirjuddington/SLADE#1255]
**SLADE Version**: (3.1.7)
**Operating System**: Windows

**Issue Details**:
Any Doom patch with a length of exactly 256 bytes will be misidentified as SRB2 Encore and not properly displayed, it can also not be edited as a Doom patch. Example is attached.
[0056.zip](https://github.com/sirjuddington/SLADE/files/6565324/0056.zip)

**Comment by Gaerzi** [comment]
In the meanwhile, selecting the offending patches and typing "type gfx_doom" in the console can be used as a workaround to set the right type manually.

**Comment by sirjuddington** [comment]
The entry in the attached example zip is correctly identified as a doom patch in v3.1.13.
