### ISSUE TITLE
assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed

### ISSUE THREAD

**Issue by danfe** [sirjuddington/SLADE#1261]
Currently, SLADE spawns lots of windows on startup about `/usr/local/include/wx-3.0/wx/strvararg.h(462): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type`.  This happens because of the following line in `src/MainEditor/UI/StartPage.cpp`:
```c++
Log::debug(S_FMT("Tip index %d/%lu", last_tip_index_, (int) tips_.size()));
```
Second argument is cast to `int`, but format specifier is `%lu` which does not match it.  There are also several bugs like this in other parts of the code, particularly in MapEditor, e.g. when various `getIndex()` calls, which return an (unsigned) integer, are similarly passed to `%lu` format.

Unfortunately, it's hard to track them all down because assert message does not specify exact format string that triggers it.

**Comment by danfe** [comment]
I've asked my friend Clang to help me find those wrong format specifiers, by patching `S_FMT` macro and building SLADE with `-Werror-format`.  Then I've hunted them down by hand, one by one.  I think I've fixed most if not all of them, you can find the patch [here](https://cgit.freebsd.org/ports/tree/games/slade/files/patch-format-strings).

**Comment by danfe** [comment]
Sorry, forgot that `long` is 4 byte type on 32-bit architectures, which is not enough to hold `int64_t` value.  So those two lines of the `src/MainEditor/UI/EntryPanel/DataEntryPanel.cpp` part of the patch need to be changed to:
```c++
int64_t val;
data_.read(&val, 8);
return S_FMT("%lld", (long long)val);
```

**Comment by sirjuddington** [comment]
Hmm, I'm having trouble getting that patch to apply correctly, if possible would you be able to submit a pull request for the changes?

**Comment by danfe** [comment]
Yes, the master branch is very different from release 3.1.13 which my patch is against.  Okay, let's try the pull request way (once I learn how to do this).

**Comment by sirjuddington** [comment]
I was trying the patch against stable (S_FMT isn't used at all in master since I switched to the fmt library)

**Comment by danfe** [comment]
> I was trying the patch against stable

Hmm, I just did this and it worked with no troubles:
```
$ md5 /tmp/patch-format-strings 
MD5 (/tmp/patch-format-strings) = 456fb2bff84722d8346e4c198a34fb86
$ git clone ...
$ git checkout --track origin/stable
$ patch < /tmp/patch-format-strings ; echo $?
<... most of the output skipped ...>
Patching file src/Utility/Tokenizer.cpp using Plan A...
Hunk #1 succeeded at 1011.
done
0
```
What the MD5 hash of the patch you were trying to apply?

**Comment by danfe** [comment]
Anyway, I've tried to create a pull request #1262 for it, not sure if I've followed all the steps correctly (git is so baroque!) but amount of green colors on GitHub suggests it's probably okay.

**Comment by sirjuddington** [comment]
Ok thanks, all merged, closing the issue
