### ISSUE TITLE
Suggestion - Combine "Open" and "Open Directory" into a new single "Open"

### ISSUE THREAD

**Issue by Frozsoul2019** [sirjuddington/SLADE#1268]
When the user selects the new single "Open" it would proceed with either the current "Open" if a file is selected to be opened, or with the current "Open Directory" if a directory is selected to be opened.  This would allow CTRL+O to be a shortcut to open either files or directories.

**Comment by sirjuddington** [comment]
Unfortunately this isn't really possible because there is no 'combined' file/dir selection dialog in wxWidgets, it's file or directory only, not both.
