### ISSUE TITLE
We need UMAPINFO support

### ISSUE THREAD

**Issue by Pedro-Beirao** [sirjuddington/SLADE#1269]
**SLADE Version**: 
**Operating System**: OSX

**Issue Details**:
UMAPINFO is growing and support for it would be awesome

**Comment by sirjuddington** [comment]
UMAPINFO support is added for the next 3.2.0 release (9d391fdae23273baa92672232ad553fd2cb83f24)

Unfortunately the macos version is still in limbo as I can't build for it and no one has stepped up to maintain the macos side of things
