### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by Pedro-Beirao** [sirjuddington/SLADE#1270]
**SLADE Version**: 
**Operating System**: OSX

@sirjuddington 
Hey Im the guy who asked about the UMAPINFO support 3 days ago.
I'd be happy to maintain the macos support, compile it whenever there's a new release.
I'm also the maintainer of the macos support of dsda-doom source port btw

**Comment by Pedro-Beirao** [comment]
So I just tried compiling the latest version of Slade, and I encountered a lot of problems, but I was able to fix them all.
Im going to make a pull request with the necessary changes to make it work on MacOS

**Comment by sirjuddington** [comment]
Yeah thanks for the pr, an active macos maintainer is sorely needed (the last working macos release is nearly 2 years old now)
