### ISSUE TITLE
Copy/pasting on TEXTUREx editor brings excess textures

### ISSUE THREAD

**Issue by Nour-T** [sirjuddington/SLADE#1280]
**SLADE Version**: (3.2.0 beta 3)
**Operating System**: (Windows 10 version 21H1 (Build 19043.1165))

**Issue Details**:
Most of TEXTUREx editor is functional to me, but when I attempt to copy and paste a texture, it stacks up the more I try to copy a file, as shown in the gif.
It can be partially be fixed by closing and reopening the program, but copying and pasting more than one file would cause the stacking issue to happen again.

![FC9edG6Dgt](https://user-images.githubusercontent.com/49839815/132386749-0c89d6bc-9186-4a43-8bc1-a024a3594579.gif)

**Comment by Nour-T** [comment]
Do note that this is my first time submitting an issue, and I did give the guidelines a good look before I posted, but I'm more than willing to cooperate if I did it wrong.

**Comment by Gaerzi** [comment]
I think this was fixed already? It looks like a duplicate of #1258.

Though yes, the fix happened a couple days /after/ the latest release, so there's no official build out there without that bug.

**Comment by Nour-T** [comment]
oooh, i see
 well then, guess I should build SLADE then
 thank you for notifying me though, i couldn't find the issue for some reason but now I do
