### ISSUE TITLE
UMAPINFO text language

### ISSUE THREAD

**Issue by Some1NamedNate** [sirjuddington/SLADE#1282]
**SLADE Version**: 3.1.13
**Operating System**: Windows

**Issue Details**:
Add the UMAPINFO language for use with the UMAPINFO lump.

https://github.com/coelckers/prboom-plus/blob/master/prboom2/doc/umapinfo.txt

**Comment by sirjuddington** [comment]
This is already done (will be in the next beta)

see 9d391fdae23273baa92672232ad553fd2cb83f24
