### ISSUE TITLE
Snap to grid not working

### ISSUE THREAD

**Issue by RobG66** [sirjuddington/SLADE#1286]
SLADE Version 3.2.0 beta
Windows 10

 A few times now I have started to edit a map and the 'snap to grid' is not working.  Exiting map editor and re-entering map editor does not fix this.  Closing slade completely and re-opening does fix it.

Rob

**Comment by sirjuddington** [comment]
The grid snapping is toggleable (shift+G by default), maybe you accidentally pressed the shortcut key for it?
