### ISSUE TITLE
Linedef specials don't save in 3.2.0. beta 3

### ISSUE THREAD

**Issue by kpuljek** [sirjuddington/SLADE#1293]
**SLADE Version**: (3.2.0. beta 3)
**Operating System**: (Linux)

**Issue Details**:
After moving to Manjaro I ended up using the 3.2.0. beta 3 and noticed that, when editing linedefs to point to other sectors via tags (like when setting a switch to open a generic door), it doesn't save the "Special" values at all. I can modify other values for the linedef, but the Specials end up forgotten and the switch always points to the sector behind it. Installing the "old" stable from Flatpak works as expected.

**Comment by Catoptromancy** [comment]
You can work around this by clicking another field. Example: Edit Special, then click on Sector Tag, then click on green check mark. Works for all the other fields that dont save too.

Also what does work well is right clicking the line/sector/thing and selecting properties at the bottom. That menu seems to be fully functional and actually better than using side panel, just takes an extra click to get to.

**Comment by kpuljek** [comment]
I know about that workaround as I've been using Slade for a while now and always make sure to click the green confirmation just in case. It just refuses to save the Specials, even if I open the right click propeties dialog and enter them in the Args tab, it shows the sector reference, but as soon as I deselect the line it resets to zeroes, even after clicking the green button. Here's a GIF, please let me know if I'm missing any steps

![Peek 2021-11-08 12-07](https://user-images.githubusercontent.com/9851336/140731810-a228d023-5312-4f48-9304-37e777f4090c.gif)
.

**Comment by kevans91** [comment]
I ran into this on FreeBSD with 3.1.13 as well... I seem to be hitting it as early as 9128396e3bb61e, but I'm still bisecting around (git's being problematic with stray odd line endings).
