### ISSUE TITLE
Graphic tools problems in latest beta

### ISSUE THREAD

**Issue by spherallic** [sirjuddington/SLADE#1299]
**SLADE Version**: 3.2.0 beta 3
**Operating System**: Windows

**Issue Details**:
Editing graphics seems to have regressed from v3.1.13.
First of all, the pencil icon seems to be labeled "Drag pixels", which seems like a mistake.
Secondly, I'm having the opposite problem of #975: Drawing pixels (or erasing/translating them) works fine for me in v3.1.13, but not anymore in v3.2.0 beta 3, even after setting a brush shape. All actions above the graphic work fine as usual, but all actions to the left of the graphic don't seem to do anything.

**Comment by sirjuddington** [comment]
This will be fixed in the next beta release (see https://github.com/sirjuddington/SLADE/commit/94e11ff7077883d92af6681fb716cb615fa2d02d)

**Comment by swc132994** [comment]
I just want to note that this has never been addressed and is still present on Slade v3.2.5
![image](https://github.com/sirjuddington/SLADE/assets/10770202/8776ef36-a893-4dd7-a536-6be88620172b)
