### ISSUE TITLE
Unable to run level because gzdoom executable cannot be set

### ISSUE THREAD

**Issue by janwilamowski** [sirjuddington/SLADE#1303]
**SLADE Version**: 3.1.13, installed with flatpak
**Operating System**: Ubuntu Linux 18.04

**Issue Details**:
In the configuration, I cannot set the zdoom pk3 path (which in my case is `/opt/gzdoom/gzdoom.pk3`). The folder selection dialog simply doesn't show the /opt directory and also won't let me enter it directly. Adding a symbolic link to the folder also doesn't work. When I manually edit the slade3.cfg and set the gzdoom executable path to `/opt/gzdoom/gzdoom`, once I try to run a very simple level from the map editor, I get an error window saying "Invalid executable path".

Since I'm on Linux I cannot use the doom2.exe directly. I'm using gzdoom v4.3.3.

**Comment by janwilamowski** [comment]
Small update: the problem seems to have something to do with flatpak. I enabled full file system access for Slade through Flatseal and have now advanced to the next error: `/opt/gzdoom/gzdoom: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory`. Should this issue be discussed on https://github.com/flathub/net.mancubus.SLADE instead?

**Comment by janwilamowski** [comment]
I ended up installing Slade through `apt`, as described on http://slade.mancubus.net/index.php?page=wiki&wikipage=Installation which worked flawlessly.

**Comment by Akeem29** [comment]
For me this isn't an option because Fedora Silverblue is weird, but I ended up setting up shell scripts that automatically load my WADs
