### ISSUE TITLE
Compiling for Visual Studio issues

### ISSUE THREAD

**Issue by ill** [sirjuddington/SLADE#1307]
I have Microsoft Visual Studio Community 2022 (64-bit) and followed all the instructions here: http://slade.mancubus.net/index.php?page=wiki&wikipage=Windows-Step-By-Step-Compilation

It seemed like none of the include paths were actually set, and I had to also download all the other libs you have listed, like zlib, lua, etc...

I had to add all of these under VC++ Directories include directories, and downloaded all of these additional things from just google searches:

$(WxWin)\include
$(WxWin)\include\msvc
$(SFML)\include
$(FREEIMAGE)\Dist\x32
$(fmt)\include
$(GLEW)\include
$(MPG)
$(LUA)\src
$(ZLIB)
$(BZLIB)\cbits

Eventually the code itself built but then there's the linking step which fails next.  It would appear I need to figure out how to compile all of these libs too to.  I've used SFML and GLEW before, but most of these seem trivial to compile on POSIX systems instead.

Have people been having better luck compiling on mac?  Or maybe I should properly follow instructions and it's somehow easier with VS 2019?

**Comment by ill** [comment]
It would really help if the windows build just came with a bunch of the libraries all precompiled and ready to go, even though you normally want to avoid comitting libs.  Or have very clear instructions on how to get things like lua ready.  I mostly just wanted to add a few useful utilities to the ZDoom texture feature and have it be part of SLADE instead of a random console app.

**Comment by ill** [comment]
Well I managed to compile it on Mac at least: https://github.com/sirjuddington/SLADE/issues/1309

**Comment by sirjuddington** [comment]
Those instructions are very out of date, it's a lot easier to compile using vcpkg to handle the external libs - see the (very basic for now) instructions [here](https://github.com/sirjuddington/SLADE/blob/master/COMPILE.md)

**Comment by ill** [comment]
Oh very nice!  Thanks!
