### ISSUE TITLE
Building .pk3 on Windows uses Absolute Filepath

### ISSUE THREAD

**Issue by GeordanKrahn** [sirjuddington/SLADE#1315]
**SLADE Version**: (3.1.13)
**Windows 10 64 bit**

**Issue Details**:
When building a .pk3 archive, the archive is built using the absolute file path to the folder where the mod files are located, rather than a relative path. The result is when the .pk3 is loaded, my /Users folder is the top level folder.

Every time this happens I need to manually change the file structure to allow the .pk3 to load into a source port properly.

**Comment by sirjuddington** [comment]
I'm not sure what you mean here - are you referring to the 'Build Archive' option in the Archive menu?

**Comment by GeordanKrahn** [comment]
Yes. When i select Archive > Build Archive, the resulting file whether it is a .zip folder, or a .pk3 always build the archive from my users folder. so i get something like this:

ArchiveName/Users/Username/.../src

when it should just be

ArchiveName/src

The only way to find out if it worked is by inspecting the archive with a tool like 7z. When it uses an absolute path, the source port will load all lumps, but they are not accessible.

**Comment by GeordanKrahn** [comment]
wierd
