### ISSUE TITLE
Incomplete Fedora step-by-step compilation instructions

### ISSUE THREAD

**Issue by maxwelljens** [sirjuddington/SLADE#1317]
**SLADE Version**: v3.2.0 beta 3 (c49b0af)
**Operating System**: Fedora 35

**Issue Details**:
I followed the instructions on [this page](http://slade.mancubus.net/index.php?page=wiki&wikipage=Fedora-Step-by-Step-Compilation) to compile SLADE3 from source on my computer. Most of the dependencies seemed satisfied, but there were two missing that prevented successful compilation: `lua-devel` and `fmt-devel`, or Lua development and fmt development files. In other words, they should be listed as part of the list of dependencies required for compilation. Both of these are available in the official Fedora repositories.

In the end I compiled SLADE3 successfully, with GTK3, and am able to use it just perfectly.

**Comment by sirjuddington** [comment]
wiki page updated
