### ISSUE TITLE
Only open/save one TEXTURES lump at a time

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#1320]
I would prefer if SLADE doesn't open all TEXTURES lumps at once, since this can often intervene with others that I was making and have specific comments that are necessary for preservation. Because it saves over the lumps, I basically have to copy/paste every other lump into a separate text document and restore them after messing with the TEXTURES editor, which is cumbersome.

Please allow an option to only open/save specific TEXTURES lumps - at the very least, saving only the one that's active. I think that alone will suffice in fact. Perhaps introduce another button, "Save All", with a confirmation dialogue warning that all formatting will be erased (with a "Do not show this again" checkbox.)

**Comment by sirjuddington** [comment]
Hmm, did you modify the other TEXTURES lumps at all in the editor? It should only ever save them if they have been modified, so as long as you don't touch them with the editor they shouldn't be overwritten.

You can also already save only the current list by clicking the save button at the top left of the list

**Comment by sirjuddington** [comment]
Closing this one as it's already possible
