### ISSUE TITLE
Crash 3.2.0 beta 4: Can't convert "lineid" to an integer on MAP lump preview

### ISSUE THREAD

**Issue by Eonfge** [sirjuddington/SLADE#1326]
**SLADE Version**: 3.2.0 beta 4
**Operating System**: Linux

**Issue Details**:

Build against WxWidgets 3.1.5, SLADE crashes once you open WAD and you click on a MAP lump.

**Stack trace**:
Version: 3.2.0 beta 4
No current action

Operating System: Linux 5.16.18-200.fc35.x86_64 x86_64
Graphics Vendor: AMD
Graphics Hardware: AMD Radeon RX 6700 XT (NAVY_FLOUNDER, DRM 3.44.0, 5.16.18-200.fc35.x86_64, LLVM 12.0.1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 21.3.8 (git-813ee839be)

Stack Trace:
0: [unknown location] [unknown:139994499855684]
1: [unknown location] [unknown:139994399725529]
2: [unknown location] [unknown:139994473401952]

Last Log Messages:
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
SLADE Initialisation OK
Opening archive /home/kevin/.var/app/net.mancubus.SLADE/IWAD/DOOM2.WAD
Opening took 396 ms
Setting up the OpenGL context
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 16384x16384
OpenGL initialization failed: Unknown error

**Comment by Eonfge** [comment]
For your info, I also made a 3.2.0 beta build against 3.1.3 that can be tried here:
https://github.com/flathub/net.mancubus.SLADE/pull/31

**Comment by sirjuddington** [comment]
Does this happen when opening any kind of opengl window (eg. the gfx editor)? The log says opengl initialization failed so I'm thinking it isn't necessarily to do with the map preview. I know wx pre-3.1.6 has issues with wayland, which might be causing it

**Comment by Eonfge** [comment]
I was running SLADE on Fedora 35, using x11 window manager. For the time being, I'll keep SLADE marked as an x11-only application but in the future we might also try Wayland.

Something not really mentioned in any of the documents, what Autotools-config settings does SLADE need for WxWidgets? Here you can find the current config-options that I use;
[ config-opts:](https://github.com/flathub/net.mancubus.SLADE/blob/3f05f399de3ca78dd28df1afc74aa7bb175c0a4b/net.mancubus.SLADE.yaml#L154)

Note that `--enable-webkit` does not exist in 3.1.4 and up.

I'll try the gfx editor later.

**Comment by sirjuddington** [comment]
Those config options should work yeah, the only 100% required one is opengl, webview is optional but reccommended. It shouldn't need the sdl stuff.

**Comment by Eonfge** [comment]
> Does this happen when opening any kind of opengl window (eg. the gfx editor)?

Can confirm...

```
Version: 3.2.0 beta 4
No current action

Operating System: Linux 5.16.18-200.fc35.x86_64 x86_64
Graphics Vendor: AMD
Graphics Hardware: AMD Radeon RX 6700 XT (NAVY_FLOUNDER, DRM 3.44.0, 5.16.18-200.fc35.x86_64, LLVM 12.0.1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 21.3.8 (git-813ee839be)

Stack Trace:

Last Log Messages:
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
SLADE Initialisation OK
Opening archive /home/kevin/.var/app/net.mancubus.SLADE/IWAD/DOOM2.WAD
Opening took 377 ms
Setting up the OpenGL context
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 16384x16384
OpenGL initialization failed: Unknown error

```

**Comment by sirjuddington** [comment]
Ok I've tracked this down to GLEW, seems glewInit is failing on linux for some reason, might just try switching to GLAD or something else to handle the OpenGL extensions...
