### ISSUE TITLE
SLADE cannot save changes on files opened in a new tab.

### ISSUE THREAD

**Issue by inkoalawetrust** [sirjuddington/SLADE#1332]
**SLADE Version**: (3.2.0) Beta 4
**Operating System**: Windows 10 21H2

**Issue Details**:
As of 3.2.0 Beta 4. SLADE can no longer save changes to files opened in a new tab. Neither the Save button or shortcut works for the file. The only way to save changes to the file is to save the whole directory or archive. By either pressing CTRL+S or going back to the directory/archives' tab and pressing the Save button there. However, you can save changes to the file normally. If you have it opened on the same tab as the directory/archive.

I've attached a video of me producing and replicating the bug below.

https://streamable.com/972fco

**Comment by inkoalawetrust** [comment]
I'm noticing another bug related to this in 3.2.0. While in another tab, you cannot press the save button on the top toolbar to save the changes done to the archive itself. You have to go to the archives' tab to press the save button.

And for that matter, you can't press CTRL+S while in another tab, to save changes to the archive itself either, this one has been a bug even prior to 3.2.0.

**Comment by sirjuddington** [comment]
That's because the 'Save' menu item/toolbar button was changed to just save whatever is in the current tab, rather than the archive that contains what is in the tab. To save the archive you need to either switch to its tab or use Save All (Ctrl+Shift+S)
