### ISSUE TITLE
Quick search in lump pane

### ISSUE THREAD

**Issue by Xenaero** [sirjuddington/SLADE#1342]
**SLADE Version**: (3.2.0)
**Operating System**: (Windows)

**Issue Details**: 
While filter does good at isolating your search, being able to jump around a larger wad or pk3 is also helpful. This is meant to be a quality of life improvement, where say if you typed the first few letters of the lump name while in the lump pane, it would locate and jump the pane to that lump. This is helpful if you're looking to view adjacent lumps quickly, especially so if you know say, one sprite's name offhand but not another that you're searching for.

**Comment by MrAlaux** [comment]
This sounds exactly like something that I could do back in 3.1.1.3, but that stopped working in 3.2.0. The description is pretty much the same, and the feature was overall identical to an option in Windows Explorer: "Select the typed item in the view". I thought that the new tree view was the culprit of the issue, but I tried toggling that and many other options and it still won't work anymore.
