### ISSUE TITLE
Flat List doesn't Drag-and-Drop anymore

### ISSUE THREAD

**Issue by spamzilla** [sirjuddington/SLADE#1343]
**SLADE Version**: 3.2.0
**Operating System**: Windows 10

**Issue Details**:
In 2.3.0, when the Entry List is set to Flat List, it won't allow me to drag-and-drop like in previous versions.

**Comment by sirjuddington** [comment]
I'm not sure what you mean - you were never able to drag entries around in previous versions, and dragging files between the entry list and file explorer still works

**Comment by sirjuddington** [comment]
Going to close this one, there was an issue with dragging files that was fixed in 3.2.1 so that should all work ok now
