### ISSUE TITLE
Deleting duplicate flat resulted in crash

### ISSUE THREAD

**Issue by auratoostronk** [sirjuddington/SLADE#1344]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
Tried to save an old file. Gave me an error that there were multiple flats named the same. Deleted one (lmp) and deleted another (png) and it crashed after the second.

**Comment by sirjuddington** [comment]
If possible can you get this to happen again at all? I can't reproduce it so a stack trace and/or any other info would be useful

**Comment by auratoostronk** [comment]
my apologies for the late response. I have not had this bug since, I'll let you know if something comes up again :)
