### ISSUE TITLE
Start page not loading on Ubuntu 22.04

### ISSUE THREAD

**Issue by Blzut3** [sirjuddington/SLADE#1349]
**SLADE Version**: 3.2.0
**Operating System**: Kubuntu 22.04

**Issue Details**:
Start page is blank with only "wxWebView Error: Frame load interrupted" logged to console.  I don't have time to confirm, but this might be exclusive to running on 22.04.  Interestingly simply replacing:
`html_startpage_->LoadURL(html_file);`
With
`html_startpage_->SetPage(html, html_file);`
Is enough to fix it.  I'm not sure if there's a particular reason you have it writing out the start page to disk vs doing that?  Of course I'm not sure why that fixes it either since the file on disk looks fine to me.

Documentation loads fine, this only affects the start page, and from what I can tell the editor is fully functional otherwise.

Binary with broken start page I'm using has been published to the DRD Team repo.  It's built with wxWidgets 3.1.5.

**Comment by sirjuddington** [comment]
Hmm ok, might have to make that conditional for gtk/osx webview backends, I'm using LoadURL because SetPage doesn't work on the ie/edge backend used in windows.

It's written to disk so that the images can be loaded, though now that the images/icons are all svgs, I could potentially just embed them

**Comment by Blzut3** [comment]
Although it would ultimately be cool to avoid writing to disk altogether, the images load fine from disk thanks to the second parameter of SetPage so either way.
