### ISSUE TITLE
Graphic viewer might flicker when cycling between graphics

### ISSUE THREAD

**Issue by MrAlaux** [sirjuddington/SLADE#1353]
**SLADE Version**: 3.2.0
**Operating System**: Windows 7

**Issue Details**:
Every time I move between graphic lumps, there's a chance that the graphic viewer will momentarily disappear for a matter of milliseconds, showing the last viewed non-graphic viewer content instead. This did not happen in 3.1.1.3.

Example:

I'm currently viewing POSSI0
![image](https://user-images.githubusercontent.com/73968015/165656227-95a3b2f8-4b4f-4c75-9ff8-95cf5a2ee78c.png)

I then click on POSSJ0
When doing so, this might happen for a very brief moment (in this case, what's displayed is a blank screen, although it could be the text editor, the start page, etc.)
![Sin título](https://user-images.githubusercontent.com/73968015/165656790-5b663ed2-90b0-4cae-a2f1-2494e411c16c.png)

Then, the expected content comes up
![image](https://user-images.githubusercontent.com/73968015/165657029-0f49eff2-0f8e-4985-8de3-a0c05dc70880.png)

**Comment by MrAlaux** [comment]
**Update:** using SLADE 3.2.1, the problem seems to be gone, although only now I realize that it might've been a problem specifically with my computer (no evidence on it, but it sounds feasible).

I'll update on the situation if the problem reappears while using the same version of SLADE, but for the time being, I think the issue can be closed, but I'll leave that decision up to the dev(s).

**Comment by sirjuddington** [comment]
Funnily enough I started getting this issue when I upgraded my PC, it's fixed for 3.2.5 either way.
