### ISSUE TITLE
Image Viewer Misplaced

### ISSUE THREAD

**Issue by MechaXYZ** [sirjuddington/SLADE#1361]
**SLADE Version**: (3.2.0)
**Operating System**: (ChromeOS Debian 11)
I really have no idea why this happens, but the image viewer is misplaced and I have no idea how to fix it.
![Screenshot 2022-04-30 4 51 09 PM](https://user-images.githubusercontent.com/93439705/166123850-87cefd9e-b35a-4b13-b57c-80d6f2f6b399.png)

**Comment by sirjuddington** [comment]
This is the same as #1351 - see https://github.com/sirjuddington/SLADE/issues/1351#issuecomment-1108431471 for a fix
