### ISSUE TITLE
Unable to edit textures

### ISSUE THREAD

**Issue by inventor200** [sirjuddington/SLADE#1364]
**SLADE Version**: 3.2.0
**Operating System**: Ubuntu 22.04

**Issue Details**:
I'm not able to locate a crash report for Slade, but I've set aside a copy of my project that will recreate all the bugs I'm finding in case any testing is needed. (I've also submitted 2 other issues that I've found today. I'm sorry lol)

If I try to edit any kind of TEXTURE entry at all, whether it's Doom2's TEXTURE1 lump, or a ZDoom TEXTURES file, the program blacks out the entire preview part of the UI, and hangs. Sometimes it just closes spontaneously. Re-opening Slade shows that nothing happened to the textures, so the data is safe. However, I have to edit the TEXTURES file in a text editor for the moment.

Slade is able to use other texture utilities, however, like the one that ports single-patch textures for ZDoom; that works perfectly fine. However, attempting to open the texture editor is what causes the hang/crash.

If there's any more tests you need me to run, then I'll write back to you here.

**Comment by inventor200** [comment]
UPDATE: I have invited you as a collaborator for the mapping project on GitHub, so you can download the contents for testing, if need be.

**Comment by sirjuddington** [comment]
This is the same issue as #1362
