### ISSUE TITLE
Mac OSX version has only partial support for system-set Dark Mode

### ISSUE THREAD

**Issue by Superjustinbros** [sirjuddington/SLADE#1384]
**SLADE Version**: (3.1.6)
**Operating System**: OSX

**Issue Details**: When running SLADE on a Macintosh with "Dark Mode" set in the system's settings, the program's text, archive manager, and file viewer will properly invert colors to display white text on a back background, however, the rest of the program will use white text on a white background, making it difficult, if not impossible, to see the program's text.
<img width="1136" alt="Screen Shot 2022-05-21 at 10 15 41 PM" src="https://user-images.githubusercontent.com/4167951/169675654-c15b4879-28c2-40f4-86e0-dc1b65c57667.png">
I would suggest giving the program the ability to detect if the system is set to Dark Mode, and, if so, automatically load a separate set of assets that recolors the general window from white and light grey to dark grey and black respectively.

**Comment by globau** [comment]
You can work around this by setting `NSRequiresAquaSystemAppearance` to `true` in `Info.plist`.

**Comment by Superjustinbros** [comment]
Where may I find this file so i can force light mode? Seems like it should always be set to true until (and if) someone makes a version that gives SLADE proper dark mode support?

**Comment by globau** [comment]
> Where may I find this file so i can force light mode?

It's inside the `SLADE.app` bundle.

1. Right-click on the SLADE application in Finder and selected "Show Package Contents"
2. Open the "Contents" directory
3. Right-click on "Info.plist" then "Open With" and select "TextEdit" (you might have to select "Other" if "TextEdit" doesn't appear in the initial list)
4. Add the following two lines near the bottom of the file, before `</dict>`:
  `<key>NSRequiresAquaSystemAppearance</key>`
  `<true/>`

The last six lines of the file should look like (the spaces at the start of each line are not important):
```
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
	<key>NSRequiresAquaSystemAppearance</key>
	<true/>
</dict>
</plist>
```

5. Save changes and Quit

> Seems like it should always be set to true until (and if) someone makes a version that gives SLADE proper dark mode support?

Correct.

**Comment by Pedro-Beirao** [comment]
This is fixed in newer versions
