### ISSUE TITLE
Crash when filter controls are toggled

### ISSUE THREAD

**Issue by narzepatel** [sirjuddington/SLADE#1403]
Version: 3.2.1 (x64)
No current action

Operating System: Windows 10 (build 19044), 64-bit edition
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: [unknown location] LibRaw::rgb_to_lch
1: [unknown location] std::unique_ptr<std::basic_streambuf<char,std::char_traits<char> >,std::default_delete<std::basic_streambuf<char,std::char_traits<char> > > >::get
2: [unknown location] LibRaw::rgb_to_lch
3: [unknown location] LibRaw::rgb_to_lch
4: [unknown location] LibRaw::rgb_to_lch
5: [unknown location] LibRaw::rgb_to_lch
6: [unknown location] LibRaw::rgb_to_lch
7: [unknown location] LibRaw::rgb_to_lch
8: [unknown location] LibRaw::rgb_to_lch
9: [unknown location] LibRaw::rgb_to_lch
10: [unknown location] LibRaw::rgb_to_lch
11: [unknown location] LibRaw::rgb_to_lch
12: [unknown location] CallWindowProcW
13: [unknown location] DispatchMessageW
14: [unknown location] IsDialogMessageW
15: [unknown location] LibRaw::rgb_to_lch
16: [unknown location] LibRaw::rgb_to_lch
17: [unknown location] LibRaw::rgb_to_lch
18: [unknown location] LibRaw::rgb_to_lch
19: [unknown location] LibRaw::rgb_to_lch
20: [unknown location] LibRaw::rgb_to_lch
21: [unknown location] LibRaw::rgb_to_lch
22: [unknown location] LibRaw::rgb_to_lch
23: [unknown location] LibRaw::rgb_to_lch
24: [unknown location] LibRaw::rgb_to_lch
25: [unknown location] BaseThreadInitThunk
26: [unknown location] RtlUserThreadStart

Last Log Messages:
Opening archive dfslaughter.pk3
Can't convert "-" to an integer (invalid)
Can't convert "\" to an integer (invalid)
Can't convert "[" to an integer (invalid)
Can't convert "[" to an integer (invalid)
SLADE Initialisation OK
Checking for updates...
Latest stable release: v3.2.1
Latest beta release: v3.2.0 beta 4
Already up-to-date

**Comment by sirjuddington** [comment]
I think this should have been fixed in 3.2.2, feel free to reopen if it still happens
