### ISSUE TITLE
Entry Too Large

### ISSUE THREAD

**Issue by jokeriago** [sirjuddington/SLADE#1412]
**SLADE Version**: (3.2.1.x)
**Operating System**: (Windows)

**Issue Details**:
(I'm trying to import a file with 883mb, but im reving a error, saying that the file is too large. Can you please increase the file size limit to 1GB, or even more? Please?)

![image](https://user-images.githubusercontent.com/111095952/184259256-09752a28-d04f-4f01-accd-114941e15c7c.png)

**Comment by sirjuddington** [comment]
There is a cvar to control this - `max_entry_size_mb`, by default it is 512, set it to 1024 for 1gb limit
