### ISSUE TITLE
[Map Editor] Add 3d floor/polyobject rendering in the 3d view

### ISSUE THREAD

**Issue by darkhog** [sirjuddington/SLADE#1421]
**SLADE Version**: (3.2.1)
**Operating System**: Windows

**Issue Details**:
Doom builder already has feature to render 3d floors directly in the 3d view, making editing them easier (not sure about polyobjects, but hey, Slade can one-up DB in that regard!). Code to do that could be either borrowed from the Doom Builder or just from GZDoom proper.

**Comment by sirjuddington** [comment]
It'll happen eventually, for now closing this as it's a duplicate of #205
