### ISSUE TITLE
Slade crash when cutting flats

### ISSUE THREAD

**Issue by EffinghamHuffnagel** [sirjuddington/SLADE#1424]
**SLADE Version**: (3.2.1.x)
**Operating System**: (Windows 10)

**Issue Details**:
Hightlighted a set of flats and tried to cut them to put in another wad. Has happened before, but not every time.

Version: 3.2.1 (x86)
Current action: arch_entry_cut
Operating System: Windows 10 (build 19043), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: NVIDIA GeForce GTX 660/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 471.41

Stack Trace:
0: (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory:3050) std::weak_ptr<slade::ArchiveEntry>::lock
1: (H:\Dev\SLADE\Build\src\Archive\ArchiveDir.cpp:106) slade::ArchiveDir::path
2: (H:\Dev\SLADE\Build\src\Archive\ArchiveEntry.cpp:159) slade::ArchiveEntry::path
3: (H:\Dev\SLADE\Build\src\MapEditor\MapTextureManager.cpp:628) slade::MapTextureManager::buildTexInfoList
4: (H:\Dev\SLADE\Build\src\MapEditor\MapTextureManager.cpp:560) slade::MapTextureManager::refreshResources
5: (H:\Dev\SLADE\Build\thirdparty\sigslot\signal.hpp:692) sigslot::signal_base<std::mutex>::operator()
6: (H:\Dev\SLADE\Build\thirdparty\sigslot\signal.hpp:464) sigslot::detail::slot<<lambda_b31a6483af5613a190c22c666209867b>,slade::Archive &,slade::ArchiveDir &,slade::ArchiveEntry &>::call_slot
7: (H:\Dev\SLADE\Build\src\Archive\Archive.cpp:1057) slade::Archive::removeEntry
8: (H:\Dev\SLADE\Build\src\Archive\Formats\WadArchive.cpp:788) slade::WadArchive::removeEntry
9: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:1195) slade::ArchivePanel::deleteEntry
10: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:1878) slade::ArchivePanel::cutEntry
11: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:3390) slade::ArchivePanel::handleAction
12: (H:\Dev\SLADE\Build\src\General\SAction.cpp:466) slade::SActionHandler::doAction
13: (H:\Dev\SLADE\Build\src\Application\SLADEWxApp.cpp:581) SLADEWxApp::onMenu
14: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:655) wxAppConsoleBase::HandleEvent
15: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:666) wxAppConsoleBase::CallEventHandler
16: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1439) wxEvtHandler::ProcessEventIfMatchesId
17: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1901) wxEvtHandler::SearchDynamicEventTable
18: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\include\wx\event.h:4007) wxEvtHandler::TryBeforeAndHere
19: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1534) wxEvtHandler::ProcessEvent
20: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1498) wxEvtHandler::TryAfter
21: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\wincmn.cpp:3542) wxWindowBase::TryAfter
22: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1547) wxEvtHandler::ProcessEvent
23: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\wincmn.cpp:3536) wxWindowBase::TryAfter
24: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1547) wxEvtHandler::ProcessEvent
25: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1660) wxEvtHandler::SafelyProcessEvent
26: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\menucmn.cpp:673) wxMenuBase::SendEvent
27: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\framecmn.cpp:295) wxFrameBase::ProcessCommand
28: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\frame.cpp:814) wxFrame::HandleCommand
29: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\frame.cpp:871) wxFrame::MSWWindowProc
30: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:2940) wxWndProc
31: [unknown location] AddClipboardFormatListener
32: [unknown location] GetClassLongW
33: [unknown location] DispatchMessageW
34: [unknown location] DispatchMessageW
35: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:166) wxGUIEventLoop::ProcessMessage
36: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:227) wxGUIEventLoop::Dispatch
37: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:239) wxEventLoopManual::ProcessEvents
38: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:288) wxEventLoopManual::DoRun
39: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:87) wxEventLoopBase::Run
40: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:377) wxAppConsoleBase::MainLoop
41: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\init.cpp:504) wxEntryReal
42: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:175) wxEntry
43: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:296) wxEntry
44: (H:\Dev\SLADE\Build\src\Application\SLADEWxApp.cpp:372) WinMain
45: (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288) __scrt_common_main_seh
46: [unknown location] BaseThreadInitThunk
47: [unknown location] RtlGetAppContainerNamedObjectPath
48: [unknown location] RtlGetAppContainerNamedObjectPath

Last Log Messages:
Can't convert "stairs_builddowndoom" to an integer (invalid)
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Opening map MAP11
Removed 233 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors

**Comment by sirjuddington** [comment]
I think this is the same crash fixed in 778de597cae25dbe48628134bdc373c58389f400, so it should be fixed in 3.2.2 when released
