### ISSUE TITLE
Filtering in the Tree list style is broken

### ISSUE THREAD

**Issue by jwaffe75** [sirjuddington/SLADE#1432]
**SLADE Version**: (3.2.1)
**Operating System**: Linux (Ubuntu Mate 22.04)

**Issue Details**:

1. In Settings, make sure Interface -> Entry List -> Folder List Style is set to Tree
2. Open any PK3, e.g., like the one attached
3. Show the filter and type CPOS, note that nothing in the Sprites folder shows up
    - Note that this happens even if I uncheck Interface -> Entry List -> "Ignore directories when filtering by name"
5. Clear the filter using the red x button
6. The whole "tree" is gone and replaced with just Sprites as a folder entry and there's no way to expand it again until you reopen the pk3

![image](https://user-images.githubusercontent.com/42820304/200133422-2b65c217-3bbc-4f90-84b1-f644a0807e28.png)

7. It seems like I just can't look at the contents of any folder anymore, if I double click the folder nothing happens, right clicking and doing Open -> In New Tab doesn't work either

Sample pk3: Note that Github is silly and required me to change its extension to .zip

[testpk3.pk3.zip](https://github.com/sirjuddington/SLADE/files/9944385/testpk3.pk3.zip)

Ping me on Discord (I'm cq75 on the zdoom discord), I don't really use this Github account much

**Comment by sirjuddington** [comment]
Does this happen still in 3.2.2? The filtering code was changed and most likely fixed this issue (at least I can't reproduce it) Same with #1431
