### ISSUE TITLE
Slade crashes when adding and deleting groups of textures

### ISSUE THREAD

**Issue by lumish** [sirjuddington/SLADE#1443]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
When I paste or delete around 5 or more textures at once Slade crashes.

Version: 3.2.1 (x86)
No current action

Operating System: Windows 10 (build 19044), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 516.94

Stack Trace:
0: (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory:3050) std::weak_ptr<slade::ArchiveEntry>::lock
1: (H:\Dev\SLADE\Build\src\Archive\ArchiveDir.cpp:106) slade::ArchiveDir::path
2: (H:\Dev\SLADE\Build\src\Archive\ArchiveEntry.cpp:159) slade::ArchiveEntry::path
3: (H:\Dev\SLADE\Build\src\MapEditor\MapTextureManager.cpp:628) slade::MapTextureManager::buildTexInfoList
4: (H:\Dev\SLADE\Build\src\MapEditor\MapTextureManager.cpp:560) slade::MapTextureManager::refreshResources
5: (H:\Dev\SLADE\Build\thirdparty\sigslot\signal.hpp:692) sigslot::signal_base<std::mutex>::operator()
6: (H:\Dev\SLADE\Build\thirdparty\sigslot\signal.hpp:464) sigslot::detail::slot<<lambda_b31a6483af5613a190c22c666209867b>,slade::Archive &,slade::ArchiveDir &,slade::ArchiveEntry &>::call_slot
7: (H:\Dev\SLADE\Build\src\Archive\Archive.cpp:1057) slade::Archive::removeEntry
8: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:1195) slade::ArchivePanel::deleteEntry
9: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:3937) slade::ArchivePanel::onEntryListKeyDown
10: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:655) wxAppConsoleBase::HandleEvent
11: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:666) wxAppConsoleBase::CallEventHandler
12: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1439) wxEvtHandler::ProcessEventIfMatchesId
13: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1901) wxEvtHandler::SearchDynamicEventTable
14: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\include\wx\event.h:4007) wxEvtHandler::TryBeforeAndHere
15: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1534) wxEvtHandler::ProcessEvent
16: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1660) wxEvtHandler::SafelyProcessEvent
17: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:3254) wxWindow::MSWHandleMessage
18: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:3898) wxWindow::MSWWindowProc
19: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:2940) wxWndProc
20: [unknown location] AddClipboardFormatListener
21: [unknown location] GetClassLongW
22: [unknown location] DispatchMessageW
23: [unknown location] IsDialogMessageW
24: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:2687) wxWindow::MSWProcessMessage
25: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:142) wxGUIEventLoop::PreProcessMessage
26: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:160) wxGUIEventLoop::ProcessMessage
27: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:227) wxGUIEventLoop::Dispatch
28: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:239) wxEventLoopManual::ProcessEvents
29: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:288) wxEventLoopManual::DoRun
30: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:87) wxEventLoopBase::Run
31: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:377) wxAppConsoleBase::MainLoop
32: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\init.cpp:504) wxEntryReal
33: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:175) wxEntry
34: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:296) wxEntry
35: (H:\Dev\SLADE\Build\src\Application\SLADEWxApp.cpp:372) WinMain
36: (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288) __scrt_common_main_seh
37: [unknown location] BaseThreadInitThunk
38: [unknown location] RtlGetAppContainerNamedObjectPath
39: [unknown location] RtlGetAppContainerNamedObjectPath

Last Log Messages:
Opening archive C:\Priv Wad Update\m Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory:3050) std::weak_ptr<slade::ArchiveEntry>::lock
1: (H:\Dev\SLADE\Build\src\Archive\ArchiveDir.cpp:106) slade::ArchiveDir::path
2: (H:\Dev\SLADE\Build\src\Archive\ArchiveEntry.cpp:159) slade::ArchiveEntry::path
3: (H:\Dev\SLADE\Build\src\MapEditor\MapTextureManager.cpp:628) slade::MapTextureManager::buildTexInfoList
4: (H:\Dev\SLADE\Build\src\MapEditor\MapTextureManager.cpp:560) slade::MapTextureManager::refreshResources
5: (H:\Dev\SLADE\Build\thirdparty\sigslot\signal.hpp:692) sigslot::signal_base<std::mutex>::operator()
6: (H:\Dev\SLADE\Build\thirdparty\sigslot\signal.hpp:464) sigslot::detail::slot<<lambda_b31a6483af5613a190c22c666209867b>,slade::Archive &,slade::ArchiveDir &,slade::ArchiveEntry &>::call_slot
7: (H:\Dev\SLADE\Build\src\Archive\Archive.cpp:1057) slade::Archive::removeEntry
8: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:1195) slade::ArchivePanel::deleteEntry
9: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:3937) slade::ArchivePanel::onEntryListKeyDown
10: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:655) wxAppConsoleBase::HandleEvent
11: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:666) wxAppConsoleBase::CallEventHandler
12: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1439) wxEvtHandler::ProcessEventIfMatchesId
13: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1901) wxEvtHandler::SearchDynamicEventTable
14: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\include\wx\event.h:4007) wxEvtHandler::TryBeforeAndHere
15: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1534) wxEvtHandler::ProcessEvent
16: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1660) wxEvtHandler::SafelyProcessEvent
17: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:3254) wxWindow::MSWHandleMessage
18: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:3898) wxWindow::MSWWindowProc
19: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:2940) wxWndProc
20: [unknown location] AddClipboardFormatListener
21: [unknown location] GetClassLongW
22: [unknown location] DispatchMessageW
23: [unknown location] IsDialogMessageW
24: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:2687) wxWindow::MSWProcessMessage
25: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:142) wxGUIEventLoop::PreProcessMessage
26: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:160) wxGUIEventLoop::ProcessMessage
27: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:227) wxGUIEventLoop::Dispatch
28: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:239) wxEventLoopManual::ProcessEvents
29: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:288) wxEventLoopManual::DoRun
30: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:87) wxEventLoopBase::Run
31: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:377) wxAppConsoleBase::MainLoop
32: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\init.cpp:504) wxEntryReal
33: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:175) wxEntry
34: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:296) wxEntry
35: (H:\Dev\SLADE\Build\src\Application\SLADEWxApp.cpp:372) WinMain
36: (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288) __scrt_common_main_seh
37: [unknown location] BaseThreadInitThunk
38: [unknown location] RtlGetAppContainerNamedObjectPath
39: [unknown location] RtlGetAppContainerNamedObjectPath

Last Log Messages:
Opening archive C:\Priv Wad Update\rampagepriv-v2.pk3
MAPINFO (Hexen/Old ZDoom) parsing not yet implemented
Opening took 1383 ms
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 32768x32768
Checking extensions...
Vertex Buffer Objects supportedrampagepriv-v2.pk3
MAPINFO (Hexen/Old ZDoom) parsing not yet implemented
Opening took 1383 ms
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 32768x32768
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported

**Comment by sirjuddington** [comment]
I think this is the same issue as #1380 which will be fixed in 3.2.2, feel free to reopen if it still happens in that version when it's released
