### ISSUE TITLE
[Editor Scripting] Attempting to use App:currentEntrySelection results in an error

### ISSUE THREAD

**Issue by SMS-Alfredo** [sirjuddington/SLADE#1454]
**SLADE Version**: (3.2.1)
**Operating System**: (Windows)

**Issue Details**:
I have a [script for SLADE](https://mb.srb2.org/addons/srb2-sprite-namer-lua-script-for-slade.4691/) I made for ease of use in making Sonic Robo Blast 2 mods, but the script only works in SLADE v3.1.13.

Now the script first has a weird error that happens as a result of using an `execute` function instead of just running the code manually, which I assume is just the result of deprecated behavior.
![image](https://user-images.githubusercontent.com/65426124/214446266-380d9e34-8e96-4efd-9fcb-c6d711b6a8be.png)

But that's not the main issue here. Fixing that by renaming the execute function and calling it myself manually (which was done in [this edited version of the script](https://github.com/sirjuddington/SLADE/files/10494863/SRB2_Sprite_Namer.zip)), an error pops up that App:currentEntrySelection is apparently a method that does not exist.
![Capture](https://user-images.githubusercontent.com/65426124/214446852-c13660f5-53c9-4a9b-b262-ed6ff30b95c1.PNG)

```
Runtime Error
Line 46: attempt to call a nil value (method 'currentEntrySelection')
stack traceback:
	[string "--Rename SRB2 Sprites SLADE script by SMS Alf..."]:46: in local 'spriteNamer'
	[string "--Rename SRB2 Sprites SLADE script by SMS Alf..."]:201: in main chunk
```

This is really odd. I know this method is still referenced in the current source code, I double checked, so it _should_ exist. And yet it doesn't. Something must be going wrong here, hence why I'm reporting this.

**Comment by sirjuddington** [comment]
It should be `App.` not `App:` since it is a namespace
