### ISSUE TITLE
Corrupted copies of sprites caused by file renaming

### ISSUE THREAD

**Issue by cozyraf** [sirjuddington/SLADE#1456]
Version: 3.2.1 (x64)
No current action

Operating System: Windows 10 (build 19044), 64-bit edition
Graphics Vendor: ATI Technologies Inc.
Graphics Hardware: AMD Radeon(TM) Vega 8 Graphics
OpenGL Version: 4.6.14761 Compatibility Profile Context 21.30.14 30.0.13014.8

Issue Details:
I was renaming all the walking sprites to have only one frame displayed for all rotations while using the filter box (because the sprites only had one rotation so I typed in WALK*0) and when I finish doing that I find out that there are corrupted copies of the sprites I renamed that, when interacting with them, can cause the program to crash. It also scatters copies of the same sprites through the pk3 if you don't click on them.

Stack Trace:
0: [unknown location] LibRaw_abstract_datastream::subfile_open
1: [unknown location] std::unique_ptr<std::basic_streambuf<char,std::char_traits<char> >,std::default_delete<std::basic_streambuf<char,std::char_traits<char> > > >::get
2: [unknown location] LibRaw::rgb_to_lch
3: [unknown location] LibRaw::rgb_to_lch
4: [unknown location] LibRaw::rgb_to_lch
5: [unknown location] LibRaw::rgb_to_lch
6: [unknown location] LibRaw::rgb_to_lch
7: [unknown location] LibRaw::rgb_to_lch
8: [unknown location] LibRaw::rgb_to_lch
9: [unknown location] LibRaw::rgb_to_lch
10: [unknown location] LibRaw::rgb_to_lch
11: [unknown location] LibRaw::rgb_to_lch
12: [unknown location] LibRaw::rgb_to_lch
13: [unknown location] LibRaw::rgb_to_lch
14: [unknown location] LibRaw::rgb_to_lch
15: [unknown location] LibRaw::rgb_to_lch
16: [unknown location] LibRaw::rgb_to_lch
17: [unknown location] LibRaw::rgb_to_lch
18: [unknown location] LibRaw::rgb_to_lch
19: [unknown location] CallWindowProcW
20: [unknown location] DispatchMessageW
21: [unknown location] IsDialogMessageW
22: [unknown location] LibRaw::rgb_to_lch
23: [unknown location] LibRaw::rgb_to_lch
24: [unknown location] LibRaw::rgb_to_lch
25: [unknown location] LibRaw::rgb_to_lch
26: [unknown location] LibRaw::rgb_to_lch
27: [unknown location] LibRaw::rgb_to_lch
28: [unknown location] LibRaw::rgb_to_lch
29: [unknown location] LibRaw::rgb_to_lch
30: [unknown location] LibRaw::rgb_to_lch
31: [unknown location] LibRaw::rgb_to_lch
32: [unknown location] BaseThreadInitThunk
33: [unknown location] RtlUserThreadStart

Last Log Messages:
Opening took 1626 ms
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 16384x16384
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Creating backup C:/Users/User/Desktop/Test.pk3.bak
Creating backup C:/Users/User/Desktop/Test.pk3.bak

**Comment by sirjuddington** [comment]
Closing this one as I think it may have been fixed in 3.2.2, feel free to repoen if it still happens
