### ISSUE TITLE
TNT and Plutonia flats failing to render in 2D and 3D editor

### ISSUE THREAD

**Issue by BLOODWOLF333** [sirjuddington/SLADE#1459]
**SLADE Version**: (3.2.1)
**Operating System**: (Windows)

**Issue Details**:
For both TNT.wad and Plutonia.wad the 2D and 3D map viewer will not render most floors and ceilings.  Doom.wad and Doom2.wad render correctly and I am pretty sure I have changed none of the settings for the mapeditor in preferences.  Made sure I have the correct wad selected for Base Resource: and even re-autodetect'd my IWADs thinking maybe it didn't like the copy in /doomseeker of my IWADs from Steam but, to no avail.
![image](https://user-images.githubusercontent.com/16950832/219587722-e8fd9e9f-7c74-4fac-a50f-1ac54b342952.png)

**Comment by kpuljek** [comment]
Same here on linux 3.2.2 (been happening in 3.2.1 as well). Definitely not due to changing settings because I haven't touched SLADE in a long while and now it's just not rendering properly.
