### ISSUE TITLE
Textures/Sprites Etc All Jumbled Up And Wrong

### ISSUE THREAD

**Issue by Laerrus811** [sirjuddington/SLADE#1460]
**SLADE Version**: (3.2.1)
**Operating System**: (Windows 10)

**Issue Details**:
I open the zip file to work on, and a lot of textures are missing, but their file name is still there. Instead of being listed as a PNG they are listed as UNKNOWN. This happened another time recently too but much worse, where assets were all jumbled up so that 3d models were now listed under texture file names, texture files were under fonts and 3d models, some were just gone and showing Unknown. 

Each time this happened, I had taken an SD Card out of the slot, and the second time it happened I had my phone plugged in, but neither of those times involved Slade being opened at the same time. Its just something I noticed I had done different recently, before everything went haywire.

This current problem though seems limited to textures being mysteriously vanished.

I opened the wad in GZDOOM and it wouldn't launch at all. 

Here is the console output from Slade3.

Windows Version: 10.0
SLADE - It's a Doom Editor
Version 3.2.1
64bit Windows Build
Written by Simon Judd, 2008-2023
Compiled with wxWidgets 3.1.6 and SFML 2.5.1
--------------------------------
Loading configuration
Loading resources
Looking for #include entry '/' / 'actions/main.cfg'
Looking for #include entry '/' / 'actions/aman.cfg'
Looking for #include entry '/' / 'actions/arch.cfg'
Looking for #include entry '/' / 'actions/pgfx.cfg'
Looking for #include entry '/actions/' / 'pgfx_brush.cfg'
Looking for #include entry '/' / 'actions/aelt.cfg'
Looking for #include entry '/' / 'actions/txed.cfg'
Looking for #include entry '/' / 'actions/anim.cfg'
Looking for #include entry '/' / 'actions/swch.cfg'
Looking for #include entry '/' / 'actions/ppal.cfg'
Looking for #include entry '/' / 'actions/data.cfg'
Looking for #include entry '/' / 'actions/ptxt.cfg'
Looking for #include entry '/' / 'actions/mapw.cfg'
Looking for #include entry '/actions/' / 'mapw_general.cfg'
Looking for #include entry '/actions/' / 'mapw_show.cfg'
Looking for #include entry '/actions/' / 'mapw_line.cfg'
Looking for #include entry '/actions/' / 'mapw_sector.cfg'
Looking for #include entry '/actions/' / 'mapw_script.cfg'
Looking for #include entry '/' / 'actions/scrm.cfg'
Loading icons
Loading entry types
Loading text languages
Can't convert "F1" to a double (invalid)
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
Can't convert "floor_raiseandcrushdoom" to an integer (invalid)
Can't convert "floor_raiseandcrushdoom" to an integer (invalid)
Can't convert "floor_raiseandcrushdoom" to an integer (invalid)
Can't convert "floor_raiseandcrushdoom" to an integer (invalid)
Can't convert "d_slow*3" to an integer (invalid)
Can't convert "stairs_buildupdoomcrush" to an integer (invalid)
Can't convert "stairs_buildupdoomcrush" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "stairs_buildupdoomcrush" to an integer (invalid)
Can't convert "stairs_buildupdoomcrush" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "sector_attach3dmidtex" to an integer (invalid)
Can't convert "sector_attach3dmidtex" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "door_waitraise" to an integer (invalid)
Can't convert "door_waitclose" to an integer (invalid)
Can't convert "floor_lowertohighestee" to an integer (invalid)
Can't convert "floor_raisetolowest" to an integer (invalid)
Can't convert "floor_lowertolowestceiling" to an integer (invalid)
Can't convert "floor_raisetoceiling" to an integer (invalid)
Can't convert "floor_lowerbytexture" to an integer (invalid)
Can't convert "floor_toceilinginstant" to an integer (invalid)
Can't convert "ceiling_raisetohighest" to an integer (invalid)
Can't convert "ceiling_tohighestinstant" to an integer (invalid)
Can't convert "ceiling_lowertonearest" to an integer (invalid)
Can't convert "ceiling_raisetolowest" to an integer (invalid)
Can't convert "ceiling_raisetohighestfloor" to an integer (invalid)
Can't convert "ceiling_tofloorinstant" to an integer (invalid)
Can't convert "ceiling_raisebytexture" to an integer (invalid)
Can't convert "ceiling_lowerbytexture" to an integer (invalid)
Can't convert "stairs_builddowndoom" to an integer (invalid)
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
SLADE Initialisation OK
Checking for updates...
Latest stable release: v3.2.1
Latest beta release: v3.2.0 beta 4
Already up-to-date
Opening archive E:/GZDOOM/sTEVES Gmae/Main Files/Current/Fools Art Gallery 2.zip
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: too many length or distance symbols
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read inflate stream: unexpected EOF in underlying stream.
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read inflate stream: unexpected EOF in underlying stream.
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: Can't read from inflate stream: invalid stored block lengths
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Error: bad zipfile offset to entry
Opening took 2568 ms

**Comment by sirjuddington** [comment]
It looks like the zip file has become corrupted somehow, if it's on the SD card you mentioned, perhaps that card is dead/dying? Either way I don't think this is an issue with SLADE itself
