### ISSUE TITLE
SEEFRIENDLYMONSTERS and DONTFOLLOWPLAYERS flags not working

### ISSUE THREAD

**Issue by Retrosath** [sirjuddington/SLADE#1463]
![doom error](https://user-images.githubusercontent.com/128912706/227722693-7141c41b-6faa-437f-994a-756007f6e5d9.png)
SLADE Version: (3.1.11)
Operating System: (Windows10)
Doom editor: Ultimate Doom Builder

I have been trying to use the flags +SEEFRIENDLYMONSTERS  and +DONTFOLLOWPLAYERS to my actors but either slade 3 or UDB does seem to recognize them. I keep getting a script error message relating to those flags everytime I try booting UDB with them. The Zdoom wiki shows the flags as legit although idk if the site has been updated recently relating to this.

**Comment by Blue-Shadow** [comment]
I don't know about UDB, but from the screenshot, you're using a very outdated version of GZDoom which has no support for those flags. To use said flags, you need GZDoom 4.8.0 or newer. The latest version of GZDoom is 4.10.0, for your information.

In regard of SLADE not recognizing the flags, you'll have to wait for the next SLADE release.

**Comment by Retrosath** [comment]
> I don't know about UDB, but from the screenshot, you're using a very outdated version of GZDoom which has no support for those flags. To use said flags, you need GZDoom 4.8.0 or newer. The latest version of GZDoom is 4.10.0, for your information.
> 
> In regard of SLADE not recognizing the flags, you'll have to wait for the next SLADE release.

Thank you! ill update GZDoom and hopefully that will be it
