### ISSUE TITLE
Slade crash on converting flat

### ISSUE THREAD

**Issue by GhoulFool** [sirjuddington/SLADE#1466]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:

After problems converting several flats at once (one converted to unknown)  I reloaded in .wad file and attempted to convert one flat at at time. Slade then crashed

stack trace as follows

Version: 3.2.1 (x64)
No current action

Operating System: Windows 7 (build 7601, Service Pack 1), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: NVIDIA GeForce GTX 760/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 474.06

Stack Trace:
0: [unknown location] LibRaw_abstract_datastream::subfile_open
1: [unknown location] LibRaw_abstract_datastream::subfile_open
2: [unknown location] std::unique_ptr<std::basic_streambuf<char,std::char_traits<char> >,std::default_delete<std::basic_streambuf<char,std::char_traits<char> > > >::get
3: [unknown location] LibRaw_abstract_datastream::subfile_open
4: [unknown location] LibRaw_abstract_datastream::subfile_open
5: [unknown location] LibRaw_abstract_datastream::subfile_open
6: [unknown location] LibRaw_abstract_datastream::subfile_open
7: [unknown location] std::unique_ptr<std::basic_streambuf<char,std::char_traits<char> >,std::default_delete<std::basic_streambuf<char,std::char_traits<char> > > >::get
8: [unknown location] std::unique_ptr<std::basic_streambuf<char,std::char_traits<char> >,std::default_delete<std::basic_streambuf<char,std::char_traits<char> > > >::get
9: [unknown location] LibRaw::rgb_to_lch
10: [unknown location] LibRaw::rgb_to_lch
11: [unknown location] LibRaw::rgb_to_lch
12: [unknown location] LibRaw::rgb_to_lch
13: [unknown location] LibRaw::rgb_to_lch
14: [unknown location] LibRaw::rgb_to_lch
15: [unknown location] LibRaw::rgb_to_lch
16: [unknown location] LibRaw::rgb_to_lch
17: [unknown location] LibRaw::rgb_to_lch
18: [unknown location] TranslateMessageEx
19: [unknown location] TranslateMessage
20: [unknown location] IsDialogMessageW
21: [unknown location] LibRaw::rgb_to_lch
22: [unknown location] LibRaw::rgb_to_lch
23: [unknown location] LibRaw::rgb_to_lch
24: [unknown location] LibRaw::rgb_to_lch
25: [unknown location] LibRaw::rgb_to_lch
26: [unknown location] LibRaw::rgb_to_lch
27: [unknown location] LibRaw::rgb_to_lch
28: [unknown location] LibRaw::rgb_to_lch
29: [unknown location] LibRaw::rgb_to_lch
30: [unknown location] LibRaw::rgb_to_lch
31: [unknown location] BaseThreadInitThunk
32: [unknown location] RtlUserThreadStart

Last Log Messages:
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 16384x16384
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Unknown icon "palette"
Opening archive D:/games/DOOMWADS/xc_pal_test_02.wad
Opening took 333 ms

**Comment by sirjuddington** [comment]
I think this is similar to the other one (#1467) - does this also still happen in 3.2.2?
