### ISSUE TITLE
Crash Dump

### ISSUE THREAD

**Issue by Rufflikerex** [sirjuddington/SLADE#1480]
I was viewing a graphic, then I clicked on an audio file (ogg). After that, SLADE crashed.

Stack Trace:
Version: 3.2.2 (x64)
No current action

Operating System: Windows 10 (build 19045), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: Quadro P600/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 528.89

Stack Trace:
0: [unknown location] [unknown:458239600]
1: [unknown location] [unknown:452822389]
2: [unknown location] [unknown:453231746]
3: [unknown location] [unknown:453236067]
4: [unknown location] [unknown:453234620]
5: [unknown location] [unknown:452729373]
6: [unknown location] [unknown:452724222]
7: [unknown location] [unknown:448655180]
8: [unknown location] [unknown:448654097]
9: [unknown location] [unknown:448649046]
10: [unknown location] [unknown:448717642]
11: [unknown location] [unknown:448717194]
12: [unknown location] [unknown:448570918]
13: [unknown location] [unknown:448579772]
14: [unknown location] [unknown:448569525]
15: [unknown location] [unknown:453246292]
16: [unknown location] [unknown:453411551]
17: [unknown location] [unknown:453414451]
18: [unknown location] [unknown:453415313]
19: [unknown location] [unknown:453411338]
20: [unknown location] [unknown:455063564]
21: [unknown location] [unknown:455563073]
22: [unknown location] [unknown:455549060]
23: [unknown location] [unknown:453246292]
24: [unknown location] [unknown:453411551]
25: [unknown location] [unknown:453410647]
26: [unknown location] [unknown:453415340]
27: [unknown location] [unknown:453411338]
28: [unknown location] [unknown:453414298]
29: [unknown location] [unknown:454472659]
30: [unknown location] [unknown:454499107]
31: [unknown location] [unknown:454509752]
32: [unknown location] [unknown:454534917]
33: [unknown location] CallWindowProcW
34: [unknown location] DispatchMessageW
35: [unknown location] IsDialogMessageW
36: [unknown location] [unknown:454506319]
37: [unknown location] [unknown:455842543]
38: [unknown location] [unknown:455842626]
39: [unknown location] [unknown:455840716]
40: [unknown location] [unknown:453898803]
41: [unknown location] [unknown:453899338]
42: [unknown location] [unknown:453251767]
43: [unknown location] [unknown:453937132]
44: [unknown location] [unknown:453400248]
45: [unknown location] [unknown:458230558]
46: [unknown location] BaseThreadInitThunk
47: [unknown location] RtlUserThreadStart

Last Log Messages:
Already up-to-date
Opening archive C:\Users\Pikaspoop\Desktop\Games\SRB2-v2210-Full\mods\CL_Dirfex_v1.0.pk3
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 32768x32768
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening archive C:\Users\Pikaspoop\Desktop\Games\SRB2-v2210-Full\mods\Judgement\V_Mecha'sXTremeMod-v1.0.1.pk3

**Comment by sirjuddington** [comment]
Unfortunately not much I can do with that stack trace, does it always happen? If it does, what is the wad/pk3 and ogg that cause it?
