### ISSUE TITLE
Drag select?

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [sirjuddington/SLADE#1483]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
Apparently selecting multiple files in the wad itself by drag select doesn't work anymore.

**Comment by sirjuddington** [comment]
Unfortunately the wxWidgets tree control used in 3.2.0+ doesn't support dragging to select. To multi select you'll have to click an entry, hold shift then click another entry to select up/down to
