### ISSUE TITLE
3.2.2 build failing on Nobara 37

### ISSUE THREAD

**Issue by jawivafo** [sirjuddington/SLADE#1487]
**SLADE Version**: (3.2.2)
**Operating System**: (Nobara 37/Fedora 37)

**Issue Details**:
Hopefully this is the right place for this. I got 3.2.2 to almost finish building on Nobara 37 (GloriousEggroll's Fedora 37 + tweaks), but it gets hung up on this step:

[100%] Linking CXX executable ../slade
/usr/bin/ld: /usr/lib64/libfreeimage.so: undefined reference to `_TIFFDataSize'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/slade.dir/build.make:4635: slade] Error 1
make[1]: *** [CMakeFiles/Makefile2:232: src/CMakeFiles/slade.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I tried including the TIFF libraries with cmake and recompiling with no luck, unfortunately that's about the limit of my abilities at solving this problem on my own, so I'm hoping somebody might know what's up.

**Comment by eGax** [comment]
I'm no expert but the issue seems to stem from `/usr/lib64/libfreeimage.so`. Does your freeimage library match the minimum required by the slade version you're trying to build?

**Comment by jawivafo** [comment]
Unfortunately I can't find any information anywhere as to what version is actually required, but as far as I can tell I do have the latest one (that being 3.19.0).

**Comment by jawivafo** [comment]
Alright, found a solution, it's not an issue with SLADE. Downgrading from 3.19.0-0.16 to 3.19.0-0.11 was enough to fix it, so must be some kind of issue with freeimage or a related library. Hope this helps anyone else who might encounter this problem.
