### ISSUE TITLE
Crash while saving after writing the word "out"

### ISSUE THREAD

**Issue by GianptDev** [sirjuddington/SLADE#1492]
**SLADE Version**: (3.2.2)
**Operating System**: (Linux)

**Issue Details**:
Slade crashes while saving after writing the keyword "out" in the text editor inside a zscript source, it crashed multiple times and I'm unable to write that word.

The thing I was writing:
![immagine](https://user-images.githubusercontent.com/89723855/236628078-1eca53f1-82ae-4d5d-ac76-82ea3680d6bd.png)

logs: https://pastebin.com/kYzLb572

**Comment by sirjuddington** [comment]
Is that valid ZScript? I thought `out` was supposed to go before the type, eg. `out array<ZV_Frame> list`, according to https://zdoom.org/wiki/ZScript_functions

Either way it shouldn't crash so this will still need to be fixed
