### ISSUE TITLE
Importing .WAV deletes file.

### ISSUE THREAD

**Issue by BeefyBoi2312** [sirjuddington/SLADE#1494]
**SLADE Version**: (3.2.2)
**Operating System**: (Windows 10)

**Issue Details**:
Whenever I try to replace a sound effect in DOOM2.WAD, I right-click on the file, click "Import" then I choose the .WAV, and then the sound effect just disappears! And when I play the mod, the sound is definitely deleted, because it's just silent!
I've tried bookmarking the sound, but it still disappears!
I'm new to doom modding, and i don't really know how the program works.

**Comment by eevee** [comment]
Off the top of my head, I _suspect_ you're having three separate problems:

1. _Some_times (maybe?), replacing an entry can move it to the end of the file?  I think?  I swear I've seen this happen but I can't seem to make it happen now.

2. Vanilla Doom can't play WAV files.  It uses its own format.  You have to right-click it after importing and use Audio > Convert WAV to Doom Format.

3. You **do not want to modify doom2.wad**!  You can make your own separate .wad file, then load that _along with_ doom2.wad.  If your wad has an entry with the same name as an entry in doom2.wad, it'll override the original.

    (Well, that's true for sounds and music.  Some other stuff like graphics can be more complicated.)

Here's, maybe, the sort of thing you want: [sound-example.zip](https://github.com/sirjuddington/SLADE/files/11438024/sound-example.zip)

It replaces the super shotgun sound.  What I did was:

- Create a new archive, in Doom WAD format
- Import files, and pick a sound I had lying around
- Right-click it and convert it to Doom format
- Rename it to `DSDSHTGN`, the name of the super shotgun sound
- Save it

And it works fine in Chocolate Doom.

**Comment by BeefyBoi2312** [comment]
Thank you! this helped a lot!

**Comment by sirjuddington** [comment]
Closing this one as the entry wasn't really deleted. I don't like that it doesn't keep the selection if the entry changes type but after having a quick look at it, it's a wxWidgets issue that isn't easy to fix
