### ISSUE TITLE
Graphic Colour Glitch.

### ISSUE THREAD

**Issue by BeefyBoi2312** [sirjuddington/SLADE#1495]
**SLADE Version**: (3.2.2)
**Operating System**: (Windows 10)

**Issue Details**:
For some reason, whenever I select multiple things and then delete them, whenever I click on a graphic, it thinks that the graphic is in grayscale? and when I try to re-map the colours, it doesn't show any colour, it's just black, grey, and white. But when I play the mod, the graphics look normal in game.

**Comment by Gaerzi** [comment]
Have you set the base resource archive so that the program knows what palette to use?

**Comment by BeefyBoi2312** [comment]
> Have you set the base resource archive so that the program knows what palette to use?

Yes, I just checked.

**Comment by sirjuddington** [comment]
I can't reproduce this one, what are you selecting and deleting beforehand? Did you maybe delete a PLAYPAL entry?

**Comment by BeefyBoi2312** [comment]
> I can't reproduce this one, what are you selecting and deleting beforehand? Did you maybe delete a PLAYPAL entry?

Yeah, I'm pretty sure I did. That's probably the problem. I'll try to add back the PLAYPAL entry.
