### ISSUE TITLE
slade does not recognise ACS script sources not named "SCRIPTS" until renamed to "SCRIPTS"

### ISSUE THREAD

**Issue by Moth-Tolias** [sirjuddington/SLADE#1508]
**SLADE Version**: 3.2.2
**Operating System**: Linux

**Issue Details**:
if you make a new text entry containing an ACS script that is not named `SCRIPTS` and try to compile it, the result does not end up in the `BEHAVIOR` lump; rather, it gets placed in its own new lump between `A_START` and `A_END`. renaming the source lump to `SCRIPTS` fixes the issue and allows renaming.

<details> 
    <summary>bonus crash log that happened while trying to understand how to get acs scripts to work</summary>
Version: 3.2.2
Current action: arch_scripts_compileacs
Operating System: Linux 6.2.0-20-generic x86_64
Graphics Vendor: AMD
Graphics Hardware: KAVERI (, LLVM 15.0.7, DRM 2.50, 6.2.0-20-generic)
OpenGL Version: 4.5 (Compatibility Profile) Mesa 23.0.2

Stack Trace:
0: [unknown location] wxLogger::DoLogWithNum(long, wchar_t const*, ...)
1: [unknown location] [unknown:140257153010040]
2: [unknown location] [unknown:140257104479408]
3: [unknown location] slade::WadArchive::findLast(slade::Archive::SearchOptions&)
4: [unknown location] slade::entryoperations::compileACS(slade::ArchiveEntry*, bool, slade::ArchiveEntry*, wxFrame*)
5: [unknown location] slade::ArchivePanel::compileACS(bool) const
6: [unknown location] slade::ArchivePanel::handleAction(std::basic_string_view<char, std::char_traits<char> >)
7: [unknown location] slade::SActionHandler::doAction(std::basic_string_view<char, std::char_traits<char> >)
8: [unknown location] SLADEWxApp::onMenu(wxCommandEvent&)
9: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
10: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
11: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
12: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
13: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
14: [unknown location] wxWindowBase::TryAfter(wxEvent&)
15: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
16: [unknown location] wxMenuBase::DoProcessEvent(wxMenuBase*, wxEvent&, wxWindow*)
17: [unknown location] wxMenuBase::SendEvent(int, int)
18: [unknown location] wxMenu::SetTitle(wxString const&)
19: [unknown location] g_closure_invoke
20: [unknown location] [unknown:140257118565334]
21: [unknown location] g_signal_emit_valist
22: [unknown location] g_signal_emit
23: [unknown location] gtk_widget_activate
24: [unknown location] gtk_menu_shell_activate_item
25: [unknown location] [unknown:140257125258089]
26: [unknown location] [unknown:140257123730696]
27: [unknown location] g_signal_emit_valist
28: [unknown location] g_signal_emit
29: [unknown location] [unknown:140257126590340]
30: [unknown location] [unknown:140257125166574]
31: [unknown location] gtk_main_do_event
32: [unknown location] [unknown:140257122298051]
33: [unknown location] [unknown:140257122650134]
34: [unknown location] g_main_context_dispatch
35: [unknown location] [unknown:140257117696376]
36: [unknown location] g_main_loop_run
37: [unknown location] gtk_main
38: [unknown location] wxGUIEventLoop::DoRun()
39: [unknown location] wxEventLoopBase::Run()
40: [unknown location] wxAppConsoleBase::OnRun()
41: [unknown location] wxEntry(int&, wchar_t**)
42: [unknown location] main
43: [unknown location] [unknown:140257104378512]
44: [unknown location] __libc_start_main
45: [unknown location] _start

Last Log Messages:
Copyright (c) 1995 Raven Software, Corp.

This is version 1.55 (Mar 20 2017)
This software is not supported by Raven Software or Activision
ZDoom changes and language extensions by Randy Heit
Further changes by Brad Carney
Even more changes by James Bentler
Some additions by Michael "Necromage" Weber
Error reporting improvements and limit expansion by Ty Halderman
Include paths added by Pascal vd Heiden
</details>

**Comment by sirjuddington** [comment]
That is normal, map scripts need to be named `SCRIPTS` to work, since it isn't named that it's treating it as a library script instead. Will keep this one open though due to the crash
