### ISSUE TITLE
CTD when confirming the properties panel of sectors.

### ISSUE THREAD

**Issue by mangomeep** [sirjuddington/SLADE#1514]
Hi there, not really sure what to do as this is my first time submitting an issue but;

Slade crashes with such an output as below when clicking OK on the properties panel for a sector. I've tried many times on both Windows and Linux, but it crashes no matter what. I've even tried with different wads but they still crash.

Windows crash log:

Version: 4.2.3 (x64)
Current action: mapw_item_properties
Operating System: Windows 11 (build 19045), 64-bit edition
Graphics Vendor: Intel
Graphics Hardware: Intel(R) Iris(R) Xe Graphics
OpenGL Version: 5.6.0 - Build 31.0.101.3616

Stack Trace:
1: [unknown location] [unknown:624791753]
2: [unknown location] [unknown:624995160]
3: [unknown location] [unknown:624508882]
4: [unknown location] [unknown:624336557]
5: [unknown location] [unknown:624482249]
6: [unknown location] [unknown:619780692]
7: [unknown location] [unknown:619083510]
8: [unknown location] [unknown:628747444]
9: [unknown location] [unknown:628912815]
10: [unknown location] [unknown:628915715]
11: [unknown location] [unknown:628916577]
12: [unknown location] [unknown:628912602]
13: [unknown location] [unknown:628916510]
14: [unknown location] [unknown:629941411]
15: [unknown location] [unknown:628912684]
16: [unknown location] [unknown:628915562]
17: [unknown location] [unknown:630439141]
18: [unknown location] [unknown:630737497]
19: [unknown location] [unknown:629968150]
20: [unknown location] [unknown:631192239]
21: [unknown location] [unknown:631194128]
22: [unknown location] [unknown:630036181]
23: [unknown location] CallWindowProcW
24: [unknown location] DispatchMessageW
25: [unknown location] [unknown:629957697]
26: [unknown location] [unknown:629929894]
27: [unknown location] [unknown:624511774]
28: [unknown location] [unknown:624378416]
29: [unknown location] [unknown:624836602]
30: [unknown location] [unknown:628747444]
31: [unknown location] [unknown:628912815]
32: [unknown location] [unknown:628915715]
33: [unknown location] [unknown:628916577]
34: [unknown location] [unknown:628912602]
35: [unknown location] [unknown:628915562]
36: [unknown location] [unknown:629973923]
37: [unknown location] [unknown:630000371]
38: [unknown location] [unknown:630011016]
39: [unknown location] [unknown:630036181]
40: [unknown location] CallWindowProcW
41: [unknown location] CallWindowProcW
42: [unknown location] glPushClientAttrib
43: [unknown location] CallWindowProcW
44: [unknown location] CallWindowProcW
45: [unknown location] [unknown:628351521]
46: [unknown location] CallWindowProcW
47: [unknown location] DispatchMessageW
48: [unknown location] [unknown:631342252]
49: [unknown location] [unknown:629400067]
50: [unknown location] [unknown:629400602]
51: [unknown location] [unknown:628752919]
52: [unknown location] [unknown:629438396]
53: [unknown location] [unknown:628901512]
54: [unknown location] [unknown:633732830]
55: [unknown location] BaseThreadInitThunk
56: [unknown location] RtlUserThreadStart

Last Log Messages:
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening map map02
Removed 1 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
Selected item 2
Selected item 2027
Nodebuilder path not set up, no nodes were built
Opening archive C:/Games/DOOM/ramp/RAMP2023/new.wad

Linux crash log:

Version: 4.2.3
Current action: mapw_item_properties
Operating System: Linux 7.3.5-arch1-1 x86_64
Graphics Vendor: Intel
Graphics Hardware: Mesa Intel(R) Graphics (ADL GT3)
OpenGL Version: 5.6 (Compatibility Profile) Mesa 23.1.1

Stack Trace:
1: [unknown location] [unknown:140234675086880]
2: [unknown location] [unknown:140234648255152]
3: [unknown location] slade::SectorSpecialPanel::selectedSpecial() const
4: [unknown location] slade::SectorPropsPanel::applyChanges()
5: [unknown location] slade::mapeditor::editObjectProperties(std::vector<slade::MapObject*, std::allocator<slade::MapObject*> >&)
6: [unknown location] slade::Edit2D::editObjectProperties()
7: [unknown location] slade::MapEditContext::handleAction(std::basic_string_view<char, std::char_traits<char> >)
8: [unknown location] slade::SActionHandler::doAction(std::basic_string_view<char, std::char_traits<char> >)
9: [unknown location] SLADEWxApp::onMenu(wxCommandEvent&)
10: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
11: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
12: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
13: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
14: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
15: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
16: [unknown location] wxMenuBase::SendEvent(int, int)
17: [unknown location] [unknown:140234681485942]
18: [unknown location] g_closure_invoke
19: [unknown location] [unknown:140234656172344]
20: [unknown location] g_signal_emit_valist
21: [unknown location] g_signal_emit
22: [unknown location] gtk_widget_activate
23: [unknown location] gtk_menu_shell_activate_item
24: [unknown location] [unknown:140234662629914]
25: [unknown location] [unknown:140234661056569]
26: [unknown location] g_signal_emit_valist
27: [unknown location] g_signal_emit
28: [unknown location] [unknown:140234664003301]
29: [unknown location] [unknown:140234662537499]
30: [unknown location] gtk_main_do_event
31: [unknown location] [unknown:140234669980551]
32: [unknown location] [unknown:140234670341432]
33: [unknown location] g_main_context_dispatch
34: [unknown location] [unknown:140234655300409]
35: [unknown location] g_main_context_iteration
36: [unknown location] gtk_main_iteration
37: [unknown location] wxWindow::DoPopupMenu(wxMenu*, int, int)
38: [unknown location] wxWindowBase::PopupMenu(wxMenu*, int, int)
39: [unknown location] slade::mapeditor::openContextMenu()
40: [unknown location] slade::mapeditor::Input::mouseUp(slade::mapeditor::Input::MouseButton)
41: [unknown location] slade::MapCanvas::onMouseUp(wxMouseEvent&)
42: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
43: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
44: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
45: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
46: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
47: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
48: [unknown location] [unknown:140234681128269]
49: [unknown location] [unknown:140234661086029]
50: [unknown location] g_closure_invoke
51: [unknown location] [unknown:140234656172344]
52: [unknown location] g_signal_emit_valist
53: [unknown location] g_signal_emit
54: [unknown location] [unknown:140234664003301]
55: [unknown location] [unknown:140234662537499]
56: [unknown location] gtk_main_do_event
57: [unknown location] [unknown:140234669980551]
58: [unknown location] [unknown:140234670341432]
59: [unknown location] g_main_context_dispatch
60: [unknown location] [unknown:140234655300409]
61: [unknown location] g_main_loop_run
62: [unknown location] gtk_main
63: [unknown location] wxGUIEventLoop::DoRun()
64: [unknown location] wxEventLoopBase::Run()
65: [unknown location] wxAppConsoleBase::MainLoop()
66: [unknown location] wxEntry(int&, wchar_t**)
67: [unknown location] main
68: [unknown location] [unknown:140234648164432]
69: [unknown location] __libc_start_main
70: [unknown location] _start

Last Log Messages:
Can't convert "stairs_builddowndoom" to an integer (invalid)
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Opening map MAP02
Removed 1 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors

**Comment by sirjuddington** [comment]
This one is fixed along with #1512 and #1513 for the next version
