### ISSUE TITLE
Texture editor crashes on Arch Linux

### ISSUE THREAD

**Issue by theraven262** [sirjuddington/SLADE#1515]
SLADE Version: 3.2.2
Operating System: Arch Linux
GPU: AMD Radeon RX 570 Series
OpenGL:  4.6
Using the amdgpu graphics driver.
Using Wayland.

Slade crashes when opening the texture editor.

Console output:
(slade:32596): Gdk-WARNING **: 14:53:56.486: The program 'slade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 165165 error_code 3 request_code 146 (unknown) minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Apart from that, the console is being filled with many instances of:
(slade:32596): Gtk-CRITICAL **: 14:53:45.392: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

Possibly related to: https://github.com/sirjuddington/SLADE/issues/1485
Had to use the above workaround in order to be able to preview graphics/maps, as the issue describes.

**Comment by sirjuddington** [comment]
Yeah I think wxWidgets has some opengl issues on linux currently, see also #1390. Going to close this one as a duplicate
