### ISSUE TITLE
Clicking "Run Map" boots to IWAD title screen without loading resources

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [sirjuddington/SLADE#1522]
SLADE Version: (3.2.3)
Operating System: Windows

Whenever I try to test a map on my PC, it open up to the title screen for the IWAD I selected without loading the PWAD.

Here, I try to load MAP02 of Perdition's Gate.

![image](https://github.com/sirjuddington/SLADE/assets/135927009/9a472f90-4e46-4457-9516-da70e7fdc95a)

I try to open the map using the "Run Map" button. Note that I have nothing loaded and have it running on GZDoom.

![image](https://github.com/sirjuddington/SLADE/assets/135927009/670738df-c9e8-46b9-b02d-cefb1701af74)

Doing so just boots me to the title screen of Doom II, without even loading PG's assets (I.E. the title screen). "Start from 3D mode camera position" does nothing either.

The strangest part is that it works fine on my laptop (which also runs 3.2.3).

**Comment by sirjuddington** [comment]
Looks like you have nothing selected for 'Run Configuration' so it is just running gzdoom with no args at all. Not sure how it has nothing selected though
