### ISSUE TITLE
Doom II does not recognize use of custom WFALL textures

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [sirjuddington/SLADE#1523]
SLADE Version: (3.2.3)
Operating System: Windows

I made a small map to test out a custom texture (The "WFALL" animated texture cut from Doom II), but the texture is absent when I load the map.
![image](https://github.com/sirjuddington/SLADE/assets/135927009/0542c6aa-3640-4eab-9ca9-9c1da9bbb73b)
![image](https://github.com/sirjuddington/SLADE/assets/135927009/492bcdb7-74b6-404c-a533-279448293783)
![image](https://github.com/sirjuddington/SLADE/assets/135927009/df49e291-7d02-46e3-a262-3244482df21f)
![image](https://github.com/sirjuddington/SLADE/assets/135927009/f220038d-7e6d-414d-9abb-fddd02709e46)

**Comment by sirjuddington** [comment]
This isn't really an issue with SLADE itself and is more of a general doom editing question - i'd recommend posting it at either doomworld (https://www.doomworld.com/forum/3-doom-editing/) or zdoom forums (https://forum.zdoom.org/viewforum.php?f=124)
