### ISSUE TITLE
Crash Stack Trace

### ISSUE THREAD

**Issue by funniperson1122** [sirjuddington/SLADE#1526]
**SLADE Version**: (3.2.2.9)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
Version: 3.2.2 (x64)
No current action

Operating System: Windows 11 (build 22621), 64-bit edition
Graphics Vendor: ATI Technologies Inc.
Graphics Hardware: AMD Radeon(TM) Graphics
OpenGL Version: 4.6.14761 Compatibility Profile Context 21.30.40 30.0.13040.13

Stack Trace:
0: [unknown location] DrvPresentBuffers
1: [unknown location] atiPPHSN
2: [unknown location] atiPPHSN
3: [unknown location] dummy_debug_proc
4: [unknown location] dummy_debug_proc
5: [unknown location] [unknown:2811857957]
6: [unknown location] [unknown:2806318864]
7: [unknown location] [unknown:2809162908]
8: [unknown location] [unknown:2812280148]
9: [unknown location] [unknown:2812445407]
10: [unknown location] [unknown:2812448307]
11: [unknown location] [unknown:2812449169]
12: [unknown location] [unknown:2812445194]
13: [unknown location] [unknown:2812448154]
14: [unknown location] [unknown:2813512067]
15: [unknown location] [unknown:2813525245]
16: [unknown location] [unknown:2813543608]
17: [unknown location] [unknown:2813568773]
18: [unknown location] DispatchMessageW
19: [unknown location] CallWindowProcW
20: [unknown location] wglSwapBuffers
21: [unknown location] DispatchMessageW
22: [unknown location] CallWindowProcW
23: [unknown location] [unknown:2811884209]
24: [unknown location] DispatchMessageW
25: [unknown location] DispatchMessageW
26: [unknown location] GetClassLongW
27: [unknown location] KiUserCallbackDispatcher
28: [unknown location] NtUserDispatchMessage
29: [unknown location] DispatchMessageW
30: [unknown location] IsDialogMessageW
31: [unknown location] [unknown:2813540175]
32: [unknown location] [unknown:2814876399]
33: [unknown location] [unknown:2814876482]
34: [unknown location] [unknown:2814874572]
35: [unknown location] [unknown:2812932659]
36: [unknown location] [unknown:2812933194]
37: [unknown location] [unknown:2812285623]
38: [unknown location] [unknown:2812970988]
39: [unknown location] [unknown:2812434104]
40: [unknown location] [unknown:2817264414]
41: [unknown location] BaseThreadInitThunk
42: [unknown location] RtlUserThreadStart

Last Log Messages:
OpenGL Version: 4.6
Max Texture Size: 16384x16384
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening archive D:/template.wad
Opening took 846 ms
PNG tool paths not defined or invalid, no optimization done.
PNG tool paths not defined or invalid, no optimization done.

**Comment by sirjuddington** [comment]
I can't do much with this without any more info eg. what you were doing when it crashed, though looking at the stack trace it is in the video driver, so maybe try updating that
