### ISSUE TITLE
Things gone wild

### ISSUE THREAD

**Issue by Laerrus811** [sirjuddington/SLADE#1537]
**SLADE Version**: (3.2.4)
**Operating System**: Windows 7

**Issue Details**:
Random Things are in the wrong place suddenly. And selecting Things and deleting them then randomly selects another Thing and moves it's position into the wrong position horizontally.

**Comment by sirjuddington** [comment]
Any screenshots/video examples of the issue? I'm not entirely sure what you mean and can't reproduce anything like it
