### ISSUE TITLE
crash saving a WAD twice from the Map Editor

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#154]
Steps to repro:

1. open this file in SLADE3 (latest from git): https://www.dropbox.com/s/1gmsnsrm5569h2e/deck.pk3
2. go into the maps/ dir and open map01 in the map editor
3. click the save button twice

crash dump follows.

----

Version: 3.1.0 beta 4
No current action

Stack Trace:
0: [unknown location] [unknown:1606025996]
1: [unknown location] [unknown:1556799472]
2: [unknown location] std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)
3: [unknown location] ArchiveEntry::getName(bool)
4: [unknown location] MapEditorWindow::saveMap()
5: [unknown location] MapEditorWindow::handleAction(wxString)
6: [unknown location] MainApp::doAction(wxString)
7: [unknown location] SToolBarButton::onMouseEvent(wxMouseEvent&)
8: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
9: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
10: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
11: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
12: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
13: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
14: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
15: [unknown location] [unknown:1611696696]
16: [unknown location] [unknown:1575446085]
17: [unknown location] g_closure_invoke
18: [unknown location] [unknown:1551457053]
19: [unknown location] g_signal_emit_valist
20: [unknown location] g_signal_emit
21: [unknown location] [unknown:1576560116]
22: [unknown location] gtk_propagate_event
23: [unknown location] gtk_main_do_event
24: [unknown location] [unknown:1554113148]
25: [unknown location] g_main_context_dispatch
26: [unknown location] [unknown:1545103112]
27: [unknown location] g_main_loop_run
28: [unknown location] gtk_main
29: [unknown location] wxGUIEventLoop::DoRun()
30: [unknown location] wxEventLoopBase::Run()
31: [unknown location] wxAppConsoleBase::MainLoop()
32: [unknown location] wxEntry(int&, wchar_t**)
33: [unknown location] main
34: [unknown location] __libc_start_main
35: [unknown location] _start

**Comment by DOOMer** [comment]
I get such a crash very often, almost every time when i  make save my map.

SLADE 3.1.0.2, Arch Linux x86_64, wxgtk 3.0.2

    Version: 3.1.0.2
    No current action

    Stack Trace:
    0: [unknown location] [unknown:1283122156]
    1: [unknown location] [unknown:1226339648]
    2: [unknown location] std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)
    3: [unknown location] ArchiveEntry::getName(bool)
    4: [unknown location] MapEditorWindow::saveMap()
    5: [unknown location] MapEditorWindow::handleAction(wxString)
    6: [unknown location] MainApp::doAction(wxString)
    7: [unknown location] SToolBarButton::onMouseEvent(wxMouseEvent&)
    8: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
    9: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
    10: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
    11: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
    12: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
    13: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
    14: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
    15: [unknown location] [unknown:1291329378]
    16: [unknown location] [unknown:1245690127]
    17: [unknown location] g_closure_invoke
    18: [unknown location] [unknown:1220997132]
    19: [unknown location] g_signal_emit_valist
    20: [unknown location] g_signal_emit
    21: [unknown location] [unknown:1246833580]
    22: [unknown location] gtk_propagate_event
    23: [unknown location] gtk_main_do_event
    24: [unknown location] [unknown:1223660236]
    25: [unknown location] g_main_context_dispatch
    26: [unknown location] [unknown:1214541024]
    27: [unknown location] g_main_loop_run
    28: [unknown location] gtk_main
    29: [unknown location] wxGUIEventLoop::DoRun()
    30: [unknown location] wxEventLoopBase::Run()
    31: [unknown location] wxAppConsoleBase::MainLoop()
    32: [unknown location] wxEntry(int&, wchar_t**)
    33: [unknown location] main
    34: [unknown location] __libc_start_main
    35: [unknown location] _start

**Comment by sirjuddington** [comment]
I believe this one is now fixed: f56ecb7
