### ISSUE TITLE
Slade not correctly compiling w/ACC and showing no errors with ACC

### ISSUE THREAD

**Issue by Scattergrunt** [sirjuddington/SLADE#1546]
**SLADE Version**: (3.2.4)
**Operating System**: (Windows/Linux/OSX)
Windows 10
**Issue Details**:
As title says slade doesn't correctly load ACC when compiling and ACC shows no errors present at all.
I also tried with a script that *should* compile fine being a simple "Hello World!" script but that also does not work. 

As far as I'm aware its SLADE and not me (unless I haven't configured it correctly), and a similar issue on linux was reported here; https://github.com/sirjuddington/SLADE/issues/1539, though I have no clue if our issues are linked in any way outside of the obvious

![image](https://github.com/sirjuddington/SLADE/assets/127327991/b665e5cb-d86e-456e-99b6-8a7213e2968f)

**Comment by FluffBallFloof** [comment]
I can put you in contact with the guy behind issue #1539, I was the guy who got ACS working within SLADE on their computer. If you haven't already managed to get things working I might be able to help?

**Comment by FluffBallFloof** [comment]
Message me on discord(same username) I'll see what I can do from there.

**Comment by Scattergrunt** [comment]
I cannot do that as it says you're not accepting friend requests

**Comment by Arkanu-of-Galatiel** [comment]
So did anyone manage to solve this? I'm having the same problem and I haven't found a solution.
