### ISSUE TITLE
No preview in TEXTURES editor

### ISSUE THREAD

**Issue by UnBeatWaterGH** [sirjuddington/SLADE#1549]
**SLADE Version**: 3.2.4
**Operating System**: Debian GNU/Linux 12 (Bookworm)

**Issue Details**:
Whenever I try to create a TEXTURES.txt file in my PK3 and use the built in graphical editor, it doesn't display anything in the preview (there is NO preview).

**Comment by Blzut3** [comment]
Assuming this is duplicate of issues mentioned above.
