### ISSUE TITLE
Flatpak migrate to a supported platform

### ISSUE THREAD

**Issue by Vuldora** [sirjuddington/SLADE#1550]
**SLADE Version**: (3.2.1)
**Operating System**: (Linux - Flatpak)

**Issue Details**:
When running a `flatpak update` the following is returned:
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   net.mancubus.SLADE

Realistically I don't think this matters much but I wanted to create an issue to inform this exist

**Comment by thecnoNSMB** [comment]
I now also get:
```
Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   net.mancubus.SLADE
```
That sounds kind of important.

**Comment by Alexander-Wilms** [comment]
The runtime has been updated:

https://github.com/flathub/net.mancubus.SLADE/commit/58020072dcf4e0b4ba22f513a4f363935b47c542
