### ISSUE TITLE
SLADE crashes anytime I try to open or create a file.

### ISSUE THREAD

**Issue by Gexant** [sirjuddington/SLADE#1558]
**SLADE Version**: 3.2.4 (x64)
**Operating System**: Windows 11 (build 22621), 64-bit edition

**Issue Details**:
SLADE Crashes anytime I try to open or create a file.
This is the message I get whenever it crashes:

Version: 3.2.4 (x64)
No current action

Operating System: Windows 11 (build 22621), 64-bit edition
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: [unknown location] IcdPresentBuffers
1: [unknown location] IcdPresentBuffers
2: [unknown location] IcdPresentBuffers
3: [unknown location] DrvSetCallbackProcs
4: [unknown location] DrvSetCallbackProcs
5: [unknown location] wglSwapMultipleBuffers
6: [unknown location] wglSwapMultipleBuffers
7: [unknown location] wglUseFontBitmapsW
8: [unknown location] wglGetPixelFormat
9: [unknown location] wglSetPixelFormat
10: [unknown location] SetPixelFormat
11: [unknown location] [unknown:4095954900]
12: [unknown location] [unknown:4095952994]
13: [unknown location] [unknown:4095951696]
14: [unknown location] [unknown:4089228511]
15: [unknown location] [unknown:4089204449]
16: [unknown location] [unknown:4087828593]
17: [unknown location] [unknown:4087687256]
18: [unknown location] [unknown:4087583858]
19: [unknown location] [unknown:4087553032]
20: [unknown location] [unknown:4087552727]
21: [unknown location] [unknown:4082938733]
22: [unknown location] [unknown:4082963524]
23: [unknown location] [unknown:4087550629]
24: [unknown location] [unknown:4087547464]
25: [unknown location] [unknown:4092534452]
26: [unknown location] [unknown:4092699823]
27: [unknown location] [unknown:4092702723]
28: [unknown location] [unknown:4092703585]
29: [unknown location] [unknown:4092699610]
30: [unknown location] [unknown:4092702570]
31: [unknown location] [unknown:4094559014]
32: [unknown location] [unknown:4093779868]
33: [unknown location] [unknown:4093798024]
34: [unknown location] [unknown:4093823189]
35: [unknown location] DispatchMessageW
36: [unknown location] SendMessageW
37: [unknown location] SendMessageW
38: [unknown location] DrawScrollBar
39: [unknown location] Str_SetPtrW
40: [unknown location] InitCommonControls
41: [unknown location] CCSetScrollInfo
42: [unknown location] DispatchMessageW
43: [unknown location] CallWindowProcW
44: [unknown location] DefSubclassProc
45: [unknown location] DSA_InsertItem
46: [unknown location] DefSubclassProc
47: [unknown location] DSA_InsertItem
48: [unknown location] DispatchMessageW
49: [unknown location] CallWindowProcW
50: [unknown location] [unknown:4093773327]
51: [unknown location] [unknown:4093798048]
52: [unknown location] [unknown:4094565096]
53: [unknown location] [unknown:4093823189]
54: [unknown location] DispatchMessageW
55: [unknown location] DispatchMessageW
56: [unknown location] IsDialogMessageW
57: [unknown location] [unknown:4093794591]
58: [unknown location] [unknown:4095131087]
59: [unknown location] [unknown:4095131170]
60: [unknown location] [unknown:4095129260]
61: [unknown location] [unknown:4093187075]
62: [unknown location] [unknown:4093187610]
63: [unknown location] [unknown:4092539927]
64: [unknown location] [unknown:4093225404]
65: [unknown location] [unknown:4092688520]
66: [unknown location] [unknown:4097519838]
67: [unknown location] BaseThreadInitThunk
68: [unknown location] RtlUserThreadStart

Last Log Messages:
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Checking for updates...
Latest stable release: v3.2.4
Latest beta release: v3.2.0 beta 4
Already up-to-date
Opening archive D:/DOOM/GZDOOM/Doom2.wad

**Comment by Arkaliasus** [comment]
you probably googled it already but apparently others had the issue back in 2019 
this link is to a forum that goes through a couple of things they tried to get it working, hope it helps :)
https://www.doomworld.com/forum/topic/107731-slade-crashes-everytime-i-try-to-open-or-create-a-file/

**Comment by Gexant** [comment]
the forum didnt help but it randomly fixed itself a few days ago, thanks for trying to help
