### ISSUE TITLE
Revise Linux Install Instructions

### ISSUE THREAD

**Issue by mrseudo** [sirjuddington/SLADE#1565]
**SLADE Version**: (3.2.4)
**Operating System**: Linux, Debian 12 "bookworm"

**Issue Details**:
Due to `apt-key add` being depreciated, the instructions for the Linux package install won't work with newer versions of Debian. (Flatpak works fine, but isn't a Debian package.) I would like to propose a new solution using the recommended package key signing method for recent Debian-based distributions, currently at Debian 12 "bookworm".

The following **bash** command sequence must be done as _root_ (superuser) or prefix commands with `sudo`:

```
mkdir -p /etc/apt/keyrings
wget http://debian.drdteam.org/drdteam.gpg -P /etc/apt/keyrings
echo -e "\ndeb [signed-by=/etc/apt/keyrings/drdteam.gpg] http://debian.drdteam.org/ stable multiverse" >> /etc/apt/sources.list
apt update
apt install slade
```
Description of Command Sequence
1. Create **keyrings** directory, if it does not exist.
2. Download the key file into **/etc/apt/keyrings**.
3. Add a new line, key path and repository to **sources.list**.
4. Update **apt**.
5. Install SLADE.

This was road-tested using Debian 12 "bookworm".

**Comment by sirjuddington** [comment]
Ok i've updated the page with the new commands
