### ISSUE TITLE
Feature Request: Keybind to rotate Things

### ISSUE THREAD

**Issue by superjamie** [sirjuddington/SLADE#1568]
**SLADE Version**: 3.2.4
**Operating System**: Linux

**Issue Details**:

There are some laptop touchpads which don't allow the mouse to be moved while a key is being pressed.

This effectively makes Quick Angle Edit impossible to use. The alternatives to edit angles are not very fast.

A key binding to rotate Things would work around this, and might provide a nicer keyboard-centric workflow anyway.

Is it possible to add an option for this?

I would bind it to `[` (counterclockwise) and `]` (clockwise) by default, but whatever is fine.

**Comment by sirjuddington** [comment]
Implemented in #1605
