### ISSUE TITLE
Crash on clicking "Remove unused Flats"

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [sirjuddington/SLADE#1569]
Version: 3.2.4 (x64)
Current action: arch_clean_flats
Operating System: Windows 10 (build 19045), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: NVIDIA GeForce GTX 970/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 536.23

Stack Trace:
0: [unknown location] [unknown:2407489972]
1: [unknown location] [unknown:2407756886]
2: [unknown location] [unknown:2403670596]
3: [unknown location] [unknown:2402973430]
4: [unknown location] [unknown:2412650164]
5: [unknown location] [unknown:2412815535]
6: [unknown location] [unknown:2412818435]
7: [unknown location] [unknown:2412819297]
8: [unknown location] [unknown:2412815322]
9: [unknown location] [unknown:2412819230]
10: [unknown location] [unknown:2413844131]
11: [unknown location] [unknown:2412815404]
12: [unknown location] [unknown:2413844110]
13: [unknown location] [unknown:2412815404]
14: [unknown location] [unknown:2413844110]
15: [unknown location] [unknown:2412815404]
16: [unknown location] [unknown:2413844110]
17: [unknown location] [unknown:2412815404]
18: [unknown location] [unknown:2412818282]
19: [unknown location] [unknown:2414341861]
20: [unknown location] [unknown:2414640217]
21: [unknown location] [unknown:2413870870]
22: [unknown location] [unknown:2413897954]
23: [unknown location] [unknown:2413913736]
24: [unknown location] [unknown:2413938901]
25: [unknown location] CallWindowProcW
26: [unknown location] DispatchMessageW
27: [unknown location] [unknown:2413860417]
28: [unknown location] [unknown:2413832614]
29: [unknown location] [unknown:2409415015]
30: [unknown location] [unknown:2412650164]
31: [unknown location] [unknown:2412815535]
32: [unknown location] [unknown:2412818435]
33: [unknown location] [unknown:2412819297]
34: [unknown location] [unknown:2412815322]
35: [unknown location] [unknown:2412818282]
36: [unknown location] [unknown:2413876643]
37: [unknown location] [unknown:2413903091]
38: [unknown location] [unknown:2413913736]
39: [unknown location] [unknown:2413938901]
40: [unknown location] CallWindowProcW
41: [unknown location] DispatchMessageW
42: [unknown location] IsDialogMessageW
43: [unknown location] [unknown:2413910303]
44: [unknown location] [unknown:2415246799]
45: [unknown location] [unknown:2415246882]
46: [unknown location] [unknown:2415244972]
47: [unknown location] [unknown:2413302787]
48: [unknown location] [unknown:2413303322]
49: [unknown location] [unknown:2412655639]
50: [unknown location] [unknown:2413341116]
51: [unknown location] [unknown:2412804232]
52: [unknown location] [unknown:2417635550]
53: [unknown location] BaseThreadInitThunk
54: [unknown location] RtlUserThreadStart

Last Log Messages:
Version check failed, unable to connect
Opening archive C:/Users/lakot/Downloads/gzdoom-4-8-2-Windows-64bit/chex.wad
Opening took 1413 ms
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 16384x16384
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported

**Comment by sirjuddington** [comment]
Unfortunately not much I can do with this one as the stack trace doesn't show anything
