### ISSUE TITLE
Crashed like heck

### ISSUE THREAD

**Issue by 77ZaRR77** [sirjuddington/SLADE#1575]
Version: 3.2.4 (x64)
Current action: arch_check_zdoom_texture_duplicates
Operating System: Windows 10 (build 19043), 64-bit edition
Graphics Vendor: Intel
Graphics Hardware: Intel(R) UHD Graphics
OpenGL Version: 4.6.0 - Build 27.20.100.9565

Stack Trace:
0: [unknown location] [unknown:68776196]
1: [unknown location] [unknown:68813333]
2: [unknown location] [unknown:69104906]
3: [unknown location] [unknown:65018436]
4: [unknown location] [unknown:64321270]
5: [unknown location] [unknown:73998004]
6: [unknown location] [unknown:74163375]
7: [unknown location] [unknown:74166275]
8: [unknown location] [unknown:74167137]
9: [unknown location] [unknown:74163162]
10: [unknown location] [unknown:74167070]
11: [unknown location] [unknown:75191971]
12: [unknown location] [unknown:74163244]
13: [unknown location] [unknown:75191950]
14: [unknown location] [unknown:74163244]
15: [unknown location] [unknown:74166122]
16: [unknown location] [unknown:75689670]
17: [unknown location] [unknown:76442475]
18: [unknown location] [unknown:76444688]
19: [unknown location] [unknown:75286741]
20: [unknown location] CallWindowProcW
21: [unknown location] DispatchMessageW
22: [unknown location] [unknown:76592812]
23: [unknown location] [unknown:74650627]
24: [unknown location] [unknown:74651162]
25: [unknown location] [unknown:74003479]
26: [unknown location] [unknown:74688956]
27: [unknown location] [unknown:74152072]
28: [unknown location] [unknown:78983390]
29: [unknown location] BaseThreadInitThunk
30: [unknown location] RtlUserThreadStart

Last Log Messages:
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Opening map MAP01
Removed 1 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
MAPINFO (Hexen/Old ZDoom) parsing not yet implemented

**Comment by sirjuddington** [comment]
Unfortunately not much I can do with this one as the stack trace doesn't show anything
