### ISSUE TITLE
Add support for LEAFS lump found in PSX Doom and Doom 64

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [sirjuddington/SLADE#1602]
LEAFS are console-exclusive lumps used in Doom 64 and Doom's port on the PSX. They are one of the component lumps of a map (like REJECT and NODES), making up the floor and ceiling of the map's sectors. These currently show up as Unknown in SLADE. Please fix it so that they show up as a LEAFS lump.

**Comment by sirjuddington** [comment]
What wad file are you seeing them show up as unknown? They are detected fine for me in DOOM64.WAD at least:

![image](https://github.com/sirjuddington/SLADE/assets/2484576/b6407d6b-38fe-4978-8f54-41da6b51212d)

**Comment by PerdGateEnjoyer** [comment]
Oh, sorry. I was fooling around with the Hexen 64 IWAD and saw a bunch of FLOORXX lumps. Someone theorized they were like LEAFS, and I didn't want to ask for something that we just found out existed, so I asked for LEAFS instead.

**Comment by Gaerzi** [comment]
Those FLOORXX lumps may be "like leafs" but that doesn't mean they'll be in the exact same format; there's a lot of ways to write even basic data.

**Comment by ljcool2006** [comment]
I'm on the same boat.
