### ISSUE TITLE
Crash upon opening any TEXTURES lump in mm8bdm-v6b.pk3

### ISSUE THREAD

**Issue by Hisbiscus** [sirjuddington/SLADE#1609]
Version: 3.2.4 (x64)
No current action

Operating System: Windows 10 (build 19043), 64-bit edition
Graphics Vendor: ATI Technologies Inc.
Graphics Hardware: AMD Radeon(TM) Vega 8 Graphics
OpenGL Version: 4.5.13497 Compatibility Profile Context 23.20.815.6656

Stack Trace:
0: [unknown location] [unknown:3439982298]
1: [unknown location] [unknown:3441022105]
2: [unknown location] [unknown:3439982411]
3: [unknown location] [unknown:3439984609]
4: [unknown location] [unknown:3440115365]
5: [unknown location] [unknown:3440901575]
6: [unknown location] [unknown:3440115222]
7: [unknown location] [unknown:3440115621]
8: [unknown location] [unknown:3440115222]
9: [unknown location] [unknown:3440114114]
10: [unknown location] [unknown:3440124569]
11: [unknown location] [unknown:3439977793]
12: [unknown location] [unknown:3434349322]
13: [unknown location] [unknown:3439982411]
14: [unknown location] [unknown:3439984609]
15: [unknown location] [unknown:3440115365]
16: [unknown location] [unknown:3440114114]
17: [unknown location] [unknown:3440115222]
18: [unknown location] [unknown:3440114114]
19: [unknown location] [unknown:3440127088]
20: [unknown location] [unknown:3439991405]
21: [unknown location] [unknown:3434264044]
22: [unknown location] [unknown:3434333455]
23: [unknown location] [unknown:3434285055]
24: [unknown location] [unknown:3433834308]
25: [unknown location] [unknown:3433939882]
26: [unknown location] [unknown:3438812852]
27: [unknown location] [unknown:3438978223]
28: [unknown location] [unknown:3438981123]
29: [unknown location] [unknown:3438981985]
30: [unknown location] [unknown:3438978010]
31: [unknown location] [unknown:3440630508]
32: [unknown location] [unknown:3441114885]
33: [unknown location] [unknown:3438812852]
34: [unknown location] [unknown:3438978223]
35: [unknown location] [unknown:3438977319]
36: [unknown location] [unknown:3438982012]
37: [unknown location] [unknown:3438978010]
38: [unknown location] [unknown:3438980970]
39: [unknown location] [unknown:3440039331]
40: [unknown location] [unknown:3440065779]
41: [unknown location] [unknown:3440076424]
42: [unknown location] [unknown:3440101589]
43: [unknown location] CallWindowProcW
44: [unknown location] DispatchMessageW
45: [unknown location] IsDialogMessageW
46: [unknown location] [unknown:3440072991]
47: [unknown location] [unknown:3441409487]
48: [unknown location] [unknown:3441409570]
49: [unknown location] [unknown:3441407660]
50: [unknown location] [unknown:3439465475]
51: [unknown location] [unknown:3439466010]
52: [unknown location] [unknown:3438818327]
53: [unknown location] [unknown:3439503804]
54: [unknown location] [unknown:3438966920]
55: [unknown location] [unknown:3443798238]
56: [unknown location] BaseThreadInitThunk
57: [unknown location] RtlUserThreadStart

Last Log Messages:
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening archive C:/Users/Dunno/Desktop/Doom/gzdoom-4-4-2-Windows-64bit/DOOM2.WAD
Opening took 2502 ms
Opening archive C:/Users/Dunno/Desktop/Doom/8BDM/Mega Man 8-Bit Deathmatch/mm8bdm-v6b.pk3
Opening took 10461 ms
Creating backup C:\Users\Dunno\Desktop\Doom\8BDM\maps\IWBTG\OHDM04.wad.bak
Creating backup C:\Users\Dunno\Desktop\Doom\8BDM\maps\IWBTG\OHDM04.wad.bak
Creating backup C:\Users\Dunno\Desktop\Doom\8BDM\maps\IWBTG\OHDM04.wad.bak

**Comment by sirjuddington** [comment]
Does this still happen in 3.2.5? If so could you post the stack trace again (it should hopefully not be full of 'unknown's in 3.2.5)

**Comment by GeminiCrafterMan** [comment]
Yes, it does still happen in v3.2.5, sorry I'm so late with the confirmation! Running the Windows version through Wine does work, but it's a little sluggish.
