### ISSUE TITLE
Crash upon opening a .pk3

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [sirjuddington/SLADE#1627]
Version: 3.2.4 (x64)
No current action

Operating System: Windows 10 (build 19045), 64-bit edition
Graphics Vendor: Intel
Graphics Hardware: Intel(R) HD Graphics 4000
OpenGL Version: 4.0.0 - Build 10.18.10.4252

Stack Trace:
0: [unknown location] [unknown:2561699031]
1: [unknown location] [unknown:2561700123]
2: [unknown location] [unknown:2561401610]
3: [unknown location] [unknown:2561473277]
4: [unknown location] [unknown:2561463084]
5: [unknown location] [unknown:2561468855]
6: [unknown location] [unknown:2553780211]
7: [unknown location] [unknown:2555271185]
8: [unknown location] [unknown:2555127896]
9: [unknown location] [unknown:2555024498]
10: [unknown location] [unknown:2554993672]
11: [unknown location] [unknown:2554993367]
12: [unknown location] [unknown:2550379373]
13: [unknown location] [unknown:2550403125]
14: [unknown location] [unknown:2555100924]
15: [unknown location] [unknown:2559975092]
16: [unknown location] [unknown:2560140463]
17: [unknown location] [unknown:2560143363]
18: [unknown location] [unknown:2560144225]
19: [unknown location] [unknown:2560140250]
20: [unknown location] [unknown:2561792748]
21: [unknown location] [unknown:2562277125]
22: [unknown location] [unknown:2559975092]
23: [unknown location] [unknown:2560140463]
24: [unknown location] [unknown:2560139559]
25: [unknown location] [unknown:2560144252]
26: [unknown location] [unknown:2560140250]
27: [unknown location] [unknown:2560143210]
28: [unknown location] [unknown:2561201571]
29: [unknown location] [unknown:2561228019]
30: [unknown location] [unknown:2561238664]
31: [unknown location] [unknown:2561263829]
32: [unknown location] CallWindowProcW
33: [unknown location] DispatchMessageW
34: [unknown location] IsDialogMessageW
35: [unknown location] [unknown:2561235231]
36: [unknown location] [unknown:2562571727]
37: [unknown location] [unknown:2562571810]
38: [unknown location] [unknown:2562569900]
39: [unknown location] [unknown:2560627715]
40: [unknown location] [unknown:2560628250]
41: [unknown location] [unknown:2559980567]
42: [unknown location] [unknown:2560666044]
43: [unknown location] [unknown:2560129160]
44: [unknown location] [unknown:2564960478]
45: [unknown location] BaseThreadInitThunk
46: [unknown location] RtlUserThreadStart

Last Log Messages:
Opening archive C:\Users\carly\Downloads\RDD_Tex.wad
Can't convert "=" to an integer (invalid)
Opening took 4097 ms
Opening archive C:\Users\carly\Downloads\RomeroDoomDump-master.zip
Can't convert "=" to an integer (invalid)
Opening took 6421 ms
Opening archive C:\Users\carly\Downloads\xa-necro_v4.zip
Can't convert "=" to an integer (invalid)
Opening took 3505 ms
Can't convert "=" to an integer (invalid)

**Comment by sirjuddington** [comment]
Unfortunately there isn't much I can do with this stack trace, though I think I know why it (and all recent windows x64 ones) all show up as 'unknown' - where you have SLADE installed there should be a `SLADE.pdb` file
![image](https://github.com/sirjuddington/SLADE/assets/2484576/4f1a17f0-4adc-4f67-994e-643c709f6fdf)
If you rename it to `SLADE-x64.pdb` future crash stack traces should be more useful (this issue will be corrected in 3.2.5 onwards)
