### ISSUE TITLE
Convert doom MUS to midi via command line

### ISSUE THREAD

**Issue by Sembiance** [sirjuddington/SLADE#1639]
With slade you can export a doom MUS file to midi format via the GUI. I would really like to have a command line app that simply takes a doom MUS as I out and outputs a midi without any GUI showing up, so I can automate it and convert thousands of files.

**Comment by sirjuddington** [comment]
Hmm I don't really have plans for any kind of command-line interface for SLADE, if you need to convert many at once you can use the 'open directory' feature, select all the MUS files and right click > Audio > Convert MUS to MIDI

**Comment by Sembiance** [comment]
If I were to take a stab at coding up a CLI app on my own to do this, built against the slade code base, which source files and classes/methods are the ones that deal with converting MUS to MIDI?  I may be able to code it up myself, but would need some tips as to which files I should look at leveraging. Thanks!

**Comment by sirjuddington** [comment]
Take a look here:
https://github.com/sirjuddington/SLADE/tree/master/thirdparty/mus2mid

**Comment by Sembiance** [comment]
Oh, that's awesome! EXACTLY what I was looking for, I got it working now. Thanks!
