### ISSUE TITLE
SRB2 Support for Map Editor.

### ISSUE THREAD

**Issue by Danfun64** [sirjuddington/SLADE#164]
I would imagine that Doom Legacy Doom maps would have to come first, and before that 3.1.0 should probably be released, but can you please add this feature? There are no good linux editors for this game.

**Comment by sirjuddington** [comment]
Closing this since AFAIK it should be supported now

**Comment by flarn2006** [comment]
I'm not seeing SRB2 in the list of games when I start the map editor. I'm on the latest version. Is there something I need to do to get it to appear?
