### ISSUE TITLE
The `sudo make install` / `sudo ninja install` fails because of `slade.pk3` file missing

### ISSUE THREAD

**Issue by Wohlstand** [sirjuddington/SLADE#1641]
**SLADE Version**: top of branch `master`
**Operating System**: Linux (Ubuntu 22.04)

**Issue Details**:
Recently, I finally figured how to properly install dependencies and build the thing. However, it fails to be installed because of the `slade.pk3` file is missing. Is that supposed it being no longer generated?

The log I get on attempt to install the thing:
```
$ sudo ninja install
[0/2] Re-checking globbed directories...
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/slade
CMake Error at src/cmake_install.cmake:67 (file):
  file INSTALL cannot find
  "/home/vitaly/_git_repos_other/SLADE/dist/slade.pk3": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)


FAILED: CMakeFiles/install.util 
cd /home/vitaly/_git_repos_other/SLADE/dist && /usr/local/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Comment by SteelT1** [comment]
Haven't ran a bisect to find the bad commit, but it seems to be a regression between v3.2.4 and v3.2.5, as it also fails due to `slade.pk3` not being generated.

**Comment by SteelT1** [comment]
Turns out building the SLADE pk3 is not on by default and has to be enabled with the `BUILD_PK3` option. So the actual issue is that the install target doesn't check if it's enabled and just assumes it is.
