### ISSUE TITLE
Custom non-TTF font replaced with OS font

### ISSUE THREAD

**Issue by SoundCrafterYT** [sirjuddington/SLADE#1646]
### SLADE Version

3.2.5

### OS

Windows

### Editor

Resource editor

### Steps to Reproduce and Observed Behavior

1. Open a WAD or a PK3
2. Open any text-based lump/file
3. Go to Text -> Color Scheme -> Other...
4. Click on "Font" and choose any Non-TTF font.
5. Font replaced with the font that the OS uses.

### Expected Behavior

Show non-TTF fonts in the text editor

### Screenshots

![Trying to explain the problem](https://www.dropbox.com/scl/fi/fg0q5f0fw8v97a4z591tj/slade_error.png)

**Comment by sirjuddington** [comment]
Nothing much you can do about it currently, however in 3.2.6+ you should be able to set the `txed_use_directwrite` cvar to false which should make non-ttf fonts work again (but disable ligature support)

**Comment by SoundCrafterYT** [comment]
How can I disable ligatures? (Or how would I)

**Comment by deli73** [comment]
OTF fonts (such as Comic Code) also seem to have this issue. I don't think comic code even has ligatures, but any font that isn't TTF might break currently if ligature support is on at all.
