### ISSUE TITLE
3D mode crashes on MacOS and Linux since the 3D floors PR

### ISSUE THREAD

**Issue by Pedro-Beirao** [sirjuddington/SLADE#1648]
### SLADE Version

3.2.5

### OS

macOS

### Editor

Map editor

### Steps to Reproduce

Happens since #1358 
Go into 3D mode, doesnt matter if 3D floors are ON or not

This seems to only happen on MacOS, both on x64 and arm64

### Crash Information

```text
slade(27786,0x203ce2240) malloc: Heap corruption detected, free list is damaged at 0x600000d3e8e0
*** Incorrect guard value: 105553167013504
slade(27786,0x203ce2240) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by Pedro-Beirao** [comment]
Ive tried to find the problem and fix it, but I haven't been able to
LLDB is no help

**Comment by sirjuddington** [comment]
That crash info doesn't really help much unfortunately, what map are you opening?

**Comment by Pedro-Beirao** [comment]
Happens in any map

Sometimes instantly after pressing the toggle 3d button, sometimes I can move the camera in 3d for less than a second before it happens

**Comment by sirjuddington** [comment]
Hmm that's weird since deleting a null pointer is supposed to do nothing, not crash. Unless the pointer is invalid somehow but I can't see how that would happen.

That being said, I don't like that it's using raw `new`/`delete` so will look at changing it to `vector` and that should hopefully fix it

**Comment by Pedro-Beirao** [comment]
Tried commit https://github.com/sirjuddington/SLADE/commit/4921aa96d51583f436ef2e2608aec3aa2d932ba7 and it now freezes Slade instead of crashing right away

Same stack trace
```
Stack Trace:
0: [unknown location] wxFatalSignalHandler(int)
1: [unknown location] _sigtramp
2: [unknown location] slade::MapRenderer3D::checkVisibleFlats()
3: [unknown location] slade::MapRenderer3D::renderMap()
4: [unknown location] slade::mapeditor::Renderer::drawMap3d()
5: [unknown location] slade::mapeditor::Renderer::draw()
6: [unknown location] slade::MapCanvas::draw()
...
```

**Comment by Pedro-Beirao** [comment]
Tried with the new release and this still happens. Slade freezes when I go to 3d mode

**Comment by sirjuddington** [comment]
Do you still get the same stack trace too? Also is it a debug or release build? Would be handy to get line numbers in the trace. Could maybe even add some extra logging to `checkVisibleFlats` if it's still happening there

**Comment by Pedro-Beirao** [comment]
Quick debug shows that the exception occurs in MapRenderer3D.cpp line 3147

`flats_[flat_idx++] = &flat;`

flats_ is empty (size=0) but flat_idx is 1

**Comment by sirjuddington** [comment]
I have no idea how that could happen unless all sectors are invisible (behind the camera), in which case it wouldn't get to that line at all. What about `n_flats_`, is that 0 as well?

**Comment by sirjuddington** [comment]
Weird, what about `sector_flats_`? I can see there it has size 59 but are they just 59 empty vectors? If not I'm completely stumped heh

**Comment by Pedro-Beirao** [comment]
![Screenshot 2024-05-29 at 16 48 17](https://github.com/sirjuddington/SLADE/assets/82064173/6aad48ee-bb6e-4a29-a59d-e9e6df8727e9)

**Comment by sirjuddington** [comment]
Ah I think I see what it is - is your `flats_use_vbo` cvar set to false? If I set it to false I get the crash.

**Comment by Pedro-Beirao** [comment]
Yes it was set to false. Setting it to true does fix it.

**Comment by sirjuddington** [comment]
Ok that's good, the latest commit should also fix the crash when the cvar is false

**Comment by Pedro-Beirao** [comment]
Yep latest commit did fix it. Thanks for looking into this!
