### ISSUE TITLE
SLADE still looks for .exe files on Linux

### ISSUE THREAD

**Issue by YourAverageYeet** [sirjuddington/SLADE#1665]
### SLADE Version

3.2.5

### OS

Linux

### Issue Details

Just for clarification, this issue lies directly between a bug report and a feature request. If "Other" is the improper type, feel free to change it.

When trying to set up the PNG compression tools for SLADE, I noticed that even though I am on Linux, it still looks for Windows executable files. There's also no option to look at "All Files" in the file selection prompt, so you can't "take the easy way out."

**Comment by sirjuddington** [comment]
This works fine for me on ubuntu, while it does say 'Executable files' as the file type, it allows selection of any file

**Comment by YourAverageYeet** [comment]
Alright, I just did some more testing on this issue (thank you for the response, by the way), and, instead of the originally stated problem, it seems that Slade cannot detect files that don't have extensions. For instance, it will detect the main, Windows `DeflOpt.exe` executable just fine, but the Linux versions of PNGcrush and PNGout, which have no extension, cannot be seen. Likewise, in my bin folder, it only detects a stray `.py` file, where everything else has no extension. This (obviously) doesn't affect folders, and VICE, which also runs on GTK3, does properly display files without extensions when selecting "All Files," so it doesn't seem to be a GTK3 issue.

This is only really a problem for users of Unix-like operating systems, where files without names are common for both user-generated and core files.

For reference, I use Kubuntu, so there also could be a problem there, but I doubt it.

**Comment by YourAverageYeet** [comment]
Visually

My `bin` folder seen through Dolphin:
![image](https://github.com/sirjuddington/SLADE/assets/80494144/56c93443-08e8-42f6-bc6d-4b4207928935)

The same folder viewed through SLADE's file dialog:
![image](https://github.com/sirjuddington/SLADE/assets/80494144/d1a00bab-dd10-4a6e-9622-653ac240f709)
