### ISSUE TITLE
SLADE lost the ability to select multiple lumps in the lump list.

### ISSUE THREAD

**Issue by Acts19quiz** [sirjuddington/SLADE#1667]
### SLADE Version

3.2.0 - 3.2.5

### OS

Windows 10

### Issue Details

In the lump viewer for SLADE 3.1.13, I can select several lumps in the list to perform mass actions, including renaming them all or deleting them all. This is very useful if I want to apply the same offsets to a series of graphics, rename a series of lumps to a pattern, delete several maps in a WAD file containing nothing but maps (to leave behind one map or a select few), copy over certain maps to another WAD, etc.

When the lump viewer was revised in 3.2.0, this seems to have stopped working. The issue persists in 3.2.5. This could be a bug, but it might also be an accident of the UI redesign (i.e., intentional removal by wxwidgets for whatever reason). It's not really a new feature request, either, since it's more about reinstating useful functionality that used to be there.

Here is a video showing the multi-selector in action.
https://github.com/sirjuddington/SLADE/assets/63941237/5dbbaf6a-2513-4e9c-b33e-b97adc61d465

If I am dum dum and forgetting a setting or UI trick that enables this, then my apologies. I searched the issue tracker (including closed issues) for relevant issues filed, but couldn't find any.

**Comment by sirjuddington** [comment]
With the new list/tree you can't multi-select by dragging the mouse like that (wxWidgets limitation), you'll have to hold shift or ctrl and multi select that way (eg. click an entry, hold shift and click another and it'll select them and everything in between)

**Comment by Acts19quiz** [comment]
I see. I can certainly understand third party libraries updating or causing issues out of your control. Thanks for the pointer.

**Comment by Acts19quiz** [comment]
I got a notification of this being closed. Just for reference, is this "closed as fixed", or "closed as not planned"?

**Comment by sirjuddington** [comment]
Not planned, since there isn't much I can do about it, and you can still multi-select with the shift/ctrl keys

**Comment by Acts19quiz** [comment]
I see. Once again, thanks for following up.
