### ISSUE TITLE
TEXTUREx Editor Crash on freedoom1.wad

### ISSUE THREAD

**Issue by vanessakindell** [sirjuddington/SLADE#1668]
### SLADE Version

3.2.5

### OS

Linux

### Editor

Resource editor

### Steps to Reproduce

I was trying to edit the TEXTUREx lump of freedoom1.wad

To reproduce:
1. Open freedoom1.wad
2. Go to Archive>Texture Editor
3. Observe crash

### Crash Information

```text
Version: 3.2.5
No current action

Operating System: Linux 6.6.10-76060610-generic x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Opening archive /home/vanessakindell/Games/GZDoom/iwads/freedoom1.wad
Opening took 184 ms
Setting up the OpenGL context
Failed to setup the OpenGL context
```

### Screenshots

![image](https://github.com/sirjuddington/SLADE/assets/16767721/b6bd24c7-b1e1-4ad4-b749-47ca8ad1e39a)

**Comment by vanessakindell** [comment]
Neofetch output:
`OS: Pop!_OS 22.04 LTS x86_64 
Host: Oryx Pro oryp5 
Kernel: 6.2.6-76060206-generic 
Uptime: 2 hours 
Packages: 3619 (dpkg), 119 (flatpak), 8 (snap) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: GNOME 42.5 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8750H (12) @ 4.100GHz 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
GPU: NVIDIA GeForce RTX 2060 Mobile 
Memory: 5551MiB / 15694MiB`

**Comment by sirjuddington** [comment]
I see in the log it says it failed to setup the OpenGL context, does viewing normal graphics work for you?

**Comment by Rogosapiens** [comment]
Those are the same I think: #1549 #1672
It is wxwidgets bug i believe and newest version fixes it afaik.
Viewing normal graphics works fine for me. Only texture editor suffers from it.
