### ISSUE TITLE
Feature Request : An option to disable/hide revert button above the text editor.

### ISSUE THREAD

**Issue by Dewzan** [sirjuddington/SLADE#1673]
### Editor

Resource editor

### Description of your feature request

I would like SLADE to ...

provide an option in the settings to hide/disable the Revert button above the text editor. I just had a particularly frustrating morning after spending about an hour on a text file, and losing my progress. I went to click on one of my other archives, and since the revert button is right below, I accidentally clicked that instead. Once the revert button is clicked, there was no way to undo it, no warning asking me whether or not to proceed or decline, and it just seems to me like it's this self-destruct button to avoid at all costs, right next to everything else. I'm bound to click it at some point, whether I like it or not.

I would argue that if I wanted to revert my text file, I would click off of the text file so it asks me to save the changes, and then I would decline saving. At least I get a warning about that.

At the very least, if my request for an option to hide/disable the Revert button gets declined, then perhaps there is a way to give a warning before proceeding with the revert, or offering a way to undo a revert.

Here's a screenshot of what happened earlier today. I went to click on the blue circle, and accidentally clicked on the red, and I lost all my progress. (The reason I hadn't saved before, was because I had never interacted with the revert button, and I didn't think something would go wrong beforehand)
![Screenshot 2024-02-29 115725](https://github.com/sirjuddington/SLADE/assets/161754745/18a5b92c-0520-4237-8b01-62ffd8bd1ff1)

Of course, there's the possibility that I may be missing something. It's the first time I've ever interacted with the revert button ever in my years of using SLADE, and it is completely meaningless to me. If I am missing something important, please feel free to correct me.

### Mock-up

![DESCRIPTION](LINK.png)
In the Slade Settings, the setting to disable the revert button would be likely be located within the Interface category, or wherever else it seems fit. It would simply be a check box that reads something along the lines of "Show Revert Button", and the default for that setting can be whichever you decide. Having the option to hide the Revert Button would ensure that the button is gone above the text editor. The revert option in the Entry menu however, would still be there, because I don't foresee anybody accidentally clicking that revert option (I use hotkeys without needing to open the Entry menu). This way, with the button above the text editor hidden, there is still a way to revert a file if needed without needing to turn the setting back on, and it is still an easy way to revert a file without being too accidentally clickable. I'm sure this change would improve the convenience of SLADE, without losing a truck load of progress.

**Comment by sirjuddington** [comment]
Hmm, I think the best way around this would be to make revert undo-able via ctrl+z, and/or add a warning dialog when it's clicked

**Comment by sirjuddington** [comment]
Ok so apparently the option has been there since 2015 (90b0b296) and defaults to true, so I guess at some point you must have turned it off

![image](https://github.com/sirjuddington/SLADE/assets/2484576/e81cdcc2-b2d1-452a-93a7-22cfb22d6e54)

If you turn that back on hopefully this shouldn't happen again
