### ISSUE TITLE
Crash When Trying to View TEXTURE1 file

### ISSUE THREAD

**Issue by Big-the-Fat** [sirjuddington/SLADE#1685]
### SLADE Version

3.2.5

### OS

Linux

### Editor

Resource editor

### Steps to Reproduce

I was...
Trying to view textures from the TEXTURE1 file in the DOOM2.wad

To reproduce:
1. Click on the TEXTURE1 file
2. Click on the EDIT TEXTURES button in the right side panel
3. Crash occurs

### Crash Information

```text
Version: 3.2.5
No current action

Operating System: Linux 5.15.0-107-generic x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Opening archive /home/fud/Desktop/DooM/Essential/DOOM2.WAD
Opening took 70 ms
Setting up the OpenGL context
Failed to setup the OpenGL context
```

**Comment by sirjuddington** [comment]
Again not much I can do without a stack trace but it's probably similar to the other issues people are having with the TEXTUREx in linux
