### ISSUE TITLE
Crash When Trying to Open TEXTURE1

### ISSUE THREAD

**Issue by Big-the-Fat** [sirjuddington/SLADE#1693]
### SLADE Version

3.2.6

### OS

Linux

### Editor

Resource editor

### Steps to Reproduce

I was... Opening TEXTURE1 file to look at textures

To reproduce:
1. Double Click on TEXTURE1 file
2. Crash occurrs

### Crash Information

```text
Version: 3.2.6
No current action

Operating System: Linux 5.15.0-112-generic x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Opening archive /home/fud/Desktop/DooM/Essential/DOOM2.WAD
Opening took 75 ms
Setting up the OpenGL context
Failed to setup the OpenGL context
```

### Screenshots

![DESCRIPTION](LINK.png)

**Comment by Big-the-Fat** [comment]
Here's  the Stack Trace output:

Version: 3.2.6
No current action

Operating System: Linux 5.15.0-112-generic x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Opening archive /home/fud/Desktop/DooM/Essential/DOOM2.WAD
Opening took 75 ms
Setting up the OpenGL context
Failed to setup the OpenGL context

**Comment by sirjuddington** [comment]
There is no actual stack trace there so not much I can do (it's blank below the 'Stack Trace:' bit). Since you're on linux it's likely related to the other issues people are having (https://github.com/sirjuddington/SLADE/issues/1672), which seems to be a wxwidgets issue
