### ISSUE TITLE
Website Debian repo instructions could use some adjustment

### ISSUE THREAD

**Issue by Blzut3** [sirjuddington/SLADE#1697]
### OS

Linux

### Issue Details

The website's instructions for using the DRD Team repo could use some refinement.  At a minimum if you're going to go with the keyring directory method you may as well just skip the apt-add-repository command since it's providing no real benefit.  (It adds the source and does an apt update, but the latter fails due to the key not being in place (causing confusion: https://forum.drdteam.org/viewtopic.php?t=10115).  So the final echo does its job and the user needs to call apt update anyway afterwords anyway which is not documented.)

```bash
sudo mkdir -p /etc/apt/keyrings
sudo wget https://debian.drdteam.org/drdteam.gpg -P /etc/apt/keyrings
echo 'deb [signed-by=/etc/apt/keyrings/drdteam.gpg] https://debian.drdteam.org/ stable multiverse' | sudo tee /etc/apt/sources.list.d/drdteam.list
sudo apt update
```

Starting with Ubuntu 22.04 and Debian 12 there is a slightly more streamlined method though which I recently added to the header of the repo:
```bash
sudo wget -P /etc/apt/sources.list.d https://debian.drdteam.org/drdteam-$(dpkg --print-architecture).sources
sudo apt update
```

**Comment by sirjuddington** [comment]
I've updated the page, also just FYI it's on the Wiki here, and since you have collaborator access you should be able to edit Wiki pages (let me know if you can't for some reason)
