### ISSUE TITLE
Additional Sector Tags in UDMF Maps aren't detected

### ISSUE THREAD

**Issue by ohyesss** [sirjuddington/SLADE#1710]
### SLADE Version

3.2.6

### OS

Linux

### Editor

Map editor

### Steps to Reproduce and Observed Behavior

Create a UDMF map, and a sector, and put a number into the additional sector tags property.
Give a special to any line, with a target sector value of the same number as the additional sector tag.
Hover over the sector, and see that there is no visual indication of the line special's connection. 

The same thing will happen with 3D Floors in the 3D Editor

### Expected Behavior

When the mouse hovers over sector, there should be an indicator showing the line special that connects to the sector with the additional sector tag.

### Screenshots

![sectortagcomparision](https://github.com/user-attachments/assets/f0e10739-d8bb-4a55-95cc-f9fc95baa6d6)

**Comment by eevee** [comment]
i wish!  this is #328
