### ISSUE TITLE
Clicking on resources with graphical previews freezes the main window

### ISSUE THREAD

**Issue by kotauskas** [sirjuddington/SLADE#1718]
### SLADE Version

e745dc0f59fd53f1c8c252a36855ea4ee5816128

### OS

Linux

### Editor

Resource editor

### Steps to Reproduce and Observed Behavior

On Arch Linux, having built SLADE with the `slade-git` AUR package:

1. Open any WAD, such as `DOOM2.WAD`
2. Click on any resource type that has a graphical preview, such as `PLAYPAL`, `ENDOOM`, any flat or any texture (not sounds, not demos)
3. Main window locks up and ceases to respond to any input

**Comment by Blzut3** [comment]
I'm guessing you're on Wayland?  Try forcing xwayland with `GDK_BACKEND=x11 slade`.  (See also: #1351)

**Comment by kotauskas** [comment]
> Try forcing xwayland with `GDK_BACKEND=x11 slade`.

That fixes everything, thanks! Closing as duplicate of #1351.
