### ISSUE TITLE
Duplicated mouse wheel events.

### ISSUE THREAD

**Issue by yosoyfreeman** [sirjuddington/SLADE#1744]
### SLADE Version

3.2.6

### OS

Linux

### Editor

Map editor

### Steps to Reproduce and Observed Behavior

While using the map editor, scroll wheel inputs are duplicated after the first scroll input.

Start a new level. Go to 3D view. Raise a ceiling with the mouse wheel. It goes up by 8 units. Do it again and it goes up by 16 and every roll of the wheel will be reported twice. If you click on another app and go back to slade it will work as intended again only one time, after which the duplication starts again.

Tested on Fedora, ubuntu and linux mint. It happens in the flatpak version, the deb package from the repositories and when compiling from scratch. Also tested different machines and mouse and made sure it's not a hardware issue.

### Expected Behavior

One scroll of the mouse should report one scroll of the mouse.

### Screenshots

You can see the first input working correctly. The next one is duplicated. Each time the app looses focus and goes back it works one time correctly.

![image](https://github.com/user-attachments/assets/4a137a70-66e5-40ee-87f9-4cffd81ede9d)

**Comment by eevee** [comment]
i'm hoping i fixed this with 3188c78, so it should be fixed in the next release

**Comment by yosoyfreeman** [comment]
Compiled the commit and tested on Linux mint, problem is fixed! Thank you a lot, i would close this issues as seems to be totally solved.
