### ISSUE TITLE
Mouse not captured on wayland in 3d mode

### ISSUE THREAD

**Issue by jiffygist** [sirjuddington/SLADE#1748]
### SLADE Version

98f9b5cbf4bd832a4f9792bc0ea216fcb8d6e9a5

### OS

Linux

### Editor

Map editor

### Steps to Reproduce and Observed Behavior

1. Run slade on wayland
2. Open a map, press Q
3. Mouse can escape the slade window, impossible to rotate 3d camera around

### Expected Behavior

When running on X, mouse works properly

### Screenshots

https://github.com/user-attachments/assets/9e39e0de-0631-4133-a122-55673ff52162

**Comment by Blzut3** [comment]
There are multiple issues with Slade under Wayland which are believed to be on wxWidget's end.  For the time being it is recommended to run under Xwayland.

**Comment by Blzut3** [comment]
Duplicate of #1595.
