### ISSUE TITLE
Remove USE_SFML_RENDERWINDOW?

### ISSUE THREAD

**Issue by Blzut3** [sirjuddington/SLADE#1760]
### SLADE Version

be9fb02

### OS

Linux

### Editor

Map editor

### Steps to Reproduce and Observed Behavior

1. Build SLADE with -DUSE_SFML_RENDERWINDOW=ON
2. Notice errors due to using GTK headers

### Expected Behavior

I'm guessing this code is due for removal.  Particularly since as of f8ca52e linking to GTK has been removed so this code path can no longer compile.  It appears it was removed as a documented option in 8423e17.

Only noticed this since I just happened to stumble across the GTK calls still remaining in src/UI/Canvas/OGLCanvas.cpp and wondered why they were there given the commit removing the GTK code.

**Comment by sirjuddington** [comment]
Ah yeah of course, knew I was missing something when I removed the GTK stuff :P

It can safely be removed since the SFML RenderWindow stuff never really worked correctly in GTK anyway, was only using it in Windows but it's no longer used there any more either.

**Comment by Blzut3** [comment]
Not sure if you wanted to remove the function `app::useSFMLRenderWindow` instead of just turning it into a function that always returns false?  Looks like it's not referenced anywhere (even before).
