### ISSUE TITLE
Sound viewer cannot identify Broadcast Wave Format

### ISSUE THREAD

**Issue by wildweasel486** [sirjuddington/SLADE#180]
Using this WAV file as an example: https://copy.com/PStWbBE2Rv4m

Importing the WAV file into SLADE will result in it failing to identify it as a WAV file. It is actually in Broadcast Wave Format, which most of my sound programs can identify. Opening SLADE's console and forcing it to identify as "snd_wav" allows the file to view and playback correctly. Presumably the issue is simply that SLADE doesn't know what to do with BWF's additional header information.

**Comment by Gaerzi** [comment]
This is a very old report with no feedback; and if there was a problem I figure it has been fixed with f9e49c064dde5ae516b481d042715875fdc367a0.
