### ISSUE TITLE
Cannot change actor/sector properties in mapeditor GUI

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#182]
How to cause this bug:
1. Change sector/actor properties (but don't click to another text box, else bug will not appear)
2. Apply it!
3. Props won't change! Fuuuuuu.

**Comment by sirjuddington** [comment]
I think in 3.1.2 I'm gonna replace the generic properties grid altogether with something better/custom, since wxPropertyGrid is kinda bad.
