### ISSUE TITLE
When dragging & dropping multiple wads onto SLADE's start page, only one is opened.

### ISSUE THREAD

**Issue by plumsinus** [sirjuddington/SLADE#186]
If I ctrl-click multiple wads in Explorer and drag them onto SLADE's start page to open them, _usually_ only one gets opened - it seems like occasionally, more than one will open properly. Earlier betas of 3.1 did not have this problem.

**Comment by sirjuddington** [comment]
Closing this since it's old and there isn't much I can do about it
