### ISSUE TITLE
Viewing textures in the texture editor is slow when CIEDE 2000 colorspace is used

### ISSUE THREAD

**Issue by plumsinus** [sirjuddington/SLADE#204]
Hi, I've noticed that when I set the colour matching to CIEDE 2000 in the colormetry preferences, viewing textures in the texture editor is quite slow, presumably because they're being converted into CIEDE 2000 space somehow. Other graphics in the main tab of the wad seem fine. The obvious workaround of not setting CIEDE 2000 while looking at textures is good enough for the time being.

**Comment by sirjuddington** [comment]
Not sure much can be done here, the CIEDE 2000 colour matching is complicated
