### ISSUE TITLE
Long name support

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#216]
ZDoom supports long map names (in PK3) and long texture names (in UDMF maps, PK3 stand-alone textures and flats, and TEXTURES definitions) now. Relevant commits include https://github.com/rheit/zdoom/commit/65e8563cf44235725ef0f198f48956eca9f467cf, https://github.com/rheit/zdoom/commit/fedf9c6a5ba40e4166b9da6874a7454a174d38fc, https://github.com/rheit/zdoom/commit/a05e62f3f7b4d690ebe5398a5c76c7c796bfad36, https://github.com/rheit/zdoom/commit/8c052818b7acdc428a590a0c0cd8922d5c7aeb94, https://github.com/rheit/zdoom/commit/03d4f23a6e94b9c6d89ac3dcea2b187014d1384c, https://github.com/rheit/zdoom/commit/26b1abe3dab611001b49ce717853b0accd8c5516. Relevant threads include [this one](http://forum.zdoom.org/viewtopic.php?f=18&t=45824) and [that one](http://forum.zdoom.org/viewtopic.php?f=18&t=45887). SLADE needs to support long names too now.

**Comment by sirjuddington** [comment]
I think all this stuff is done now, but I'll keep this open in case I missed something
