### ISSUE TITLE
MIDI playing crashing SLADE

### ISSUE THREAD

**Issue by Armaetus** [sirjuddington/SLADE#218]
After a bit of playing a MIDI, the program crashes with this for me:

![slade-error](https://cloud.githubusercontent.com/assets/6969122/5232154/1bab14f2-7716-11e4-82be-10b34b3ba57a.jpg)

This is with version 3.1.0.1 on Windows 7 Home Premium 64 bit.

**Comment by MajorCooke** [comment]
Where can I find a copy of this development version?

**Comment by Gaerzi** [comment]
devbuilds.drdteam.org/slade/
