### ISSUE TITLE
Import archive as lumps

### ISSUE THREAD

**Issue by haleyjd** [sirjuddington/SLADE#222]
I don't see a feature for importing another archive into the current one and having its lumps just become top-level lumps of the current archive. This type of operation particularly makes sense for WAD files. Bonus points if you can select which archive has priority in the event of conflicts with existing lumps in the target archive.

**Comment by sirjuddington** [comment]
Closing - a script could be written to do this, it's also mostly possible to do just via copy+paste

Feel free to reopen the issue if needed
