### ISSUE TITLE
CTRL-Z and CTRL-Y (undo/redo) in map editor don't works

### ISSUE THREAD

**Issue by riderr3** [sirjuddington/SLADE#229]
In latest build from source, CTRL-Z and CTRL-Y (undo/redo) in map editor don't works (both 2d and 3d). At least I can undo/redo from upper panel but this is very annoying.

**Comment by riderr3** [comment]
Resource editor also.

**Comment by Zalewa** [comment]
I confirm. Ubuntu 14.04 with classic Gnome here.

**Comment by sirjuddington** [comment]
Should be working again now
