### ISSUE TITLE
Smooth lines actually not smooth.

### ISSUE THREAD

**Issue by riderr3** [sirjuddington/SLADE#230]
I remember some months ago its worked but not now.
BTW i am on Ubuntu 14 with gallium/ati video driver.

![2015-01-29 13 14 34](https://cloud.githubusercontent.com/assets/1625116/5972968/3fa2aa9e-a873-11e4-8729-ff01a537df61.png)

**Comment by sirjuddington** [comment]
This is a driver issue by the looks of it

**Comment by sirjuddington** [comment]
Going to close this one as it isn't an issue with SLADE
