### ISSUE TITLE
Line action special window is too small by default

### ISSUE THREAD

**Issue by riderr3** [sirjuddington/SLADE#231]
![2015-01-28 23 27 09](https://cloud.githubusercontent.com/assets/1625116/5972987/a7e9c10a-a873-11e4-9f16-efedb97162a0.png)

**Comment by sirjuddington** [comment]
Yeah, eventually I need to make SLADE more aware of font sizes and size the interface accordingly, especially with high-dpi/'retina' displays becoming more prominent.

**Comment by eevee** [comment]
I've been having a, uh, somewhat worse problem:

![image of line special dialog, collapsed so small only two buttons are visible](https://cloud.githubusercontent.com/assets/94112/8510041/2d0aa5de-2281-11e5-8b8b-8188077a67f7.png)

I did a lot of fiddling with sizers to no avail.  No idea why this is happening, and it only happens with the "change special" dialog, not the full properties dialog.
