### ISSUE TITLE
Mouse scroll doesn't scroll "Input Preferences" (and other lists)

### ISSUE THREAD

**Issue by Zalewa** [sirjuddington/SLADE#239]
Ubuntu 14.04 with gnome classic. Trying to scroll "Input Prefences" vertically doesn't scroll anything. The same applies to other lists such as "sector specials" or "line specials".

**Comment by sirjuddington** [comment]
What version of wxWidgets are you using to compile? I remember a similar thing happening with a certain verson of wx in linux/gtk (may have been 3.0)

**Comment by Zalewa** [comment]
```
test@test-VirtualBox:~$ dpkg -l | grep libwx | grep 3.0 | tr -s ' ' | cut -d' ' -f-3
ii libwxbase3.0-0:i386 3.0.0-2
ii libwxbase3.0-dev 3.0.0-2
ii libwxgtk-media3.0-0:i386 3.0.0-2
ii libwxgtk-media3.0-dev 3.0.0-2
ii libwxgtk3.0-0:i386 3.0.0-2
ii libwxgtk3.0-dev 3.0.0-2
```

**Comment by sirjuddington** [comment]
If possible, try compiling with wxWidgets 3.0.2 and see if it still happens

**Comment by Zalewa** [comment]
Compiling with wxWidgets 3.0.2 solves the problem. Sorry for the late reply. Even the download page acknowledges the problem: http://codelite.org/LiteEditor/WxWidgets30Binaries#toc2

**Comment by sirjuddington** [comment]
Closing this issue as wx 3.0.2 is now in the ubuntu repository (at least on 15.04)
