### ISSUE TITLE
Input preferences - key bindings column is positioned behind the screen when the page is first opened

### ISSUE THREAD

**Issue by Zalewa** [sirjuddington/SLADE#240]
Input preferences - key bindings column is positioned behind the screen when the page is first opened. You can adjust the table by resizing the preferences dialog box.

![Imgur](http://i.imgur.com/wgMtb5S.jpg)

**Comment by sirjuddington** [comment]
Unfortunately this looks like another wxWidgets issue, has been around for [a long time](https://groups.google.com/forum/#!topic/wx-dev/oR8HxfDyfnY) apparently

**Comment by sirjuddington** [comment]
Closing - not much can be done about it
