### ISSUE TITLE
Adding the "fly" actor class to the configs

### ISSUE THREAD

**Issue by Blue-Shadow** [sirjuddington/SLADE#251]
This [actor class](https://github.com/rheit/zdoom/blob/master/wadsrc/static/actors/hexen/flies.txt), which was added recently to ZDoom.

I would've done it myself, except that I don't know to which category it should belong and whether it should be exclusive to Hexen or be available to all games (I mean, the actor's sprites are provided by ZDoom itself, after all).

**Comment by Gaerzi** [comment]
LittleFly is given ednum 112 in mapinfo/hexen.txt, it's not present in the other games, so it should be Hexen-only.

**Comment by Blue-Shadow** [comment]
Alright, noted.

Thanks for the addition.
