### ISSUE TITLE
Quotation marks inside parameters choke the config parser, forcing the settings to reset

### ISSUE THREAD

**Issue by simon-v** [sirjuddington/SLADE#254]
Every now and then the first time setup window pops up on program start, indicating that the user settings were reset. The .slade3 directory is present and is read-writable. Looking inside it shows all the config files intact. The settings are then overwritten with the default values and need to be set anew. This seems to happen without any obvious indications as to why.

I would like to help narrow it down, but i don't know where to start.

Program and library versions:
slade 3.1.0.1.r64 built from git
wxgtk 3.0.2
System information:
ArchLinux x86_64, Kernel version 4.0.1

**Comment by sirjuddington** [comment]
Next time it happens, could you post the slade log file? (should be in .slade3)

**Comment by simon-v** [comment]
I have discovered the reason for the reset by looking at a diff of both my config file and the newly-generated one. It seems that the config parser chokes on this line:
```        run_last_extra          "-warp 01 "+warp -300 2350""```
Note the extraneous quotation marks.

When the quotation marks are replaced with single quotes, the configuration loads normally. Perhaps, some sort of escaping or conversion procedure is in order.

**Comment by simon-v** [comment]
By the way, there was no log file in the .slade3 directory. Perhaps, the feature has to be turned on?..

**Comment by sirjuddington** [comment]
Hmm ok, double quotes within configs will indeed break things. Also, the log file is in the same directory as the executable sorry, forgot where it was saved in linux :P
