### ISSUE TITLE
External editor support for lumps

### ISSUE THREAD

**Issue by jmickle1** [sirjuddington/SLADE#257]
Currently each lump has a series of editors built in to slade, especially the Graphic lumps. To increase ease of use for content creators, I propose a system to define external editors for lump types in settings.

The way I see it working is to have a list of each recognized lump type in the preferences (Graphic, Audio, Map, Text, MIDI, and a HEX fallback, possibly?) and a path to an external editor to open them with. Then in the right-click menu, an "open in external editor" option would load them up for editing. This could work by creating a temporary file in the system and tracking changes while the external editor is open.

More details for specific file types:

Graphics:
They would need to be converted to PNG before editing, but this could be automatic before opening the file for editing. A checkbox option could specify whether the graphic is automatically converted back into Doom Graphic format afterwards (or whichever format the lump was already in). All graphic formats can be treated the same way as far as I can see.

Audio:
Audio files would need to be separated from MIDI and MUS files, for obvious reasons. Doom SND format would need to be converted to WAV upon editing, possibly with an option to convert back afterwards, similar to the suggested approach for Graphics. Other filetypes could stay the same. (maybe an option to always convert to WAV upon editing regardless of original format)

Map:
This is already supported in a non-generalized way with Slade's own editor and opening in Doombuilder. While it is not a top priority since these are the two major editors, it would make sense to take the same approach as other external editors here.

Text:
No special circumstances.

MIDI:
MUS files would need to be converted to MIDI before editing. Optionally convert back to MUS afterwards.

**Comment by Gaerzi** [comment]
Personally I hate the MUS format and will oppose inclusion of a MIDI to MUS converter.

**Comment by jmickle1** [comment]
Yeah, that's fair enough. There is no strict need for a MIDI to MUS converter since doom.exe 1.9 supports midi files.

**Comment by sirjuddington** [comment]
This is already a planned feature for 3.1.1 - see #2

**Comment by Gaerzi** [comment]
I guess it can be closed as duplicate then.
