### ISSUE TITLE
External Plugin system for processing lumps

### ISSUE THREAD

**Issue by jmickle66666666** [sirjuddington/SLADE#258]
As a companion feature to https://github.com/sirjuddington/SLADE/issues/257 , I propose a plugin system for processing lumps. As opposed to the external editors, this system would be for single-purpose plugins, such as a MIDI>MUS or similar function. It could also work for simple editors like the color remapping tool, but the scope is definitely for simple tasks.

A /plugins/ folder structure would house a folder for each recognized lump type (Graphic, Audio etc), and scripts or executables would be placed in those folders. These would then populate a Plugins section of the right-click menu for lumps. Anything in the root /plugins/ folder would appear for every lump type. 

A simple temporary file system would track changes when processing a lump with a plugin, which could safely be removed once the plugin application has terminated. 

As far as unsafe usage is concerned (processing a text file with some form of graphic processing plugin), this is down to user error. The only solution I imagine could work is having accompanying config files for each plugin that define what lump/file types it supports. This would of course be more work and not completely necessary.

**Comment by sirjuddington** [comment]
Closing - this is/will be covered by the scripting system
