### ISSUE TITLE
OSX: Changing font in text editor preferences cause a crash

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#264]
"Under Text Editor/Fonts & Colors, when I try and click on "Courier, 10" in the settings panel, SLADE beachballs and eventually dies.  Editing the stylesheet config file by hand seems to work okay."

See [this thread](http://mancubus.net/forums/index.php/topic,1866.msg0.html) for further information.

**Comment by sirjuddington** [comment]
This looks like an issue in wxWidgets 3.0.0, that has since been fixed. The wx library used in the osx fork will need to be updated to 3.0.2
