### ISSUE TITLE
OSX: ACC executable cannot be selected from scripting preferences

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#265]
"Under Scripting/ACS -> Location of acc executable, I can't actually select the acc executable when I browse for it.  If I put the path in manually, it works."

See [this thread](http://mancubus.net/forums/index.php/topic,1866.msg0.html) for further information.

**Comment by sirjuddington** [comment]
Fixed in 78ab9df4cb2449798ae605cd073c7a11a131f402
