### ISSUE TITLE
Slade fails to run past the Setup window on OSX - again

### ISSUE THREAD

**Issue by PresidentPeople** [sirjuddington/SLADE#274]
Basically #198, but without the splash window.  All options are still grayed out after either completing or dismissing the setup prompt.  

Curiously, the tip of the day changes as I select Slade in the Force Quit window.  

http://puu.sh/iacuz/6339867263.png

**Comment by sirjuddington** [comment]
Does this still happen in 3.1.1.3+ ?

**Comment by PresidentPeople** [comment]
I've since moved to a new computer, and a newer version of OSX, but I didn't have any issues with the initial setup in v3.1.1.3 on this new computer.  

Sort-of-related: I'm unable to check anymore, but one of the recent updates (this or the last, I believe) broke compatibility with OSX 2.6.8.  Got the ol' no entry sign. 🚫

Looking back, this issue might have been OS version-related, and I apologize for not stating which one I was running before.

**Comment by Gaerzi** [comment]
I know nothing about Macs (except that they're an overpriced walled garden :stuck_out_tongue: ). Is OS 2.6.8 worth supporting?

**Comment by alexey-lysiuk** [comment]
What is OSX 2.6.8 actually? Maybe it's 10.6.8 as X in OS name is Ten not Iks/Eks and all Apple's OSes for Intel were 10.x.x (starting with 10.4 Tiger).

**Comment by PresidentPeople** [comment]
I meant 10.6.8, sorry.  Not sure how that slipped by.

**Comment by sirjuddington** [comment]
Yeah, the minimum OSX (macOS now, I guess) required is 10.7 now

**Comment by sirjuddington** [comment]
Closing - resolved issue

Feel free to reopen the issue if needed
