### ISSUE TITLE
Installation on OS X using Homebrew

### ISSUE THREAD

**Issue by alexey-lysiuk** [sirjuddington/SLADE#275]
I created a guide about installation on OS X using [Homebrew](http://brew.sh/).
Is it feasible to reference it somehow in the Wiki? In [Compiling SLADE](https://github.com/sirjuddington/SLADE/wiki/Compiling-SLADE) section, for example.
Please note that the guide and the formulae are subject to change. At the moment, wxWidgets from Homebrew cannot be used directly. But most likely this will be fixed with the next wxWidgets release.
In your opinion, what is the best way to mention the guide in the Wiki?

**Comment by sirjuddington** [comment]
Hmm, is there any chance you could convert it to markdown and write it directly on the wiki? The wiki *should* be open to any GitHub user for editing.

**Comment by alexey-lysiuk** [comment]
Sure, the guide itself is already in markdown format.
Note that a separate repository with formulae (.rb files) is needed to simplify the installation process.
I just don't want to copy read-me from this repository to the Wiki and to keep both versions up-to-date.
That's why I was asking about reference. But if you insist, I will add the guide's content to the Wiki.

**Comment by Gaerzi** [comment]
You could always put a link to the original article in an "External links" section at the bottom of the article.

**Comment by alexey-lysiuk** [comment]
I'm in doubt about a proper location. It's more about installing rather than compiling, i.e. build from source but for usage, not for development.
Actually, I can add a page with the complete guide. However from where should I link it, from Installation, Downloads or Advanced/Compiling?

**Comment by alexey-lysiuk** [comment]
I have added [the page](https://github.com/sirjuddington/SLADE/wiki/Installation-on-OS-X-using-Homebrew). The question is still about the best place to refer it.

**Comment by Gaerzi** [comment]
I put it on the [Compilation](https://github.com/sirjuddington/SLADE/wiki/Compiling-SLADE) page since it does involve compilation. I also made sure that the Windows-centric [Installation](https://github.com/sirjuddington/SLADE/wiki/Installation) page had a notice linking Linux and Mac users to the Compilation page.

**Comment by alexey-lysiuk** [comment]
Great, thanks.
