### ISSUE TITLE
Half-Life WAD3 Issues

### ISSUE THREAD

**Issue by Xylemon** [sirjuddington/SLADE#281]
It seems loading Half-Life's WAD3 format produces incorrect texture names (or in this screenshot, nothing at all): http://bloodbathsoftworks.com/xylemon/images/screencaps/selection-07-06-2015_05:05:39.png

Also, it seems Slade wants to export textures from WAD3 as "hlt" files for some reason rather than a BMP.

**Comment by Xylemon** [comment]
Again, thanks for the awesome quick fix! The only problem though is I still can't export textures from WAD3 files as BMPs, Slade forces me to export them as "hlt" files.

**Comment by Gaerzi** [comment]
Yes, SLADE's export feature is a direct export, without format conversion. For image an "export as PNG" was added for convenience. BMP was not chosen for such a role because this format doesn't allow to preserve some metadata (such as offsets) and it doesn't have transparency in 8-bit mode.

**Comment by Xylemon** [comment]
I see, thanks for the information.
