### ISSUE TITLE
Silverspring soundfont playback issue

### ISSUE THREAD

**Issue by GlaiceOldSchoolRTS** [sirjuddington/SLADE#288]
When I fire up some MIDI or MUS playback using the Silverspring 1.5 soundfont, the guitars and percussion are HEAVILY distorted and ruin the sound of the song, but they sound fine when using Synthfont hearing from this video: https://www.youtube.com/watch?v=Jqsi-E5wr-c (Font is in comments) or even in-game utilizing BASSMIDI for playback with GZDoom.

Another minor issue with the Merlin Vienna soundfont has a few issues with the synth strings but seem to be OK everywhere else. I could get an unlisted private video for you to hear if needed.

I also am using Realtek onboard sound btw.

Do you have any idea why playback seems distorted for certain instruments under SLADE 3.1.0.3?

-Doom Video Vault

**Comment by Gaerzi** [comment]
It's a FluidSynth issue. See [ZDoom wiki](http://zdoom.org/wiki/FluidSynth).
