### ISSUE TITLE
Build of 3.1.0.4 for OS X 

### ISSUE THREAD

**Issue by alexey-lysiuk** [sirjuddington/SLADE#292]
I've prepared a binary build of 3.1.0.4 for OS X and uploaded it [here](https://drive.google.com/open?id=0B61jNyEkZMJLa2k5NEUxREIyYlU&authuser=0).
Requirements are Intel Mac with 64-bit CPU running OS X 10.6 or later.

It was built from the corresponding tag using third-party libraries from [this repository](https://github.com/alexey-lysiuk/slade-osx-build). You can replicate the build yourself if needed.

I see no reason to maintain my fork, as the main repository has the identical source code, just without a build environment. I think it's better to add OS X version to [the release](https://github.com/sirjuddington/SLADE/releases/tag/3.1.0.4).

**Comment by sirjuddington** [comment]
Hmm ok, that's fair enough. I'll see if I can get it building properly myself now that I have a working OS X VM.

**Comment by alexey-lysiuk** [comment]
I have added Xcode project in addition to CMake-based building environment.
At the moment, it doesn't pack all resources into .pk3 but it has a target to create a disk image.

**Comment by alexey-lysiuk** [comment]
Maybe I am missing something but still there is not binary builds for OS X.
There is Windows-only versions of 3.1.0.5 and 3.1.1 beta 1 releases.
If you have some troubles building using [this repository](https://github.com/alexey-lysiuk/slade-osx-build), let me know.
Alternatively, I can provide you with the binary builds for OS X that can be added to releases.

**Comment by sirjuddington** [comment]
Ok finally got builds up for 3.1.0.5 and 3.1.1 beta 1. VM shat itself so I just ended up reinstalling OSX on my macbook and building it there, seems to work fine.
