### ISSUE TITLE
SLADE crashes on new WAD/open WAD

### ISSUE THREAD

**Issue by Mistranger** [sirjuddington/SLADE#297]
Windows 7 x64
If there are no audio devices at all, or if user have disabled all of them (my Realtek internal audio card automatically disables playback devices if there are no audio jacks connected), SLADE crashes when you open or create a WAD.

**Comment by sirjuddington** [comment]
If possible, would you be able to post a stack trace?

**Comment by Mistranger** [comment]
Looks like I've solved the problem. It was crashing because of old openal32.dll in program distribution. I've updated it with new dll (1.1 from the official site) and now SLADE works fine. I think it's time to update the openal32.dll with new version.

**Comment by Mistranger** [comment]
3.1.0.5 still have outdated openal32.dll and therefore still crahes on new/open WAD if there are no active sound devices available on Windows. Please update Windows package with newest openal32.dll

**Comment by sirjuddington** [comment]
Ok the dll has been updated in the installer and 7z releases for 3.1.0.5
