### ISSUE TITLE
Annoying highlights

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#299]
One thing that bothers the living daylights out of me is how highlights can hang around when one switches programs, such as starting up GZDoom to test something and an irritable tag hangs over like a little brother just trying to screw with you and mess you up in something important.

Can this be changed to detect if the program's not in focus, turn off all the highlights?

**Comment by Gaerzi** [comment]
Do you mean the tooltip that appears when hovering on keywords in the text editor? Because that I think can be blamed entirely on wxWidgets.

**Comment by MajorCooke** [comment]
Yep that's it.

**Comment by sirjuddington** [comment]
Well I had more of a look at this, 8987195ba57018bc67f07b4067434ec8c70a7f31 should make things a little bit better but they still like to stay showing sometimes. As Gez said, this isn't an issue with SLADE in particular, it seems to be a wx/Scintilla thing, so I'm not sure there is much more I can do short of not using them and implementing something myself manually.

**Comment by MajorCooke** [comment]
Unfortunately there's a crash that may need addressing. I posted it shortly after this one. https://github.com/sirjuddington/SLADE/issues/300
