### ISSUE TITLE
Annoying Hint Crash

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#300]
Yet another problem involving those highlights. I don't recall if this affects Windows 7 or not, but I know it happens on Windows 10. Here's how to reproduce.

1. Open Slade, then open a file with DECORATE in it. It needs to have an A_ function which you can hover the mouse over and let the hint pop up.
2. Click anywhere on the red highlighted text. This is important to reproducing it.
3. Open another program, or windows explorer, anything will do as long as it doesnt take up the entirety of the function.
4. Simply reposition the mouse over the function. Slade will pull itself to higher priority over all other programs, and the attempt to display the function's abilities will cause it to crash, two times in a row.

The easiest way to avoid the crash in the main time is to disable the mouseover tip display. Thankfully there's the ability to display them with paranthesis and commas.

**Comment by sirjuddington** [comment]
Hopefully fixed with 06bd9fc
