### ISSUE TITLE
Next Unused Tag selecting random

### ISSUE THREAD

**Issue by Catoptromancy** [sirjuddington/SLADE#301]
After highlighting a line or sector and clicking the "..." button for TAG/ID a seemingly random tag is selected. Sometimes though rarely does it select the next unused tag.

The "..." button should be labelled "Next unused tag" or similar; that seems to be is purpose.

**Comment by sirjuddington** [comment]
Fixed. Note that it gets the next tag not in use by any sectors, so if a line has a sector tag of 1 but no sector has a tag of 1, the '...' button will return 1.
