### ISSUE TITLE
Mac Invalid executable path when running in map editor

### ISSUE THREAD

**Issue by Puffycheeses** [sirjuddington/SLADE#302]
I have tried GZdoom and Chocolate doom but when i press run i get invalid executable path.

Chocolate doom
![Chocolate Doom](http://i.imgur.com/9K5qMWm.png)

GZdoom
![GZdoom](http://i.imgur.com/ollZM0i.png)

The error
![Error](http://i.imgur.com/ESobrm8.png)

**Comment by Monsterovich** [comment]
Works fine for me in linux. I don't see the full path of your executable.

**Comment by sirjuddington** [comment]
I think this one is fixed in 3.1.1 beta 2
