### ISSUE TITLE
Batch-converting VILE\x sprites removes all but the sprite number

### ISSUE THREAD

**Issue by jmickle1** [sirjuddington/SLADE#304]
Steps:

> open doom2.wad
> select more than one VILE\ sprite (eg. VILE\1 to VILE\8)
> r-click > convert to > png

Actual Result: 

The sprites are all renamed to just have the number. "VILE\1" becomes "1" etc.

Slade 3.1.0.4
Windows 8.1

**Comment by Monsterovich** [comment]
I can't reproduce. It doesn't happen in 3.1.0.2 and in the lastest build too.

**Comment by Monsterovich** [comment]
http://www.youtube.com/watch?v=czlM21Y1w4s

**Comment by jmickle1** [comment]
way to be snarky. thought about maybe trying to reproduce on the same operating system? 
http://i.imgur.com/DXFvTPV.gif

**Comment by jmickle1** [comment]
If you want some more information that might help: '\' is an invalid character in filenames on Windows, but not on Linux and other Unix-related systems.

**Comment by Monsterovich** [comment]
But I don't know how this is related with filenames inside the archive.

**Comment by jmickle1** [comment]
Neither do I! I don't know how the code works, I'm just reporting a bug and providing whatever information I can. It is possibly related since the bug is reproducible on windows but not linux.

**Comment by haleyjd** [comment]
Converting graphics to PNG seems to send the lumpname through ArchiveEntry::setExtensionByType, which treats the lumpname as if it is a platform-specific physical filename and allows wx to do transformations on it willy-nilly. This needs to be significantly scaled back so that only known transformations to lump names take place when doing conversions.

**Comment by sirjuddington** [comment]
Yes, @haleyjd is correct, it's running that function on the entry names even for archives that don't have filename extensions, which ends up treating these names as paths in windows (everything before the \ is not part of the 'name' so ends up removed)
