### ISSUE TITLE
DeHackEd SYNTAX format

### ISSUE THREAD

**Issue by Aeyesx** [sirjuddington/SLADE#306]
Hello!

I'd like to reguest a DeHackEd syntax format to make reading more clear as it can get very long.

**Comment by sirjuddington** [comment]
Added: 9c90e5f

**Comment by Aeyesx** [comment]
Thanks for adding those! It's great to see those!

I was wondering if ZDaemon Dehacked Extensions could be added either? Those were existing either in older zdoom versions and who knows where else.
http://www.zdaemon.org/?CMD=info&NAME=deh
There are Heretic and Hexen codepointers and some specific ones.

There is some DeHackEd sample showing how long those lists can get : http://pastebin.com/MaZ1GAQk
