### ISSUE TITLE
SLADE Crash & Not Responding On Windows

### ISSUE THREAD

**Issue by AA1999** [sirjuddington/SLADE#308]
Anything i want to do with the map editor results to a crash & not responding.
Also renaming my 50 textures resulted to deletion of all my sprites , sounds , music 
i was using the pk3 format by the way.
Keeping slade open for medium time and longer results the not responding on exiting...

**Comment by sirjuddington** [comment]
Do you get a stack trace at all? I can't really do much without it.

**Comment by AA1999** [comment]
Stack trace ? Where ?

**Comment by Monsterovich** [comment]
>Stack trace ? Where ?

All stack traces should be saved to the slade configuration directory as "slade3_crash.log".
On linux/mac it's ~/.slade/. On windows it may be in "Application data".

**Comment by AA1999** [comment]
Here is the text of slade3_crash.log :

Version: 3.1.0.4
No current action

Stack Trace:
0: [unknown location] wcsnicmp
1: [unknown location] wcsnicmp
2: [unknown location] wcsnicmp
3: [unknown location] HeapFree
4: [unknown location] free
5: (c:\dev\slade3\src\memchunk.cpp:100) MemChunk::clear
6: (c:\dev\slade3\src\entrypanel.cpp:145) EntryPanel::openEntry
7: (c:\dev\slade3\src\archivepanel.cpp:2421) ArchivePanel::openEntry
8: (c:\dev\slade3\src\archivepanel.cpp:2955) ArchivePanel::onEntryListFocusChange
9: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:612) wxAppConsoleBase::HandleEvent
10: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:623) wxAppConsoleBase::CallEventHandler
11: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1751) wxEvtHandler::SearchDynamicEventTable
12: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1585) wxEvtHandler::TryHereOnly
13: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1495) wxEvtHandler::ProcessEvent
14: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1647) wxEvtHandler::SafelyProcessEvent
15: (f:\programming\libs\wxwidgets-3.0.2\src\msw\listctrl.cpp:2232) wxListCtrl::MSWOnNotify
16: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3857) wxWindow::HandleNotify
17: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3048) wxWindow::MSWHandleMessage
18: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3645) wxWindow::MSWWindowProc
19: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2711) wxWndProc
20: [unknown location] gapfnScSendMessage
21: [unknown location] gapfnScSendMessage
22: [unknown location] GetScrollBarInfo
23: [unknown location] GetScrollBarInfo
24: [unknown location] KiUserCallbackDispatcher
25: [unknown location] SendMessageW
26: [unknown location] DetachScrollBars
27: [unknown location] ImageList_GetBkColor
28: [unknown location] AttachScrollBars
29: [unknown location] GetEffectiveClientRect
30: [unknown location] DPA_Merge
31: [unknown location] DPA_Merge
32: [unknown location] CCGetScrollInfo
33: [unknown location] gapfnScSendMessage
34: [unknown location] gapfnScSendMessage
35: [unknown location] PeekMessageA
36: [unknown location] CallWindowProcW
37: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2271) wxWindow::MSWDefWindowProc
38: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3651) wxWindow::MSWWindowProc
39: (f:\programming\libs\wxwidgets-3.0.2\src\msw\listctrl.cpp:3060) wxListCtrl::MSWWindowProc
40: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2711) wxWndProc
41: [unknown location] gapfnScSendMessage
42: [unknown location] gapfnScSendMessage
43: [unknown location] gapfnScSendMessage
44: [unknown location] DispatchMessageW
45: [unknown location] IsDialogMessageW
46: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2612) wxWindow::MSWSafeIsDialogMessage
47: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2494) wxWindow::MSWProcessMessage
48: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:148) wxGUIEventLoop::PreProcessMessage
49: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:166) wxGUIEventLoop::ProcessMessage
50: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:232) wxGUIEventLoop::Dispatch
51: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:206) wxEventLoopManual::DoRun
52: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:78) wxEventLoopBase::Run
53: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:334) wxAppConsoleBase::MainLoop
54: (f:\programming\libs\wxwidgets-3.0.2\src\common\init.cpp:495) wxEntryReal
55: (f:\programming\libs\wxwidgets-3.0.2\src\msw\main.cpp:188) wxEntry
56: (f:\programming\libs\wxwidgets-3.0.2\src\msw\main.cpp:415) wxEntry
57: (c:\dev\slade3\src\mainapp.cpp:306) WinMain
58: (f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c:618) __tmainCRTStartup
59: [unknown location] BaseThreadInitThunk
60: [unknown location] RtlInitializeExceptionChain
61: [unknown location] RtlInitializeExceptionChain

**Comment by Monsterovich** [comment]
Does it work in 3.1.1?

**Comment by AA1999** [comment]
I don't know...
But even after an upgrade the result was the same...
That file was for the latest upgrade...

**Comment by eevee** [comment]
Why on earth is `free` calling `wcsnicmp` at all...?

**Comment by AA1999** [comment]
@Monsterovich  
Beta version of an application is not good and stable , is it ?

**Comment by AA1999** [comment]
@sirjuddington 
Anyway , can you please fix the issue in the next update ?

**Comment by eevee** [comment]
They asked if it works in 3.1.1 so we know if it _has_ been fixed in the next update.  :)

**Comment by AA1999** [comment]
I used the latest beta and i still see the crash...

**Comment by sirjuddington** [comment]
Next time you get the crash, could you post the stack trace again? You should see a window like the picture [here](http://i.imgur.com/5YlnS2n.png), though in the latest beta it is a bit different, there should be a 'Copy to Clipboard' button. Click that and then paste it here.

**Comment by AA1999** [comment]
Most of the time i see the "**SLADE 3 is not responding**" Window , and in my Ubuntu 14.04 ,
Each time i exit and return , i see no recent files. That means it crashes silencely in my ubuntu compiled version...
And i remember i was working on my pk3 and just went for a job and when i returned i saw it was closed without any alert !

But if i saw that i will take an screenshot...

**Comment by Gaerzi** [comment]
This used to happen when the configuration files were corrupted. Have you tried to delete (or at least rename, to keep the old configs as backup in case it's not the issue) the config files?

Or perhaps you can put a file named "portable" (no extension) in the same directory as the Slade executable, so it won't look for the normal config wherever it is and create a new one. Just see if it still fails to start normally.

**Comment by AA1999** [comment]
Very strange things are happening in the ubuntu compiled version... (still haven't tried dear Gaerzi's solution)

I exited one time with no silent crash and after my return , the recent files tab was showing the recent file i was working...

After i exited again and return , i saw that the silent crash removed the recent file completely... Like a restore !

What's wrong with this app seriously ??!!!!

**Comment by AA1999** [comment]
Dear SirJuddington ,

The slade3_crash.log in the AppData folder contains the old version crashes ,

Where is the stack trace for the beta unzipped version ?

**Comment by sirjuddington** [comment]
If you aren't getting that window show up like in the screenshot I linked last time, there isn't much I can do. It really sounds like you have some kind of problem with your system.

**Comment by AA1999** [comment]
I have one Laptop & one Computer ,

The laptop is old and contains a pentium dual core cpu & an old VGA...

But the PC is up to date and contains a core i3 cpu and a Geforce VGA ,

I was reporting this form my laptop but when i tried slade on pc i got that window ,

Because i most of the time work with the laptop and working on my pk3 file form there and i'm reporting this from my old laptop , i won't see that window...

But i will post an screenshot from the PC as soon as i can...

**Comment by AA1999** [comment]
Finally got the window !!!

The contents are :


`
Version: 3.1.1 Beta 3
No current action

Operating System: Linux 3.13.0-80-generic i686
Graphics Vendor: Intel Open Source Technology Center
Graphics Hardware: Mesa DRI Mobile IntelÂ® GM45 Express Chipset x86/MMX/SSE2
OpenGL Version: 2.1 Mesa 10.1.3

Stack Trace:
0: [unknown location] [unknown:-1229732733]
1: [unknown location] [unknown:-1217281020]
2: [unknown location] ArchiveTreeNode::getArchive()
3: [unknown location] ArchiveEntry::unlock()
4: [unknown location] MapEditorWindow::openMap(Archive::mapdesc_t)
5: [unknown location] MainWindow::openMapEditor(Archive*)
6: [unknown location] ArchivePanel::handleAction(wxString)
7: [unknown location] MainApp::doAction(wxString)
8: [unknown location] SToolBarButton::onMouseEvent(wxMouseEvent&)
9: [unknown location] wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
10: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
11: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
12: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
13: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
14: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
15: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
16: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
17: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
18: [unknown location] wxWindow::GTKProcessEvent(wxEvent&) const
19: [unknown location] [unknown:-1226989943]
20: [unknown location] [unknown:-1237229890]
21: [unknown location] g_closure_invoke
22: [unknown location] [unknown:-1243611095]
23: [unknown location] g_signal_emit_valist
24: [unknown location] g_signal_emit
25: [unknown location] [unknown:-1235998205]
26: [unknown location] gtk_propagate_event
27: [unknown location] gtk_main_do_event
28: [unknown location] [unknown:-1243053640]
29: [unknown location] g_main_context_dispatch
30: [unknown location] [unknown:-1245809560]
31: [unknown location] g_main_loop_run
32: [unknown location] gtk_main
33: [unknown location] wxGUIEventLoop::DoRun()
34: [unknown location] wxEventLoopBase::Run()
35: [unknown location] wxAppConsoleBase::MainLoop()
36: [unknown location] wxAppConsoleBase::OnRun()
37: [unknown location] wxAppBase::OnRun()
38: [unknown location] wxEntry(int&, wchar_t**)
39: [unknown location] wxEntry(int&, char**)
40: [unknown location] main
41: [unknown location] __libc_start_main
42: [unknown location] _start

Last Log Messages:
11:34:15 AM: Opening map MAP01
11:34:15 AM: Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
11:34:20 AM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
11:34:24 AM: Read game configuration "doom2" + "zdoom"
11:34:24 AM: Opening map MAP01
11:34:25 AM: Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
11:34:45 AM: Read game configuration "doom2" + "zdoom"
11:34:45 AM: Opening map MAP01
11:34:45 AM: Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
11:35:34 AM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
11:35:43 AM: Read game configuration "doom2" + "zdoom"


`

**Comment by AA1999** [comment]
Another one while exiting :

Version: 3.1.1 Beta 3
No current action

Operating System: Linux 3.13.0-80-generic i686
Graphics Vendor: Intel Open Source Technology Center
Graphics Hardware: Mesa DRI Mobile IntelÂ® GM45 Express Chipset x86/MMX/SSE2
OpenGL Version: 2.1 Mesa 10.1.3

Stack Trace:
0: [unknown location] [unknown:-1229319037]
1: [unknown location] [unknown:-1216867324]
2: [unknown location] ArchiveTreeNode::getArchive()
3: [unknown location] ArchiveEntry::unlock()
4: [unknown location] MapEditorWindow::onClose(wxCloseEvent&)
5: [unknown location] wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
6: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
7: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
8: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
9: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
10: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
11: [unknown location] wxEvtHandler::DoTryChain(wxEvent&)
12: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
13: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
14: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
15: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
16: [unknown location] wxWindowBase::Close(bool)
17: [unknown location] MainApp::OnExit()
18: [unknown location] wxEntry(int&, wchar_t**)
19: [unknown location] wxEntry(int&, char**)
20: [unknown location] main
21: [unknown location] __libc_start_main
22: [unknown location] _start

Last Log Messages:
02:48:21 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
02:52:09 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
02:52:50 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
02:53:08 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
02:59:02 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
02:59:18 PM: Read game configuration "doom2" + "zdoom"
02:59:18 PM: Opening map MAP01
02:59:19 PM: Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
03:18:53 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
03:21:56 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
03:22:21 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak

**Comment by AA1999** [comment]
Another :

Version: 3.1.1 Beta 3
No current action

Operating System: Linux 3.13.0-80-generic i686
Graphics Vendor: Intel Open Source Technology Center
Graphics Hardware: Mesa DRI Mobile IntelÂ® GM45 Express Chipset x86/MMX/SSE2
OpenGL Version: 2.1 Mesa 10.1.3

Stack Trace:
0: [unknown location] [unknown:-1229183869]
1: [unknown location] [unknown:-1216732156]
2: [unknown location] BrowserCanvas::showItem(int, int)
3: [unknown location] BrowserCanvas::updateLayout(int)
4: [unknown location] BrowserCanvas::onSize(wxSizeEvent&)
5: [unknown location] wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
6: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
7: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
8: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
9: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
10: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
11: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
12: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
13: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
14: [unknown location] wxWindow::DoSetSize(int, int, int, int, int)
15: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
16: [unknown location] wxBoxSizer::RecalcSizes()
17: [unknown location] wxSizer::Layout()
18: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
19: [unknown location] wxBoxSizer::RecalcSizes()
20: [unknown location] wxSizer::Layout()
21: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
22: [unknown location] wxBoxSizer::RecalcSizes()
23: [unknown location] wxSizer::Layout()
24: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
25: [unknown location] wxBoxSizer::RecalcSizes()
26: [unknown location] wxSizer::Layout()
27: [unknown location] wxWindowBase::Layout()
28: [unknown location] wxTopLevelWindowBase::DoLayout()
29: [unknown location] [unknown:-1224920117]
30: [unknown location] wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
31: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
32: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
33: [unknown location] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
34: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
35: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
36: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
37: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
38: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
39: [unknown location] [unknown:-1226494700]
40: [unknown location] g_cclosure_marshal_VOID__BOXED
41: [unknown location] g_closure_invoke
42: [unknown location] [unknown:-1243062231]
43: [unknown location] g_signal_emit_valist
44: [unknown location] g_signal_emit
45: [unknown location] gtk_widget_size_allocate
46: [unknown location] [unknown:-1237467643]
47: [unknown location] g_cclosure_marshal_VOID__BOXED
48: [unknown location] [unknown:-1243142748]
49: [unknown location] g_closure_invoke
50: [unknown location] [unknown:-1243064628]
51: [unknown location] g_signal_emit_valist
52: [unknown location] g_signal_emit
53: [unknown location] gtk_widget_size_allocate
54: [unknown location] [unknown:-1235390902]
55: [unknown location] g_cclosure_marshal_VOID__BOXED
56: [unknown location] [unknown:-1243142748]
57: [unknown location] g_closure_invoke
58: [unknown location] [unknown:-1243064628]
59: [unknown location] g_signal_emit_valist
60: [unknown location] g_signal_emit
61: [unknown location] gtk_widget_size_allocate
62: [unknown location] [unknown:-1235382079]
63: [unknown location] g_cclosure_marshal_VOID__VOIDv
64: [unknown location] [unknown:-1243143081]
65: [unknown location] [unknown:-1243136818]
66: [unknown location] g_signal_emit_valist
67: [unknown location] g_signal_emit
68: [unknown location] gtk_container_check_resize
69: [unknown location] [unknown:-1237237152]
70: [unknown location] [unknown:-1242767208]
71: [unknown location] [unknown:-1245275056]
72: [unknown location] g_main_context_dispatch
73: [unknown location] [unknown:-1245260696]
74: [unknown location] g_main_loop_run
75: [unknown location] gtk_main
76: [unknown location] wxGUIEventLoop::DoRun()
77: [unknown location] wxEventLoopBase::Run()
78: [unknown location] wxDialog::ShowModal()
79: [unknown location] MapCanvas::changeTexture3d(selection_3d_t)
80: [unknown location] MapCanvas::onMouseDown(wxMouseEvent&)
81: [unknown location] wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
82: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
83: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
84: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
85: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
86: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
87: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
88: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
89: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
90: [unknown location] wxWindow::GTKProcessEvent(wxEvent&) const
91: [unknown location] [unknown:-1226441079]
92: [unknown location] [unknown:-1236681026]
93: [unknown location] g_closure_invoke
94: [unknown location] [unknown:-1243062231]
95: [unknown location] g_signal_emit_valist
96: [unknown location] g_signal_emit
97: [unknown location] [unknown:-1235449341]
98: [unknown location] gtk_propagate_event
99: [unknown location] gtk_main_do_event
100: [unknown location] [unknown:-1242504776]
101: [unknown location] g_main_context_dispatch
102: [unknown location] [unknown:-1245260696]
103: [unknown location] g_main_loop_run
104: [unknown location] gtk_main
105: [unknown location] wxGUIEventLoop::DoRun()
106: [unknown location] wxEventLoopBase::Run()
107: [unknown location] wxDialog::ShowModal()
108: [unknown location] MapCanvas::changeTexture3d(selection_3d_t)
109: [unknown location] MapCanvas::onMouseDown(wxMouseEvent&)
110: [unknown location] wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
111: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
112: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
113: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
114: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
115: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
116: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
117: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
118: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
119: [unknown location] wxWindow::GTKProcessEvent(wxEvent&) const
120: [unknown location] [unknown:-1226441079]
121: [unknown location] [unknown:-1236681026]
122: [unknown location] g_closure_invoke
123: [unknown location] [unknown:-1243062231]
124: [unknown location] g_signal_emit_valist
125: [unknown location] g_signal_emit
126: [unknown location] [unknown:-1235449341]
127: [unknown location] gtk_propagate_event
128: [unknown location] gtk_main_do_event
129: [unknown location] [unknown:-1242504776]
130: [unknown location] g_main_context_dispatch
131: [unknown location] [unknown:-1245260696]
132: [unknown location] g_main_loop_run
133: [unknown location] gtk_main
134: [unknown location] wxGUIEventLoop::DoRun()
135: [unknown location] wxEventLoopBase::Run()
136: [unknown location] wxAppConsoleBase::MainLoop()
137: [unknown location] wxAppConsoleBase::OnRun()
138: [unknown location] wxAppBase::OnRun()
139: [unknown location] wxEntry(int&, wchar_t**)
140: [unknown location] wxEntry(int&, char**)
141: [unknown location] main
142: [unknown location] __libc_start_main
143: [unknown location] _start

Last Log Messages:
08:38:40 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
08:39:28 PM: Opening archive /home/arshia/.config/zdoom/Doom2.wad
08:39:32 PM: Read game configuration "doom2" + "zdoom"
08:39:34 PM: Opening map TITLEMAP
08:39:34 PM: Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
08:39:38 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
08:39:43 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
08:39:45 PM: Creating backup /media/arshia/Windows & Ubuntu/Users/Chizari/Desktop/TFC Project/TFC.pk3.bak
08:40:10 PM: Read game configuration "doom2" + "zdoom"
08:40:10 PM: Opening map TITLEMAP
08:40:10 PM: Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors

**Comment by sirjuddington** [comment]
I think most of these have been fixed now (I recognise some of the stack traces, at least), so closing this
