### ISSUE TITLE
Timidity is.. Well

### ISSUE THREAD

**Issue by DevilHunter1337** [sirjuddington/SLADE#309]
Come to find out, you cannot control if Timidity plays or stops.. or even close with slade for that matter. I have no clue if its because I have a slightly modified Timidity (grabbed it from zdoom wiki) or what.

Anyhow, for starters... You cannot stop the song playing. 
You can keep clicking on the song, thus spawning a ton of Timidity processes. 
When you go to close slade, the processes never close.
And uhh.. that's pretty much it. 

Granted however, it does work sorta flawlessly cept the programs mentioned above. Not sure if it makes any diff, but I'm still on XP.

**Comment by Monsterovich** [comment]
>Anyhow, for starters... You cannot stop the song playing.
>You can keep clicking on the song, thus spawning a ton of Timidity processes. 

I have been surprised that wxProcess::Kill(pid) is not working on windows. This is a simple function which should kill any process with *pid*. Pfff.

**Comment by DevilHunter1337** [comment]
How would I know?? I don't have Windows 7 or 10 on this pc.

**Comment by DevilHunter1337** [comment]
It be nice if I could have a build with the fix to see if it works... I can't build from source because this requires a newer version of VC... unless there is another way to compile on XP

**Comment by sirjuddington** [comment]
Well there is the VC2005 solution/project which Gez uses, though I'm not sure how up to date it is, and also you would need VC2005

**Comment by DevilHunter1337** [comment]
Which one would it be? I have Visual C++ 2005 Express Edition.

**Comment by sirjuddington** [comment]
Hmm, not sure about that one, I haven't tried to build using that for a while so I'm not sure where to get that exe from (is there a project to build it in the solution?)

Either way, I just released [3.1.1 beta 1](https://github.com/sirjuddington/SLADE/releases/tag/3.1.1_b1), which should have this fix.

**Comment by DevilHunter1337** [comment]
I just downloaded and tested that Beta build.. Same issue

**Comment by Monsterovich** [comment]
>I just downloaded and tested that Beta build.. Same issue

Are you still on xp?

**Comment by DevilHunter1337** [comment]
Welp if so then I duno. I guess I should try to start saving up to get a new pc then. I know for a fact this pc is too weak and old to handle the newer windows..

**Comment by sirjuddington** [comment]
What are your specs? You'd be surprised how little windows 7 requires in terms of hardware (even 10 isn't much more)

**Comment by DevilHunter1337** [comment]
Sorry for not responding in some time. I have been busy with RL issues and such. I don't have my XP machine anymore, I'm now stuck to this Windows 8.1 Laptop. It's not that old but, should be enough for today's standards.

I guess I can try compiling Slade on this thing since I do have VS 2013 installed. However, I did try to compile zandronum, and failed. Might need VS 2005 for that. Anyhow, I will report back once I figure it out.

**Comment by DevilHunter1337** [comment]
OK so.. I run into this... 

 1>LINK : fatal error LNK1181: cannot open input file 'flac.lib'
     1>Done Building Project "C:\Doom Ports\SVNs\SLADE\SLADE.vcxproj" (Build target(s)) -- FAILED.

Build FAILED.

Time Elapsed 00:51:06.30

That's the only error. I followed the guide step by step so.. I have no clue what its missing...

**Comment by sirjuddington** [comment]
Closing - old issue, possibly fixed by now

Feel free to reopen the issue if needed
