### ISSUE TITLE
Error compiling in Void Linux, wxWidgets not found

### ISSUE THREAD

**Issue by Derpford** [sirjuddington/SLADE#316]
When compiling in Void Linux, I get the following error:

>-- Found ZLIB: /usr/local/lib/libz.a (found version "1.2.7")
>-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6")
>-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
>-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
>-- Found OpenGL: /usr/lib64/libGL.so
>CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>  Could NOT find wxWidgets (missing: wxWidgets_FOUND) (Required is at least
>  version "3.0")
>Call Stack (most recent call first):
>  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
>  /usr/share/cmake-3.2/Modules/FindwxWidgets.cmake:870 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>  src/CMakeLists.txt:5 (find_package)
>
>
>-- Configuring incomplete, errors occurred!
>See also "/home/derpford/slade-git/SLADE/dist/CMakeFiles/CMakeOutput.log".

wxWidgets is already installed. I've uninstalled wxGTK, and have tried exporting the location of wxWidgets to LD_LIBRARY_PATH (as per the earlier issue with wxWidgets), to no avail.

**Comment by Monsterovich** [comment]
What wxwidgets version do you have?

**Comment by Derpford** [comment]
xbps-query says I have 3.0.2_2 installed.

**Comment by Monsterovich** [comment]
>I've uninstalled wxGTK

>monsterovich@asus ~ $ wx-config --libs
>-L/usr/lib/i386-linux-gnu -pthread   -lwx_gtk2u_xrc-3.0 -lwx_gtk2u_html-3.0 -lwx_gtk2u_qa-3.0 >-lwx_gtk2u_adv-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0 

Install it again. :P

**Comment by Derpford** [comment]
That's funny, the install instructions say to /not/ install wxGTK.
However, that fixed it; now I get to go install all the other deps. Thanks!

**Comment by Derpford** [comment]
Further problem. Now I'm getting exactly the same error that started the other issue re: wxWidgets and wxGTK.

>[  0%] Building CXX object src/CMakeFiles/slade.dir/mus2mid/mus2mid.o
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:92:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/home/derpford/slade-git/SLADE/src/mus2mid/../Structs.h:741:41: error: conversion from 'const char [1]' to 'strin
>g {aka wxString}' is ambiguous
>  key_value_t(string key, string value = "")
>                                         ^
>/home/derpford/slade-git/SLADE/src/mus2mid/../Structs.h:741:41: note: candidates are:
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:30:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
>   wxString(wxChar ch, size_t nRepeat = 1)
>   ^
>/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from 'const char [1]' to 'wxCha
>r {aka wchar_t}'
>/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
>   wxString(int);
>   ^
>/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from 'const char [1]' to 'int'
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: error: conversion from 'const char [5]' to 'string {a
>ka wxString}' is ambiguous
> };
> ^
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: note: candidates are:
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:30:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
>   wxString(wxChar ch, size_t nRepeat = 1)
>   ^
>/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from 'const char [5]' to 'wxCha
>r {aka wchar_t}'
>/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
>   wxString(int);
>   ^
>/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from 'const char [5]' to 'int'
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: error: conversion from 'const char [6]' to 'string {a
>ka wxString}' is ambiguous
> };
> ^
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: note: candidates are:
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:30:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
>   wxString(wxChar ch, size_t nRepeat = 1)
>   ^
>/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from 'const char [6]' to 'wxCha
>r {aka wchar_t}'
>/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
>   wxString(int);
>   ^
>/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from 'const char [6]' to 'int'
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: error: conversion from 'const char [7]' to 'string {a
>ka wxString}' is ambiguous
> };
> ^
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: note: candidates are:
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:30:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
>   wxString(wxChar ch, size_t nRepeat = 1)
>   ^
>/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from 'const char [7]' to 'wxChar {aka wchar_t}'
>/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
>   wxString(int);
>   ^
>/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from 'const char [7]' to 'int'
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: error: conversion from 'const char [5]' to 'string {aka wxString}' is ambiguous
> };
> ^
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: note: candidates are:
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:30:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
>   wxString(wxChar ch, size_t nRepeat = 1)
>   ^
>/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from 'const char [5]' to 'wxChar {aka wchar_t}'
>/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
>   wxString(int);
>   ^
>/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from 'const char [5]' to 'int'
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: error: conversion from 'const char [8]' to 'string {aka wxString}' is ambiguous
> };
> ^
>/home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:131:1: note: candidates are:
>In file included from /home/derpford/slade-git/SLADE/src/mus2mid/../Main.h:30:0,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.h:32,
>                 from /home/derpford/slade-git/SLADE/src/mus2mid/mus2mid.cpp:32:
>/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
>   wxString(wxChar ch, size_t nRepeat = 1)
>   ^
>/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from 'const char [8]' to 'wxChar {aka wchar_t}'
>/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
>   wxString(int);
>   ^
>/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from 'const char [8]' to 'int'
>src/CMakeFiles/slade.dir/build.make:77: recipe for target 'src/CMakeFiles/slade.dir/mus2mid/mus2mid.o' failed
>make[2]: *** [src/CMakeFiles/slade.dir/mus2mid/mus2mid.o] Error 1
>CMakeFiles/Makefile2:75: recipe for target 'src/CMakeFiles/slade.dir/all' failed
>make[1]: *** [src/CMakeFiles/slade.dir/all] Error 2
>Makefile:75: recipe for target 'all' failed
>make: *** [all] Error 2
>

**Comment by Derpford** [comment]
Note that wxWidgets is version 3.0.2, but wxGTK is version 2.8. I can't find a version of wxGTK that's greater than 3.

**Comment by Monsterovich** [comment]
>/usr/include/wx-2.8 

:3

**Comment by Derpford** [comment]
Well, then I don't know what's wrong. Maybe there's a wx library that isn't
downloading along with the rest of it?

**Comment by Monsterovich** [comment]
>Well, then I don't know what's wrong. Maybe there's a wx library that isn't downloading along with the rest of it?

You are using wx 2.8 instead of 3.0.

**Comment by Derpford** [comment]
Oh. Mistook your previous message to mean that wxGTK2.8 was OK. Where can I
find the source for 3.0?

**Comment by Monsterovich** [comment]
>Where can I find the source for 3.0?

http://wxwidgets.org/

and wiki says:
>When ./configure-ing wxWidgets, you will need to specify --enable-mediactrl and --enable-webview. Instructions for compiling wxWidgets can be found in “docs/gtk/install.txt” in the wxWidgets tarball.

**Comment by Derpford** [comment]
Boy, does this feel like a Laurel and Hardy routine.

>checking for GST... configure: WARNING: GStreamer 0.10 not available, falling back to 0.8
>checking for GST... configure: WARNING: GStreamer 0.8/0.10 not available.
>configure: error: GStreamer not available

I have version 0.10 installed, both GStreamer and GStreamer-devel.

**Comment by Derpford** [comment]
Installing 32-bit versions of the GStreamer libraries does not help.

**Comment by Monsterovich** [comment]
automake sucks!!111

**Comment by Derpford** [comment]
Any ideas? Maybe I should fiddle with my $PATH?

**Comment by sirjuddington** [comment]
I'm assuming you already checked, but does Void Linux have wxWidgets 3.0 on its package manager at all? It's been out for quite a while now so I see no reason why it shouldn't be.

**Comment by Derpford** [comment]
>I'm assuming you already checked, but does Void Linux have wxWidgets 3.0 on its package manager at all? It's been out for quite a while now so I see no reason why it shouldn't be.
It's in there. I've got it installed. And now I'm trying compiling with the flags enabled, as Void Linux's package manager uses precompiled binaries, and there's a good chance they compiled this binary without the extra options.

Especially since it apparently can't find gstreamer.

**Comment by sirjuddington** [comment]
Compiling wx? What happens when you try to compile SLADE now? (also try starting from scratch perhaps, delete the slade directory and clone it again etc.)

**Comment by Derpford** [comment]
I have wxWidgets 3.0.2 installed currently.

1. I clone the repo using git, into a directory called "slade-git".
2. I cd to SLADE/dist.
3. I run `cmake ..`
4. I get this error:

>CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>  Could NOT find wxWidgets (missing: wxWidgets_FOUND) (Required is at least
>  version "3.0")
>Call Stack (most recent call first):
>  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
>  /usr/share/cmake-3.2/Modules/FindwxWidgets.cmake:870 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>  src/CMakeLists.txt:5 (find_package)
>
>
>-- Configuring incomplete, errors occurred!
>See also "/home/derpford/slade-git/SLADE/dist/CMakeFiles/CMakeOutput.log".

**Comment by sirjuddington** [comment]
Well either the package manager has installed wx to somewhere non standard, or the CMake FindwxWidgets module is wrong somehow. Try taking a look at the CMake module (/usr/share/cmake-3.2/Modules/FindwxWidgets.cmake) and see what it's looking for.

**Comment by Derpford** [comment]
It starts by looking for wx-config.
Problem is, wx-config is called wx-config-3.0 on my system for no apparent reason.

**Comment by Derpford** [comment]
Moving wx-config-3.0 to wx-config fixes the issue. Possible alternative route: Tell CMake to look for wx-config-3.0 through environment variables. I'm too tired to try this right now.
