### ISSUE TITLE
Crash upon changing text style preferences

### ISSUE THREAD

**Issue by Hexagonaldonut** [sirjuddington/SLADE#321]
I actually ran into two different crashes, one of which I neglected to grab the stack trace for (if I can duplicate it, I'll make sure to do that). For the one I DID grab the stack trace for, well, the title says it all. It appears to happen when changing to Dark style and clicking Apply OR OK.

The stack trace is as follows:

Version: 3.1.0.5
Current action: main_preferences
Stack Trace:
0: [unknown location] [unknown:0]
1: (c:\dev\slade3\src\maprenderer2d.cpp:2749) MapRenderer2D::updateVerticesVBO
2: (c:\dev\slade3\src\maprenderer2d.cpp:2952) MapRenderer2D::forceUpdate
3: (c:\dev\slade3\src\mapcanvas.cpp:2289) MapCanvas::forceRefreshRenderer
4: (c:\dev\slade3\src\mapeditorwindow.cpp:930) MapEditorWindow::forceRefresh
5: (c:\dev\slade3\src\dialogs\preferences\colourprefspanel.cpp:205) ColourPrefsPanel::applyPreferences
6: (c:\dev\slade3\src\dialogs\preferences\preferencesdialog.cpp:221) PreferencesDialog::applyPreferences
7: (c:\dev\slade3\src\dialogs\preferences\preferencesdialog.cpp:249) PreferencesDialog::onButtonClicked
8: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:612) wxAppConsoleBase::HandleEvent
9: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:623) wxAppConsoleBase::CallEventHandler
10: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1751) wxEvtHandler::SearchDynamicEventTable
11: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1585) wxEvtHandler::TryHereOnly
12: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1495) wxEvtHandler::ProcessEvent
13: (f:\programming\libs\wxwidgets-3.0.2\src\common\wincmn.cpp:3427) wxWindowBase::TryAfter
14: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1508) wxEvtHandler::ProcessEvent
15: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1647) wxEvtHandler::SafelyProcessEvent
16: (f:\programming\libs\wxwidgets-3.0.2\src\msw\button.cpp:369) wxButton::SendClickEvent
17: (f:\programming\libs\wxwidgets-3.0.2\src\msw\button.cpp:422) wxButton::MSWCommand
18: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:5353) wxWindow::HandleCommand
19: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3044) wxWindow::MSWHandleMessage
20: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3645) wxWindow::MSWWindowProc
21: (f:\programming\libs\wxwidgets-3.0.2\src\msw\toplevel.cpp:467) wxTopLevelWindowMSW::MSWWindowProc
22: (f:\programming\libs\wxwidgets-3.0.2\src\msw\dialog.cpp:436) wxDialog::MSWWindowProc
23: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2711) wxWndProc
24: [unknown location] GetWindowLongW
25: [unknown location] GetWindowLongW
26: [unknown location] ReleaseDC
27: [unknown location] WCSToMBEx
28: [unknown location] KiUserCallbackDispatcher
29: [unknown location] SendMessageW
30: [unknown location] ImageList_Draw
31: [unknown location] ImageList_Draw
32: [unknown location] ImageList_Draw
33: [unknown location] GetWindowLongW
34: [unknown location] GetWindowLongW
35: [unknown location] CallWindowProcW
36: [unknown location] CallWindowProcW
37: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2271) wxWindow::MSWDefWindowProc
38: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3651) wxWindow::MSWWindowProc
39: (f:\programming\libs\wxwidgets-3.0.2\src\msw\anybutton.cpp:662) wxAnyButton::MSWWindowProc
40: (f:\programming\libs\wxwidgets-3.0.2\src\msw\button.cpp:441) wxButton::MSWWindowProc
41: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2711) wxWndProc
42: [unknown location] GetWindowLongW
43: [unknown location] GetWindowLongW
44: [unknown location] GetMessageW
45: [unknown location] DispatchMessageW
46: [unknown location] IsWindowEnabled
47: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2612) wxWindow::MSWSafeIsDialogMessage
48: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2494) wxWindow::MSWProcessMessage
49: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:148) wxGUIEventLoop::PreProcessMessage
50: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:166) wxGUIEventLoop::ProcessMessage
51: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:232) wxGUIEventLoop::Dispatch
52: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:206) wxEventLoopManual::DoRun
53: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:78) wxEventLoopBase::Run
54: (f:\programming\libs\wxwidgets-3.0.2\src\msw\dialog.cpp:214) wxDialog::ShowModal
55: (c:\dev\slade3\src\dialogs\preferences\preferencesdialog.cpp:273) PreferencesDialog::openPreferences
56: (c:\dev\slade3\src\mainwindow.cpp:816) MainWindow::handleAction
57: (c:\dev\slade3\src\mainapp.cpp:1111) MainApp::doAction
58: (c:\dev\slade3\src\mainapp.cpp:1183) MainApp::onMenu
59: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:612) wxAppConsoleBase::HandleEvent
60: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:623) wxAppConsoleBase::CallEventHandler
61: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1751) wxEvtHandler::SearchDynamicEventTable
62: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1585) wxEvtHandler::TryHereOnly
63: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1495) wxEvtHandler::ProcessEvent
64: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1416) wxEvtHandler::DoTryApp
65: (f:\programming\libs\wxwidgets-3.0.2\src\common\wincmn.cpp:3433) wxWindowBase::TryAfter
66: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1508) wxEvtHandler::ProcessEvent
67: (f:\programming\libs\wxwidgets-3.0.2\src\common\wincmn.cpp:3427) wxWindowBase::TryAfter
68: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1508) wxEvtHandler::ProcessEvent
69: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1647) wxEvtHandler::SafelyProcessEvent
70: (f:\programming\libs\wxwidgets-3.0.2\src\common\menucmn.cpp:666) wxMenuBase::SendEvent
71: (f:\programming\libs\wxwidgets-3.0.2\src\common\framecmn.cpp:298) wxFrameBase::ProcessCommand
72: (f:\programming\libs\wxwidgets-3.0.2\src\msw\frame.cpp:826) wxFrame::HandleCommand
73: (f:\programming\libs\wxwidgets-3.0.2\src\msw\frame.cpp:889) wxFrame::MSWWindowProc
74: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2711) wxWndProc
75: [unknown location] GetWindowLongW
76: [unknown location] GetWindowLongW
77: [unknown location] GetMessageW
78: [unknown location] DispatchMessageW
79: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:170) wxGUIEventLoop::ProcessMessage
80: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:232) wxGUIEventLoop::Dispatch
81: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:206) wxEventLoopManual::DoRun
82: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:78) wxEventLoopBase::Run
83: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:334) wxAppConsoleBase::MainLoop
84: (f:\programming\libs\wxwidgets-3.0.2\src\common\init.cpp:495) wxEntryReal
85: (f:\programming\libs\wxwidgets-3.0.2\src\msw\main.cpp:188) wxEntry
86: (f:\programming\libs\wxwidgets-3.0.2\src\msw\main.cpp:415) wxEntry
87: (c:\dev\slade3\src\mainapp.cpp:306) WinMain
88: (f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c:618) __tmainCRTStartup
89: [unknown location] BaseThreadInitThunk
90: [unknown location] RtlInitializeExceptionChain
91: [unknown location] RtlInitializeExceptionChain

(I tried attaching it, but GitHub keeps throwing errors. :)

**Comment by sirjuddington** [comment]
Hmm, this is one I've seen reported before but I've never been able to get it to happen myself...

Did you have the map editor open at the time, or had it been opened at all before then?

**Comment by sirjuddington** [comment]
Closing - old issue, possibly fixed

Feel free to reopen the issue if needed
