### ISSUE TITLE
Backgrounding a modified archive should maybe prompt to save

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#330]
With "close an archive when its tab is closed" turned _off_, closing an archive tab doesn't actually close the archive, so you don't get a prompt to save changes, which can be mildly alarming if you've forgotten about that pref.

Also, I tried this with a new archive, then did "close all" to verify that I do get a save prompt.  I said yes to saving, then cancelled the OS save dialog...  and SLADE closed the archive anyway.  I think the native behavior is supposed to be that cancelling the save dialog cancels the close, not the save?  I just tried with KWrite and that's what happened, anyway.

(Also also, I'm kinda thinking the "close an archive yadda" pref was a mistake — I think the behavior we _actually_ wanted was that closing a _nested_ archive while its parent is still open doesn't actually close it.  At least, that's the behavior _I_ wanted, since I'll sometimes open a child archive just to poke around in it, then close it when I'm done, and suddenly its textures all vanish from the map editor.)

**Comment by sirjuddington** [comment]
That option was added pretty early on, initially the default behaviour was for archives to stay open until closed via the archive manager (not the tab), but most people found it confusing so I added that option and set it on by default. It doesn't really have anything to do with nested archives.

The second point should now be fixed (a3343d7)
