### ISSUE TITLE
Crash when opening a map in the editor

### ISSUE THREAD

**Issue by zephz** [sirjuddington/SLADE#332]
Slade crashes whenever i double-click to open any map in the editor. 

Here's the stack trace:

Version: 3.1.1 Beta 1
No current action

Stack Trace:
0: [unknown location] [unknown:0]
1: (c:\dev\slade3\src\maprenderer2d.cpp:2749) MapRenderer2D::updateVerticesVBO
2: (c:\dev\slade3\src\maprenderer2d.cpp:2952) MapRenderer2D::forceUpdate
3: (c:\dev\slade3\src\mapcanvas.cpp:2332) MapCanvas::forceRefreshRenderer
4: (c:\dev\slade3\src\mapeditorwindow.cpp:930) MapEditorWindow::forceRefresh
5: (c:\dev\slade3\src\maptexturemanager.cpp:497) MapTextureManager::refreshResources
6: (c:\dev\slade3\src\maptexturemanager.cpp:583) MapTextureManager::setArchive
7: (c:\dev\slade3\src\mapeditorwindow.cpp:537) MapEditorWindow::openMap
8: (c:\dev\slade3\src\archivepanel.cpp:3449) ArchivePanel::onEntryListActivated
9: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:612) wxAppConsoleBase::HandleEvent
10: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:623) wxAppConsoleBase::CallEventHandler
11: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1751) wxEvtHandler::SearchDynamicEventTable
12: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1585) wxEvtHandler::TryHereOnly
13: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1495) wxEvtHandler::ProcessEvent
14: (f:\programming\libs\wxwidgets-3.0.2\src\common\event.cpp:1647) wxEvtHandler::SafelyProcessEvent
15: (f:\programming\libs\wxwidgets-3.0.2\src\msw\listctrl.cpp:2568) wxListCtrl::MSWOnNotify
16: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3857) wxWindow::HandleNotify
17: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3048) wxWindow::MSWHandleMessage
18: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3645) wxWindow::MSWWindowProc
19: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2711) wxWndProc
20: [unknown location] GetDC
21: [unknown location] GetDC
22: [unknown location] DefWindowProcW
23: [unknown location] DefWindowProcW
24: [unknown location] KiUserCallbackDispatcher
25: [unknown location] SendMessageW
26: [unknown location] Ordinal414
27: [unknown location] Ordinal384
28: [unknown location] Ordinal384
29: [unknown location] Ordinal384
30: [unknown location] GetDC
31: [unknown location] GetDC
32: [unknown location] IsWindowUnicode
33: [unknown location] CallWindowProcW
34: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2271) wxWindow::MSWDefWindowProc
35: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:3651) wxWindow::MSWWindowProc
36: (f:\programming\libs\wxwidgets-3.0.2\src\msw\listctrl.cpp:3060) wxListCtrl::MSWWindowProc
37: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2711) wxWndProc
38: [unknown location] GetDC
39: [unknown location] GetDC
40: [unknown location] GetWindowLongW
41: [unknown location] DispatchMessageW
42: [unknown location] IsDialogMessageW
43: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2612) wxWindow::MSWSafeIsDialogMessage
44: (f:\programming\libs\wxwidgets-3.0.2\src\msw\window.cpp:2494) wxWindow::MSWProcessMessage
45: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:148) wxGUIEventLoop::PreProcessMessage
46: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:166) wxGUIEventLoop::ProcessMessage
47: (f:\programming\libs\wxwidgets-3.0.2\src\msw\evtloop.cpp:232) wxGUIEventLoop::Dispatch
48: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:206) wxEventLoopManual::DoRun
49: (f:\programming\libs\wxwidgets-3.0.2\src\common\evtloopcmn.cpp:78) wxEventLoopBase::Run
50: (f:\programming\libs\wxwidgets-3.0.2\src\common\appbase.cpp:334) wxAppConsoleBase::MainLoop
51: (f:\programming\libs\wxwidgets-3.0.2\src\common\init.cpp:495) wxEntryReal
52: (f:\programming\libs\wxwidgets-3.0.2\src\msw\main.cpp:188) wxEntry
53: (f:\programming\libs\wxwidgets-3.0.2\src\msw\main.cpp:415) wxEntry
54: (c:\dev\slade3\src\mainapp.cpp:309) WinMain
55: (f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c:618) __tmainCRTStartup
56: [unknown location] RegisterWaitForInputIdle

**Comment by Monsterovich** [comment]
>Slade crashes whenever i double-click to open any map in the editor. 

- What map did you open?
- BTW, you may try to disable VBO and report back.

**Comment by Gaerzi** [comment]
Go to preferences->General->OpenGL and uncheck "Use Vertex Buffer Object if supported". Then apply, close preferences, and try opening a map again.

**Comment by sirjuddington** [comment]
Closing - old issue, possibly fixed

Feel free to reopen the issue if needed
