### ISSUE TITLE
Opening a .wad with slade from file association opens a new instance of Slade

### ISSUE THREAD

**Issue by jmickle66666666** [sirjuddington/SLADE#333]
Windows 8. Tested on 3.1.0.4, 3.1.0.5, 3.1.1 beta

Steps to reproduce:
* Associate .wad files with Slade
* Double click any .wad file to open it
* Double click another .wad file

Actual result:
* Separate instances of Slade run for each opened .wad file

Expected result:
* The second .wad file should open inside of the first instance of slade. Having more than one instance of Slade open can cause small issues with configurations not being saved correctly, among other things

**Comment by Manuel-K** [comment]
Although I understand the reason of this change, I'm not that happy about it because it prevents me from viewing two maps at the same time. There doesn't seem to be a way to open two map editors in a single SLADE instance… 

Am i missing something?

**Comment by Gaerzi** [comment]
Feel free to create a new issue for having the option not to have  SLADE running in single-instance mode.

Opening two map editors in the same instance would be more complicated to implement.
