### ISSUE TITLE
ACC errors written to stderr are not displayed

### ISSUE THREAD

**Issue by DavidPH** [sirjuddington/SLADE#335]
It is possible to use gdcc-acc (an alternative ACS compiler) with Slade as-is. However, if there is a compile error, the details are written to stderr rather than stdout, which causes SLADE to not capture them.

**Comment by Kyle873** [comment]
+1 for making gdcc-acc play nice with Slade. We would love to use gdcc-acc for DoomRL Arsenal but the error output as it is is a no go.
