### ISSUE TITLE
Compilation Error [AudioEntryPanel.h]

### ISSUE THREAD

**Issue by DavidKeaton** [sirjuddington/SLADE#337]
Compilation from terminal (latest grab of SLADE) using `cmake .. && make` fails when reaching `AudioEntryPanel.h`. 

The fix I added let it continue merrily with compilation. (produced with `git diff > slade.patch`)

```
diff --git a/src/AudioEntryPanel.h b/src/AudioEntryPanel.h
index ed3dba3..5308079 100644
--- a/src/AudioEntryPanel.h
+++ b/src/AudioEntryPanel.h
@@ -1,9 +1,12 @@

 #ifndef __AUDIO_ENTRY_PANEL_H__
 #define __AUDIO_ENTRY_PANEL_H__

+#undef wxUSE_MEDIACTRL
+#define wxUSE_MEDIACTRL 1
+
 #include "EntryPanel.h"
 #include <wx/mediactrl.h>

 #undef Status
 #include <SFML/Audio.hpp>
```

**Comment by Gaerzi** [comment]
This doesn't look like the right way to fix this compilation issue...

**Comment by DavidKeaton** [comment]
How would one go about it? The define I added to make it compile, the undef I placed to remove the redefinition warnings (in theory). Care to explain? :-)

**Comment by Gaerzi** [comment]
The wxUSE macro shouldn't be redefined in a program's code. Normally it's something you set up in your wxWidgets setup.h before building the library.

See [this thread](https://forums.wxwidgets.org/viewtopic.php?t=2487) on the issue.

**Comment by sirjuddington** [comment]
Did you compile wxWidgets yourself, or do you have it installed from a package repository? If you compiled it yourself you need to specify --enable-mediactrl when configuring wx.

**Comment by DavidKeaton** [comment]
Gentoo's `emerge` all `USE` flags for wx.

**Comment by sirjuddington** [comment]
Closing - old issue

Feel free to reopen the issue if needed
