### ISSUE TITLE
Question: Relevance of IDE Projects

### ISSUE THREAD

**Issue by alexey-lysiuk** [sirjuddington/SLADE#341]
There are a few IDE projects/solutions in the repository. Seems like they are not updated for a while, different set of source files are missing from different project files.
Are these projects still relevant? Should these files be updated when making a pull request with added files?

**Comment by sirjuddington** [comment]
The windows VS projects have gotten a bit messy over time I think :P

I use the following:
SLADE-VS2012.sln
SLADE.vcxproj
SLADE.vcxproj.filters

And Gez uses:
Slade3.sln
Slade3.vcproj

I should probably clean up all the different IDE related stuff at some point. Ideally I'd just use cmake for everything but I'm not sure how well that works with VS (I assume it'd also be more work to keep up to date when new source files are added)

**Comment by eevee** [comment]
FWIW, I've added files before, and all I had to do was run `cmake` again to regenerate the makefile.

**Comment by sirjuddington** [comment]
Yeah that's because the cmake file has a wildcard search for sources, so anything in src/ will be included. Problem is the VS project has the sources organised into virtual folders (VS calls them 'filters' for whatever reason), which I'd need to either rearrange into real folders, or write them into the cmake file directly.

**Comment by eevee** [comment]
A couple real folders might be nice — `src` is kind of a mess  :)

**Comment by sirjuddington** [comment]
I'd like to organise all the sources into folders eventually (already kind of started with the 'Dialogs' stuff at least), though it would be a fair amount of work. Perhaps after 3.1.1 final is released...

**Comment by Gaerzi** [comment]
No need to keep this open anymore I think.
