### ISSUE TITLE
Saving a directory still sometimes deletes new files

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#343]
I create a new file manually, I see the "modified files" check run several times in SLADE, but nothing happens.  Later I mash Ctrl-S in SLADE out of habit and the new file is silently deleted.

It's probably a pain since the code was all designed to work with archives, which are read and written as single units...  but we should really really not ever delete files from a directory unless they were explicitly deleted within SLADE itself.

**Comment by eevee** [comment]
Somewhat related: if I _do_ successfully "load selected changes" in an otherwise unchanged directory, SLADE now considers it modified.  I've never seen this cause problems, but it makes me vaguely uneasy.

**Comment by eevee** [comment]
Also it's super annoying to get the prompt at all when I haven't changed the file in SLADE  :)

**Comment by sirjuddington** [comment]
Hmm, I can't get this to happen, at least on Windows. If I add a new file SLADE will pick it up and ask to apply the changes etc.

**Comment by eevee** [comment]
Aha, figured out how to reproduce.

1. Pick a directory to work with.  Create or find a dummy file somewhere, _outside_ that directory.
2. Open the directory in SLADE.
3. Manually move the dummy file into the directory.
4. Switch back to SLADE.  It'll check for changes and not find any.  (Seems to be because the file's mtime is older than when SLADE opened/checked the directory, but from a read of the code I don't understand why that would be?  The mtime is never examined for a newly-added file.)
5. Open the dummy file in an external text editor and make changes to it.
6. Switch back to SLADE.  It'll check for changes _again_ and _still_ not find any.  (May depend on how your editor saves files.  I used vim, and the file's mtime was definitely updated.)
7. At this point, if you save the archive in SLADE, the dummy file will be silently deleted.

Clearly something funny is going on here with mtimes, but SLADE should definitely never ever be deleting files it doesn't know about.

**Comment by eevee** [comment]
Working on this now...

**Comment by eevee** [comment]
Oh, I'm totally wrong.  It's actually `ignore_dir_archive_changes` — it gets set to true the first time the "update archive?" dialog shows, but then never gets unset until you save.

**Comment by eevee** [comment]
Well I've almost fixed this, except that wxwidgets thinks the app is being deactivated (on GTK, anyway) anytime it shows a standard modal dialog.

**Comment by eevee** [comment]
The [ticket I filed on wx](http://trac.wxwidgets.org/ticket/17260#ticket) has a fix and is now marked closed, though I haven't tried it out (not eager to build wx) and I have no idea when there might be a 3.0.3.

An alternative solution would be to track which changes are _not_ applied, and not re-propose those again.  So if you hit cancel, you're guaranteed not to get another dialog until you change a file again, regardless of how many times the check actually runs.  I think that's a good idea anyway; I just haven't done it yet  :)

**Comment by sirjuddington** [comment]
I wouldn't count on wx3.0.3 coming any time soon, knowing their general release schedule, though 3.0.2 is more than a year old now, so who knows. I get the feeling the next one will be 3.1.0 instead of 3.0.3, which will then take another few years to show up on package repositories :P

**Comment by sirjuddington** [comment]
Closing - not much else can be done about this one

Feel free to reopen the issue if needed
