### ISSUE TITLE
SLADE 3.1.0.5 shows up in the task manager, but it doesn't open.

### ISSUE THREAD

**Issue by ClevelandRock** [sirjuddington/SLADE#345]
SLADE 3.1.0.5 shows up in the task manager, but it doesn't open. I don't know what caused it, because I just started having this problem. I've tried reinstalling it and restarting my computer. Nothing seems to help.

**Comment by ClevelandRock** [comment]
I searched my hard drive for "slade," found the location of "slade3.cfg," and removed it. SLADE now works perfectly. Here is a copy of the file I removed (renamed to .txt).
[slade3.cfg.txt](https://github.com/sirjuddington/SLADE/files/36268/slade3.cfg.txt)

**Comment by sirjuddington** [comment]
Weird, the config file is just cut off for some reason, did you have a crash on exit before this started happening?

**Comment by ClevelandRock** [comment]
I don't recall having any issues with it before this.

**Comment by sirjuddington** [comment]
Ok, well it is resolved so I'm closing this issue, and have opened another (#346) to implement more config checks.
