### ISSUE TITLE
Better error checking when reading configuration

### ISSUE THREAD

**Issue by sirjuddington** [sirjuddington/SLADE#346]
Too many issues occur relating to a corrupted/invalid slade config file - need to check for problems and reset it (or ignore the problem section) if any are found.

Example broken config:
[slade3.cfg.txt](https://github.com/sirjuddington/SLADE/files/36268/slade3.cfg.txt)

**Comment by eevee** [comment]
Related: I had problems with keybinds getting corrupted between early 3.x releases; SLADE managed to launch, but none of the keys worked and everything showed in menus as ??.  Don't know why it happened, but maybe a completely invalid keybind should be ignored and replaced by the default.

**Comment by sirjuddington** [comment]
@eevee no idea how that would have happened, would probably have to see the config file that caused it to determine what might have caused it, if it is even still relevant.

**Comment by eevee** [comment]
I have no idea either, and I don't think I still have a copy of the garbled config.  As I recall it looked fine overall, but the keybinds were all completely bogus non-ASCII characters.
