### ISSUE TITLE
Double clicking in Lines Mode causes SLADE to crash

### ISSUE THREAD

**Issue by Eggbertx** [sirjuddington/SLADE#349]
While editing a map, if I double click in any area while in Lines Mode, SLADE crashes with this error. If it helps, I'm running Linux.
> Version: 3.1.0.5
> No current action
> 
> Stack Trace:
> 0: [unknown location] [unknown:-2084383764]
> 1: [unknown location] [unknown:-2137631104]
> 2: [unknown location] LinePropsPanel::openObjects(std::vector<MapObject*, std::allocator<MapObject*> >&)
> 3: [unknown location] MapCanvas::editObjectProperties(std::vector<MapObject*, std::allocator<MapObject*> >&)
> 4: [unknown location] MapCanvas::onMouseDown(wxMouseEvent&)
> 5: [unknown location] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
> 6: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
> 7: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
> 8: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
> 9: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
> 10: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
> 11: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
> 12: [unknown location] [unknown:-2076176542]
> 13: [unknown location] [unknown:-2118555377]
> 14: [unknown location] g_closure_invoke
> 15: [unknown location] [unknown:-2142977951]
> 16: [unknown location] g_signal_emit_valist
> 17: [unknown location] g_signal_emit
> 18: [unknown location] [unknown:-2117411924]
> 19: [unknown location] gtk_propagate_event
> 20: [unknown location] gtk_main_do_event
> 21: [unknown location] [unknown:-2140310836]
> 22: [unknown location] g_main_context_dispatch
> 23: [unknown location] [unknown:2145533984]
> 24: [unknown location] g_main_loop_run
> 25: [unknown location] gtk_main
> 26: [unknown location] wxGUIEventLoop::DoRun()
> 27: [unknown location] wxEventLoopBase::Run()
> 28: [unknown location] wxAppConsoleBase::MainLoop()
> 29: [unknown location] wxEntry(int&, wchar_t**)
> 30: [unknown location] main
> 31: [unknown location] __libc_start_main
> 32: [unknown location] _start

**Comment by Monsterovich** [comment]
>Version: 3.1.0.5
Update your version.

**Comment by sirjuddington** [comment]
3.1.0.5 is the current non-beta version.

But yeah, if you compiled it yourself, try switching to the '3.1.1' branch, compiling that and see if it still happens there.
