### ISSUE TITLE
Draw pixel-by-pixel in graphics

### ISSUE THREAD

**Issue by ZwipZwapZapony** [sirjuddington/SLADE#350]
Would it be possible... well, of course it would be possible, but would it be feasible and practical to make the graphic viewer have the ability to draw on a pixel-by-pixel basis, for example to fix minor issues in a sprite quickly (without having to export stuff, use an image editor, and then re-import it)?

Of course, all I'm asking for is a pixel-by-pixel basis. No fancy line tools or fill buckets, just a drawing pencil, MS Paint style. And it's of course okay if it only works for paletted lumps.

And obviously, as this is only a minor feature request, I'm okay with it if you won't add it.

**Comment by Gaerzi** [comment]
Well, it is on the long-term todo list:
```--- Gfx Editor ---
- Basic pixel-drawing tools
```

**Comment by ZwipZwapZapony** [comment]
...Oh. I... well... I just checked through all open issues, and it wasn't in any of those. Good to know it's (sort of) planned.

**Comment by Gaerzi** [comment]
Yeah, that file predates the move to GitHub, that's why it's a bit obscure compared to the issue tracker. :)

**Comment by sirjuddington** [comment]
It's also on the [Roadmap](https://github.com/sirjuddington/SLADE/wiki/Roadmap) for 3.1.3, which is a ways off but it's something I might end up doing earlier than that, depending on my motivation to get the other planned stuff done :P

**Comment by ZwipZwapZapony** [comment]
Sounds better than on a simple "to-do" list, even though 3.1.3 is far into the future. I hope everything goes as (or better than) planned.
Thanks for wanting to do this some time in the future, and also thanks for Slade in general. It's a (really) nice Wad editor. (But don't make draw tools sooner just because I said I like Slade.)

**Comment by Gaerzi** [comment]
Alright, guess what #706 was about?
