### ISSUE TITLE
Quality control

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#354]
Since https://github.com/sirjuddington/SLADE/commit/bb4f28e9ff9c040406b88c578892bcbd3867809b

- Compile errors https://github.com/sirjuddington/SLADE/pull/353
- Timidity process stop function doesn't work anymore at all!
- Every entry type is OKT module 
![wtf](https://cloud.githubusercontent.com/assets/3750982/11506593/daccf2ba-9858-11e5-9d61-d7da5f530ba2.png)

**Comment by Gaerzi** [comment]
Don't worry about the OKT stuff, that's just because there's some changes I haven't committed yet. You can always comment out its declaration from types_audio.txt in the meantime.

TiMidity was correctly stopped in my tests.

**Comment by Monsterovich** [comment]
>TiMidity was correctly stopped in my tests.
What OS do you use?

**Comment by Gaerzi** [comment]
Windows 7.

**Comment by Monsterovich** [comment]
Everything is fixed.
