### ISSUE TITLE
Question: 'Unused variable' compiler warnings

### ISSUE THREAD

**Issue by alexey-lysiuk** [sirjuddington/SLADE#364]
While building with Clang using default settings there are lots of `unused variable '...'` and `field '...' is not used` warnings reported.
Compilation log is polluted with this junk and it's quite easy to miss an important/useful warning.
Is it worth fixing all them? Or is it better to just disable them via compiler options?

**Comment by Monsterovich** [comment]
I only get 2-3 warnings. I'm using clang.

**Comment by alexey-lysiuk** [comment]
I see, looks like Apple changed default warning flags.
Also, I'm generating Xcode project to build SLADE. I will check using a makefile.
