### ISSUE TITLE
Other audio crackles while SLADE is open under PulseAudio

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#373]
1. Have something already playing audio.  Browser video and ZDoom have both been affected.
2. Launch SLADE.
3. Open an archive.  (This creates an `ArchivePanel`, which optimistically creates an `AudioEntryPanel`, which I assume is the culprit.)

The existing audio crackles until SLADE is closed.  In the worst cases, I've had the existing audio echo over itself with a several-second delay.  Muting SLADE in the PulseAudio mixer doesn't help.

Starting SLADE _first_ helps _sometimes_ — at least, I don't recall noticing any crackling when launching ZDoom from within SLADE.

Someone else in #zdoom who's also using Arch + PulseAudio also had this problem.

I'm not sure if this is SLADE's fault or SFML's fault or Pulse's fault, but it's kind of annoying so I'm ticketing it in the hopes that someone has some ideas.  :)

**Comment by eevee** [comment]
Confirming that commenting out `audio_area = new AudioEntryPanel(this);` in `ArchivePanel.cpp` seems to eliminate the crackle.  (Of course, clicking on audio would then segfault.)

Still get a crackle if I don't create a new `wxMediaCtrl`, so it's not gstreamer.

Some relevant stderr noise:

```
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
```

```
fluidsynth: error: Unable to open file "/usr/share/sounds/sf2/FluidR3_GS.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/FluidR3_GS.sf2"
fluidsynth: error: Unable to open file "/usr/share/sounds/sf2/FluidR3_GM.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/FluidR3_GM.sf2"
```

**Comment by eevee** [comment]
Hm, starting the JACK server seems to fix this.

**Comment by ebonyclock** [comment]
So who's to blame? PulseAudio or Slade? (my sound is messed up when using slade and PulseAudio equalizer at once)

**Comment by PkmX** [comment]
I have the same problem on Arch + PulseAudio v9.0.

I also found an issue that may be related: the SLADE source (named `ALSA plug-in [slade]` in `pavucontrol`) drops and reconnects constantly when under high CPU load (darktable was using all cores for image processing, then I re-confirmed with `stress --cpu 8`). This causes lots of crackles as the stream reconnects and it can occur multiple times within a second.

**Comment by eGax** [comment]
It's definitely a PulseAudio issue that seems have been frequent over the years as a quick Google search reveals many similar issues.

  https://www.google.com/search?safe=off&client=ms-android-americamovil-us&q=Pulseaudio+crackling+under+heavy+cpu+load&spell=1&sa=X&ved=0ahUKEwjer8-Gy9PQAhWX3oMKHZU3BK4QvwUIFygA&biw=320&bih=452&dpr=1.5

In the past maybe four years ago had the similar issue on Arch Linux,  but knock on wood not at all under Manjaro Linux. Although I also don't try to use Slade during darktable edits or high Cpu load times in general.

**Comment by ebonyclock** [comment]
Yes, now I also see that it's some problem with PulseAudio, I hear crackling with other software e.g. zdoom or even chrome in some circumstances.

**Comment by falsechicken** [comment]
This is still an issue with PulseAudio 10 under Ubuntu 17.04. Just to keep the issue up to date.

**Comment by OrdinaryMagician** [comment]
Pulseaudio is just problematic in general. I'd suggest [this fix](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Glitches.2C_skips_or_crackling) from the Arch wiki, it worked for me.

**Comment by eevee** [comment]
Oh, right; I tried that some time ago and haven't heard any mystery crackles since.  No idea what SLADE in particular is doing to trigger it.  (PulseAudio's official position is that this is a problem with bad drivers, but that's not much consolation...)

**Comment by sirjuddington** [comment]
Ok I'm going to close this one then, I've added a [troubleshooting & faq](https://github.com/sirjuddington/SLADE/wiki/Troubleshooting-%26-FAQ) page to the wiki with a link to the fix

**Comment by mihahauke** [comment]
Just as a comment, I updated the system and slade and it doesn't crackle any more. (It seems that pulse audio eq + slade break sound in skype but well... I can live with that)
