### ISSUE TITLE
Don't clamp arg values in UDMF

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#380]
Storing a negative number or a number greater than 255 is physically impossible in Hexen, but actually fairly useful in UDMF:

* Various floor and ceiling movement specials may want to move a sector by 256 or more units.
* Sector tags and line/thing ids can be greater than 255.
* `FloorAndCeiling_LowerRaise` has a fourth (obscure) argument whose only valid nonzero value is 1998.

**Comment by sirjuddington** [comment]
Are negative arg values actually valid though, even in UDMF? I agree it should allow args > 255 if the map is UDMF format

**Comment by eevee** [comment]
They are!  The one example I've seen where it's useful is a polyobj swinging door that you can push open from both sides — to make it swing in both directions, one side has to use a negative byte angle.  Just tried it myself and it works beautifully.

**Comment by eevee** [comment]
Easy workaround: the prop grid doesn't restrict the range of arg values.
