### ISSUE TITLE
True support for missing UDMF properties

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#386]
Currently, a missing UDMF prop is treated as identical to a prop with its default value.  There are a few cases where this doesn't hold.
- Vertex-based slopes use the `floorz` and `ceilingz` properties of vertices.  If the property is _missing_, ZDoom uses the actual floor or ceiling height of the sector instead.  SLADE has no way to distinguish between an explicit height of 0 and the default value of "sector height".  You can hack around this by explicitly giving the vertex the sector's height, of course, but that might trigger sloping in another triangular sector that shares the same vertex.  This is the root of #334.
- Some boolean properties, like `checkswitchrange`, don't actually default to false — they default to whatever `MAPINFO` does.  If you have `checkswitchrange` turned on by default in `MAPINFO`, it's impossible to explicitly exclude only a single switch from the check, because setting the prop to false causes SLADE to not write it out at all.

Unfortunately this risks impacting everywhere that reads or writes UDMF properties.  It's _also_ very difficult to do in the UI, since wx's "undefined value" state is already being used for the case of editing multiple objects with differing values.  I have no idea what to do about it.

**Comment by sirjuddington** [comment]
I think for a future release (possibly 3.1.2, we'll see) I will replace the wx property grid with something custom, which should cover the UI issue. It'll also probably, rather than listing all the possible UDMF properties, just list what properties exist on the object, with an 'add properties' button. Obviously some standard properties would still always be visible.

**Comment by Gaerzi** [comment]
I have a problem with the property grid not displaying (and thus not allowing to set) unset properties.

![Example](http://i.imgur.com/gKnzAiB.png)

If you try to use the "Add Property" button to add an existing but not displayed special, it'll tell you it already exists so it won't add it. The Item Property panel suffers from the same issue.

**Comment by sirjuddington** [comment]
Ticking 'Show All' should show them. If it's unticked all properties that don't have 'show_always' set in the game config and don't have a non-default value set will be hidden.

**Comment by Gaerzi** [comment]
... I never noticed the "show all" box.


Okay, that works.

**Comment by sirjuddington** [comment]
Pretty sure this one is implemented now
