### ISSUE TITLE
Merge keybinds with actions, and expose more keybinds in menus

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#395]
There's a lot of overlap between keybinds and actions, both functionality-wise and code-wise.  I think they could be combined without too much hullabaloo.

My primary motivation here is that a bunch of map editing functionality isn't listed in menus or toolars anywhere, which makes it nearly undiscoverable.  (Great example: I didn't find out that you can copy/paste properties for _ages_.)

I took a crack at this a little while ago, and got about halfway there.  It cut a lot of duplicated code out of `MapCanvas` and `MapEditor`.  I also had the idea of giving each action a "context" — for example, "flip line" only exists in lines mode — and ignoring any action that doesn't fit the current context.  That cut out a lot of "what state are we in?" checks as well.

I'm ticketing this so you can tell me if you hate the idea and I can stop intermittently working on it  ;)

**Comment by sirjuddington** [comment]
I don't have any objections, as long as it doesn't break anything :p
