### ISSUE TITLE
C++11

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#396]
Honestly at this point the biggest reason I want C++11 is to end the deluge of people on Twitter who are loudly aghast when I say I can't use C++11.

edit: Oh I guess there's a 14 now, right?

**Comment by Gaerzi** [comment]
That doesn't seem like a valid reason as far as I'm concerned. :p

**Comment by eevee** [comment]
Well also there are iterators and initializer lists and variadic templates and hashmaps, all of which I've wanted to use at one point or another.

**Comment by Gaerzi** [comment]
In any case, that's not a user feature and we'd lose the ability to compile with VC++ 2005. So I'm not in favor.

**Comment by eevee** [comment]
Is there something VC++ 2005 can do that later VC++ cannot?

**Comment by Gaerzi** [comment]
The ability to compile executable that will run on older versions of Windows. The builds I compile will run on WinXP, Win2K, WinME, and Win98; if I have to move to VC++2015 I'll lose all that.

**Comment by jmickle66666666** [comment]
Are there any proven users that use Win2k, WinME or Win98? Keep in mind all of those OSs' *extended* support have all ended, at least 9 years ago aside from XP.

VC++2015 can still target windows XP, and if there is any case for targetting such old versions, XP is the only possible candidate for inclusion.

**Comment by eevee** [comment]
Wow.  I'm actually amazed that all the _dependencies_ still work on Windows 98.  (Has it actually been tried, ooc?)

Also I'd be pretty surprised if VC++2015 could spit out a binary that worked on WinXP but somehow _not_ Win2K.

**Comment by Gaerzi** [comment]
I don't know which system they used exactly, but there have been people who could only use my builds, yes.

**Comment by sirjuddington** [comment]
Eventually I'd like to move to C++11, but yeah there are still some people who can't run the builds I make from VS2013/15, even with XP targeting enabled, for whatever reason. However eventually it's gotta come to the point where XP (and earlier) support is dropped altogether. Currently I'm thinking 3.2.0 could potentially make the move, which is still a sufficient ways off.

**Comment by eevee** [comment]
Someone on Twitter mentioned [KernelEx](http://sourceforge.net/projects/kernelex/), a gizmo that lets 2K/XP apps run on 98/ME.

**Comment by Blzut3** [comment]
@Gaerzi Pre-XP support isn't really a reason to use 2005 in this case since I have verified that your builds do not run on 98 nor 2000.  You can get the splash screen to show with KernelEx on 98, but Slade will just crash before it finishes starting up.  Windows 2000 doesn't even get that far.

I have also confirmed that sirjuddington's binaries work just fine on XP: http://maniacsvault.net/loosefiles/sladexp.png
