### ISSUE TITLE
Request: Expandable and contractible text/code

### ISSUE THREAD

**Issue by UnknownToaster** [sirjuddington/SLADE#40]
One nice touch would to be able to contract scripts and actors down to just a writable title so that you can limit how much is actually displayed when trying to get through a lot of code.

Next to each actor or script start could have a small box off to the left with a minus that contracts the related code down, then the box changes to a plus to allow it to contract. If you have tons of actors, to contract it down to just a few lines would be amazing convenience.

Nothing of huge importance but a nice touch.

**Comment by sirjuddington** [comment]
In for 3.1.2
