### ISSUE TITLE
Unable to launch zdoom from slade

### ISSUE THREAD

**Issue by JulianGindi** [sirjuddington/SLADE#415]
I've been trying to research the problem on my own but I haven't had much luck. When I attempt to hit the green "play" button from within Slade...zdoom does not appear to attempt to launch. I get the following error when I attempt to hit play:

```
execvp(/Applications/ZDoom.app, -iwad, /Users/gindi/Documents/zdoom/DOOM2.WAD, -file, /Users/gindi/Documents/zdoom/MAP01.wad) failed with error 13!
```

I am using mac osx 10.10.4 and slade version 3.1.1. I am using zdoom as my game "executable"

**Comment by kevans91** [comment]
Hello!

Has this been an issue for you in the past or with running /Applications/ZDoom.app directly? 13 seems to be a "Permission denied" error.

**Comment by JulianGindi** [comment]
I just started working with zdoom/Slade so I can't say I've experienced it
before. I'm able to launch zdoom.app directly without any issue.

**Comment by JulianGindi** [comment]
This can be closed. I was able to get it to work by pointing slate at the executable within the zdoom.app package. Thanks for the help!

**Comment by eevee** [comment]
Is this something that _should_ work?  `.app` is usually the thing executed on OS X, right?

**Comment by JulianGindi** [comment]
I'd say it should probably work by just pointing to the .app. I could probably whip up a PR to fix this issue if you would like.

**Comment by kevans91** [comment]
Yeah, being able to point it to the bundle and having it "just work" seems
to make sense. From my limited usage of OS X/Finder, it's pretty standard
to equate "Opening the bundle" to "Executing the application within".

**Comment by Gaerzi** [comment]
Feel free to make the PR; in the meanwhile I'll close this.
