### ISSUE TITLE
Sector draw issues

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#419]
See the video:
https://www.youtube.com/watch?v=6au8ToUnVsg&feature=youtu.be
https://www.youtube.com/watch?v=BO7PitM4Jrk&feature=youtu.be

**Comment by eevee** [comment]
These look like my fault, and were hopefully fixed by #416 — were you using a build with that merged yet?

**Comment by eevee** [comment]
I found another draw problem as well; will look into it soon.

**Comment by Monsterovich** [comment]
>These look like my fault, and were hopefully fixed by #416 — were you using a build with that merged yet?
These commits resolved only half of this issue.

**Comment by eevee** [comment]
Which half?  :)

**Comment by Monsterovich** [comment]
This.
https://www.youtube.com/watch?v=aME7i1TF2cA&feature=youtu.be

**Comment by sirjuddington** [comment]
That's how it's supposed to work - after line drawing it will create sectors on the front side of the lines drawn.

**Comment by eevee** [comment]
I'm a little torn on whether that _should_ be the behavior, since as you observe, it gives different results when drawing into an enclosed vs unenclosed void.  But it's definitely not new.

**Comment by sirjuddington** [comment]
I think it's best the way it is, at least by default. It follows a simple rule and doesn't try to guess what the user wants to do (which often turns out wrong). Clockwise for an enclosed space, anti-clockwise for a 'column'.

I may add an option to automatically reverse the direction of line drawing if the user draws anti-clockwise, so that it always ends up clockwise.

**Comment by Gaerzi** [comment]
Maybe pressing a modifier key (alt, ctrl, or shift) while drawing lines could flip the lines, so if people start drawing something "the wrong way" then they could just hit that and keep on drawing their figure.

**Comment by sirjuddington** [comment]
I thought of that as well, however I get the feeling most people would end up forgetting to do it :P (especially people new to mapping in general)

But yeah that is another option I guess

**Comment by sirjuddington** [comment]
Closing this, added #441 for discussed option
