### ISSUE TITLE
Fullpath support in the TEXTURES editor

### ISSUE THREAD

**Issue by Doom2fan** [sirjuddington/SLADE#427]
In ZDoom fullpath is supported in TEXTURES and other lumps. (The path just needs to have quotes around it AFAIK)
SLADE does not have fullpath support in the TEXTURES editor, which can be extremely annoying.
[Example PK3](https://dl.dropboxusercontent.com/u/15054795/TEXTURES%20fullpath.PK3)

**Comment by sirjuddington** [comment]
Didn't know this was a thing. Unfortunately it won't be trivial to add so will likely have to wait until 3.1.2
