### ISSUE TITLE
Map canvas loses focus on save

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#428]
I can reproduce this every time — just focus the map canvas and press ctrl-s — but for the life of me cannot figure out what's going on.  `MapEditorWindow::buildNodes` calls `wxExecute`, which seems to fire a focus kill event that moves the focus from the canvas...  to...  the canvas.  After that, `wxWindow::FindFocus` still thinks the canvas has the focus, but it doesn't respond to keydown events.  Pressing tab once does move the focus back to the canvas, but the event claims there was no previous focused element.

**Comment by sirjuddington** [comment]
Weird, looks to me like a wxGTK issue, it doesn't happen in Windows at all

**Comment by sirjuddington** [comment]
Does this still happen? Wondering if it perhaps was due to having the text editor open somewhere (e3f6aa27bf8bf2dba3a0b69d7788a86ab23feb30)

**Comment by eevee** [comment]
Alas, it does.  Even with no archive entries open whatsoever, and regardless of whether "automatically save parent archive" is checked.

I'm still baffled; I swear this didn't always happen, but I have no idea when it started.

**Comment by sirjuddington** [comment]
Closing - old issue, possibly fixed

Feel free to reopen the issue if needed
