### ISSUE TITLE
Can't undo some prop grid edits

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#429]
Pick a line and change its special using the prop grid's `...` button.  You can press undo after this, but the change isn't actually reverted.

Not sure why; it looks like the code is doing everything right.

**Comment by Monsterovich** [comment]
So, undo doesn't work for MapObjectPropsPanel at all. You just have no access to undo functions inside this class.

**Comment by eevee** [comment]
Check out `MapObjectPropsPanel::onPropertyChanged`.  It creates an undo record via `theMapEditor`.  (I do have auto-apply on.)

**Comment by sirjuddington** [comment]
This is a weird one, it only seems to happen if you change the special via `...` first. If you change some other properties then use `...` to change the special it works fine.

**Comment by sirjuddington** [comment]
This doesn't seem to be happening any more (at least for me) so I'm closing the issue
