### ISSUE TITLE
Allow to build against wxWidgets with media/GStreamer support disabled

### ISSUE THREAD

**Issue by danfe** [sirjuddington/SLADE#442]
wxWidgets can be compiled with `--disable-mediactrl` switch: this is sometimes desired because it pulls GStreamer, and some people are not really big fans of it. ;-)

It turns out that SLADE assumes that `wxMediaCtrl` class is always available (there are no `#if wxUSE_MEDIACTRL` checks throughout the code).  Please consider the following patches for two source code files and `CMakeLists.txt`:

[Patch for AudioEntryPanel.cpp](http://svnweb.freebsd.org/ports/head/games/slade/files/patch-src_AudioEntryPanel.cpp?view=markup)
[Patch for AudioEntryPanel.h](http://svnweb.freebsd.org/ports/head/games/slade/files/patch-src_AudioEntryPanel.h?view=markup)
[Patch for CMakeLists.txt](http://svnweb.freebsd.org/ports/head/games/slade/files/patch-src_CMakeLists.txt?view=markup)

This is a quick fix I've come up with while porting SLADE to FreeBSD, and probably can be polished further.

**Comment by Monsterovich** [comment]
>sirjuddington added the linux label 13 hours ago

>FreeBSD

You did it wrong.

**Comment by Gaerzi** [comment]
There were no freebsd labels, now there is one.

**Comment by sirjuddington** [comment]
It technically applies to linux too as some distros don't provide a wx package with mediactrl  enabled

**Comment by danfe** [comment]
*Sigh...* I should not have mentioned FreeBSD.  He did nothing wrong.  This issue is not FreeBSD specific (if you read those patches, there's nothing like `#ifdef __FreeBSD__` or similar); in fact, the bug does not exhibit itself with official `wx30-gtk2` package because it includes mediactrl support by default.  Users can build their own packages and optionally disable heavy features like GStreamer and WebKit if they don't need them.  That's what I did, and why I hit the bug.  The fact that I was using FreeBSD makes no difference, it would be exactly the same on pretty much any GNU/Linux distribution (modulo the fact that it's probably easier to build custom packages on FreeBSD :-).

The reason I've mentioned it (in a context that I was trying to solve the build problem on it) was because I did not try to find elegant way how to make mediactrl usage in SLADE **generally optional**: putting `#if wxUSE_MEDIACTRL` in dozen places does not look rightmost thing.  More to it, `CMakeLists.txt` patch also hacky; I'm not sure why `OPTIONAL_COMPONENT` constraint in `find_package(wxWidgets ...)` is not able to detect absent classes and libraries and avoid polluting `wxWidgets_LIBRARIES`, maybe because it trusts `wx-config` too much, I dunno...  But to quickly get working package my solution was good enough; however, I believe that SLADE developers would probably find a better way to unhardcode mediactrl than a bunch of preprocessor directives, and not so many of them.

**Comment by Gaerzi** [comment]
This could be worked around a bit like how I did for FluidSynth; encapsulate the MediaCtrl thing in a different class where you can put all the #ifdef and that will still compile as a stub if MediaCtrl is disabled. Then there's only one check needed in the AudioEntryPanel class.

**Comment by danfe** [comment]
Right, encapsulation in a separate class comes first to mind when thinking about how to do it in a better way.
