### ISSUE TITLE
Allow user to bind mouse1 and mouse2 keys in the map editor

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#449]
I heard this suggestion from some people, who used slade. They wanted to configure key bindings like in DB2, but this is just impossible. Full customization will be very useful.

**Comment by eevee** [comment]
What else would you bind mouse1 or mouse2 to?

**Comment by Monsterovich** [comment]
>What else would you bind mouse1 or mouse2 to?

What if I want use right mouse button to draw lines?

**Comment by eevee** [comment]
I think that would take some modification to line-draw mode as well, if you mean that mouse2 would _continue_ to draw lines.

I'm not opposed, just genuinely curious how this could work  :)

**Comment by sirjuddington** [comment]
This is something I thought about when implementing the keybinds system, but ultimately decided against, as the left/right mouse buttons have well defined standard roles in GUI applications (ie. left click to select, right click to bring up a context menu) which I would rather not go against.

**Comment by Monsterovich** [comment]
Why is this closed?

**Comment by sirjuddington** [comment]
Because it's a [no].

**Comment by Monsterovich** [comment]
Then you are losing people that would possibly migrate to Slade. Enjoy!
