### ISSUE TITLE
slade refuses to compile

### ISSUE THREAD

**Issue by qwertyuiop924** [sirjuddington/SLADE#452]
Slade refuses to compile on my system. `make` gives the following error:

    /usr/bin/ld: /usr/local/lib/libfreetype.a(autofit.c.o): undefined reference to symbol 'hb_buffer_get_glyph_positions'
    /usr/lib/libharfbuzz.so.0: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    src/CMakeFiles/slade.dir/build.make:9024: recipe for target 'slade' failed
    make[2]: *** [slade] Error 1
    CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/slade.dir/all' failed
    make[1]: *** [src/CMakeFiles/slade.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

After doing some research, it looks like a dependency of some kind was unmet, and that's why `ld` is complaining. I am unsure how or why, not knowing much about the internals of your project.

I am running archlinux, my `uname -srvmo` is `Linux 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux`, and I am running `openrc` instead of `systemd`, which is not standard, though probably not relevant. This is especially puzzling, considering that some of you are running Manjaro, which is an arch distro.

**Comment by eGax** [comment]
I can tell you the PKGBUILDS up on the [AUR](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=slade&outdated=&SB=n&SO=a&PP=50&do_Search=Go) would not compile for me on Manjaro Linux, failing with a similar message as you received.

Slade from git does manually compile for me though the terminal with:

```
git clone https://github.com/sirjuddington/SLADE.git slade
mkdir slade/build
cd slade/build
cmake ..
make
```

**Comment by qwertyuiop924** [comment]
The error is consistent, even if the slade sources are fresh from git.

**Comment by eGax** [comment]
Hmm..ok. I compiled it a few days ago fine. I'll try now to see if there is any change for me as well.

**Comment by qwertyuiop924** [comment]
No, I'm running the same version of freetype2 you are.

**Comment by eevee** [comment]
I'm also running Arch and have had no problems.

Is that the _only_ error?  There's no other output higher up in the terminal?

**Comment by Monsterovich** [comment]
>/usr/bin/ld: /usr/local/lib/libfreetype.a(autofit.c.o): undefined reference to symbol 'hb_buffer_get_glyph_positions'

This looks like libfreetype depends on something that is missing on your system.

**Comment by qwertyuiop924** [comment]
Um... How do you do that?

**Comment by eevee** [comment]
It's `harfbuzz`, which I only just realized is an entirely separate package.  Do you have it installed?

**Comment by qwertyuiop924** [comment]
yes, I do. Also, here is the gist of my full build output. I figured it would help.
https://gist.github.com/qwertyuiop924/db194c459b5d1072a7d2

**Comment by eevee** [comment]
That almost seems like `-lharfbuzz` is just missing entirely from the compiler invocation?  I'm not much of a C wizard, though.

**Comment by qwertyuiop924** [comment]
adding `-lharfbuzz` to the beginning of the list of libraries to link in the compiler invocation in `SLADE/build/src/CMakeFiles/slade.dir/link.txt` seemed to work. Now here's a question: Why wasn't it there in the first place, and why haven't huge quantities of people had massive amount of compiler errors because of this yet?
