### ISSUE TITLE
stopping then re-playing MIDI with FluidSynth causes bad channel settings

### ISSUE THREAD

**Issue by devinacker** [sirjuddington/SLADE#453]
This is with 3.1.1 beta 3 on Windows; I would have attempted to track the issue down myself but my environment isn't really set up for it at the moment.

Anyway, stopping playback of a MIDI/MUS lump and then immediately restarting (i.e. without switching to a different lump first) causes some dropped notes followed by default parameter settings on every channel. 

I suspect the problem is in MIDIPlayer::stop():

```
fluid_player_stop(fs_player);
fluid_synth_system_reset(fs_synth);
```

I can't test this myself, but I suspect since the MIDI reset is sent after playback is stopped, the event  stays queued until the same player instance starts playing again, at which point the reset occurs and interferes with program changes and other events at the start of the song. Switching those two calls might work, but again, that's just my guess.

**Comment by Gaerzi** [comment]
There's the same problem if you wait for the song to be over, then click the play button again. I'll try to see if swapping does fix the issue, it has annoyed me for a long while.

**Comment by Gaerzi** [comment]
Nope, doesn't fix it.

**Comment by devinacker** [comment]
What about removing the `fluid_synth_system_reset` call entirely? It may not even be necessary just for normally stopping playback assuming nothing gets left in the sound buffer afterwards...

**Comment by sirjuddington** [comment]
I'm going to close this one since the MIDI playback stuff has been changed in 3.2.0 and I'm not sure if this is still a thing. Feel free to reopen if it is.

**Comment by devinacker** [comment]
This still has problems in 3.2.1, although it seems to behave a little differently than it used to:

* If you press stop, then press play again, the song will restart, but all MIDI events will be dropped/ignored until the point where playback was originally stopped (i.e. if you stop 5 seconds in and then play again, you'll get 5 seconds of silence followed by defaults on all channels)
* If you let the song play to the end, then press play again, nothing happens.
