### ISSUE TITLE
Displaying 3d Floors and Slopes in 3d Mode

### ISSUE THREAD

**Issue by TammySilverwolf** [sirjuddington/SLADE#454]
I know I'm kind of pining for what GZDoom builder can do, but it /does/ make things so much easier when editing complex architecture. I'm using linux and I've never been able to get Gzdoom builder to run under wine.

I'm not sure how difficult it'd be to implement but I thought I'd mention it and see what happened. Loving SLADE otherwise, though :)

**Comment by eevee** [comment]
Slopes in all forms work in 3.1.1 beta, and in cases like `Plane_Align` can be edited live in 3D mode.

3D floors are a bit harder, but I've started working on them; see #205.

**Comment by TammySilverwolf** [comment]
Huh, awesome, I'm not sure why I don't see them in the editor. Maybe I've missed a setting somewhere, I'll take a look. Thanks for the heads up!

**Comment by eevee** [comment]
I think slopes might not actually be rendered at the moment if you have `flats_use_vbo` off.
