### ISSUE TITLE
Extreme lag when viewing Graphics and Resizing Slade3's Window on Win10

### ISSUE THREAD

**Issue by Doommarine23** [sirjuddington/SLADE#458]
I've recently updated from a Win7 install on which Slade3 worked flawlessly to Win10. I am on the latest beta release (3.1.1 beta 3) from the website and have done a clean install of the program.

While most of the program seems to work without issue, I am running into a very big problem.

**Viewing any kind of textures or sprites, basically graphical data causes the program to halt for a second until it loads.**

(Sometimes it performs like normal for a few moments and instantly switches as it did on Win7)

I have reset my monitor's color mode to sRGB and have tried all the color modes in Slade3's configuration. They have either done nothing, or made it worse. 

**Viewing other forms of data such as folders, ACS, DECORATE and Audio has not caused an issue.**

**Resizing the window is also a problem. When viewing a non-graphical file, there is zero issue. However when I am viewing a graphical file, if the resize affects the graphical editor's inner-window at all, it completely freezes for a second just like my first issue.**

**Comment by sirjuddington** [comment]
This sounds a lot like a driver issue, especially if the only thing that has changed on your system is Win7 -> Win10. Try updating your video drivers and see if it helps.

**Comment by Doommarine23** [comment]
I apologize, I forgot to mention I am on new drivers however I have yet to restart my computer. So please give me a moment to do that and we'll see if it improves, thank you for the suggestion.

**Comment by Doommarine23** [comment]
Okay, I've tested again and it seems to work like a charm. Thank you so much, its funny to think that despite being so experienced with computers, the simplest things sometimes slip me up. I appreciate it dearly.
