### ISSUE TITLE
"Keep Folders On Top" Toggle

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#462]
While the ability to sort is very much welcomed now in 3.1.1, it's... kind of weird to sort them and not have the folders on top.

I suggest a little check box next to the "Up One Level" button that pulls the user back out of one directory level (I don't remember what it's named) that allows folders to always be on top.

And, perhaps, maybe another option to disable folder sorting? Granted this would probably require the "Keep Folders On Top" checked but that's just my technical guess at limitations.

**Comment by eevee** [comment]
Does this even need to be a toggle, really?  I can't imagine many cases where you wouldn't want directories separate.

**Comment by MajorCooke** [comment]
@eevee Do you use windows?

**Comment by eevee** [comment]
I don't, no.
