### ISSUE TITLE
Modifying zip/pk3 outside of SLADE will cause muddled entry data on save

### ISSUE THREAD

**Issue by sirjuddington** [sirjuddington/SLADE#477]
**SLADE Version**: 3.1.1
**Operating System**: Any

**Issue Details**:
If you have a zip/pk3 open in SLADE, modify it with an external program, then save again in SLADE, entries will end up with the wrong data randomly.

**Comment by Gaerzi** [comment]
Maybe detect if an archive was modified outside SLADE and prompt the user about how external changes will be lost?

**Comment by sirjuddington** [comment]
Yeah I was thinking that too, I'm sure it's been requested before, thought it was in an issue already but guess not. I'll add one (#482).
