### ISSUE TITLE
Still have problems with shared sidedefs

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#484]
Someone in #zdoom a few days ago had an issue where copy/pasting from a Doom-format map into a UDMF-format map produced several sidedefs shared by multiple lines.

SLADE has absolutely no idea what to do with these.  The map checks will correctly detect that sector references are wrong on some lines, but attempting to fix them modifies the sides in-place, which will corrupt _other_ sectors.  SLADE (correctly!) pretends sides are just parts of lines, so there's no user-visible way to create new sides.  And due to the way deletion works, sometimes even deleting and recreating the architecture can't fix the problem.

I don't know how to reproduce the original problem, but there should definitely be some way to fix this problem within the editor.  I think the most obvious place is when correcting sector references.  It shouldn't be too hard; I fixed the broken map by hacking the UDMF loader to clone sidedefs if they already belonged to a line.

**Comment by sirjuddington** [comment]
Hopefully 04c86b2 fixes this one
