### ISSUE TITLE
Run map from anywhere

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#488]
Apparently this is a Doom Builder feature, and it sounds pretty slick.  Right-click somewhere, "start from here"?

ZDoom 2.8 supports `+warp` from the command line, but far more portable would be to transparently move the player 1 start.

**Comment by Gaerzi** [comment]
That's how it's done in DB2 yes. The map is saved as a temp file, with the player start moved, and ran. Shouldn't be too hard to do that.

**Comment by jmickle66666666** [comment]
More details on Doom Builder's implementation  :- starts from current mouse position in 2D mode, or start from camera position in 3d mode. 

Incredibly useful feature, saves a surprising amount of time/effort.
