### ISSUE TITLE
Ctrl-W in an open archive entry tab closes the whole archive

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#489]
Surprise!  This should probably just close that one tab.

**Comment by sirjuddington** [comment]
Hmm, that's because it's technically 'Close Archive', not 'Close Tab'. I could change the behaviour to 'Close Tab', though, and it probably would work fine.

**Comment by sirjuddington** [comment]
Or perhaps not, it's used in multiple places, some where it wouldn't make sense to just be 'close tab'. Might be best to change the shortcut for this action and add a new action 'Close Tab (Ctrl+W)'...
