### ISSUE TITLE
Ctrl-Shift-M in an archive opens an entry in a tab

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#491]
...rather than creating a new map.

For the life of me, I can't figure out why.

**Comment by sirjuddington** [comment]
Doesn't happen for me in Windows, but it does in my linux mint vm, when I press `Ctrl+M` while an item in the entry list is highlighted, so it looks like it's a wxGTK issue.

**Comment by eevee** [comment]
Oh, no, I wonder if that's because `^M` is `\r`?  I've never heard of that leaking into a GUI app before.

**Comment by eevee** [comment]
Yeah, Ctrl-M in a `CHAR` event produces a key code of 13, which is of course the same as the Enter key.  wxDataView doesn't have this problem, because it ignores the keypress if any modifiers are held down.

I'm surprised this doesn't happen in Windows, since the documentation says that Ctrl-(letter) keypresses are always translated into a key code of 1 through 26 in a `CHAR` event.  So the key code should still be 13, which is still `WXK_RETURN`.

Anyway, filing a wx ticket: http://trac.wxwidgets.org/ticket/17458#ticket

**Comment by sirjuddington** [comment]
While the ctrl+m issue still seems to exist, ctrl+shift+m now appears to open the map editor as expected, so I'll close this one
