### ISSUE TITLE
Compilation errors on openSUSE

### ISSUE THREAD

**Issue by Luke-Nukem** [sirjuddington/SLADE#497]
**SLADE Version**:
3.1.1.1
**Operating System**:
Linux - openSUSE Tumblewed

**Issue Details**:
Basically a series of errors like ```/MapLine.h:132:11: error: could not convert '(const char*)"<line NULL>"' from 'const char*' to 'Debuggable'```

As I'm using the SUSE open build system to build SLADE (to rpm), you can see the full log [here](https://build.opensuse.org/package/live_build_log/home:luke_nukem/slade/openSUSE_Tumbleweed/x86_64)

Any help would be much appreciated as I don't have much time for troubleshooting myself.

**Comment by sirjuddington** [comment]
Looks like the compiler used doesn't like something in the Debuggable stuff, @eevee, any ideas?

**Comment by Luke-Nukem** [comment]
From memory, version 3.1.0.5 built fine. So perhaps starting with diffs from there might help.

**Comment by sirjuddington** [comment]
Probably because 3.1.0.5 didn't have the `Debuggable` stuff

**Comment by eevee** [comment]
Aha, I think I see the problem.  PR incoming shortly.

**Comment by Luke-Nukem** [comment]
Many thanks. Will try a new build soon.
