### ISSUE TITLE
Ads whenever SLADE starts-up

### ISSUE THREAD

**Issue by Quaker540** [sirjuddington/SLADE#500]
**SLADE Version**: (3.1.1.1)
**Operating System**: (Windows XP SP3 32-bit)

**Issue Details**:
Everytime I open SLADE, my browser opens with the following link: http://ie.adsplx.com/ad/468_60.html?size=%40%403%40%403%40%40#data=%7B%22h3%22%3A%22%22%2C%22url%22%3A%22http%3A%2F%2F%2F%22%2C%22li%22%3A%5B%5D%2C%22h1%22%3A%22Navigation%20to%20the%20webpage%20was%20canceled%22%2C%22msg%22%3A%22%22%2C%22country%22%3A%22gr%22%2C%22uid%22%3A%22fujitsuxmhw2080at_k004t852du35t852du35x%22%7D.

Unfortunately I don't know when or how this started. Please fix this issue. Thanks a lot!

**Comment by eevee** [comment]
That sounds an awful lot like you've been infected with malware, unrelated to SLADE.  It's probably just trying to hijack the embedded IE that SLADE uses for its start page.

**Comment by Monsterovich** [comment]
This link is not working for me in linux. :P

I recommend [this](http://z-oleg.com/avz4en.zip) software to scan your PC. It might help you.

**Comment by Gaerzi** [comment]
What browser do you use normally? You probably have IE infected and not notice it because you're generally using Firefox or Chrome.

**Comment by sirjuddington** [comment]
Closing this as it is not really related to SLADE itself

**Comment by Quaker540** [comment]
Thanks a lot for that link, Monsterovich, and everyone else involved in this. No doubt something was wrong with my system. I'm using Firefox and Opera. Thanks guys!
