### ISSUE TITLE
Thing icons missing.

### ISSUE THREAD

**Issue by retrogamedesigner** [sirjuddington/SLADE#501]
**SLADE Version**: (3.X.X.x)
**Operating System**: Windows 10

**Issue Details**:
Regardless of the version of Slade I'm running (I've tried 3.05 and 3.1.1.1), the "Thing" icons are missing when I run Slade on a new Dell XPS 13 laptop (i5 processor, Windows 10, Intel integrated graphics). All I can see are faint black circles where the icons should be. If I select one or more "Things" and edit them, the appropriate icons will appear, but once I finish editing by confirming or canceling the changes and leaving edit mode, they are replaced by the subtle black holes.

I'd previously been using an old Dell Inspiron laptop (i5 processor, AMD Radeon graphics card, Windows 7) and updating my version of Slade along the way, without any major issues.

I've also discovered that my Mac all-in-one (quad-core i5, NVidia GeForce 755m graphics card, Mac OS X v10.9.5) runs Slade without this issue.

Does anyone know what would cause this issue? Are there any settings in Slade or Windows 10 that would solve this problem, or is it caused by a more complicated issue? Does this have to do with the XPS 13's lack of graphics card and use of Intel integrated graphics?

Thanks

**Comment by sirjuddington** [comment]
I get that too on my macbook, seems to be an intel driver issue with point sprites. You'll have to disable them in the options (Edit -> Preferences -> General -> OpenGL -> untick 'Enable point sprites if supported')

**Comment by retrogamedesigner** [comment]
Thanks, that solved the problem.
