### ISSUE TITLE
Copy-pasting map data from Doom-format maps into UDMF maps results in corrupted map

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#502]
**SLADE Version**: 3.1.2 Alpha (latest from git) - happens in latest official release as well
**Operating System**: Linux (Arch)

**Issue Details**:
Steps to reproduce:
1. Create a new UDMF-format map WAD
2. Save this WAD
3. Open an existing Doom-format map WAD
4. Select and Copy some sectors
5. Open the UDMF-format map
6. Paste the sectors into this map
7. Enter 3D preview mode
8. Observe: pasted map geo looks ok in SLADE's 3D preview
9. Open the map in a source port that supports UDMF (eg ZDoom, GZDoom)
10. Observe: pasted map geo is totally corrupted, with some sectors not appearing, line collisions not working properly, etc

Expected result: map data can be copied and pasted between Doom and UDMF format maps without issues.

I can attach a map of the corrupted output if it helps.

**Comment by eevee** [comment]
I had this same problem when copy/pasting E3M8 into a new UDMF map, and I still haven't figured out what actually went wrong.  I think deleting the nodes helped, but every time SLADE rebuilt them, the map would be screwy in GZDoom again.

See also #484, which is about shared sidedefs after copying from Doom to UDMF.

**Comment by JPLeBreton** [comment]
A somewhat labor-intensive workaround for this bug is to convert the Doom-format map in its entirety to UDMF using a tool like UDMF-Convert (https://github.com/CO2/UDMF-Convert) and then opening that in Slade before copy-pasting.

**Comment by sirjuddington** [comment]
Haven't really had much of a look into this, but off hand I have no idea why it would happen. Does it happen just when copy+pasting between different maps of the same format? eg. UDMF -> UDMF?

**Comment by JPLeBreton** [comment]
Pasting UDMF->UDMF and Doom->Doom works just fine.

**Comment by sirjuddington** [comment]
Ok I think I know what this one is, copying from Doom->UDMF clears all line flags, including 'two sided' and 'impassable'. Looks like the either doom or zdbsp doesn't like two-sided lines without the 'two sided' flag set.

**Comment by eevee** [comment]
Ha.  Can confirm that my copy of E3M8 has no two-sided or impassable flags on any of the pasted lines.

**Comment by eevee** [comment]
Ha.  Can confirm that my copy of E3M8 has no two-sided or impassable flags on any of the pasted lines.

I wonder if SLADE should just always force one-sided lines to be impassable, and not expose the two-sided flag at all?  Are there any obscure mapping tricks that rely on having these flags be incorrect?

**Comment by jmickle66666666** [comment]
Could be a convenience with an option to turn off? (being able to freely enter the void isn't a mapping trick, but could potentionally be a desired element of a map!)

**Comment by PROPHESSOR** [comment]
May be this project can help you to easy convert Boom map to UDMF format without lots of copy-pasting https://github.com/PROPHESSOR/Boom2UDMF
