### ISSUE TITLE
Delete texture patches quicker

### ISSUE THREAD

**Issue by DeathEgg** [sirjuddington/SLADE#505]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
When deleting patches from a texture, you should be able to press the minus button and it will automatically delete the first patch in the texture list instead of having to individually click it.

**Comment by sirjuddington** [comment]
Closing this as I'm not sure I want it to work like that, plus you can select multiple patches at remove them all at once which should be just as quick
