### ISSUE TITLE
TEXTURE1/PATCHES error

### ISSUE THREAD

**Issue by DeathEgg** [sirjuddington/SLADE#506]
**SLADE Version**: (3.1.1.1)
**Operating System**: (Windows 10)

**Issue Details**:
I keep deleting large amounts of textures from TEXTURE1 and PATCHES and it moves every patch list to the next texture. For example, PATCH1 would go to TEXTURE1, PATCH2 to TEXTURE2, PATCH3 to TEXTURE3, etc. If I delete PATCH1 and TEXTURE1, then TEXTURE2 would have PATCH3, TEXTURE3 would have PATCH4, etc.

**Comment by sirjuddington** [comment]
I can't get this to happen, you wouldn't happen to have the texture/patch list sorted by any chance?

**Comment by sirjuddington** [comment]
Closing this issue, feel free to reopen it if it still happens
