### ISSUE TITLE
Compiling a script outside of a map can clobber the source code

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#507]
If you have a script named `acs/foo` (no extension) in a zip/directory archive, SLADE will compile it on top of itself, losing the source code.

I don't know what the right thing is, but it's probably not that.  Maybe prompt to rename to `.acs`?

**Comment by XaserAcheron** [comment]
Aaaarrrgh, I'm getting this now, even with an .acs extension. I'm using Open Directory so I'm not sure if that has anything to do with it, but it didn't happen to me before. Are there any known workarounds for now?

**Comment by eevee** [comment]
I've just been keeping the script source in a separate directory: `acs-source/foo.acs` correctly compiles to `acs/foo.o`.

I don't understand why SLADE would be overwriting a file named `foo.acs`, though, yikes.

**Comment by XaserAcheron** [comment]
Ah, that helps a ton -- it indeed works "normally" if the source is outside the /acs directory.

**Comment by Gaerzi** [comment]
When compiling non-map ACS, SLADE will import the resulting bytecode into an entry of the same name but in the proper namespace. The problem here is "of the same name", it should have a step where it strips the .acs extension if present and puts .o instead.

**Comment by XaserAcheron** [comment]
I figured this'd have something to do with the "extensions don't always matter" philosophy of ZDoom modding. Though it's already acknowledged and tagged with [bug] anyway, so whatever it is, it's known. :P

**Comment by XaserAcheron** [comment]
Awesome! Thanks for the patch here -- it's a tiny thing, but having the .acs and the .o next to each other in the same folder makes my inner OCD-er happy. :P
