### ISSUE TITLE
Running SLADE a second time should focus the first copy

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#508]
I spent the last fifteen minutes trying to figure out what horrible problem would cause a fresh build of SLADE to immediately exit with status 255 with seemingly no error...  only to realize it's because I already had a stable copy of SLADE running.

If SLADE is already running, starting it again should focus the existing instance.  And probably print something to stderr so I can tell what's going on.  :)

Someone brought this up in the ZDoom thread, too.

**Comment by Danfun64** [comment]
So you're saying there is no valid reason for two working slade instances at once?

**Comment by eevee** [comment]
I'm not arguing that one way or the other.  SLADE _currently_ prevents itself from being run twice, and if it's going to do that, it should do it more politely.  :)

**Comment by sirjuddington** [comment]
In master it'll open a second copy if you don't specify any archives to open on the command line.

**Comment by Manuel-K** [comment]
I agree that it would be a good idea to print a message to stdout if the second instance is closed.

**Comment by Manuel-K** [comment]
Partial fix: #514

**Comment by jmickle66666666** [comment]
just a note: in many other applications you can choose between "multi-instance mode" or not upon installation, and change the setting in preferences later.

**Comment by Gaerzi** [comment]
I agree this could be a configuration option, and in fact I said so in #333.
