### ISSUE TITLE
Misaligned entry contents window

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#512]
**SLADE Version**: 3.1.1.1
**Operating System**: Windows 10
**Issue Details**:Entry contents window is misaligned and has a white section, where normally the grey checkered background should be at, which also effects how the sprites are shown.
![capture2](https://cloud.githubusercontent.com/assets/9903201/14866400/95f84b8c-0c91-11e6-8553-bfe8c63b2a43.PNG)

**Comment by sirjuddington** [comment]
Can you post a screenshot of the entire window? I can't really see what is going on there

**Comment by SteelTitanium** [comment]
![image](https://cloud.githubusercontent.com/assets/9903201/14901728/f244b88e-0d64-11e6-8ee4-e6110af87b9c.png)As you can see, the texture here i'm using is misaligned and is cut off. Not letting me see anything small such as sprites.

**Comment by sirjuddington** [comment]
Hmm that's weird, are your video drivers up to date?

**Comment by SteelTitanium** [comment]
I figured it had something to do with the graphics card, I am using modified drivers. I'll try installing latest unmodified and let you know.

**Comment by SteelTitanium** [comment]
It's still the same.

**Comment by Monsterovich** [comment]
![slade2](https://cloud.githubusercontent.com/assets/3750982/14953184/b52d86c0-106f-11e6-8487-0d044096bbb3.png)

I have the same in linux, but it doesn't look such buggy.

**Comment by sirjuddington** [comment]
Then I don't really know what it might be, what video card do you have?

**Comment by SteelTitanium** [comment]
Intel GMA X3100.

**Comment by SteelTitanium** [comment]
I went back to Windows 7, and checked again. The problems seems to be fixed, I don't know if the problem was with using Windows 7 drivers on Windows 10 or what. But I'll close this issue and open again if the problem appears again at some point.
