### ISSUE TITLE
Archive manager crash when I clicked textures.txt

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#520]
**SLADE Version**: master branch
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
SLADE CRASHED WHEN I CLICKED TEXTURES.TXT LUMP. HALP!
But texture manager actually works through a panel.

Version: 3.1.2 Alpha
No current action

Operating System: Linux 4.2.0-25-generic i686
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: [unknown location] MainApp::OnFatalException()
1: [unknown location] [unknown:-1232194429]
2: [unknown location] [unknown:-1217074036]
3: [unknown location] wxString::CmpNoCase(wxString const&) const
4: [unknown location] JumpToCalculator::Entry()
5: [unknown location] wxThread::CallEntry()
6: [unknown location] [unknown:-1232200038]
7: [unknown location] [unknown:-1235754303]
8: [unknown location] [unknown:1552615460]

Last Log Messages:
11:43:01: Loading icons
11:43:02: Loading entry types
11:43:02: Loading text languages
11:43:02: Loading text style sets
11:43:02: Loading colour configuration
11:43:21: Loading base resource
11:43:24: Base resource loaded
11:43:24: SLADE Initialisation OK
11:43:25: Read game configuration "doom2" + "zdoom"
11:43:27: Opening directory /home/monsterovich/Distfiles/projects/HellVsMarines as archive
11:43:47: Opening took 19562 ms

**Comment by sirjuddington** [comment]
How recently have you pulled the source and built, https://github.com/sirjuddington/SLADE/commit/862c5b8c89d1111ea9445f2b9b6c1aad5ba30bb4 should have fixed that

**Comment by Monsterovich** [comment]
I have the lastest build of master, so it's not fixed.

**Comment by Monsterovich** [comment]
And It happened only in directory archive.

**Comment by Monsterovich** [comment]
My textures.txt
http://pastebin.com/EpYqEtwk

**Comment by sirjuddington** [comment]
Maybe this is fixed with https://github.com/sirjuddington/SLADE/pull/541?

**Comment by simon-v** [comment]
This seems oddly similar to my own issue, #503.

It seems to be fixed in 3.1.1.2-r115.

**Comment by Monsterovich** [comment]
Fixed.
