### ISSUE TITLE
SLADE renaming always CAPS

### ISSUE THREAD

**Issue by danylopez123** [sirjuddington/SLADE#521]
**SLADE Version**: (3.1.1.1)
**Operating System**: (Windows)

**Issue Details**:
Im trying to insert an sprite named like PLAYc0 but always goes to PLAYC0, no matter if i try to rename it, still the same caps

**Comment by Gaerzi** [comment]
Edit->Preferences->Editing, uncheck the option to "Force uppercase entry names in Wad Archives".
