### ISSUE TITLE
Option to pick default media player.

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#522]
Since SLADE recognizes chiptunes, it can play them, but on Microsoft Windows, it would try to use Windows Media Player to play the lump, which it don't support. It would be nice to pick a different player, or at least for chiptunes lump files.

**Comment by Gaerzi** [comment]
Using the windows media player is a fallback based on wx code that's built around it; picking a different player would be more complicated.

**Comment by Monsterovich** [comment]
You mean modules? So, slade is bundled with libbass that supports them?

**Comment by sirjuddington** [comment]
The WMP fallback is pretty much meant for playing mp3s on windows, and will be going away in 3.2.0 (I have mp3 playback via SFML+libmpg123 mostly working in a branch). SLADE can't actually play chiptunes as far as I know (unless you mean modules which it does), so closing this issue
