### ISSUE TITLE
error: no matching function for call to 'wxString::CompareTo(string, wxString::caseCompare)'

### ISSUE THREAD

**Issue by Luke-Nukem** [sirjuddington/SLADE#523]
**SLADE Version**: commit/4e23d041c45a9bf55fbb73bc7ce1c75ca4de05b3
**Operating System**: Linux

**Issue Details**:
New build errors. Using [openSUSE build service](https://build.opensuse.org/package/live_build_log/home:luke_nukem/slade/openSUSE_Tumbleweed/x86_64) system for building.

[  222s] /home/abuild/rpmbuild/BUILD/SLADE-master/src/UI/Lists/ArchiveEntryList.cpp: In static member function 'static bool ArchiveEntryList::entrySort(long int, long int)':
[  222s] /home/abuild/rpmbuild/BUILD/SLADE-master/src/UI/Lists/ArchiveEntryList.cpp:588:70: error: no matching function for call to 'wxString::CompareTo(string, wxString::caseCompare)'
[  222s]     result = le->getName().CompareTo(re->getName(), string::ignoreCase);
[  222s]                                                                       ^
[  222s] In file included from /home/abuild/rpmbuild/BUILD/SLADE-master/src/./Application/Main.h:32:0,
[  222s]                  from /home/abuild/rpmbuild/BUILD/SLADE-master/src/UI/Lists/ArchiveEntryList.cpp:31:
[  222s] /usr/include/wx-3.0/wx/string.h:2387:7: note: candidate: int wxString::CompareTo(const wxChar_, wxString::caseCompare) const
[  222s]    int CompareTo(const wxChar_ psz, caseCompare cmp = exact) const
[  222s]        ^
[  222s] /usr/include/wx-3.0/wx/string.h:2387:7: note:   no known conversion for argument 1 from 'string {aka wxString}' to 'const wxChar\* {aka const wchar_t*}'
[  223s] src/CMakeFiles/slade.dir/build.make:5462: recipe for target 'src/CMakeFiles/slade.dir/UI/Lists/ArchiveEntryList.o' failed

**Comment by Luke-Nukem** [comment]
I finally found time to look in to this. The error is a result of most *stable* Linux distros sticking with the stable release of wxWidgets, rather than the development version (3.1).

The only course of action is to either get the distros to update, or use an older version of SLADE.

**Comment by Gaerzi** [comment]
Compilation instructions mention wxWidgets 3.0 as the minimum, not 3.1.

**Comment by sirjuddington** [comment]
Yeah, it shouldn't need wx3.1, I can compile it fine on ubuntu with wx3.0.
