### ISSUE TITLE
Cant write ^ character

### ISSUE THREAD

**Issue by danylopez123** [sirjuddington/SLADE#524]
**SLADE Version**: (3.1.1.1)
**Operating System**: (Windows)

**Issue Details**:
Everytime i try to type an ^ it remplaces to an \

**Comment by Gaerzi** [comment]
That behavior comes from how \ is a legit character for some sprite frames (used notably by the arch-vile) but it's not possible to have that character in a file name. By default SLADE is configured to use ZDoom's character substitution for it; try changing that by checking Preferences->Editing->Use percent encoding instead.

**Comment by danylopez123** [comment]
It solved my problem, thanks

**Comment by Gaerzi** [comment]
Glad to hear it.
