### ISSUE TITLE
Better color matching when converting to palette

### ISSUE THREAD

**Issue by Blastfrog** [sirjuddington/SLADE#525]
I'd prefer if color matching worked slightly differently than it does now. I have a source color of 255,255,71, but it translates to 235,219,87 instead of 255,255,35. Clearly, the latter is closer to the human eye.

Should probably leave the color matching as it is when generating colormaps, to stay true to the original utility. Perhaps make it an option.

**Comment by Gaerzi** [comment]
There are already color matching options; that's what the entire "colorimetry" preference page is for.

I've implemented all the CIE algorithms for getting things "closer to the human eye" and -- honestly -- I haven't been really convinced by any of them.

Do you have some other algorithm to suggest?

**Comment by Gaerzi** [comment]
Without further feedback, I'm just going to close this as [already in]...
