### ISSUE TITLE
Compile Error OpenGL/Drawing.cpp on Fedora 22

### ISSUE THREAD

**Issue by RodneyBrown** [sirjuddington/SLADE#530]
Slade Version: I've tried testing and stable branches

**Issue Details**:
[ 59%] Building CXX object src/CMakeFiles/slade.dir/OpenGL/Drawing.o
In file included from /usr/include/gtk-2.0/gdk/gdkscreen.h:32:0,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/rbrown/slade/src/OpenGL/Drawing.cpp:48:
/usr/include/gtk-2.0/gdk/gdktypes.h:114:39: error: conflicting declaration ‘typedef struct _GdkDrawable GdkWindow’
 typedef struct _GdkDrawable           GdkWindow;
                                       ^
In file included from /usr/include/wx-3.0/wx/string.h:24:0,
                 from /home/rbrown/slade/src/./Application/Main.h:32,
                 from /home/rbrown/slade/src/OpenGL/Drawing.cpp:30:
/usr/include/wx-3.0/wx/defs.h:3412:31: note: previous declaration as ‘typedef struct _GdkWindow GdkWindow’
     typedef struct _GdkWindow GdkWindow;
                               ^
src/CMakeFiles/slade.dir/build.make:5006: recipe for target 'src/CMakeFiles/slade.dir/OpenGL/Drawing.o' failed
make[2]: **\* [src/CMakeFiles/slade.dir/OpenGL/Drawing.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/slade.dir/all' failed
make[1]: **\* [src/CMakeFiles/slade.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by sirjuddington** [comment]
Are you using the GTK3 build of wxWidgets? I think it'll only work with GTK2, currently

**Comment by johnsto** [comment]
You can compile for GTK3 by changing references for GTK2 in `src/CMakeLists.txt` to GTK3, and updating the header includes in `src/OpenGL/Drawing.cpp` to point to gtk-3.0. 

There are a few deprecation warnings emited during compilation, but SLADE appears to function normally otherwise.

**Comment by sirjuddington** [comment]
Closing - can work around by building/using wx with gtk2, gtk3 support coming

Feel free to reopen the issue if needed
