### ISSUE TITLE
building textured bridges using sectors

### ISSUE THREAD

**Issue by D3X1KAXYZ** [sirjuddington/SLADE#540]
Feature Request

- texture properties for bridges

- set bridge dimensions using a sector

_side note: if possible please add an auto save feature. Slade likes to crash on me and i lose my progress. as of right now it does not bother me as i am just experimenting, but i hope to start making mods in the near future._
_also 3.1.1.2 is much more stable than 3.1.1.1 for me. it still crashes but not as frequently as 3.1.1.1 did.._

**Comment by Gaerzi** [comment]
I believe this to be a duplicate of #205.

**Comment by D3X1KAXYZ** [comment]
# @Gaerzi lol yes it is. very sorry about that.
