### ISSUE TITLE
Invalid sectors after dragging geometry

### ISSUE THREAD

**Issue by m-x-d** [sirjuddington/SLADE#542]
**SLADE Version**: 3.1.1.2
**Operating System**: Windows 7 x64

**Issue Details**:
1. Open the attached map.
2. Set grid size to 2 mu.
3. Select vertex 3.
4. Move it 2 mu to the left.
Result: broken sectors.
Also, undoing vertex move doesn't fix sectors.

![slade_drag_bug](https://cloud.githubusercontent.com/assets/7252064/15994443/8ce8f384-310d-11e6-9348-4066a5ac26c3.jpg)
[drag_bug.zip](https://github.com/sirjuddington/SLADE/files/311034/drag_bug.zip)

**Comment by eevee** [comment]
I'll have a look; this is pretty up my alley.

**Comment by eevee** [comment]
Undoing works for me on a stable build, fwiw.

**Comment by eevee** [comment]
Think I've fixed it; explanation in #548.
