### ISSUE TITLE
Map editor: Browse Texture window size and position should be remembered

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#543]
1. open a map in the map editor
2. right-click a wall in 3D mode
3. resize the texture browser window so it shows more stuff
4. pick something
5. right-click another wall in 3D mode
6. observe: texture browser window is back to its default size

expected behavior: texture browser window should open at its last-seen size and position

**Comment by eevee** [comment]
This drives me _up the wall_ — the texture browser window is so tiny by default too.

**Comment by sirjuddington** [comment]
Yeah it probably should, not sure why I didn't do this already
