### ISSUE TITLE
PageUp/PageDn key presses should update Entry Contents pane the way Up/Down arrow keys do

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#544]
1. open a WAD and browse its non-map (sounds, graphics) content
2. use the up/down arrow keys to move the selection up and down entries
3. observe: with each new item selected, the Entry Contents pane to the right updates
4. use the pgup/pgdn keys to move selection in page increments
5. observe: the Entry Contents pane does not update to show the new selected item's contents

**Comment by sirjuddington** [comment]
This doesn't happen for me in windows, so seems to be a linux-only issue.
