### ISSUE TITLE
TEXTURES lump conversion should enclose any texture names with dashes in quotes

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#545]
1. open TNT.WAD
2. right-click its TEXTURE1 lump and select "Convert to TEXTURES"
3. delete the original TEXTURE1 lump and save the wad under a different name
4. open the new wad in ZDoom
5. observe: ZDoom throws an error on METAL-BD, a texture with a dash in its name
6. hand-edit the TEXTURES lump: enclose METAL-BD and METAL-RM in quotes
7. save and open the new wad in ZDoom
8. observe: ZDoom doesn't have any problem loading those textures

expected result: SLADE encloses any texture names with dashes in quotes

**Comment by Gaerzi** [comment]
Might be simpler and safer to always enclose all names in quotes. Who knows what other characters would cause troubles?

**Comment by sirjuddington** [comment]
This isn't mentioned at all in the zdoom wiki TEXTURES article either, perhaps it should?

**Comment by JPLeBreton** [comment]
Yeah, if this is something ZDoom should handle more gracefully, I'm happy to file a bug with them. My wild guess is, the parser always assumes the - character is indicating a negative number, so a letter after a - throws it off.
