### ISSUE TITLE
Ctrl+S doesen't save text lumps opened in other tab

### ISSUE THREAD

**Issue by Jayman2000** [sirjuddington/SLADE#549]
**SLADE Version**: 3.1.1.2
**Operating System**: Linux

**Issue Details**:
If I am editing a lump as text in another tab than the wad itself, and I press Ctrl+S, SLADE will save the archive that the lump is in, not the lump itself.

**Steps to reproduce**:
1. Create a new archive
2. Create a new lump. Edit it as text and make changes to it.
3. Double click on it to open it in a new tab.
4. Make some more changes to it and click the save button, but do not save the archive itself.
5. Press Ctrl+S. Notice that the \* next the archive's name disappears indicating that the archive has been saved.

**Comment by sirjuddington** [comment]
This is because 'Save' in the File menu is actually 'Save Archive', not 'Save whatever is in the current tab', so it's not really a bug. Entries open in tabs still behave exactly the same as if they were open in their parent archive's tab.
