### ISSUE TITLE
SLADE dosen't follow #includes in decorate files

### ISSUE THREAD

**Issue by Jayman2000** [sirjuddington/SLADE#550]
**SLADE Version**: 3.1.1.2
**Operating System**: Linux

**Issue Details**:
If you define zdoom actors in a lump other than the main DECORATE lump, and you include them in the main DECORATE lump, they will not be available from the map thing type selector.

**Comment by sirjuddington** [comment]
Do you have an example wad/pk3? This works fine for me.

**Comment by Jayman2000** [comment]
[descent.zip](https://github.com/sirjuddington/SLADE/files/327744/descent.zip)

**Comment by sirjuddington** [comment]
Ok I see what's happening there, put quotes around your `#include` paths and it will work fine
