### ISSUE TITLE
backslashes in values of name/value pairs are stripped.

### ISSUE THREAD

**Issue by MarkJeronimus** [sirjuddington/SLADE#555]
**SLADE Version**: 3.1.1.2
**Operating System**: Windows 10

**Issue Details**:
When upgrading from an older version of Slade (possibly only when using the 7z), and starting this version, all backslashes in values of name/value pairs of slade.cfg are stripped. This makes all paths invalid, and incidentally triggers bug #554.

After removing all offending paths from slade.cfg by hand, and configuring new paths in Slade, I see it now uses forward slashes.

In these files, I sorted all name/value pairs in the sections for easier comparing (e.g. kdiff3).
From 3.1.0: [slade3.cfg.good.txt](https://github.com/sirjuddington/SLADE/files/333605/slade3.cfg.good.txt)
After running 3.1.1.2 once: [slade3.cfg.txt](https://github.com/sirjuddington/SLADE/files/333604/slade3.cfg.txt)

**Comment by sirjuddington** [comment]
Unfortunately there isn't really much I can do about this now. Between 3.1.0 and 3.1.1, backslash was changed to be an 'escape' character within quoted strings, and so Windows paths in configs from earlier versions will end up with the backslashes removed. There isn't any way to tell if a config is from 3.1.0 or a later version, so I can't really add anything to convert it.

**Comment by MarkJeronimus** [comment]
From what I see, there are some new keys added, so you could check for presense of those keys. Breaking upgrade compatibility with previous versions is a serious offence in software engineering.

**Comment by sirjuddington** [comment]
Closing - old issue

Feel free to reopen the issue if needed
