### ISSUE TITLE
Map editor: min/max distances on ambient sound things can't be set higher than 255

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#556]
**SLADE Version**: (3.1.1.2) (also latest git)
**Operating System**: (Windows and Linux)

**steps to reproduce:**
1. place an ambient sound thing in a map
2. open its properties
3. use number keys to try setting its min and max distances to anything higher than 255
4. observe: field only accepts numbers between 0 and 255

expected behavior: since min and max distance are defined in world units, number should be any value between 0 and largest map dimension.

**Comment by sirjuddington** [comment]
This is the same issue as #380 (if the map format is UDMF, Hexen format has a hard limit of 255 for args)

**Comment by sirjuddington** [comment]
Fixed along with #380
