### ISSUE TITLE
SLADE not successfully making calls to external programs. (acc.exe, PNG tools, etc...)

### ISSUE THREAD

**Issue by darkmessenger84** [sirjuddington/SLADE#557]
**SLADE Version**: (3.1.1.2)
**Operating System**: (Windows 7)

**Issue Details**:
SLADE not successfully making calls to external programs. (acc.exe, PNG tools, etc...)

When attempting to compile ACS, it fails and no output is shown in the error window.
![slade_2016-06-29_17-33-56](https://cloud.githubusercontent.com/assets/20210311/16460529/ae1d8fbe-3e1f-11e6-9046-e8746624011c.png)

When attempting to use PNG tools, the error window appears saying that it failed to create optimised file.
![slade_2016-06-29_17-35-05](https://cloud.githubusercontent.com/assets/20210311/16460586/fc73f7d4-3e1f-11e6-9cdd-7683474e79a2.png)

Paths to PNG tools
![slade_2016-06-29_17-43-13](https://cloud.githubusercontent.com/assets/20210311/16460780/058c249e-3e21-11e6-851a-660c364d2868.png)

Path to ACC
![slade_2016-06-29_17-44-00](https://cloud.githubusercontent.com/assets/20210311/16460798/203780d6-3e21-11e6-8c92-0c1a2c5459dc.png)

Console log
![slade_2016-06-29_17-42-29](https://cloud.githubusercontent.com/assets/20210311/16460756/eacea9e2-3e20-11e6-8260-d402dde42d7a.png)

**Comment by Gaerzi** [comment]
Hmm. Just as a quick guess here: can you try putting ACC or PNGout in a different path, one without any space in it (e.g. C:\Test\acc.exe), and see if it works for you?

**Comment by darkmessenger84** [comment]
That doesn't really make sense as this setup was working just fine over a week ago, and has just stopped working out of the blue. It would also appear that other application built with wxWidgets have run in to the same problem. https://goo.gl/9Jgtlh

**Comment by sirjuddington** [comment]
Hmm, thought it was putting quotes around executable paths but looks like it doesn't.

**Comment by sirjuddington** [comment]
For me it seems to work fine anyway with a space in the path, so perhaps it was an access rights issue or something...

**Comment by Gaerzi** [comment]
With Program Files that's possible, ever since Vista it is virtualized in Windows.
