### ISSUE TITLE
Automatic crashlog report mechanism

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#558]
This is my friend's idea. The reality shows that the most of slade users are too lazy/can't report issues on issue tracker by some reason ex. random crashes (they can't reproduce them). A lot of slade bugs were not fixed for years. Need some feedback on this.

**Comment by jmickle66666666** [comment]
For privacy concerns the user should be made aware of any automatic data reporting, either with a confirmation before sending an error report (very likely to be declined most of the time), or by asking the user upon install if crash reports should be sent automatically.

**Comment by sirjuddington** [comment]
I've been wanting to do something like this for a while, just haven't found an easy way to do it. Ideally I'd just have the error dialog have "Send" and "Don't Send" buttons, and clicking "Send" would automatically send the stack trace etc. via email to some SLADE error inbox somewhere, problem is there aren't any good/simple email libs I can find for wxWidgets.
