### ISSUE TITLE
Only open/save one TEXTURES lump at a time

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#562]
Since the TEXTURES editor was changed recently, this is causing some serious issues. I keep one of my textures lump separated from the rest because it uses long names. 

I don't want SLADE to open it or save it. Ever. I want to keep it separate and I don't want SLADE touching it, but that's not possible at the moment. 

It's also quite aggravating. Please consider changing this.

**Comment by sirjuddington** [comment]
Yeah I think the save button should probably only save the texture list that is currently visible.

**Comment by sirjuddington** [comment]
Hmm, after testing this out a bit it actually won't save over a TEXTURES lump if it hasn't been modified at all in the texture editor, so I'm not sure how this is an issue unless you are editing textures in the lump you don't want overwritten.

**Comment by MajorCooke** [comment]
Strange, because I could've sworn it removed all formatting and the likes.

**Comment by sirjuddington** [comment]
Closing this one, feel free to reopen if it's still an issue
