### ISSUE TITLE
Colourise option doesn't work at all

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#567]
**SLADE Version**: master

**Issue Details**:
http://www.zimagez.com/zimage/2016-07-2201-02-09.php
Sprite is always black, nevermind what color I choose.

**Comment by sirjuddington** [comment]
Not sure what is going on there, works for me<sup>TM</sup>. Is it only with that graphic or everything?

**Comment by Monsterovich** [comment]
>everything

**Comment by sirjuddington** [comment]
Hmm, maybe your colorimetry settings are screwed up somehow? Could you post a screenshot of your colorimetry preferences page?

**Comment by Monsterovich** [comment]
>Hmm, maybe your colorimetry settings are screwed up somehow?
Yeah.

**Comment by Monsterovich** [comment]
I realised that slade just doesn't save these options.
http://www.zimagez.com/zimage/2016-07-2613-09-36.php
