### ISSUE TITLE
Slade removes copied resources by invalid checks

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#568]
**SLADE Version**: since you added option that checks for changes outside slade

**Issue Details**:

What I did:
1. I made duplicates of GHIT@0 http://www.zimagez.com/zimage/2016-07-2213-11-03.php
2. I  renamed/deleted my duplicates, slade tries to remove original GHIT@0 lumps again and again. http://www.zimagez.com/zimage/2016-07-2213-11-53.php

This bug is annoying.

**Comment by sirjuddington** [comment]
I can't reproduce this, did you delete the duplicates outside of slade?

**Comment by Monsterovich** [comment]
No, I did these actions in slade.
