### ISSUE TITLE
Line_SetPortal (special 156) lines should draw arrows for portal references

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#570]
http://zdoom.org/wiki/Line_SetPortal

I'm doing a project that makes extensive use of the recent-ish ZDoom portal functionality, in which a line can be a portal to another line. I'm spoiled on the handy lines SLADE draws for other line->line or line->sector references, and it's way harder to keep track of portals without these.

Specifically, any line with special 156 and Arg1 >0 should draw an arrow to the line ID with that number.

**Comment by Gaerzi** [comment]
This has been in since 25bcc17c9d686cd2bbcb5a8a4a6fb4135f792654.
