### ISSUE TITLE
Crash in renderPathedThings while deleting things in latest git master

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#573]
**SLADE Version**: latest git master
**Operating System**: Linux

**Issue Details**:
1. open any map with two or more InterpolationPoints in it
2. delete any thing
3. observe: SLADE crashes.

Seems related to drawing the arrow-lines that connect InterpolationPoints?

[slade3_crash_log.zip](https://github.com/sirjuddington/SLADE/files/392193/slade3_crash_log.zip)

**Comment by Monsterovich** [comment]
Can you record a video with doing this?

**Comment by JPLeBreton** [comment]
Okay, here's a video:
https://youtu.be/Xq8nxW2afiE
A few annotations to show what I'm doing.

**Comment by JPLeBreton** [comment]
Alternate steps to repro:
1. open Doom.wad E1M1 in map editor, with ZDoom set as the port used
2. place two InterpolationPoint things anywhere, such that a two-sided arrow line connects them
3. hover over any thing and press the delete key

**Comment by Monsterovich** [comment]
```C++
		Drawing::drawArrow(map->getThing(thing_paths[a].to_index)->getPoint(MOBJ_POINT_MID),
			map->getThing(thing_paths[a].from_index)->getPoint(MOBJ_POINT_MID),
			(thing_paths[a].type == PATH_DRAGON_BOTH || thing_paths[a].type == PATH_DRAGON) ? dragoncol : pathedcol, 
			(thing_paths[a].type == PATH_NORMAL_BOTH || thing_paths[a].type == PATH_DRAGON_BOTH), 
			arrowhead_angle, arrowhead_length);
```

**Comment by JPLeBreton** [comment]
Just sync'd and can confirm the crash is fixed, thanks! I'm noticing that the final InterpolationPoint in a path doesn't have an arrow pointing to it, though, which may be an unintended side effect of the fix. I can file that separately if desired.

**Comment by Monsterovich** [comment]
>I'm noticing that the final InterpolationPoint in a path doesn't have an arrow pointing to it

I just fixed the crash and added ignore condition for zero tids, because they wouldn't work anyway.
