### ISSUE TITLE
SCallTip.cpp regression: Tips with very long arguments don't work

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#574]
**SLADE Version**: since you upgraded TextEditorPanel

**Issue Details**:
Example: A_CustomPunch, A_SpawnItemEx (A_SpawnItem works fine :P)

**Comment by sirjuddington** [comment]
You mean it doesn't show at all or displays incorrectly? Works fine for me.

**Comment by Monsterovich** [comment]
>Works fine for me.

[video.zip](https://github.com/sirjuddington/SLADE/files/393411/video.zip)

**Comment by Monsterovich** [comment]
http://www.zimagez.com/zimage/2016-08-0218-49-59.php
