### ISSUE TITLE
possible memory leak in Slade 3.1.1.3

### ISSUE THREAD

**Issue by roidejaneiro** [sirjuddington/SLADE#580]
SLADE (3.1.1.3)
Windows 8

Details:

I think I detected some kind of memory leak. Im currently working on a very big map (about 40k vertices by now) in a pk3 file together with some custom textures, sounds etc.  When I open the map in the map editor Slade uses about 350mb of memory. When saving in the map editor (safe map changes) I see a huge increase of memory usage in the task manager. After the map is saved the used memory stays at ca. 900 mb. If i save again without changing anything the memory usage rises again but drops back to the before mentioned 900mb. But when I change some things in the map and then try to save again I get back to even more used memory. I can play that game until the used memory reaches 1500mb. Here the program displays an error. Klicking "ignore" lets me get back to the map editor but the map is not saved.

I captured a video of me producing the error. I hope it helps. 
https://youtu.be/9FYr0gWOrzo

 If you need it I can provide my pk3 too.

Greetings
Roi

**Comment by Monsterovich** [comment]
It seems that creating backup files takes a lot of memory by some reason.

**Comment by roidejaneiro** [comment]
Is there any way to disable backup?

**Comment by sirjuddington** [comment]
It's possible that the backup file for the map is getting too large, take a look in `C:\Users\<username>\AppData\Roaming\SLADE3\backups` for a zip file corresponding to the archive you're editing, how big is it?

To check if it is the backups, try setting `max_map_backups` to 0 in the console.

**Comment by sirjuddington** [comment]
I think this is probably the same issue as #739, i'll need to look at reworking some of the undo/redo stuff in 3.2.0. Closing this one
