### ISSUE TITLE
OpenGL Compilation Error

### ISSUE THREAD

**Issue by Danfun64** [sirjuddington/SLADE#586]
**SLADE Version**: (3.1.1.x) Stable branch commit: c9e57c277a0ecf5618147707ffa83a16fdd59aed
**Operating System**: Xubuntu 16.04.1 AMD64

**Issue Details**:
I updated my SLADE recently, as I often do, and I got an error in src/OpenGL/Drawing.cpp
I deleted my cloned repo and started over, but got pretty much the same error.

https://paste.debian.net/hidden/d498a0c8/

**Comment by sirjuddington** [comment]
Oops, try compiling again, should work now
