### ISSUE TITLE
Windows Defender detects virus, prevents download and installation of 3.1.1.3

### ISSUE THREAD

**Issue by ozbonus** [sirjuddington/SLADE#587]
**SLADE Version**: (3.X.X.x)
3.1.1.3
**Operating System**: (Windows/Linux/OSX)
Windows 10

**Issue Details**:
Windows Defender declares that the 7z and exe binaries contain viruses when using real time protection. 

![capture](https://cloud.githubusercontent.com/assets/9308425/17831344/ca78c8aa-6718-11e6-8c6f-e39eb6bf38ca.PNG)

![capture2](https://cloud.githubusercontent.com/assets/9308425/17831358/15ba6ad0-6719-11e6-8c3a-f1123ee05f05.PNG)

Forcing download and then requesting a scan with Windows Defender does not detect anything, nor does a meta-scan through virustotal.com.

**Comment by Blue-Shadow** [comment]
I got that, too, a few days ago. I'm suspecting a false positive, here. Malwarebytes Anti-Malware reports the archive and executable to be clean.

I put the executable on Windows Defender's exclusion list, so that it doesn't bother me about it.

**Comment by sirjuddington** [comment]
I'm not getting this at all, are your windows defender definitions up to date?

**Comment by Blue-Shadow** [comment]
For me, yes, always.

**Comment by Gaerzi** [comment]
Another report: 
https://www.doomworld.com/vb/doom-editing/90397-slade-windows-defender-threat/

**Comment by Blue-Shadow** [comment]
I just thought I should've mentioned the operating system I'm running: it's Windows 10 Home 64-bit Single Language version 1511. I have yet to upgrade to 1607 (Anniversary Update) due to my unstable, and majorly slow Internet connection.

**Comment by Gaerzi** [comment]
Another report: http://forum.zdoom.org/viewtopic.php?f=12&t=53354

**Comment by sirjuddington** [comment]
Not much I can do about it really, just windows defender being the useless piece of junk it always is.
