### ISSUE TITLE
Compare archives by their content, highlight different files

### ISSUE THREAD

**Issue by Doomer-** [sirjuddington/SLADE#588]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

Feature request: ability to compare archives (two open tabs) by their content, highlighting files which differ. Useful for comparing different release versions of the same wad for example.

Thanks in advance!

**Comment by sirjuddington** [comment]
Closing - could now be done by writing a script

Feel free to reopen the issue if needed
