### ISSUE TITLE
Allow mass file appending

### ISSUE THREAD

**Issue by Altazimuth** [sirjuddington/SLADE#590]
**SLADE Version**: All
**Operating System**: All

**Issue Details**:
Add a feature to mass append to files, like mass rename. This is useful for scenarios where you want a large group of files with varying lengths of names to all have the same ending (for example adding file extensions). With regular renaming it will extend all the shorter names with whitespace, then append.

For example let's say the files need to have .edf appended to the end:
- MYEDF
- MYEDF2
- MYEDF10

If we put in the rename box "MYEDF**.edf" then we get the following files:
- MYEDF  .edf
- MYEDF2 .edf
- MYEDF10.edf

This could be achieved either by making mass renaming append instead in these scenarios, or (likely easier) adding an "Append" option underneath "Rename Each", or "Rename".

**Comment by sirjuddington** [comment]
Closing - this could be done via script

Feel free to reopen the issue if needed
