### ISSUE TITLE
Opening Files screws up DPI scaling

### ISSUE THREAD

**Issue by AlexMax** [sirjuddington/SLADE#592]
**SLADE Version**: 3.1.1.3
**Operating System**: Windows

**Issue Details**:
I run 150% DPI settings on Windows. (That's good!)

Up until a recent release of SLADE, it didn't support high DPI. (That's bad!)

[SLADE 3.1.1.3 now supports high DPI](http://puu.sh/r1owY/087d76f7f6.png). (That's good!)

Unfortunately, [it completely jacks up when I open a file](http://puu.sh/r1oxn/fbd4070137.png). The text turns tiny, and the menu seems torn between small dimensions and large text. (That's bad)

**Comment by sirjuddington** [comment]
Hmm thought I had 'fixed' this (by disabling wx's retarded "high dpi support" which results in what you posted in the second screenshot). Maybe try toggling the 'Disable display scaling on high DPI settings' option in the SLADE.exe properties Compatibility tab.

I have been (slowly) working on some proper high DPI support, which might make it in for 3.1.2, whenever that is released.

**Comment by sirjuddington** [comment]
This should hopefully be fixed with https://github.com/sirjuddington/SLADE/commit/d17415194f31b9728469c22d5eb535d476e24c4a
