### ISSUE TITLE
Palette PNG Importing borked

### ISSUE THREAD

**Issue by DeathEgg** [sirjuddington/SLADE#597]
**SLADE Version**: (3.1.1.3)
**Operating System**: Windows 10

**Issue Details**:

Whenever I try to import a PNG file of a palette individually for each screen, the last five lines of the palette stay the same as the original palette that was there.

**Comment by Gaerzi** [comment]
Could you attach that PNG palette?

**Comment by DeathEgg** [comment]
![new bitmap image](https://cloud.githubusercontent.com/assets/2774893/18818846/53e242ce-8339-11e6-9199-715380ec90db.PNG)

It's the Wolfenstein 3D palette.
