### ISSUE TITLE
Map Editor: 2D Thing Preview Oddities

### ISSUE THREAD

**Issue by ElBaha** [sirjuddington/SLADE#601]
**SLADE Version**: 3.1.1.4
**Operating System**: Windows 10 Anniversary Update (64-bit)
**GPU**: Intel Iris Graphics 540
**GPU Driver**: Version 15.40.28.4501 

**Issue Details**:

I'm not terribly familiar with SLADE, so this may just be a misconfiguration issue. That being said, my Linux machine doesn't have issues, so this may just be a bug!

Effectively, in 2D Preview mode, Things like to just render as only a shadow, or disappear entirely, depending on zoom level and camera placement. 

At most zoom levels, my Things simply render as shadows, rather than faded (or full opacity) icons. 

![scr1](https://cloud.githubusercontent.com/assets/4324417/19025303/08aec9d8-88e5-11e6-926b-85b103df154c.png)
![scr5](https://cloud.githubusercontent.com/assets/4324417/19025309/3e645bf6-88e5-11e6-832d-a50b8bdfe71c.png)

Upon zooming in closer, opacities will change somewhat.

![scr2](https://cloud.githubusercontent.com/assets/4324417/19025334/90be1b1c-88e5-11e6-8d8e-3e1c9dc1c37a.png)

When zoomed in even further, Things are suddenly rendered correctly!

![scr7](https://cloud.githubusercontent.com/assets/4324417/19025364/d8c28448-88e5-11e6-8929-70ee5b460617.png)
![scr3](https://cloud.githubusercontent.com/assets/4324417/19025366/de41a4f8-88e5-11e6-836c-25016ad7e73a.png)

However, with certain camera adjustments, a Thing may disappear entirely...

![scr8](https://cloud.githubusercontent.com/assets/4324417/19025344/aa477948-88e5-11e6-9355-35a2295c44c6.png)

...and re-appear when the camera is adjusted once more.

![scr9](https://cloud.githubusercontent.com/assets/4324417/19025388/05163f76-88e6-11e6-9758-02f41f2a0946.png)

The renderer also does weird stuff if one hits the 'apply' button after changing map editor preferences, which may be unrelated.

![scr10](https://cloud.githubusercontent.com/assets/4324417/19025485/7886abd4-88e7-11e6-8346-bc20bffc7412.png)

Here's an archive containing a video of all of this happening live...

[BugVideo.zip](https://github.com/sirjuddington/SLADE/files/505375/BugVideo.zip)

...and another archive containing the little test map all of this has been happening on.

[Test1wad.zip](https://github.com/sirjuddington/SLADE/files/505377/Test1wad.zip)

If you need any more information, want me to test builds, or anything of the such, I'd be happy to provide!

**Comment by sirjuddington** [comment]
Yeah this is something I get too on my macbook pro. It's something to do with the intel drivers not liking what I'm doing to draw things (not sure if I'm doing something wrong, but it works fine on anything else).

To get around it you can either disable point sprites in the OpenGL options, or set thing shadow opacity to 0 in the thing display options.

**Comment by sirjuddington** [comment]
Closing - driver issue, can be worked around

Feel free to reopen the issue if needed
