### ISSUE TITLE
Entry Contents for Doom Graphics is off center

### ISSUE THREAD

**Issue by MadelineChumley** [sirjuddington/SLADE#602]
**SLADE Version**: (3.1.1.4)
**Operating System**: Windows 10 Pro, 64-bit
**Issue Details**:
Whenever I load a file and try to look at Doom Graphic, the Entry Contents display is shifted a bit upwards, which makes it difficult to display and edit.
![sladeissue2](https://cloud.githubusercontent.com/assets/19980177/19214219/b022a1dc-8d43-11e6-9502-89750076c792.png)

**Comment by SteelTitanium** [comment]
What's your GPU? It's not a problem with SLADE, but how your GPU handles OpenGL stuff on Windows 10, I know because on 10, my Intel X3100 would do the same thing, and not on Windows 7.

**Comment by MadelineChumley** [comment]
It's an "Intel(R) HD Graphics 3000."

**Comment by sirjuddington** [comment]
Try updating your video drivers if you can

**Comment by MadelineChumley** [comment]
Can't seem to be able to update my computer. On the bright side, I found out the graphics can appear normally if I open them separately in a new tab. Still have no idea why this is, but at least I have a workaround.
![sladeissueworkaround](https://cloud.githubusercontent.com/assets/19980177/19310973/2d341f0a-9052-11e6-9416-4d9852746012.png)

**Comment by sirjuddington** [comment]
Will close this one since it's an old one and i'd like to think still isn't an issue after this long
