### ISSUE TITLE
Recent Files bug and First Time Setup after launching bug

### ISSUE THREAD

**Issue by JustABroccoli562** [sirjuddington/SLADE#606]
**SLADE Version**: (3.1.1.4)
**Operating System**: (macOS El Capitan)

**Issue Details**:
When i open a ceratin wad, it's recent files won't be saved and it appears blank, and after opening this wad, if i close SLADE and open it back, The First time setup appears, resetting everything except Recent files and my input.
It's really annoying.

**Comment by Gaerzi** [comment]
Only a certain wad? What is its name and path, are there any exotic characters?

**Comment by sirjuddington** [comment]
Closing - no reply received

Feel free to reopen the issue if needed
