### ISSUE TITLE
Duke3D .ART file editor issues

### ISSUE THREAD

**Issue by StrikerMan780** [sirjuddington/SLADE#609]
**SLADE Version**: (3.1.1.4)
**Operating System**: (Windows)

**Issue Details**:
It seems when you resize the SLADE window or change to different .ART files, the arrow buttons for scrolling through the tiles disappear. This makes editing .ART files a real pain.

Also, this is more a suggestion than an issue, but could a side-panel allowing you to quickly scroll through .art tiles in a list be added? (Kind of like in the TEXTURES editor.) Perhaps each tile can have a small thumbnail and the corresponding build engine tile number.

**Comment by sirjuddington** [comment]
The multi-image controls have been changed so the first part shouldn't happen, and the second request is something I have on the radar to do, perhaps for 3.2.0 (along with being able to select multiple gfx entries and seeing them all as thumbnails, etc.)
