### ISSUE TITLE
crash after viewing a few sprites in the attached wad file

### ISSUE THREAD

**Issue by anotak** [sirjuddington/SLADE#610]
**SLADE Version**: (3.1.1.4)
**Operating System**: Windows 10

**Issue Details**:
Scrolling through sprites in this wad crashes SLADE when viewing, but only some of the time. The sprite data is sort of corrupted-looking  (er, it was sort of intentional), but it should be within the spec unless I missed something? but SLADE appears to crash after viewing a few of them (but not consistently). No issues in zdoom or gzdoom or doom builder. The precise crash varies, sometimes it's a simple thrown exception (and I've sent the autoreporter). Other times I just get "SLADE has stopped working", other times I get the autoreporter window constantly reopening before I can click anything (it says "opengl error" or something like that when this happens?). Other times it just silently closes with no message at all.
This may be related, but I'm using a high DPI setting in windows 10 and when I open a wad file slade decides to resize itself and ignore the OS DPI settings but only once I open a wad file.

[a_g_rsrc.zip](https://github.com/sirjuddington/SLADE/files/568104/a_g_rsrc.zip)

**Comment by anotak** [comment]
to clarify i don't encounter this issue scrolling through sprites in doom2.wad

**Comment by anotak** [comment]
after further investigation, yes, they're invalid sprites (an FF is at the end of every "pole" causing extra columns), and they do crash doom builder as well as slumped and xwe. however they don't crash zdoom at all.

**Comment by sirjuddington** [comment]
Hmm, perhaps they are using the 'tall columns' technique which SLADE doesn't support yet (see #235), though I didn't think they caused a crash.
