### ISSUE TITLE
Script Editor feature

### ISSUE THREAD

**Issue by JustABroccoli562** [sirjuddington/SLADE#612]
It would have been nice if script editor was added to SLADE 3.
I make maps on SLADE 3 and i don't like the lack of script editor here.
It would have been easier to script stuff.
There should be languages to choose and all that.

**Comment by sirjuddington** [comment]
SLADE's map editor does have a script editor (ACS only for now) - 'Script Editor' in the 'View' menu.

**Comment by Gaerzi** [comment]
Ideally it should be possible to have several scripts for a single map. It's certainly possible in ZDoom (even if not necessarily useful) to have both FraggleScript and ACS; and you can always add USDF/ZSDF to the mix.
