### ISSUE TITLE
Windows 10 Issues

### ISSUE THREAD

**Issue by MrDrSushi** [sirjuddington/SLADE#613]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows)

**Issue Details**:
Im using Win 10 Pro and menus on Slade aren't showing correctly, doesn't matter the font/screen size, menus are shown cropped and uneven with characters spaced and/or incomplete.

Another constant issue is window dimensions, it flips flops without any logic, if you already have it opened on the centre of your desktop and decides to open up a new wad file, the current window will flip to a new position with new dimensions.

Suggestion: could we have a feature to always remember the windows dimensions on every run? So when you open your slade it will always start from the last known coordinates and using the last known dimensions.

**Comment by sirjuddington** [comment]
SLADE does remember the window positions normally, this sounds like a DPI scaling issue - are you using a DPI scale over 100%?

**Comment by aagons** [comment]
Precisely right! I can't remember exactly the settings but I believe it's 150% - all I have is a big 4K monitor and resolution wise it's necessary otherwise it is impossible to read any text displayed.

Is it possible to have slade working flawlessly under this settings?

And last but not least, thanks for clarifying about the window position settings! Would it be possible to have this option in the near future?

**Comment by sirjuddington** [comment]
For now, try changing the 'Disable display scaling on high DPI settings' in the compatibility options for SLADE.exe (set it to whatever it isn't currently).

I have been working on some fixes for high DPI stuff (see [high_dpi branch](https://github.com/sirjuddington/SLADE/tree/high_dpi)) which should fully correct the issue, however they won't likely be in an official release for a while yet.

**Comment by aagons** [comment]
I'm back to the same question, I couldn't find anywhere the option, where do I go to find it? There is nothing in preferences, sorry to bother again on this silly question but I couldn't find it

**Comment by Gaerzi** [comment]
It's not in SLADE's own preferences; its [directly in Windows](https://technet.microsoft.com/en-us/library/ff629368.aspx)

> To do this, right-click the application’s shortcut and then click Properties. On the Compatibility tab, select Disable Display Scaling On High DPI Settings, and then click OK.

**Comment by sirjuddington** [comment]
Closing - possibly resolved

Feel free to reopen the issue if needed
