### ISSUE TITLE
Slade 3 icons does not show

### ISSUE THREAD

**Issue by NotMarioHead** [sirjuddington/SLADE#618]
SLADE Version: 3.1.1.4
Operating System: Windows 10
Issue Details:
As you can see in the image, all the slade icons are not showing, what i can do?

![iconsnotshowing](https://cloud.githubusercontent.com/assets/24209676/20649905/ab9f4994-b4a8-11e6-9560-385b8e142071.PNG)

**Comment by Gaerzi** [comment]
Open the console and look at error messages in it. I suspect there's an access right issue in the temporary folder.

**Comment by sirjuddington** [comment]
Closing - no reply received

Feel free to reopen the issue if needed
