### ISSUE TITLE
"Scroll-lag" with touchpad (MacBook Air)

### ISSUE THREAD

**Issue by Ace83** [sirjuddington/SLADE#620]
**SLADE Version**: 3.1.1.4 (I think, at least the file is last modified 26th of sep 2016)
**Operating System**: OSX

**Issue Details**:
Whenever I scroll in a menu there's a 1-2 second "pause" before anything happens. So, the touchpad appears a bit quirky although there are no problems in other programs. I always have to use arrow keys to navigate properly, which make the workflow a bit slow.
Edit: This issue is not appearing in all menus. It seems like it happens only in, for instance, the preference menu and the texture browser.

**Comment by sirjuddington** [comment]
Closing this issue since it's old and no one else reported it. If it still happens in the latest version feel free to reopen it
