### ISSUE TITLE
Properties window bug

### ISSUE THREAD

**Issue by Ace83** [sirjuddington/SLADE#622]
**SLADE Version**: 3.1.1.4 (I think, at least the file is last modified 26th of sep 2016)
**Operating System**: OSX

**Issue Details**:
The properties window is missing the Ally/Friendly feature in UDMF (ZDoom port) and the angle selections are out of view (no matter how I resize the window). [Screenshot](http://sv.tinypic.com/r/20psc5v/9)

**Comment by Gaerzi** [comment]
The missing UDMF properties have been added with 700034363271e04979cca1538d0b600d8160ecfa. The angle selector is the real issue, apparently Mac-specific.

**Comment by sirjuddington** [comment]
This should be fixed as the angle selector is a custom-drawn control now
