### ISSUE TITLE
Textures editor issue

### ISSUE THREAD

**Issue by GeekZolda** [sirjuddington/SLADE#624]
**SLADE Version**: (3.1.1.4)
**Operating System**: (Windows 10)

**Issue Details**:

Whenever I use the "textures" editor, the textures.txt file comes out all messed up, 

Here's a few exemples : 

Sprite "GLOCA0", 119, 150
{
	YScale 1.200
	Offset -134, -53
	Patch "GLOCA0", 0, 0
}

Becomes : 

Sprite "GLOCA0", 119, 150
{
	Offset -134, -53
	Patch "GLOCA0", 0, 0
}

Sprite "BBATC0", 472, 384
{
	XScale 1.900
	YScale 2.100
	Offset -65, 28
	Patch "BBATC0", 0, 0
}

Becomes : 

Sprite "BBATC0", 472, 384
{
	YScale 2,000
	Offset -65, 28
	Patch "BBATC0", 0, 0
}

It's a really strange issue and it's making my life a nightmare. Any idea what might cause it ?

**Comment by GeekZolda** [comment]
Oh, using the power of my weak ass brain, I found the source of the problem, the decimal separator. I'm on a french pc, so it tried looking for "," commas instead of "." and it always fudged up the txt file.

Is there anyway Slade can enforce use of the "." instead of the comma ?

**Comment by sirjuddington** [comment]
I'm going to close this one because it's likely fixed in 3.2.0 - it uses fmt to format strings rather than wxWidgets. If it is still a problem in 3.2.0 feel free to reopen
