### ISSUE TITLE
CMakelists.txt maybe missing definition.

### ISSUE THREAD

**Issue by Catoptromancy** [sirjuddington/SLADE#627]
**SLADE Version**: (3.1.2.alpha), current repo
**Operating System**: (Linux, Debian 8.6)

**Issue Details**:
Many similar errors when compling:
`error: â€˜nullptrâ€™ was not declared in this scope
  UDMFPropMap* map = nullptr;`

Adding this line on line 32 of src/CMakelists turns errors into warnings.
`add_definitions(-std=c++11)`

Slade does compile with many warnings, but editing CMakelists should not be needed.

**Comment by Monsterovich** [comment]
For me slade won't compile without such flags:

cmake .. -DNO_FLUIDSYNTH=1 -DNO_COTIRE=0 -DCMAKE_CXX_FLAGS=-std=c++0x
