### ISSUE TITLE
Compiler warnings without an error are not displayed

### ISSUE THREAD

**Issue by DavidPH** [sirjuddington/SLADE#630]
GDCC (and possibly other compilers now or in the future) has the ability to issue compiler warnings written to stderr. However, if the compilation is otherwise successful, these are not shown to the user. Given the unusual variety of exit conditions being handled, this might require an extra option when selecting the compiler in Slade to always display the program output?

**Comment by sirjuddington** [comment]
Hmm, it should already output stderr to the console when compiling, but I guess I can add an option to always show compiler output in the pop up window even if compilation was successful.
