### ISSUE TITLE
Saving without nodes

### ISSUE THREAD

**Issue by Catoptromancy** [sirjuddington/SLADE#631]
**SLADE Version**: (3.1.2.alpha)
**Operating System**: (Linux)

**Issue Details**:
There should be an option to save without building nodes. The drop-down list of nodebuilders in the dialog should also have a "None" option.

Saving also brings up the nodebuilder dialog everytime. Setting a nodebuilder should be in the preferences, not something that requires input every time a map is saved. 

Related and still an issue, I am now using an entirely different linux distro.
http://mancubus.net/forums/index.php/topic,3321.0.html

I also like saving without nodes anyway, I have several megawads in a zip at 1mb. None of the maps are saved with nodes. 

Nodeless is also a great quick-save feature. To ensure map progress is not lost, a nodeless save would be very quick. Nodes are not needed for quick-saves. There is no testing, just saving.

**Comment by jmickle66666666** [comment]
Saving without a nodebuilder is definitely a handy feature, there are a number of reasons why it would be handy.
