### ISSUE TITLE
Crash!!!

### ISSUE THREAD

**Issue by AntonZab** [sirjuddington/SLADE#633]
SLADE Version: (3.1.1.4)
Operating System: (Windows XP SP3)

Issue Details:
32-bit Microsoft Visual Studio 2015 Runtimes (x86) Installed but
Slade Editor Not loading/ Gives crash
![445](https://cloud.githubusercontent.com/assets/10308177/21744316/4b0c8818-d52c-11e6-9334-aceec012fd9c.JPG)
The entry point in the procedure could not be found

**Comment by alexey-lysiuk** [comment]
Looks like this version was built without Windows XP support. It will run only on Vista and newer.

**Comment by sirjuddington** [comment]
Yeah it has been since 3.1.1.3 I think, I know why now so hopefully 3.1.1.5 will run in XP just fine.
