### ISSUE TITLE
Can you help to assemble all translations from the "Colourise" command

### ISSUE THREAD

**Issue by Tomasm21** [sirjuddington/SLADE#638]
**SLADE Version**: 3.1.1.4
**Operating System**: Windows 10 Pro

**Issue long text to better understand what I want**:
Hello. I'm mapper and scripter for both zdoom and zdaemon. Right now I'm working on zdaemon huge map and creating a map for archinvasion LA project.
I want to make something new and unusual for the team. Inside the game all online players try to survive from attacking 500 archviles. 
I'm planning to change the color of some archviles. And because this is ZDaemon which is very old version of zdoom it doesn't have DECORATE. 
So I cannot create new actors that would inherit all archvile features but use new coloured skins. I can't save all archvile states between S_Start and S_End.
Also zdaemon cannot use saturated colors nor RGB style colors (not sure for this). Probably only Doom2 palette. 

All I want to do is to change archvile body skin color using  https://zdoom.org/wiki/CreateTranslation, >>  void CreateTranslation(int transnumber, a:b=c:d, ...);

I have already done it but I'm not satisfied with the result:
![f9d2e17b93d8](https://cloud.githubusercontent.com/assets/25200026/22065749/46b0516e-dd92-11e6-8360-251c90a21e71.png)

Some pixels still contain old archvile original colors. And manually it's almost impossible to affect all needed to translate colors. Furthermore when various states of the same actor iterate then there are even more colors. But they are similar.
Currently I have changed colors with the help of slade's "Colour remap" manually: http://pastebin.com/XNyn4YXx

I think I will do this again if you will be kind enough to help me to fully see all translations. In zdaemon it's the only way to achieve different color.

In Slade (1.3.3.4) there are commands  like "**Colour remap**" and the "**Colourise**". The "Colour remap" has helped me to do this initial color change and to see the result. But it's not enough. Result is not excellent.
The excellent result is achieved when using "**Colourise**". It changes colours differentially and attach same 256 color palette. The result is breathtaking. It's like completely another color archviles: 
![archviles_colored2](https://cloud.githubusercontent.com/assets/25200026/22065882/e5271de6-dd92-11e6-8b6b-f85e0b0b8c0b.png)

I want to see this inside zdaemon after using "_CreateTranslation(int transnumber, a:b=c:d, ...);_ "
Only I need to know what color indexes changed into what. When I switch these "colourised" images to colour remap then
all of them have appropriate index color from Doom2 palette. 

Feature request: **Can you be so kind and enrich "Colourise" tool with the log table where it is written what palette colors changed into what**. Perhaps also ranges like "48:61" or something similar.
If this is impossible for you to do then:

How to recolor archvile fastly and efficiently without leaving any old colors in some pixels?

Maybe someone else can help me to achieve high quality result?

**Comment by Aeyesx** [comment]
I am givíng this thumb up.
The colorizing is pain sometimes and Colourise works very well. It would be awesome if there was **exception** to ignore some colors from recolor.

Also Mvice/Tomas,

> So I cannot create new actors that would inherit all archvile features but use new coloured skins. I can't save all archvile states between S_Start and S_End.

This is not a true, you can create as many archviles you wan't using separated sprites without decorate ))

**Comment by Gaerzi** [comment]
Hey!

![sladerecolor3](https://cloud.githubusercontent.com/assets/4178859/23580680/75dd3afa-0106-11e7-91b4-4fee5cf51abd.png)

Basically I've improved the colour remap feature to integrate colourise and tint; and I've added a checkbox to force it to create plain palette translation -- they'll work in ZDaemon if ZDaemon can handle translations made of several different ranges, because there's a lot of ranges for a colourised translation, sometimes you get only one or two colors in a range, so to cover all 256 colors of the palette... For instance, the yellow archvile from your picture (I've used the eyedropped to get the exact same color) is made up of 199 ranges and represents a text string of 3365 characters.

**Comment by Aeyesx** [comment]
HOLYYY!!! GREAT JOB GAERZI!! Super-uber well done! Appreciated! This saves a lot of work!

There are 2 ways to use these,
1) You can modify sprites with it effectively and in a best way pallete allows
2) You can use these ranges and save them into a .TXT which you can use in ACS to directly recolor enemies  in-game!

This is excelent, really big thanks for this.

**Comment by Tomasm21** [comment]
Awesome. Thank you very much. Let's wait for the next release. 3.12 or 3.1.1.6? Currently 3.1.1.5 at this date. But if the string consists of 3365 characters then it doesn't sound so good. I doubt whether it would work or will be accepted. Maybe then I'll add new sprites. We'll see.

**Comment by Gaerzi** [comment]
Well, keep in mind you probably don't need to colourise the entire palette for the archvile, which is mostly in the light tan range, so you could optimize a bit to reduce the size of the resulting translation. For VILEA1D1, I could get it down to "just" 59 ranges and 994 characters! :stuck_out_tongue_closed_eyes: 

As for the next release, I don't know, @sirjuddington decides that.

**Comment by Aeyesx** [comment]
In theory its possible just to download the source and compile it right? The range doesn't really matter, it could be put into separate .txt file that is loaded as translation table...

**Comment by Tomasm21** [comment]
I have compiled latest alpha and have seen this new feature. It's great and everything works both in zdoom and zdaemon. Even though range list is long but it is still accepted and works well. Thank you very much SLADE team.
