### ISSUE TITLE
Crash when deleting Things

### ISSUE THREAD

**Issue by Xymph** [sirjuddington/SLADE#641]
**SLADE Version**: 3.1.1.5 and .4
**Operating System**: Windows 7

**Issue Details**:

I use Slade mainly to crop maps down to the areas needed for DoomWiki map views.

Usually this works fine, but [Daedalus MAP01](https://doomwiki.org/wiki/Daedalus:_Alien_Defense) causes Slade to crash when attempting to delete the PolyObject Anchors in the north. Drag-selecting them and hitting Del crashes, deleting them one by one crashes too (at the second one). The same goes for the Interpolation Points in the southern playable area. Prior to the anchors, deleting misc. other things in other control sectors went fine. I've submitted a bunch of crash reports via Slade for this. v3.1.1.4 crashes too.

Strictly speaking I don't need to delete Things for map views (only Linedefs), but when a crash happens I lose some effort and time, which is annoying. So I hope this can be fixed prior to the big 3.1.2 update.

**Comment by sirjuddington** [comment]
Does this still happen for you in 3.1.2 beta? I can't reproduce it there.

**Comment by Xymph** [comment]
Nope, no crash. If you didn't specifically address it, I suppose it was magically fixed by other work done in the beta so far. Gotta love magic fixes. 😉
Thanks.
