### ISSUE TITLE
Graphic preview in grayscale

### ISSUE THREAD

**Issue by Xymph** [sirjuddington/SLADE#642]
**SLADE Version**: 3.1.1.5
**Operating System**: Windows 7

**Issue Details**:
When previewing graphic lumps in the WAD directory, types like PNG & BMP are shown in color. But types "Graphic (Doom)" and "Graphic (Flat)" are in grayscale. It would be helpful if they can be displayed in color too.

I'm not sure whether this is a FAQ, but I searched open & closed issues and nothing obvious came up.

**Comment by Gaerzi** [comment]
Typical result of not having selected a base resource archive. SLADE looks for palette in this order, IIRC:
1. Palette from palette chooser (if not "existing/global")
2. Palette from current archive
3. Palette from base resource archive
4. Grayscale palette as a fallback

**Comment by Xymph** [comment]
Thanks! :+1:
