### ISSUE TITLE
 Support Flats with size of 32x32 Or Other Non Power-Of-Two Images.

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#645]
**SLADE Version**: (3.1.1.5)
**Operating System**: Windows

**Issue Details**:
When I try to convert a 32x32 flat to doom flat, it's gets resized, cropping half of the image, an option to allow converting of 32x32 flats and smaller powers of 2 flats would be nice.

**Comment by Gaerzi** [comment]
Does #649 address this or is there further work to be done for it?

**Comment by SteelTitanium** [comment]
It indeed does address this.

**Comment by SteelTitanium** [comment]
After doing some more testing, even with #649, it indeed tries to resize 32x32 flats. 
![ss 2017-02-01 at 03 26 36](https://cloud.githubusercontent.com/assets/9903201/22524972/61c60bf4-e893-11e6-805a-168357aab662.png)

**Comment by Gaerzi** [comment]
That's what I thought. You'll want to update the [valid_flat_size array](https://github.com/sirjuddington/SLADE/blob/master/src/Graphics/SImage/SIFormat.cpp#L211..L235) in Graphics\SImage\SIFormat.cpp. When you try to convert an image of a size it doesn't recognize, it falls back to the last smaller dimensions. So for example with 32x32, it goes through 2x2, 10x12, 16x16, and then arrive at 32x64, which is bigger than your 32x32, so fall back to 16x16. You'll see this logic in [convertWritable()](https://github.com/sirjuddington/SLADE/blob/master/src/Graphics/SImage/SIFormat.cpp#L449..L457).
