### ISSUE TITLE
Copying and pasting files in directory mode immediately deletes original

### ISSUE THREAD

**Issue by StrikerMan780** [sirjuddington/SLADE#652]
**SLADE Version**: (3.1.1.5)
**Operating System**: (Windows)

**Issue Details**:
When working with directories, and you copy an entry and paste it, (EDIT: Then rename the new entry) the original copy of the file gets deleted from the hard disk immediately, without the user even saving. I nearly lost work permanently because of this bug, it's severe.

**Comment by sirjuddington** [comment]
I can't reproduce this one at all, and it really shouldn't ever happen as SLADE will not touch anything on disk until you save the directory.

**Comment by StrikerMan780** [comment]
Try renaming the duplicate entry.

**Comment by Gaerzi** [comment]
Filesystems do not tolerate duplicate file names, whereas archives do (even zip files!). SLADE misses some logic to catch when a dir entry (so, a file) being pasted, created, or renamed is given the name of an already existing file in the same dir.

**Comment by XaserAcheron** [comment]
It seems sirjuddington has confirmed this elsewhere given the tag/milestone change, but just in case: I get this when doing something as innocuous as copying a file from folder A and pasting it into folder B -- the files vanish from A. I'm using Windows 7 in case this is relevant.

[Fortunately on my side, my entire use case for directory-mode is developing a mod stored in a Git repo, so I've been able to `git checkout` the missing files right afterward, but yeah, still shouldn't happen. :P ]
