### ISSUE TITLE
No textures in map editor

### ISSUE THREAD

**Issue by alexey-lysiuk** [sirjuddington/SLADE#655]
It seems like abd0ea5 broke loading of textures in the map editor. I'm pretty sure that c4e788b was fine.
For example, all textures are missing after opening MAP01 from `doom2.wad`. The base resource WAD is set correctly.
I tried on macOS only but it's hardly a platform-specific issue.

**Comment by fluffymormegil** [comment]
Hi. This bug, or something akin to it but with different causation, seems to have reappeared.

I built 8c4d70ee on my Linux system and everything _runs_, and I've got one of the official IWADs specified as the base resource, but when I go into edit a map, the map editor can't find any of the wall textures, only the flats.

**Comment by Gaerzi** [comment]
You should open a new issue.
