### ISSUE TITLE
More Map Checks 

### ISSUE THREAD

**Issue by Catoptromancy** [sirjuddington/SLADE#660]
SLADE Version: (3.1.2.alpha)
Operating System: (Linux) Debian 8.7

**Feature Request**
Map Checks should also check for Unknown Sector Specials and Unknown Linedef types. 

"Missing tags" does not seem to be working, or it does something else. A sector/line tagged without another sector/line tag should be considered missing tag.

**Comment by sirjuddington** [comment]
The missing tags check is for lines with a special that requires a tag, but have no tag set
