### ISSUE TITLE
Dragging linedefs or vertices in ways that trigger automatic linesplitting etc. sometimes causes a hang

### ISSUE THREAD

**Issue by fluffymormegil** [sirjuddington/SLADE#664]
**SLADE Version**: 3.1.2 alpha
**Operating System**: Linux

**Issue Details**:
Sometimes, when I drag level geometry into a new position, SLADE's map editor appears to get stuck in an infinite loop when trying to adjust vertices, create sectors, etc. in response to the geometry change.

I will try and find a reproducible test case.

**Comment by sirjuddington** [comment]
Closing - no reproducible test case given (i'd assume it's pretty random - a bit hard to do anything about unfortunately)

Feel free to reopen the issue if needed
