### ISSUE TITLE
Using SLADE to create folders in ZIP or directory archives breaks something causing a subsequent crash

### ISSUE THREAD

**Issue by fluffymormegil** [sirjuddington/SLADE#673]
**SLADE Version**: 3.1.2 alpha cc26950e (and at least some earlier commits)
**Operating System**: Linux

**Issue Details**:
When editing a ZIP or directory archive, using SLADE's internal folder creation button to create a new folder in the archive places SLADE in an incoherent state of some kind, such that subsequently saving the archive reliably causes SLADE to crash.

**Comment by Gaerzi** [comment]
I believe this is fixed by e3e8bdbf75bb97bed630fd254bca63be86619619 ; feel free to reopen if it isn't.
