### ISSUE TITLE
Tries to read everything as music. . .

### ISSUE THREAD

**Issue by hoosieraussie** [sirjuddington/SLADE#685]
**SLADE Version**: (3.1.1.5)
**Operating System**: (Windows)

For whatever reason Slade is reading almost everything as being music types instead of what they really are. Anyone know what's causing this/how to fix this?

![image](https://cloud.githubusercontent.com/assets/26257426/23670415/d7df4cc8-0324-11e7-8e96-9dc093d90ef1.png)

**Comment by Gaerzi** [comment]
This can happen when there are bugs while parsing the entry type configuration files. Your slade.pk3 or res folder is mismatched or corrupted, make a clean reinstall of SLADE 3 and that should disappear.

**Comment by hoosieraussie** [comment]
I've tried reinstalling three times now, and the issue's still there. . . :\

**Comment by Gaerzi** [comment]
Do you get any error message in the console?

**Comment by hoosieraussie** [comment]
Quite a few, it appears:

21:01:34: Warning: Entry type mus requires undefined format mus
21:01:34: Warning: Entry type midi requires undefined format midi
21:01:34: Warning: Entry type xmi requires undefined format xmi
21:01:34: Warning: Entry type hmi requires undefined format hmi
21:01:34: Warning: Entry type hmp requires undefined format hmp
21:01:34: Warning: Entry type gmid requires undefined format gmid
21:01:34: Warning: Entry type imf requires undefined format imf
21:01:34: Warning: Entry type snd_spc requires undefined format snd_spc
21:01:34: Loading text languages
21:01:34: Loading text style sets
21:01:34: Loading colour configuration
21:01:34: Icon "logo" does not exist
21:01:35: Icon "archive" does not exist
21:01:35: Error: Couldn't add an image to the image list.
21:01:35: Icon "wad" does not exist
21:01:35: Error: Couldn't add an image to the image list.
21:01:35: Icon "zip" does not exist
21:01:35: Error: Couldn't add an image to the image list.
21:01:35: Icon "folder" does not exist
21:01:35: Error: Couldn't add an image to the image list.
21:01:35: Icon "wad" does not exist
21:01:35: Icon "zip" does not exist
21:01:35: Icon "wad" does not exist
21:01:35: Icon "wad" does not exist
21:01:35: Icon "wad" does not exist
21:01:35: Icon "zip" does not exist
21:01:35: Icon "zip" does not exist
21:01:35: Icon "zip" does not exist
21:01:35: Icon "newarchive" does not exist
21:01:35: Icon "newzip" does not exist
21:01:35: Icon "mapeditor" does not exist
21:01:35: Icon "open" does not exist
21:01:35: Icon "opendir" does not exist
21:01:35: Icon "save" does not exist
21:01:35: Icon "saveas" does not exist
21:01:35: Icon "saveall" does not exist
21:01:35: Icon "close" does not exist
21:01:35: Icon "closeall" does not exist
21:01:35: Icon "exit" does not exist
21:01:35: Icon "undo" does not exist
21:01:35: Icon "redo" does not exist
21:01:35: Icon "archive" does not exist
21:01:35: Icon "settings" does not exist
21:01:35: Icon "archive" does not exist
21:01:35: Icon "console" does not exist
21:01:35: Icon "undo" does not exist
21:01:35: Icon "wiki" does not exist
21:01:35: Icon "logo" does not exist
21:01:35: Icon "newarchive" does not exist
21:01:35: Icon "newzip" does not exist
21:01:35: Icon "open" does not exist
21:01:35: Icon "opendir" does not exist
21:01:35: Icon "save" does not exist
21:01:35: Icon "saveas" does not exist
21:01:35: Icon "saveall" does not exist
21:01:35: Icon "close" does not exist
21:01:35: Icon "closeall" does not exist
21:01:35: Icon "newentry" does not exist
21:01:35: Icon "newfolder" does not exist
21:01:35: Icon "importfiles" does not exist
21:01:35: Icon "texeditor" does not exist
21:01:35: Icon "mapeditor" does not exist
21:01:35: Icon "run" does not exist
21:01:35: Icon "rename" does not exist
21:01:35: Icon "delete" does not exist
21:01:35: Icon "import" does not exist
21:01:35: Icon "export" does not exist
21:01:35: Icon "up" does not exist
21:01:35: Icon "down" does not exist
21:01:35: Icon "settings" does not exist

**Comment by Gaerzi** [comment]
Yeah, the formats are left undefined, and it doesn't find any icons. SLADE needs the content of [this directory](https://github.com/sirjuddington/SLADE/tree/master/dist/res) zipped in a file named slade.pk3. For whatever reason, the resource file (or directory) is missing several components. That's why I suggested a clean reinstall.

If you have a folder named res in the directory where you're putting SLADE, delete it (or install SLADE in another directory). For making development easier, SLADE prioritizes a res folder over a slade.pk3 when it exists.

**Comment by hoosieraussie** [comment]
I reinstalled it in a different location and it's working now! Thanks a million!

**Comment by Gaerzi** [comment]
Alright.
