### ISSUE TITLE
Issue with parsing of comments in decorate

### ISSUE THREAD

**Issue by alexey-lysiuk** [sirjuddington/SLADE#686]
**SLADE Version**: [the current master](https://github.com/sirjuddington/SLADE/commit/d2653d6e39af6aa12a2816f859e1db1faa572991)
**Operating System**: all

**Issue Details**:
Token and comment without white space between them are parsed as the single token.
*ZDoom handles them correctly however.

Here is the sample decorate:
```
actor test : clip 2300//
{
}
```
In this case DoomEdNum will be parsed as `2300//`.

A particular combination of decorate definitions can even cause an infinite loop.
For example, maps from [Vulcan Episode 1](https://forum.zdoom.org/viewtopic.php?t=55439) cannot be opened because of this.

**Comment by alexey-lysiuk** [comment]
The problem with Vulcan is the mentioned usage of comments without white space(s) before them.
This breaks decorate parser and finally it enters infinite loop in old decorate branch: there is no tokens left and there is no check for such bad definition.

**Comment by Gaerzi** [comment]
Infinite loop fixed.
