### ISSUE TITLE
Permanent rebuild via Xcode

### ISSUE THREAD

**Issue by alexey-lysiuk** [sirjuddington/SLADE#687]
**SLADE Version**: [the current master](https://github.com/sirjuddington/SLADE/commit/d2653d6e39af6aa12a2816f859e1db1faa572991)
**Operating System**: macOS

**Issue Details**:
The latest version is rebuilding on each run when Xcode project was used as generator target in CMake.
Precompiled (prefix) headers are always out of date effectively invalidating previous build a whole.

My investigation shown that it started with [this commit](https://github.com/sirjuddington/SLADE/commit/67acce99674e833bb51f795f6a3fd3ca230f8a77).

It's enough to revert moving of the following lines from the mentioned commit to make Xcode happy again:
```
if (NOT NO_COTIRE)
	set_target_properties(slade PROPERTIES COTIRE_CXX_PREFIX_HEADER_INIT "common.h")
	cotire(slade)
endif()
```
At the moment I cannot check on other platforms but working with source code on macOS is apparently broken because of this.

**Comment by Gaerzi** [comment]
Can you or @matthew-mcallister make a PR for that? I don't feel confident fussing around with CMake stuff.

**Comment by alexey-lysiuk** [comment]
Sure I can. However like I said I cannot test this change on other platforms right now. I'm not sure that it won't introduce the same problem there.

**Comment by alexey-lysiuk** [comment]
This looks like a problem with Cotire: building via `make` is working fine but Xcode project is rebuilding (including prefix headers) on every build/run.
There are explicit prefix header options for Xcode in `src/CMakeLists.txt` but their removal didn't change anything.

**Comment by matthew-mcallister** [comment]
Since there are already precompiled headers set manually for xcode, does it make sense to just disable cotire when using xcode? All it would add is a unity source file, which I just found out isn't even getting used by make.

**Comment by alexey-lysiuk** [comment]
I would like to investigate this first. Disabling Cotire is one of the options taking into account that unity is also broken (with Xcode at least).
