### ISSUE TITLE
TEXTURES editor confuses blend with tint

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#693]
**SLADE Version**: (3.1.1.5)
**Operating System**: Windows 10 Professional Anniversary

**Issue Details**:

1. [Download D4D.pk3 (doesn't matter which) and D4DResources.pk3](https://forum.zdoom.org/viewtopic.php?f=43&t=54843)
2. Open up the D4D.pk3 and load D4DResources.pk3 as a base archive.
3. Click on Textures.AED file and look at the first couple of definitions. You'll see they have **Blend** as their mode of translation, like so:

```
Sprite X202C0, 125, 125
{
	Offset 62, 62
	Patch X202B0, 0, 0
	{
		Blend 255, 128, 64, 1.0
	}
}
```

4. Open the texture editor (you'll have to click on the TEXTURES.font tab and then click back to TEXTURES.AED because it's glitchy) and click on X202C0.
5. Click on the patch X202B0. 

Bug: Notice that it confuses **Tint** with **Blend**, which is wrong.

**Comment by Gaerzi** [comment]
Is it wrong? I'll need more information in how exactly it is wrong. Because, [quoth the wiki](https://zdoom.org/wiki/TEXTURES#Patch):

> ``Blend <int r>,<int g>,<int b>[,<float alpha>]``
>
>  This statement has two different effects depending on how it is used:
>  Specifying a color string and omitting the alpha parameter creates a custom colormap to translate the image to. This has the same effect as using Sector_SetColor, but applies the coloring directly to this patch.
>   **If an alpha is supplied with the color, this blends a solid color into the patch, akin to screen tinting.**

Emphasis mine. The above sentence is the only instance of "tint" in the entire article.

When I look at this, from your example:
``Blend 255, 128, 64, 1.0``
I distinctly count four parameters, the last one being an alpha value. Which means that the effect is "akin to tinting". Which, as it turns out is exactly what SLADE calls a tint.

**Comment by Gaerzi** [comment]
Now there is a thing that looks like a bug, it's that the r, g, b format is badly read. It's multiplied by 255 as if it were written on a 0.0-to-1.0 scale, even though it's already on a 0-to-255 scale, and then forced back to an 8-bit int. There's an amusing mathematical property where, for x in range from 0 to 255, (x*255)%256 = 256-x, so every channel is inverted.

**Comment by MajorCooke** [comment]
That could have been it, but I won't know until the next release.
