### ISSUE TITLE
Respect DoomEdNums defined in MAPINFO

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#694]
**SLADE Version**: latest/all
**Operating System**: all

**Issue Details**:

Issue #440 is an umbrella issue which contains several features and would be a lot of work to resolve completely. The most valuable part of this work for me would be to parse MAPINFO for DoomEdNums for any custom actors defined, so that I can define them in that one file - centrally - rather than in individual actor definitions (which live in multiple files that are a pain to cross-coordinate) and place these in the map editor.

As it is, I'm left with a choice of either defining DoomEdNums for my custom classes at dozens of places in a half-dozen different files and being able to place and recognize placed instances of them in the map editor, or being able to define them in one place and not being able to do so. Both are pretty crummy for working on mods that define more than a few of their own actor classes.

**Comment by Gaerzi** [comment]
Things to do:
- [ ] Keep every parsed actor in memory, even if they don't have editor number
- [ ] Parse MAPINFO for editor numbers defined there
- [ ] Enable inheritance of properties

**Comment by sirjuddington** [comment]
There is some work towards this in the zscript branch, it's the last thing I want to get done before releasing the first beta for 3.1.2

**Comment by JPLeBreton** [comment]
Last I heard the larger body of ZScript work is on hold, but I'm wondering how much work this would be on its own, or if there's a workaround. It's pretty much the main usability snag I have with SLADE these days. If not that's okay, thanks for all the work lately; the Lua stuff seems exciting.

**Comment by sirjuddington** [comment]
Yeah this at least will likely be in soon, most of the work for it is done in the [mapinfo](https://github.com/sirjuddington/SLADE/tree/mapinfo) branch. Main reason I haven't merged it in to master yet is it probably needs more testing, especially since it includes the rewritten tokenizer.

**Comment by usernameak** [comment]
@Gaerzi inheritance of properties is partially added in #767

**Comment by sirjuddington** [comment]
This should all be done now in https://github.com/sirjuddington/SLADE/commit/5dffecee92fb51119a377c8613227e76c2e93bf5

**Comment by JPLeBreton** [comment]
Just built latest, and while I see the actors I've defined via DECORATE in the editor view + thing type browser, I don't see the actors I've defined via ZScript.
In case it helps, my ZScript class data looks like this:
```
class FloppyDisk : MediaLogPROX
{
	Default
	{
		//$Group "Autobio";
		//$NotAngled;
		//$Sprite diskA0;
	}
    [state definitions, etc...]
}
```

**Comment by sirjuddington** [comment]
Yeah, ZScript parsing isn't in just yet
