### ISSUE TITLE
Tokenizer and quoted backslashes

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#697]
The tokenizer contains the following code for processing a quoted string:

```c++
	//if (position < size - 1 && current[0] == '\\' && current[1] == '\"')
	if (current[0] == '\\')
		incrementCurrent();

```
The apparent intent is to prevent parsing an escaped quote mark as the end delimiter of the string. However, all it does is strip the string from its backslashes.

I noticed this when testing the open console command with a Windows file path. The console uses the tokenizer to parse its commands, and so "d:\games\doom\doom2.wad" gets turned into "d:gamesdoomdoom2.wad" which of course fails to open.

The commented-out line (which only strips the backslash if it's followed by a quote mark) seems correct, but it was presumably commented out for a reason. Will it break anything if this gets reverted to a fixed behavior, or should it be made to some new conditional that'd be toggled with something like enableBackslashes()?

**Comment by sirjuddington** [comment]
This is intentional yes, it treats `\` as an escape character, so that path needs to be `d:\\games\\doom\\doom2.wad`

**Comment by fluffymormegil** [comment]
As I understand it, at an API level Windows is quite happy to treat `/` as a path separator, so `d:/games/doom/doom2.wad` *should* work and avoids the whole issue.

**Comment by sirjuddington** [comment]
Closing

Feel free to reopen the issue if needed
