### ISSUE TITLE
Overlapping Things checker throws false positives for DM vs. SP/coop starts

### ISSUE THREAD

**Issue by fluffymormegil** [sirjuddington/SLADE#702]
**SLADE Version**: 3.1.2 alpha
**Operating System**: all

**Issue Details**:

The Overlapping Things checker will report DM starts that overlap Player N starts, even though this should not actually cause a problem in any normal gameplay scenario.

Manually tweaking the flags on the placed start things so that the DM starts are marked DM-only and the Player N starts are marked not-DM works for game modes where that functionality is available, but the flags to do that are not part of the original Doom.

**Comment by Gaerzi** [comment]
I'll address this; already working on some other error checker features.
