### ISSUE TITLE
Boom zero-tagged special 260 lines should not be shown as affecting other zero-tagged lines

### ISSUE THREAD

**Issue by iid** [sirjuddington/SLADE#71]
Boom zero-tagged special 260 lines should not be shown as affecting other zero-tagged lines
They are only supposed to make themselves translucent.
![slade3-boom-line-type-260-bug](https://f.cloud.github.com/assets/4338275/1919026/9cac6d84-7dcb-11e3-8d85-6f73d2964403.PNG)

**Comment by Wevah** [comment]
This seems to be occurring again.

**Comment by sirjuddington** [comment]
Bit late for 3.2.11 unfortunately, this will be fixed (again) in 3.3.0
