### ISSUE TITLE
Conversion from PNG to planar (STARTUP) produces incorrect data

### ISSUE THREAD

**Issue by ETTiNGRiNDER** [sirjuddington/SLADE#715]
**SLADE Version**: 3.1.1.5
**Operating System**: Linux (Mint 17.2)

**Issue Details**:
When creating a STARTUP lump for Hexen, converting from a PNG to planar graphic results in broken data.  The lump comes out too large and a hex view of it suggests that some PNG header cruft is being left at the beginning of it.

Conversion from GIF to planar appears to work fine.

**Comment by sirjuddington** [comment]
Fixed in 114ff08
