### ISSUE TITLE
Map editor and anonymous functions issue

### ISSUE THREAD

**Issue by Blue-Shadow** [sirjuddington/SLADE#716]
**SLADE Version**: (3.1.1.5)
**Operating System**: (Windows)

**Issue Details**:
If you load a resource file with the map editor which contains actor code that makes use of [anonymous functions](https://zdoom.org/wiki/Actor_states#Anonymous_functions), SLADE becomes unresponsive.

To produce, create a new map while loading [this file](https://www.dropbox.com/s/wq2vpoyw6hsrya7/anon_func.pk3?dl=1) as a resource.

**Comment by sirjuddington** [comment]
Can you see if this still happens in 3.1.2 beta 1? I can't reproduce it

**Comment by Blue-Shadow** [comment]
Tested it. It does not seem to happen.
