### ISSUE TITLE
Slade freezes when I try to open any archive

### ISSUE THREAD

**Issue by Monsterovich** [sirjuddington/SLADE#718]
Probably when slade tries to initialize the sound device. It happens randomly.

**SLADE Version**: master
**Operating System**: Linux

**Issue Details**:
monsterovich@eee /sdcard/Games/SLADE/new $ gdb ./slade 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./slade...(no debugging symbols found)...done.
(gdb) run
Starting program: /sdcard/Games/SLADE/new/slade 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xaeb0ab40 (LWP 19554)]
[New Thread 0xae1dbb40 (LWP 19555)]
[New Thread 0xad70fb40 (LWP 19556)]
[New Thread 0xacdffb40 (LWP 19557)]
[New Thread 0xa9a7ab40 (LWP 19560)]
[New Thread 0xa9279b40 (LWP 19561)]
[New Thread 0xa8a78b40 (LWP 19562)]
[New Thread 0xa8277b40 (LWP 19567)]
[New Thread 0xa78ffb40 (LWP 19569)]
[New Thread 0xa70feb40 (LWP 19570)]
[New Thread 0xa66ffb40 (LWP 19571)]
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK Server VM (build 25.121-b13, mixed mode)
[New Thread 0xa56ffb40 (LWP 19581)]
[New Thread 0xa4efeb40 (LWP 19582)]
[New Thread 0xa46b9b40 (LWP 19584)]
[New Thread 0xa3eb8b40 (LWP 19585)]
[Thread 0xa4efeb40 (LWP 19582) exited]
[Thread 0xa46b9b40 (LWP 19584) exited]
[New Thread 0xa46b9b40 (LWP 19586)]
[Thread 0xa46b9b40 (LWP 19586) exited]
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

[Thread 0xa3eb8b40 (LWP 19585) exited]

**<FREEZE HERE>**
**CTRL+C**
Thread 1 "slade" received signal SIGINT, Interrupt.
0xb7fd9d0d in __kernel_vsyscall ()
**NOW CONTINUE**
(gdb) continue
Continuing.
**Works fine!**
ALSA lib pcm_dmix.c:1079:(snd_pcm_dmix_open) unable to open slave
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': File descriptor in bad state
Failed to open the audio device
An internal OpenAL call failed in SoundSource.cpp(37).
Expression:
   alGenSources(1, &m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(38).
Expression:
   alSourcei(m_source, AL_BUFFER, 0)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(37).
Expression:
   alGenSources(1, &m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(38).
Expression:
   alSourcei(m_source, AL_BUFFER, 0)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(37).
Expression:
   alGenSources(1, &m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(38).
Expression:
   alSourcei(m_source, AL_BUFFER, 0)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(75).
Expression:
   alSourcef(m_source, AL_GAIN, volume * 0.01f)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(75).
Expression:
   alSourcef(m_source, AL_GAIN, volume * 0.01f)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

fluidsynth: warning: Requested a period size of 64, got 940 instead
fluidsynth: warning: Requested 16 periods, got 4 instead
[New Thread 0xa3eb8b40 (LWP 19591)]
fluidsynth: error: Unable to open file "/usr/share/sounds/sf2/FluidR3_GS.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/FluidR3_GS.sf2"
fluidsynth: error: Unable to open file "/usr/share/sounds/sf2/FluidR3_GM.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/FluidR3_GM.sf2"
An internal OpenAL call failed in SoundSource.cpp(75).
Expression:
   alSourcef(m_source, AL_GAIN, volume * 0.01f)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

[New Thread 0xa46b9b40 (LWP 19592)]
[New Thread 0xa4efeb40 (LWP 19593)]
[New Thread 0xa2ab9b40 (LWP 19594)]
[Thread 0xa4efeb40 (LWP 19593) exited]
[Thread 0xa46b9b40 (LWP 19592) exited]
[Thread 0xa2ab9b40 (LWP 19594) exited]

(slade:19550): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
[New Thread 0xa2ab9b40 (LWP 19604)]
An internal OpenAL call failed in Sound.cpp(87).
Expression:
   alSourceStop(m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(60).
Expression:
   alSourcei(m_source, AL_BUFFER, 0)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(61).
Expression:
   alDeleteSources(1, &m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(60).
Expression:
   alSourcei(m_source, AL_BUFFER, 0)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(61).
Expression:
   alDeleteSources(1, &m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(60).
Expression:
   alSourcei(m_source, AL_BUFFER, 0)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundSource.cpp(61).
Expression:
   alDeleteSources(1, &m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

[New Thread 0xa4efeb40 (LWP 19605)]
[New Thread 0xa46b9b40 (LWP 19606)]
[New Thread 0xa22b8b40 (LWP 19607)]
[New Thread 0xa11e9b40 (LWP 19608)]
[Thread 0xa22b8b40 (LWP 19607) exited]
[Thread 0xa11e9b40 (LWP 19608) exited]
[Thread 0xa4efeb40 (LWP 19605) exited]
[Thread 0xa2ab9b40 (LWP 19604) exited]
[New Thread 0xa4efeb40 (LWP 19609)]
[New Thread 0xa11e9b40 (LWP 19610)]
[New Thread 0xa22b8b40 (LWP 19611)]
[Thread 0xa11e9b40 (LWP 19610) exited]
[Thread 0xa46b9b40 (LWP 19606) exited]
[Thread 0xa4efeb40 (LWP 19609) exited]
[New Thread 0xa36afb40 (LWP 19612)]
[Thread 0xa22b8b40 (LWP 19611) exited]
[New Thread 0xa22b8b40 (LWP 20159)]
[New Thread 0xa4efeb40 (LWP 20160)]
[New Thread 0xa46b9b40 (LWP 20161)]
[Thread 0xa22b8b40 (LWP 20159) exited]
[Thread 0xa46b9b40 (LWP 20161) exited]
[New Thread 0xa46b9b40 (LWP 20164)]
[Thread 0xa46b9b40 (LWP 20164) exited]
[New Thread 0xa46b9b40 (LWP 20165)]
[New Thread 0xa22b8b40 (LWP 20166)]
[Thread 0xa46b9b40 (LWP 20165) exited]
[Thread 0xa22b8b40 (LWP 20166) exited]
[New Thread 0xa22b8b40 (LWP 20167)]
[Thread 0xa22b8b40 (LWP 20167) exited]
[Thread 0xa4efeb40 (LWP 20160) exited]
[New Thread 0xa4efeb40 (LWP 21385)]
[Thread 0xa36afb40 (LWP 19612) exited]
[Thread 0xae1dbb40 (LWP 19555) exited]
[Thread 0xacdffb40 (LWP 19557) exited]
[Thread 0xa9a7ab40 (LWP 19560) exited]
[Thread 0xa3eb8b40 (LWP 19591) exited]
[Thread 0xa56ffb40 (LWP 19581) exited]
[Thread 0xa66ffb40 (LWP 19571) exited]
[Thread 0xa70feb40 (LWP 19570) exited]
[Thread 0xa4efeb40 (LWP 21385) exited]
[Thread 0xa78ffb40 (LWP 19569) exited]
[Thread 0xa8277b40 (LWP 19567) exited]
[Thread 0xa8a78b40 (LWP 19562) exited]
[Thread 0xa9279b40 (LWP 19561) exited]
[Thread 0xad70fb40 (LWP 19556) exited]
[Thread 0xaeb0ab40 (LWP 19554) exited]
[Inferior 1 (process 19550) exited normally]
(gdb)

**Comment by sirjuddington** [comment]
This one looks like an issue with SFML, did you build SLADE with the latest version of it?
