### ISSUE TITLE
macOS package is missing binaries

### ISSUE THREAD

**Issue by fragglet** [sirjuddington/SLADE#729]
I downloaded SLADE-3.1.2_b1.dmg from the website, but the app is missing some libraries.

```
$ /Applications/SLADE.app/Contents/MacOS/slade 
dyld: Library not loaded: /usr/local/opt/ftgl/lib/libftgl.2.dylib
  Referenced from: /Applications/SLADE.app/Contents/MacOS/slade
  Reason: image not found
Abort trap: 6
```

It may be that you had a special version of libftgl installed when you built the slade binary? `otool -L /Applications/SLADE.app/Contents/MacOS/slade` shows it's the only one with a `/usr/local/opt` path.

**Comment by sirjuddington** [comment]
Strange, perhaps that is the FTGL lib I have installed via homebrew interfering with things.

It looks like there was recently an update to @alexey-lysiuk's slade-macos-build repository to fix FTGL in CMake, which will hopefully fix things for the next beta

**Comment by alexey-lysiuk** [comment]
If it helps I uploaded the latest build I have at the moment [here](https://devbuilds.drdteam.org/experimental/SLADE-3.1.2_b1-5-gf521c71a.dmg).

**Comment by sirjuddington** [comment]
Should be fixed with beta 2
