### ISSUE TITLE
Error compiling lastest

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#737]
**SLADE Version**: latest git master
**Operating System**: Linux

**Issue Details**:
Clean make of latest produces this error:
```
/home/jpl/x/slade/src/Archive/Formats/DirArchive.cpp: In constructor ‘DirArchive::DirArchive()’:
/home/jpl/x/slade/src/Archive/Formats/DirArchive.cpp:59:2: error: ‘separator’ was not declared in this scope
  separator = "/";
  ^~~~~~~~~
/home/jpl/x/slade/src/Archive/Formats/DirArchive.cpp:59:2: note: suggested alternative: ‘separator_’
  separator = "/";
  ^~~~~~~~~
  separator_
make[2]: *** [src/CMakeFiles/slade.dir/build.make:378: src/CMakeFiles/slade.dir/Archive/Formats/DirArchive.o] Error 1
```
Arch Linux 64-bit with gcc 7.1.1 20170528, cmake version 3.8.2, if that helps.

**Comment by JPLeBreton** [comment]
FWIW I was able to get it to continue past that step of compilation by simply forward declaring `string separator` before that function, but I've no idea what the architectural/coding-standards-palatable version of that is.

**Comment by fadookie** [comment]
I am able to reproduce this issue on macOS 10.11.6 w/ Xcode 8.2.1 with a clean rebuild:
```
/Users/eliot/Dev/eliot/SLADE/src/Archive/Formats/DirArchive.cpp:59:2: Use of undeclared identifier 'separator'; did you mean 'separator_'?
```

**Comment by JPLeBreton** [comment]
Still can't compile; see my second comment about the link errors.

**Comment by alexey-lysiuk** [comment]
Built fine from scratch on macOS. Clean build should solve linking issues.

**Comment by sirjuddington** [comment]
Yeah works for me, might need to run cmake again to update the build (there are new source files)

**Comment by JPLeBreton** [comment]
Ahh, yes, needed to re-run cmake. Thanks very much!
