### ISSUE TITLE
compilation error on linux : 'MessageType' is not a class or namespace

### ISSUE THREAD

**Issue by delacroix0815** [sirjuddington/SLADE#743]
**SLADE Version**: git revision c5e02b3b5d0ef22f51b6e8f4d8669421bd3f6b16
**Operating System**: Linux

**Issue Details**:
[  0%] Building CXX object src/External/CMakeFiles/external.dir/mus2mid/mus2mid.o
In file included from /home/chris/sources/SLADE/src/./Application/Main.h:84:0,
                 from /home/chris/sources/SLADE/src/External/mus2mid/mus2mid.h:32,
                 from /home/chris/sources/SLADE/src/External/mus2mid/mus2mid.cpp:32:
/home/chris/sources/SLADE/src/./General/Log.h:5:2: warning: scoped enums only available with -std=c++11 or -std=gnu++11
  enum class MessageType
  ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::info(int, const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:34:58: error: 'MessageType' is not a class or namespace
  inline void info(int level, const char* text) { message(MessageType::Info, level, text); }
                                                          ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::info(const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:35:47: error: 'MessageType' is not a class or namespace
  inline void info(const char* text) { message(MessageType::Info, text); }
                                               ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::warning(int, const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:37:61: error: 'MessageType' is not a class or namespace
  inline void warning(int level, const char* text) { message(MessageType::Warning, level, text); }
                                                             ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::warning(const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:38:50: error: 'MessageType' is not a class or namespace
  inline void warning(const char* text) { message(MessageType::Warning, text); }
                                                  ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::error(int, const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:40:59: error: 'MessageType' is not a class or namespace
  inline void error(int level, const char* text) { message(MessageType::Error, level, text); }
                                                           ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::error(const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:41:48: error: 'MessageType' is not a class or namespace
  inline void error(const char* text) { message(MessageType::Error, text); }
                                                ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::debug(int, const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:43:59: error: 'MessageType' is not a class or namespace
  inline void debug(int level, const char* text) { message(MessageType::Debug, level, text); }
                                                           ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::debug(const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:44:48: error: 'MessageType' is not a class or namespace
  inline void debug(const char* text) { message(MessageType::Debug, text); }
                                                ^
/home/chris/sources/SLADE/src/./General/Log.h: In function 'void Log::console(const char*)':
/home/chris/sources/SLADE/src/./General/Log.h:46:50: error: 'MessageType' is not a class or namespace
  inline void console(const char* text) { message(MessageType::Console, text); }
                                                  ^
make[2]: *** [src/External/CMakeFiles/external.dir/build.make:135: src/External/CMakeFiles/external.dir/mus2mid/mus2mid.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:242: src/External/CMakeFiles/external.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

I am using GCC Version 5.4.0

**Comment by sirjuddington** [comment]
Try re-running cmake to rebuild the makefile, it looks like c++11/14 support isn't being enabled

**Comment by delacroix0815** [comment]
Did that. Same error. For completeness, this is the output of cmake building the makefile:

chris@rasmatazz 21:08:27 ~/sources/slade-build $ cmake ../SLADE/
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/lib/ccache/bin/cc
-- Check for working C compiler: /usr/lib/ccache/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.9 loaded.
-- Found wxWidgets: -L/usr/lib64;-pthread;;;-lwx_gtk2u_aui-3.0;-lwx_gtk2u_gl-3.0;-lwx_gtk2u_stc-3.0;-lwx_gtk2u_richtext-3.0;-lwx_gtk2u_propgrid-3.0;-lwx_gtk2u_media-3.0;-lwx_gtk2u_xrc-3.0;-lwx_gtk2u_webview-3.0;-lwx_gtk2u_html-3.0;-lwx_gtk2u_qa-3.0;-lwx_gtk2u_adv-3.0;-lwx_gtk2u_core-3.0;-lwx_baseu_xml-3.0;-lwx_baseu_net-3.0;-lwx_baseu-3.0 (found suitable version "3.0.2", minimum required is "3.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.31
-- Found FluidSynth: /usr/lib64/libfluidsynth.so  
-- Found FreeImage: /usr/lib64/libfreeimage.so  
-- Found SFML: /usr/lib64/libsfml-system.so;/usr/lib64/libsfml-audio.so;/usr/lib64/libsfml-window.so  
-- Found FTGL: /usr/lib64/libftgl.so  
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found GLEW: /usr/include  
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.8.0") 
-- Found CURL: /usr/lib64/libcurl.so (found version "7.54.1") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- CXX target slade cotired without precompiled header. ccache requires configuration setting "sloppiness" to be set to "pch_defines,time_macros".
-- run `pk3` target to build slade.pk3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chris/sources/slade-build

**Comment by delacroix0815** [comment]
You were right about the c++11 support not being enabled. After running cmake i edited CmakeCache.txt and added CMAKE_CXX_FLAGS:STRING=-std=c+11. After that make ran fine. 

But shouldn't cmake autodetect and set -std=c+11 automatically ?

**Comment by delacroix0815** [comment]
Compiling fine with latest commit https://github.com/sirjuddington/SLADE/commit/8e895208828a41eb6240152bb1b6f2baafc54230 , thank you !
