### ISSUE TITLE
In the tutorial of importing Textures in 'Wiki' the link "Nick Baker's 5th episode set" is broken or unreachable.

### ISSUE THREAD

**Issue by adil25** [sirjuddington/SLADE#747]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
(i need the nb5tex2.zip file, for which i clicked on the link 'Nick Baker's 5th episode set' but either the link is broken or not reachable because of any reason. Though i searched this file in google but unfortunately could not find it. please anyone help would be appreciated in getting the above mentioned file i.e.  Nick Baker's 5th episode set in zip form......Thanks )

**Comment by sirjuddington** [comment]
Looks like they were removed from realm667 at some point. You can still find the texture pack at Afterglow's textures page on Doomworld [here](https://www.doomworld.com/afterglow/textures/zips/nb5texd2.zip)

**Comment by Blue-Shadow** [comment]
They're still there: http://realm667.com/index.php/en/texture-stock-mainmenu-152-97360/doom-style-mainmenu-153-87237/616-5th-episode-texture-pack

**Comment by adil25** [comment]
@sirjuddington and @Blue-Shadow ...Thank you.....
