### ISSUE TITLE
Another similar Issue: In the tutorial of importing Textures in 'Wiki' the link "Adrenix Texture Pack" is also broken or unreachable.

### ISSUE THREAD

**Issue by adil25** [sirjuddington/SLADE#748]
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
(i need the adrenxtx.zip/adrenxtx file, for which i clicked on the link 'Adrenix Texture Pack' but either the link is broken or not reachable because of any reason. Though i searched this file in google but unfortunately could not find it too. please help would be appreciated in getting the above mentioned file i.e. Adrenix Texture Pack in zip form......Thanks )

**Comment by sirjuddington** [comment]
You can still get these from realm667 [here](http://www.realm667.com/index.php/en/texture-stock-mainmenu-152-97360/other-sources-styles-mainmenu-155-26369/893-adrenix-texture-pack)

**Comment by adil25** [comment]
ok. Thanks
