### ISSUE TITLE
Crash when deleting sector

### ISSUE THREAD

**Issue by axredneck** [sirjuddington/SLADE#755]
**SLADE Version**: current master (commit c4bfa47)
**Operating System**: AntergOS linux, updated 06.07.2017

**Issue Details**:
How to reproduce:
1. Create WAD archive
2. Create UDMF map in it (i created MAP01)
3. Create sector
4. Select it and press Delete

[stack-trace.txt](https://github.com/sirjuddington/SLADE/files/1132217/stack-trace.txt)

**Comment by crisisinaptica** [comment]
I can reproduce this one.
In addition while I was taking a closer look in the debugger,  every time I select a sector SLADE opens a window and informs me of this:

An assertion failed!
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

Here's the backtrace:
[assertion_when_sector_is_selected.txt](https://github.com/sirjuddington/SLADE/files/1132460/assertion_when_sector_is_selected.txt)

**Comment by axredneck** [comment]
Thank You ! Now it works.
