### ISSUE TITLE
I have my own build where I've fixed some bugs

### ISSUE THREAD

**Issue by usernameak** [sirjuddington/SLADE#767]
Can i give it to you and you'll try to merge that? But there's a problem. It uses wxGTK3 that is supported only on Arch Linux. And for some reasons links in the WebView don't work.

The changes:

- Doom Builder style borders on the things in 3d mode (thin bounding box and arrow)
- Now sprites that are scaled through TEXTUREx are scaled in map editor
- GTK3
- Doom Builder style hilight in 3d mode
- Fixed a bug in TEXTUREx editor when pressing Enter is required to save the changes
- Buggy support of translations for sprites

**Comment by sirjuddington** [comment]
It's best to fork SLADE on GitHub and create a pull request.

I already added GTK3 support in the gtk3 branch, including a cmake option to enable/disable it (if you have the gtk2 build of wx). Not sure why I didn't merge it in yet.
