### ISSUE TITLE
(3.1.2.beta4) Graphics lumps always ask for saving, even if unmodified

### ISSUE THREAD

**Issue by ioan-chera** [sirjuddington/SLADE#768]
**SLADE Version**: (3.1.2.beta4)
**Operating System**: macOS

**Issue Details**:
Nearly _every time_ I have a graphics lump selected, and move to another lump, I'm asked whether to save the lump or not (and then it's marked as blue, so I have to save the wad again). It doesn't matter that I didn't change _anything_, it just thinks the lump is dirty and asks me.

EDIT: seems to happen if I decide to change the offsets of one graphic, and then select another graphic lump. The offset textbox of the new lump will automatically gain focus, and that will cause SLADE to think it has been modified (despite me not changing anything), causing that other graphic lump to be dirty. It only stops when I hit some other kind of lump (such as a marker).

It also happens if I rename one graphic lump: then the offset text box is focused, dirtying the lump again.

**Comment by XaserAcheron** [comment]
I get the same symptoms (Windows user) with text lumps: I modify a file in the text editor, save it, and it prompts "the file has been modified; do you wish to save?" when I navigate away from the text editor even though I haven't modified anything since. The detection seems a bit overzealous.
