### ISSUE TITLE
Selecting macOS Finder tags in the "Open" dialog results in a blank view

### ISSUE THREAD

**Issue by ioan-chera** [sirjuddington/SLADE#769]
**SLADE Version**: (3.1.1.5)
**Operating System**: macOS

**Issue Details**:
I have some files tagged in macOS Finder with some colors. Normally, this makes the standard Open panel in any application to allow jumping quickly to files with that tag. Unfortunately in SLADE, clicking a tag results in a brief visit to that destination which quickly is replaced by a blank screen.

**Comment by sirjuddington** [comment]
That'd be a wxWidgets issue then, SLADE is just using wx to handle file dialogs.

**Comment by sirjuddington** [comment]
Closing this since there isn't much I can do about it, hopefully fixed in a newer version of wx
