### ISSUE TITLE
Alt+Backspace and Cmd+Backspace don't act like they should under macOS

### ISSUE THREAD

**Issue by ioan-chera** [sirjuddington/SLADE#770]
**SLADE Version**: (3.1.1.5)
**Operating System**: macOS

**Issue Details**:
When in the text editor, Alt+Backspace acts as "undo", even when I'm under macOS. The problem is that under macOS, Alt+Backspace should have the same effect as Ctrl+Backspace in Windows (delete back a word), whereas for Undo I should use Cmd+Z (and Redo is Cmd+Shift+Z). Also, Cmd+Backspace currently deletes back only one word, when in fact it should delete to the start of line.

Other common controls on Mac are the simple Emacs or Terminal controls, e.g. ctrl+K deleting to the end of line etc. Do *not* implement these outside of macOS.

**Comment by sirjuddington** [comment]
Another wx issue I'm guessing, SLADE only manually implements the keys under 'Text Editor' in Input->Preferences. Everything else is left to wxStyledTextCtrl.

**Comment by sirjuddington** [comment]
Closing this since there isn't much I can do about it, hopefully fixed in a newer version of wx
