### ISSUE TITLE
Feature request: LUA - Example for moving/renaming files

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#774]
Right now I'm still working on learning LUA, but in the mean time, it'd be greatly appreciated if we could get a few LUA examples on moving and rename files, especially in archives.

One example can demonstrate how to move and rename particular items in specific folders.

The other would be, say, mass moving everything from the Sprites folder into the Graphics folder.

**Comment by sirjuddington** [comment]
There are some very basic examples on the scripting docs page for now. In 3.2.0 the scripting API is being changed a bit and expanded a lot, and I plan to also move a bunch of hard-coded functionality (eg. 'maintenance' functions, etc.) to be scripts instead, which will serve as some better examples

**Comment by MajorCooke** [comment]
Sounds good. So will it still be LUA or will it be something else?

**Comment by sirjuddington** [comment]
Still lua, by changed a bit I mostly meant the naming is a bit different (API functions use PascalCase) and a couple of things are moved around
