### ISSUE TITLE
Feature request: Special comments for parsing custom ZScript functions

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#775]
I'm not sure what the plan is for parsing custom functions found in ZScript, but for now I can at least suggest a special comment prefix and suffix to indicate SLADE should parse and color the functions appropriately. In addition, hovering over them will show the values just like regular functions in ACS/Decorate.

```
// !@ A_MyFunction(int inputVar1, [bool inputVar2 = false]);
```
Or something like that -- I don't know what's planned, you guys might have something much better.

**Comment by sirjuddington** [comment]
This probably won't be needed, parsing ZScript functions properly should be in soon(ish)

**Comment by MajorCooke** [comment]
Awesome!
