### ISSUE TITLE
No JPG pictures preview after update

### ISSUE THREAD

**Issue by Gato606** [sirjuddington/SLADE#776]
**SLADE Version**: (3.1.2 Beta 2 -  DRD Team Package Repository)

**Operating System**: (Linux Xubuntu 64bits)

**Issue Details**:
Good day. I updated Slade to the version v3.1.2 Beta 2 a couple days ago, it looks pretty nice. Though, with the update I'm having some problems: now when I try to see a JPG image preview on the "Entry Contents" field it doesn't work, it shows message "Error loading entry: Unable to read image data (unsupported format?)" This is weird cause in a previous version, the JPG images were shown without problems.  PNG pictures preview works normally.
![screenshot_2017-08-10_12-17-05](https://user-images.githubusercontent.com/30907267/29187787-abcbbbb2-7dd6-11e7-95d4-fc0c1f963baa.jpg)

**Comment by Gaerzi** [comment]
If you open the console, do you get a more precise error message in it?

**Comment by Gato606** [comment]
Hope this helps:
![screenshot_2017-08-11_00-55-42](https://user-images.githubusercontent.com/30907267/29202954-91ce61f4-7e32-11e7-9e4a-6d73a4a598c7.jpg)

**Comment by Gaerzi** [comment]
That seems to be an issue with the libraries (either Free Image or libjpeg) rather than with SLADE itself.

**Comment by Gato606** [comment]
Thanks for the answer.

Though I checked Free Image:
libfreeimage3 version 3.17.0+ds1-2  Seems to be in the latest version.

And libjpeg, I uninstalled the version libjpeg62 which seems to be the problem (according to the console) and I kept libjpeg8 and libjpeg9, restarted the OS, but I keep having the same problem...

What else I can do?

**Comment by Gaerzi** [comment]
To be honest I'm kinda stumped. Perhaps @Blzut3 could shed some light, since IIRC he's the one who maintains the DRD package repository; and he definitely knows more about Linux issues than I do.
