### ISSUE TITLE
Feature request: expose Line and Thing Args to Lua

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#778]
**SLADE Version**: git master latest
**Operating System**: all

**Issue Details**:
Thought of something where Lua would be useful to me today so I tried to implement it: "select all lines that run a particular script number". Iterating through all lines with special 80 was easy enough but I couldn't find any way to reference Arg1 etc, and it doesn't appear in the docs so I assume it's not exposed to Lua yet. This seems pretty high bang for buck; lots of data that's hard to seek out easily from the GUI editor could be sifted through in a few lines of Lua. Not urgent, I'm sure yall have plans to expose all kinds of cool stuff to Lua.

**Comment by sirjuddington** [comment]
They should already be available via `MapObject`'s generic `intProperty()`, eg. `line:intProperty('arg0')`

I didn't add them directly as properties of `MapLine` as they aren't always relevant (like in doom format maps)

**Comment by JPLeBreton** [comment]
Ah, perfect, that works. So intProperty should get anything that's a valid UDMF key?

**Comment by sirjuddington** [comment]
It doesn't really have to be a valid UDMF key, if it doesn't exist it'll just return `0`. You can technically use them to get/set arbitrary UDMF values.
