### ISSUE TITLE
Problems attempting to compile from source

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#782]
**SLADE Version**: Latest
**Operating System**: Linux

**Issue Details**:
Currently running Fedora 26 64-bit, I am trying to compile SLADE from source, but it always errors out during this part.

```
[ 88%] Building CXX object src/CMakeFiles/slade.dir/UI/ConsolePanel.o
/home/steelt/SLADE-master/src/UI/ConsolePanel.cpp: In member function ‘void ConsolePanel::initLayout()’:

/home/steelt/SLADE-master/src/UI/ConsolePanel.cpp:95:25: error: ‘wxSTC_WRAP_WHITESPACE’ was not declared in this scope
  text_log_->SetWrapMode(wxSTC_WRAP_WHITESPACE);
                         ^~~~~~~~~~~~~~~~~~~~~

/home/steelt/SLADE-master/src/UI/ConsolePanel.cpp:95:25: note: suggested alternative: ‘wxSTC_WRAPINDENT_SAME’
  text_log_->SetWrapMode(wxSTC_WRAP_WHITESPACE);
                         ^~~~~~~~~~~~~~~~~~~~~
                         wxSTC_WRAPINDENT_SAME

make[2]: *** [src/CMakeFiles/slade.dir/build.make:5228: src/CMakeFiles/slade.dir/UI/ConsolePanel.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:157: src/CMakeFiles/slade.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by SteelTitanium** [comment]
Apparently I needed version 3.1.0 of wxWidgets. But now I came across another problem, cc1plus starts using a extremely large amount of ram when building lua.o, slowing down the compiling process.

**Comment by sirjuddington** [comment]
Lua.cpp takes a long time to compile because sol2 is a particularly template-heavy library. Not much I can do about that really, though apparently with c++17 sol2 will add some improvements to help with compile times.
