### ISSUE TITLE
Crash when doing noting

### ISSUE THREAD

**Issue by Zom-B** [sirjuddington/SLADE#788]
**SLADE Version**: (3.1.2)
**Operating System**: (Windows 10)

**Issue Details**:
* Open Slade by double-clicking on a WAD,
* Wait a few (1-5) minutes,
* Windows pops up with a program crash and all unsaved work is gone.

I've worked with 3.1.0 for a few years and thought it's time for a casual upgrade, but after this I'm going back to 3.1.0.

**Comment by sirjuddington** [comment]
No idea what that would be. Could you see if the log file says anything? It should be in `%APPDATA%\SLADE3\slade.log`
