### ISSUE TITLE
BCC compile bug

### ISSUE THREAD

**Issue by xIddqDx** [sirjuddington/SLADE#793]
**SLADE Version**: (3.1.2.5)
**Operating System**: (Windows 10)

**Issue Details**:
Beta 5 can't compile script with bcc
In Beta 4 all works fine
[Log.txt](https://github.com/sirjuddington/SLADE/files/1310236/Log.txt)

https://github.com/wormt/bcc

**Comment by sirjuddington** [comment]
Is this still an issue in the latest version? From the log it looks like a problem with the script rather than slade
