### ISSUE TITLE
Double unsaved changes confirmations when editing. 

### ISSUE THREAD

**Issue by JohnSmith25** [sirjuddington/SLADE#796]
**SLADE Version**: (3.1.2 Beta 5)
**Operating System**: (Linux Mint 18.1)

**Issue Details**:
When I am pasting something into a .dec file and pressing Alt+S, Enter key for confirmation and then selecting another file a unsaved changes confirmation window appears again for the last edited file. The same issue happens when I edit a .dec file normally without pasting any texts into it. The bug is minor but it is irritating to work like that. 

Steps to reproduce:
1. Select any file and paste texts into it.
2. Press Alt+S and then confirm the change.
3. Select now any other file.
4. The confirmation window will appear again.

**Comment by wildweasel486** [comment]
Confirmed on my end. It is also possible to get it to prompt you to save a lump after you've already confirmed to save and close a WAD/PK3.

**Comment by sirjuddington** [comment]
I implemented a few changes a while ago that should fix this behaviour, if it is still an issue please reopen this
