### ISSUE TITLE
Struggling to build Slade 3.1.1.5 on Linux with wxWidgets 

### ISSUE THREAD

**Issue by Zombie-Ryushu** [sirjuddington/SLADE#799]
**SLADE Version**: (3.X.X.x)
3.1.1.5
**Operating System**: (Windows/Linux/OSX)
Mageia Linux

**Issue Details**:
[ 39%] Building CXX object src/CMakeFiles/slade.dir/Archive/Formats/BZip2Archive.o
cd /builddir/build/BUILD/SLADE-3.1.1.5/build/src && /usr/bin/c++   -DINSTALL_PREFIX=\"/usr\" -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -isystem /usr/lib64/wx/include/gtk2-unicode-3.0 -isystem /usr/include/wx-3.0 -I/usr/include/SFML -I/usr/include/freetype2 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I/builddir/build/BUILD/SLADE-3.1.1.5/src/. -I/builddir/build/BUILD/SLADE-3.1.1.5/src/./External/dumb -I/builddir/build/BUILD/SLADE-3.1.1.5/src/./Application  -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -pthread -DNDEBUG   -o CMakeFiles/slade.dir/Archive/Formats/BZip2Archive.o -c /builddir/build/BUILD/SLADE-3.1.1.5/src/Archive/Formats/BZip2Archive.cpp
/builddir/build/BUILD/SLADE-3.1.1.5/src/Application/MainApp.cpp: In member function 'virtual bool MainApp::OnInit()':
/builddir/build/BUILD/SLADE-3.1.1.5/src/Application/MainApp.cpp:1009:30: error: 'wxHandleFatalExceptions' was not declared in this scope
  wxHandleFatalExceptions(true);
                              ^
/builddir/build/BUILD/SLADE-3.1.1.5/src/Application/MainApp.cpp: In member function 'virtual void MainApp::OnFatalException()':
/builddir/build/BUILD/SLADE-3.1.1.5/src/Application/MainApp.cpp:1215:5: error: 'class SLADEStackTrace' has no member named 'WalkFromException'
  st.WalkFromException();

**Comment by Gaerzi** [comment]
What about master? There were compilation fixes recently with 246f5f719580bbd652ecaccd7f6ccadcaefabc7c, 21249bb71ecf03a23f574c03898762b674ac9fc1, e0281f0a20239b1a7f09c8897608a5e2ae79bb93 and aad6a47785ae0316cbbe25e7386f06fea892b477 so you could try again to see if it works with current development version.

**Comment by nevesnunes** [comment]
I also had similar errors, due to cmake pulling dependencies for gtk-2 instead of gtk-3.

I noticed that branch gtk3 has the option WX_GTK3. I tried adding it back to master and it compiled fine. Is there a reason this option was removed?
