### ISSUE TITLE
Slade crashes when using Textures editor

### ISSUE THREAD

**Issue by JohnSmith25** [sirjuddington/SLADE#807]
**SLADE Version**: (3.1.1.5)
**Operating System**: (Linux Mint 18.1)
**Issue Details**:
When I am trying to edit the Textures definition and saving the changes it will crash when I close the Textures tab. The crash also happens when I just view a Textures Definition and closing it without doing any changes to it. 

Stack trace: https://pastebin.com/K9rPreYB

Steps to reproduce:
1. Open any .pk3 file with a Textures definition on it.
2. Change stuff around in it.
3. Try to save it and close the tab of it.
4. Slade will now crash with a stack trace.

**Comment by sirjuddington** [comment]
I can't reproduce this in 3.1.2 beta, if possible could you try it with that?

**Comment by JohnSmith25** [comment]
Yes I just made a short test and it doesn't crashes anymore at all, so no error is happening or anything like that. I tested the 3.1.2 beta 4 version. I was still using the older version because it was not crashing so frequently like one of the beta version did whose number I forget.

**Comment by Gaerzi** [comment]
Issue closed, then.
