### ISSUE TITLE
Suggestion: Prevent extension renaming on import/export

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#811]
I think a checkbox when importing a file to replace another along with exporting should be included. For example, I have a .md3 file and every time I import a new one in on top of it, the file is renamed from .md3 to .dat instead of keeping it.

I'd appreciate it if we could have said checkbox so once it's checked, it won't do that anymore.

**Comment by Frozsoul2019** [comment]
This issue also occurs when importing a .lua file to replace en existing .lua file.  The imported file gets renamed to .txt when it should remain as .lua
