### ISSUE TITLE
Cannot rename folders within ZIPs to 'doom.doom2.tnt'

### ISSUE THREAD

**Issue by Talon1024** [sirjuddington/SLADE#821]
**SLADE Version**: (3.1.2 Beta 5, master)
**Operating System**: (Linux)

**Issue Details**:
I cannot rename folders within PK3/ZIPs to 'doom.doom2.tnt' or 'doom.doom2.plutonia'. Creating folders with these names works just fine, but I cannot rename folders to the aforementioned names,

**Steps to reproduce**:
1. Open SLADE
2. Create a ZIP archive
3. Create a folder named 'filter'
4. Within the 'filter' folder, create a folder named 'doom2.tnt'
5. Try renaming 'doom2.tnt' to 'doom.doom2.tnt'
6. The folder will be renamed to 'doom.doom2'

**Comment by Xane123** [comment]
It looks like to me that SLADE might be treating the name as a file and removing the second "extension" at the end. It shouldn't do this for folders, though, obviously.
