### ISSUE TITLE
Map Saving Freeze

### ISSUE THREAD

**Issue by PhantomDoom741** [sirjuddington/SLADE#823]
**SLADE Version**: 3.1.1.4
**Operating System**: OSX El Capitan 10.11.6

**Issue Details**:
Today I was creating a new map on SLADE. When I finished it, I tried to save the map but SLADE froze. Even after one minute, SLADE didn't unfreeze so I force-quitted it. Unfortunately, my map wasn't saved so I think I'm going to redo it tomorrow.

**Comment by sirjuddington** [comment]
Going to close this one since there really isn't much to go on, and it may be fixed in a later version
