### ISSUE TITLE
Asterisk filter misbehaving

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#825]
**SLADE Version**: (3.1.1.5 beta)
**Operating System**: Windows 10 x64

**Issue Details**:
When using the [filter search bar](https://puu.sh/yGk85/313a00f6b0.png), the desired items I'd only like to see are the highlighted ones in the image. However, the non-highlighted items are something I was not anticipating on seeing. 

To put it simply, I wanted any lump to show that has the starting N085. Any character could do for the frame, so long as it had the appended C upon it, but unfortunately it doesn't take that into account -- it shows the rotations D, E, F and G which is something I don't want.

**Comment by sirjuddington** [comment]
Ah yeah ok, `*` should really mean 1-or-more characters, not 0-or-more

**Comment by sirjuddington** [comment]
Hmm ok looks like this is a wxWidgets thing, I'm just using `wxString::Matches` to check if entry names match the filter, so there's not much I can do apart from writing the match check myself.

**Comment by MajorCooke** [comment]
I see. Well, it would be greatly appreciated if you could allow for this to work... better.

**Comment by sirjuddington** [comment]
This is fixed in 3.2.0
