### ISSUE TITLE
SLADE seems to assign random line IDs to newly created linedefs

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#828]
**SLADE Version**: 3.1.2-b5-r21-g5720bf83
**Operating System**: Linux

**Issue Details**:
While working on a map I noticed that anytime new linedefs are created by any action, they get assigned a random line ID. I don't recall ever enabling something like this, nor I can find an option anywhere for it, so I assume it must be a bug.

Examples:
* Create single line in a sector: gets the line ID 1132527617
* Create a sector: lines get the IDs 1132527617, 1127088128, 32, 180, -10928, -10928, and so on.

Numbers seem to change every now and then.

I have no idea what could be causing this, but it's driving me crazy.

**Comment by usernameak** [comment]
seems to be an uninitialized var

**Comment by JPLeBreton** [comment]
Possibly related to https://github.com/sirjuddington/SLADE/issues/789 ?

**Comment by OrdinaryMagician** [comment]
Oops, my fault then. I definitely messed up when trying to merge #824 myself, because that fix seems to not be on my copy anymore.

**Comment by OrdinaryMagician** [comment]
Double oops, it's actually unrelated. Even from a clean clone of the latest git master it's still assigning random IDs (though I have to check by reading the TEXTMAP lump directly, because of the properties dialog crash that pull request was fixing).
