### ISSUE TITLE
Translations are removed when opening the TEXTURES editor

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#835]
**SLADE Version**: 3.1.2-b5 r24 1e3a596
**Operating System**: Linux

**Issue Details**:
When the TEXTURES editor is opened, any texture definitions that contain translations get them immediately cleared, so they get lost forever when saving. This issue may be OS-agnostic, as I've come across Windows users who also have this happen.

**Comment by sirjuddington** [comment]
This one is probably related to #837 - something is wrong with the translation parser
