### ISSUE TITLE
Saved translation files are "not valid"

### ISSUE THREAD

**Issue by Xane123** [sirjuddington/SLADE#837]
**SLADE Version**: 3.1.2 Beta 5
**Operating System**: Windows

**Issue Details**:
Saving a translation to a file through the button in the "colour remap" dialog makes a valid translation. However, trying to load it using the other button, even if it's something saved through SLADE 3 just before it, it's considered "not a valid translation file" even though the syntax is correct.
![image](https://user-images.githubusercontent.com/17244146/35072324-1421ae02-fbb2-11e7-9f93-9a640d636ea0.png)
This didn't occur in older versions from what I remember; I sometimes save a translation to use it on other objects down the line so if it existed before Beta 5 I would've noticed it and reported it then.

This is in the "beta 5" downloaded from SLADE's website, not any recent commit, so I don't know whether this error still exists. To reproduce it, just save any translation to a text file then load it. The error will appear regardless of if it's valid or not.

**Comment by OrdinaryMagician** [comment]
This error still happens on master.

**Comment by Xane123** [comment]
Ah, it's great this'll be fixed. (Also, I see the referenced other issue, which was something else that keeps me from wanting to mess with the TEXTURES editor.)

**Comment by Xane123** [comment]
I know this is very late and pointless, but I didn't know there was a "dev-builds" directory until it was linked somewhere, but now that I have a dev-build of SLADE, I can confirm this was fixed; Now I can import a translation with no problems!
