### ISSUE TITLE
Some few issues with interface on Linux

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#839]
**SLADE Version**: (3.1.2 Beta 5)
**Operating System**: (Linux)

**Issue Details**:
Unlike the windows version, drag and drop don't work, neither does selection highlighting, so I can't manually highlight sections, only using ctrl + a, which isn't ideal.

**Comment by sirjuddington** [comment]
Do you mean in the entry list / main editor?

**Comment by SteelTitanium** [comment]
Yeah, in the entry list / main editor.

**Comment by SteelTitanium** [comment]
I just also noticed that you can't drag and drop an entry like you could with the Windows version.

**Comment by sirjuddington** [comment]
The entry list uses a different wx control in 3.2.0, so hopefully this is fixed there
