### ISSUE TITLE
Providing Linux packages on the Website

### ISSUE THREAD

**Issue by Luraktinus** [sirjuddington/SLADE#851]
i noticed that there are no Linux downloads in the download page, they should be added for users that dont wanna compile SLADE.

besides, its just fair because there are files for Win and Mac

**Comment by MartinHowe426** [comment]
In addition, the DRD Team builds do not include the latest Ubuntu version 18.04 LTS in the repository so I can't even download a generic Linux executable file, let alone compile SLADE on my system :( I have posted on the DRD Team forum about this, but thought Sir Juddington should know.

**Comment by Luraktinus** [comment]
flatpak, appimages or snaps as packages pls

**Comment by sirjuddington** [comment]
I've had a look at flatpak/snap/appimage, and they would certainly be ideal for getting official releases on linux, but they seem like too much of a pain to set up, especially to get working on older distros and including all 'optional' features (webview startpage etc). If someone else wants to set one up with all that, feel free.

**Comment by MartinHowe426** [comment]
Workaround for Ubuntu 18.04LTS: Thanks to some kind advice from Blzut3 in his capacity as DRD Team admin, it seems the DRD Team repo does work on the latest Ubuntu, you just need to ignore the apt-add-repository commands error messages. If you go ahead and run the get key line, it still works. No I have no idea how as I am by no means an expert in APT, I am just pleased that it does.

**Comment by Alexander-Wilms** [comment]
SLADE is now available at https://flathub.org/apps/details/net.mancubus.SLADE
If you would like to have push-access to https://github.com/flathub/net.mancubus.SLADE, you can ask anybody on this list: https://github.com/orgs/flathub/people

**Comment by sirjuddington** [comment]
Very nice, thanks a lot for setting that up, I'll put it up on the website when I get a chance.

One minor thing - the current version is actually 3.1.4, not 3.1.1.4 as the flathub page says

**Comment by Alexander-Wilms** [comment]
Yeah, I fixed that here https://github.com/sirjuddington/SLADE/commit/960e70294ef265224d22d42e508253fec6fdbc1f#diff-20d62ee4d4724cf0d33a36e15a19f701R61, but I can add a patch to the package as well
