### ISSUE TITLE
Shadowcaster - DAT archive support broken (3.1.2 beta 5)

### ISSUE THREAD

**Issue by darkhaven3** [sirjuddington/SLADE#852]
**SLADE Version**: 3.1.2 beta 5
**Operating System**: Windows 10

**Issue Details**:
Shadowcaster archives are no longer read properly. I don't know exactly which beta this cropped up in, but in 3.1.2, most of the data formats contained in RAVDATA.DAT, HD_CASTR and CD_CASTR were properly identified as "SC gfx"/"SC wall", etc. Now many are identified as "Graphic (Arah)" or "Unknown". I would also like to request - for purposes of continued development of a source port of Shadowcaster - support for saving DAT/LIB archives.

**Comment by sirjuddington** [comment]
Shadowcaster archives/entries all seem to work ok now, closing the issue
