### ISSUE TITLE
Memory error building SLADE with yaourt on Arch Linux

### ISSUE THREAD

**Issue by Gustavo6046** [sirjuddington/SLADE#853]
**SLADE Version**: 3.1.2 beta 5
**Operating System**: "GNU/Linux" -> "Arch Linux"

**Issue Details**:
So, I tried to install SLADE 3 on my Arch Linux PC (which is my main and only PC currently), using `yaourt`, but there is inconveniently a necessary C++ build (which barely worked in a previous Xubuntu environment, although from the `apt` repository).

After building around 97% of the C++ objects, the `make` command (which is important, since SLADE does not seem to have prebuilt binaries for Linux!) suddenly uses all memory while trying to build `CMakeFiles/slade.dir/Scripting/Lua.o`.

Is there any alternative to compiling SLADE 3 in order to install it? Low-end PCs _(which are common with Arch Linux, since the minimalistic distribution is one of the few that can use well the low resources available)_ might not be able to compile it. Unfortunately mine is one of them.

**Comment by SteelTitanium** [comment]
As a workaround, you could try compiling with clang, as it handels template heavy files better. And the memory usage will be much lower. Compiling with clang sure helps me.

**Comment by Gustavo6046** [comment]
Clang is indeed much better, I'll try always using it instead of GCC in the future.

The problem was with linking. The system linker `ld` was too slow. But miraculously it managed to run after a few minutes of drag in the mud. Thank you!

**Comment by OrdinaryMagician** [comment]
Alternatively you can remove -pipe from the CFLAGS/CXXFLAGS in makepkg.conf
