### ISSUE TITLE
Unable to move camera up/down in 3d preview

### ISSUE THREAD

**Issue by fadookie** [sirjuddington/SLADE#854]
**SLADE Version**: 3.1.2 Beta 5
**Operating System**: OSX 10.11.6

**Issue Details**:
Steps To Reproduce:
1. Create a new map
2. Raise ceiling height a bit
3. Enter 3D preview mode
4. Press up or down keys to adjust camera height

Expected Behavior:
Camera moves up or down on Y Axis

Actual Behavior:
Camera moves slightly up/down by a few units as long as key is held (seems to be capped to about 6 units) and then snaps back to original position as soon as key is released.

See gif:
![slade-camera-stuck](https://user-images.githubusercontent.com/110764/37448341-2815cbf2-27e3-11e8-8e23-73a2e652c069.gif)

**Comment by sirjuddington** [comment]
You need to disable gravity (default key `G` in 3d mode)

**Comment by fadookie** [comment]
Ah thanks... rather unusual for a 3D editor but I guess it makes sense to have this on by default for a typical doom level.
