### ISSUE TITLE
It is impossible to work with ACS

### ISSUE THREAD

**Issue by PROPHESSOR** [sirjuddington/SLADE#855]
**SLADE Version**: (3.1.2.5)
**Operating System**: (Linux Mint)

**Issue Details**:
It breaks my ACS code in the map editor.
After re-opening the map using the Map Editor and pressing Ctrl + 5 (Open Script Editor), I see an empty window ....
But the code exists in the SCRIPTS file ...
Another problem is the bug with updating the BEHAVIOR lump.

**Comment by PROPHESSOR** [comment]
This can be fixed if you put the SCRIPTS and BEHAVIOR files before the ENDMAP token

**Comment by PROPHESSOR** [comment]
But after compiling and saving it deletes the SCRIPTS file and creates an empty BEHAVIOR file

**Comment by PROPHESSOR** [comment]
As I can see, it was fixed

**Comment by Gaerzi** [comment]
Well then.
