### ISSUE TITLE
ACS scripts cannot compile at all

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#860]
**SLADE Version**: (3.1.2.5)
**Operating System**: Windows 10

**Issue Details**:

I don't know when this started happening, but it was relatively recently when it did. https://puu.sh/zRhHw/2e0c3a2e16.png

Whenever I try to compile ANY acs lump, this happens. It doesn't matter if it's inside a map WAD or in the Scripts/ folder, and my console log outputs this:

```
Error: Execution of command 'C:/Games/doom 2/base/SLADE/ACC/acc.exe  "C:\Games\doom 2\base\SLADE\temp\GameType.acs" "C:\Games\doom 2\base\SLADE\temp\GameType.o"' failed (error 193: unknown error c1)
ACS compiler output:
Error: File 'C:\Games\doom 2\base\SLADE\temp\GameType.acs' couldn't be removed (error 2: the system cannot find the file specified.)
```

**Comment by MajorCooke** [comment]
I managed to fix it by moving the ACC into C:\ACC. So it must be the space in the **doom 2** that must have thrown it off.

**Comment by sirjuddington** [comment]
This is a weird one, I can't reproduce it myself, using a path to acc.exe with spaces in it works fine (Window 10).

Can probably change the command line to add quotes around the acc.exe path, doubt it would affect anything but would hopefully fix this
