### ISSUE TITLE
Fail when manage external files

### ISSUE THREAD

**Issue by Gustavo6046** [sirjuddington/SLADE#863]
**SLADE Version**: 3.1.2-4b
**Operating System**: Arch Linux

**Issue Details**:
SLADE fails to add and manage external files (although it gets to open them, as far as the console says):
![Problem view](https://user-images.githubusercontent.com/4016417/38449308-83a4784e-39e3-11e8-8b4e-143b36432d55.gif)

Is there any possible fix for it? Probably has to do with Linux.

**Comment by sirjuddington** [comment]
Does this still happen with the latest version of SLADE?

**Comment by Gustavo6046** [comment]
Probably not. The 'environment of execution' has changed drastically since and I am unable to reproduce this issue. It's probably not in SLADE. :)
