### ISSUE TITLE
Slade freezing after "create new map" window open

### ISSUE THREAD

**Issue by Arbars** [sirjuddington/SLADE#865]
**SLADE Version**: (3.1.2 Beta 5) from DRD Team Repository
**Operating System**: Linux Mint 18.3 x64

**Issue Details**:
Slade freezing after opening "create new map" window.
No matter what is base game.
![2018-04-11 01-37-59](https://user-images.githubusercontent.com/10302498/38598383-ebf3664c-3d7d-11e8-805b-d1dc9388705a.png)

Log from terminal:

```
(slade:5950): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
Unhandled unknown exception; terminating the application.

```

**Comment by sirjuddington** [comment]
Does this still happen with the latest version?
