### ISSUE TITLE
Specific image file causes consistent crash upon viewing

### ISSUE THREAD

**Issue by Xane123** [sirjuddington/SLADE#869]
**SLADE Version**: 3.1.2 Beta 5
**Operating System**: Windows

**Issue Details**:
I exported a couple images from Substance Designer to prepare a test material for my game but every time SLADE 3 tries to display this image, it crashes. To test this, download and open [this ZIP file](https://github.com/sirjuddington/SLADE/files/1940414/crash.zip) in SLADE then select the image inside.
![blocks_metal](https://user-images.githubusercontent.com/17244146/39159258-a5909abc-4732-11e8-88a1-481184b61e11.png)
Here's the crash log/stack trace:
> Version: 3.1.2 Beta 5
> No current action
> 
> Operating System: Windows 10 (build 16299), 64-bit edition
> Graphics Vendor: OpenGL not initialised
> Graphics Hardware: OpenGL not initialised
> OpenGL Version: OpenGL not initialised
> 
> Stack Trace:
> 0: (c:\dev\slade-build\src\graphics\simage\formats\sifimages.h:232) SIFPng::readImage
> 1: (c:\dev\slade-build\src\graphics\simage\siformat.h:72) SIFormat::loadImage
> 2: (c:\dev\slade-build\src\graphics\simage\simage.cpp:646) SImage::open
> 3: (c:\dev\slade-build\src\general\misc.cpp:121) Misc::loadImageFromEntry
> 4: (c:\dev\slade-build\src\maineditor\ui\entrypanel\gfxentrypanel.cpp:184) GfxEntryPanel::loadEntry
> 5: (c:\dev\slade-build\src\maineditor\ui\entrypanel\gfxentrypanel.cpp:169) GfxEntryPanel::loadEntry
> 6: (c:\dev\slade-build\src\maineditor\ui\entrypanel\entrypanel.cpp:153) EntryPanel::openEntry
> 7: (c:\dev\slade-build\src\maineditor\ui\archivepanel.cpp:2744) ArchivePanel::openEntry
> 8: (c:\dev\slade-build\src\maineditor\ui\archivepanel.cpp:3349) ArchivePanel::onEntryListFocusChange
> 9: (f:\programming\libs\wxwidgets-3.1.0\src\common\appbase.cpp:658) wxAppConsoleBase::HandleEvent
> 10: (f:\programming\libs\wxwidgets-3.1.0\src\common\appbase.cpp:669) wxAppConsoleBase::CallEventHandler
> 11: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1383) wxEvtHandler::ProcessEventIfMatchesId
> 12: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1831) wxEvtHandler::SearchDynamicEventTable
> 13: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1574) wxEvtHandler::TryHereOnly
> 14: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1484) wxEvtHandler::ProcessEvent
> 15: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1669) wxEvtHandler::SafelyProcessEvent
> 16: (f:\programming\libs\wxwidgets-3.1.0\src\msw\listctrl.cpp:2244) wxListCtrl::MSWOnNotify
> 17: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:3735) wxWindow::HandleNotify
> 18: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:2929) wxWindow::MSWHandleMessage
> 19: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:3524) wxWindow::MSWWindowProc
> 20: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:2668) wxWndProc
> 21: [unknown location] AddClipboardFormatListener
> 22: [unknown location] EndTask
> 23: [unknown location] EndTask
> 24: [unknown location] CallNextHookEx
> 25: [unknown location] IsWindow
> 26: [unknown location] KiUserCallbackDispatcher
> 27: [unknown location] SendMessageW
> 28: [unknown location] DSA_Sort
> 29: [unknown location] DPA_DeleteAllPtrs
> 30: [unknown location] DSA_Sort
> 31: [unknown location] Ordinal234
> 32: [unknown location] Ordinal234
> 33: [unknown location] Ordinal234
> 34: [unknown location] Ordinal20
> 35: [unknown location] DSA_Sort
> 36: [unknown location] AddClipboardFormatListener
> 37: [unknown location] EndTask
> 38: [unknown location] EndTask
> 39: [unknown location] EndTask
> 40: [unknown location] CallWindowProcW
> 41: [unknown location] DefSubclassProc
> 42: [unknown location] DefSubclassProc
> 43: [unknown location] DefSubclassProc
> 44: [unknown location] AddClipboardFormatListener
> 45: [unknown location] EndTask
> 46: [unknown location] EndTask
> 47: [unknown location] EndTask
> 48: [unknown location] CallWindowProcW
> 49: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:2210) wxWindow::MSWDefWindowProc
> 50: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:3530) wxWindow::MSWWindowProc
> 51: (f:\programming\libs\wxwidgets-3.1.0\src\msw\listctrl.cpp:3077) wxListCtrl::MSWWindowProc
> 52: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:2668) wxWndProc
> 53: [unknown location] AddClipboardFormatListener
> 54: [unknown location] EndTask
> 55: [unknown location] EndTask
> 56: [unknown location] DispatchMessageW
> 57: [unknown location] IsDialogMessageW
> 58: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:2532) wxWindow::MSWSafeIsDialogMessage
> 59: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:2416) wxWindow::MSWProcessMessage
> 60: (f:\programming\libs\wxwidgets-3.1.0\src\msw\evtloop.cpp:145) wxGUIEventLoop::PreProcessMessage
> 61: (f:\programming\libs\wxwidgets-3.1.0\src\msw\evtloop.cpp:163) wxGUIEventLoop::ProcessMessage
> 62: (f:\programming\libs\wxwidgets-3.1.0\src\msw\evtloop.cpp:229) wxGUIEventLoop::Dispatch
> 63: (f:\programming\libs\wxwidgets-3.1.0\src\common\evtloopcmn.cpp:233) wxEventLoopManual::ProcessEvents
> 64: (f:\programming\libs\wxwidgets-3.1.0\src\common\evtloopcmn.cpp:273) wxEventLoopManual::DoRun
> 65: (f:\programming\libs\wxwidgets-3.1.0\src\common\evtloopcmn.cpp:76) wxEventLoopBase::Run
> 66: (f:\programming\libs\wxwidgets-3.1.0\src\common\appbase.cpp:380) wxAppConsoleBase::MainLoop
> 67: (f:\programming\libs\wxwidgets-3.1.0\src\common\init.cpp:503) wxEntryReal
> 68: (f:\programming\libs\wxwidgets-3.1.0\src\msw\main.cpp:181) wxEntry
> 69: (f:\programming\libs\wxwidgets-3.1.0\src\msw\main.cpp:289) wxEntry
> 70: (c:\dev\slade-build\src\application\sladewxapp.cpp:476) WinMain
> 71: (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253) __scrt_common_main_seh
> 72: [unknown location] BaseThreadInitThunk
> 73: [unknown location] RtlGetAppContainerNamedObjectPath
> 74: [unknown location] RtlGetAppContainerNamedObjectPath
> 
> Last Log Messages:
> Loading colour configuration
> Loading base resource
> Base resource loaded
> Loading game configurations
> Read game configuration "doom2" + "zdoom"
> SLADE Initialisation OK
>Checking for updates...
>Latest stable release: v3115 "3.1.1.5"
>Latest beta release: v3120_b5 "3.1.2 Beta 5"
>Already up-to-date

**Comment by sirjuddington** [comment]
Looks like FreeImage doesn't like the png for some reason. I can fix the crash but you still won't be able to view it in SLADE.

**Comment by Xane123** [comment]
That'll be fine. I'm guessing if I save the image in another program before importing it, FreeImage would be more likely to accept it but I don't know what Substance Designer's doing with its images.
