### ISSUE TITLE
Map editor renderer not working properly

### ISSUE THREAD

**Issue by TheRektafire** [sirjuddington/SLADE#872]
**SLADE Version**: (3.1.2 beta 5)
**Operating System**: (Windows 7 64 bit)

**Issue Details**:
I recently downloaded Slade 3 in the hopes that I could make some UDMF maps (I can't use GZDoom Builder at the moment and Eureka doesn't support them so Slade is my only option for the time being). However the map editor renderer appears to be broken, at least on the system I am using. The textures are not rendered properly, sprites aren't displayed correctly, and text is displayed as orange or white squares. Here is an example screenshot of this issue

![untitled](https://user-images.githubusercontent.com/11543824/39789112-8fd73998-52f3-11e8-8425-16e6d3832d7d.png)

The console reveals a "wxWebView Error: INET_E_UNKNOWN_PROTOCOL" and "Error: OLE Automation error in Navigate: error code 0" error, and the slade3.log file reveals an "wxWebView Error: INET_E_RESOURCE_NOT_FOUND"

**Full console dump:**

`Windows Version: 6.1
SLADE - It's a Doom Editor
Version 3.1.2 Beta 5
Written by Simon Judd, 2008-2018
Compiled with wxWidgets 3.1.0 and SFML 2.4.2
--------------------------------
Loading configuration
Loading resources
Loading icons
Loading entry types
Loading text languages
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
Read game configuration "doom2" + "zdoom"
SLADE Initialisation OK
Checking for updates...
Latest stable release: v3115 "3.1.1.5"
Latest beta release: v3120_b5 "3.1.2 Beta 5"
Already up-to-date
Read game configuration "doom2" + "zdoom"
Read game configuration "doom2" + "zdoom"
Initialising OpenGL...
OpenGL Version: 3.1
Max Texture Size: 8192x8192
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening map map01
wxWebView Error: INET_E_UNKNOWN_PROTOCOL
Error: OLE Automation error in Navigate: error code 0``

**full slade3.log dump:**

`21:26:57: SLADE - It's a Doom Editor
21:26:57: Version 3.1.2 Beta 5
21:26:57: Written by Simon Judd, 2008-2018
21:26:57: Compiled with wxWidgets 3.1.0 and SFML 2.4.2
21:26:57: --------------------------------
21:26:57: Loading configuration
21:26:57: Loading resources
21:26:58: Loading icons
21:26:58: Loading entry types
21:26:58: Loading text languages
21:26:58: Loading text style sets
21:26:58: Loading colour configuration
21:26:58: Loading base resource
21:26:58: Base resource loaded
21:26:58: Loading game configurations
21:26:58: Read game configuration "doom2" + "zdoom"
21:26:58: SLADE Initialisation OK
21:26:58: Checking for updates...
21:26:58: Latest stable release: v3115 "3.1.1.5"
21:26:58: Latest beta release: v3120_b5 "3.1.2 Beta 5"
21:26:58: Already up-to-date
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 3.1 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
21:27:03: Read game configuration "doom2" + "zdoom"
21:27:04: Read game configuration "doom2" + "zdoom"
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 3.1 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
21:27:04: Initialising OpenGL...
21:27:04: OpenGL Version: 3.1
21:27:04: Max Texture Size: 8192x8192
21:27:04: Checking extensions...
21:27:04: Vertex Buffer Objects supported
21:27:04: Point Sprites supported
21:27:04: Framebuffer Objects supported
21:27:04: Opening map map01
21:27:04: wxWebView Error: INET_E_UNKNOWN_PROTOCOL
21:27:04: Error: OLE Automation error in Navigate: error code 0
21:29:01: wxWebView Error: INET_E_RESOURCE_NOT_FOUND
21:29:01: wxWebView Error: INET_E_RESOURCE_NOT_FOUND
`

**Comment by sirjuddington** [comment]
I'm not sure why this was labeled as 'awaiting info' but I am going to close the issue, if it is still happening for you try updating your video drivers
