### ISSUE TITLE
Map editor intermittently freezing

### ISSUE THREAD

**Issue by kaadmy** [sirjuddington/SLADE#876]
**SLADE Version**: (3.1.2-beta5)
**Operating System**: Arch Linux (Installed from AUR)

**Issue Details**:

After using the map editor for 20+ minutes it starts to hang and lag every 1-2 seconds and gets worse over time.

The CPU load also increases considerably, going from ~40% to 90%+ during that time.

**Comment by sirjuddington** [comment]
Hopefully this one is fixed with #912
