### ISSUE TITLE
Broken tracker music playback

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#877]
**SLADE Version**: 3.1.2 beta 5 (c8e96d0)
**Operating System**: Linux

**Issue Details**:
Playing back any tracker format music in the editor just results in ear-grating loud screeching.

**Comment by sirjuddington** [comment]
Does 967ba17 fix this?

**Comment by OrdinaryMagician** [comment]
Yup, it does.
