### ISSUE TITLE
Adding Offsets to Indexed PNG Can Break Transparency

### ISSUE THREAD

**Issue by TheKins** [sirjuddington/SLADE#880]
**SLADE Version**: (3.1.2 Beta 5)
**Operating System**: (Windows 10)

**Issue Details**:
Applying offsets to a indexed PNG-based graphics lump can result in the transparency values becoming messed up.

**Reproduction Steps:**
1.) Download this PNG. I dunno if GitHub is gonna do weird processing stuff to it. If it does, you can grab the original file [here](http://thekinsie.com/crap/water-pistol-hud-sprite_8bit.png).
![water-pistol-hud-sprite_8bit](https://user-images.githubusercontent.com/2977232/40618425-cf6c50d4-62d4-11e8-9f94-355c92d6655b.png)

2.) Apply offsets to it.

3.) Switch your focus to another entry, so that it's unloaded.

4.) Switch back to the PNG. You'll find it now looks something like this.
![water-pistol-hud-sprite_8bit - copy](https://user-images.githubusercontent.com/2977232/40618470-ebad1472-62d4-11e8-96e1-ed350b188111.png)

**Notes:**
From NeuralStunner when I last bought this up:
> I've had this problem before whenever I used a tRNS that contains less than 256 entries. Even if the only entry is for index 0 (as I sometimes do with grayscale) it gets un-transparent. I wonder if it's actually deciding that the chunk is invalid and rewriting it incorrectly. (I have a suspicion that this is FreeImage's doing.)

**Comment by sirjuddington** [comment]
Ok, it looks like this one was fixed since beta 5 (at least it is fixed in the latest dev build (http://slade.mancubus.net/dev/build/), try that build and see if it still happens for you
