### ISSUE TITLE
Map preview doesn't render things

### ISSUE THREAD

**Issue by Xymph** [sirjuddington/SLADE#881]
**SLADE Version**: 3.1.1.5 and 3.1.2 beta 5
**Operating System**: Windows 7

**Issue Details**:
When selecting a map marker in the lump browser, the map layout is normally previewed in linedefs and light-grey thing dots. On one WAD/map the dots are missing.

**Reproduction Steps**:
Load [this WAD](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/3hafinal) and select MAP02: no dots are rendered even though the map does contain things.

**Comment by Gaerzi** [comment]
Seems like the THINGS lump is malformed and therefore fails identification.
`15:38:26: > type map_things
15:38:26: Identifying as Map Things
15:38:26: THINGS: Identification failed`

**Comment by Gaerzi** [comment]
We still need to find out why the identification fails with that lump.
