### ISSUE TITLE
OGG crash

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#883]
This issue with playback of some OGG files, [reported on ZDoom](https://forum.zdoom.org/viewtopic.php?f=124&t=60902) seems to be from within SFML.

A test file can be found [here](https://drive.google.com/open?id=14QoYf7JTmeGTe_9Kyf_hkuqIB4k6gi4X).

**Comment by sirjuddington** [comment]
Yeah this one is an issue in sfml that I'm really surprised hasn't been fixed yet, it's been around for a long time now

**Comment by sirjuddington** [comment]
Closing, duplicate of #705
