### ISSUE TITLE
Scaling problems

### ISSUE THREAD

**Issue by 333333h1t** [sirjuddington/SLADE#900]
**SLADE Version**: (v3.1.2 Beta 5) (gtk3 branch)
**Operating System**: Fedora 28

**Issue Details**:
First of all I'm using the gtk3 branch because the master did not compile me.
https://github.com/sirjuddington/SLADE/issues/840

What happens is that the part where the map is viewed does not change to the same size as the window, so it leaves parts in black.

Also 3d mode is unusable, it stays spinning.

![screenshot](https://user-images.githubusercontent.com/39890228/43047739-4c88b410-8db2-11e8-86f8-713d38be7ae7.png)

**Comment by sirjuddington** [comment]
Does this still happen for you? If so, what version of wxWidgets are you building it with?

**Comment by sirjuddington** [comment]
Going to close this since it's pretty old now, feel free to reopen if it still happens
