### ISSUE TITLE
Is there a way to quickly deselect things? 

### ISSUE THREAD

**Issue by jordanforbes** [sirjuddington/SLADE#901]
**SLADE Version**: (3.1.1.5)
**Operating System**: OSX

**Issue Details**:

when I'm in 3D mode sometimes I'll select a sector and extrude it, which puts it out of the way of my mouse. Is there a hotkey I can hit that will quickly deselect everything? I've looked throughout the interface area in the settings and haven't found anything like that but maybe I'm just missing it. It would make things a little easier.

**Comment by sirjuddington** [comment]
There is a 'clear selection' keybind for 3d mode, defaults to `C`
