### ISSUE TITLE
Map editor panels freeze during editing

### ISSUE THREAD

**Issue by JadingTsunami** [sirjuddington/SLADE#909]
**SLADE Version**: v3.1.2 Beta 5
**Operating System**: OSX (macOS High Sierra)

**Issue Details**:
After using the map editor for a little while, all the panels freeze until SLADE is restarted.

This is a visual glitch -- by hovering over the little "x" to close the panel, the panel will refresh, but then and only then. Otherwise, visually the panel appears frozen.

This is a 100% reproducible issue when using the map editor; it's only a matter of time until it happens.

NOTE: I have auto-apply enabled.

**Comment by sirjuddington** [comment]
Closing this one as well - if it still happens with latest it can be reopened
