### ISSUE TITLE
Latest build misses key events on MacOS

### ISSUE THREAD

**Issue by JadingTsunami** [sirjuddington/SLADE#910]
**SLADE Version**: Latest (aeffde54bec6aeef7cd62d7f7207804307b43ea7)
**Operating System**: OSX (macOS High Sierra)

**Issue Details**:
MacOS misses key events in the latest build (e.g., escape, arrow keys).

Adding a bind for wxEVT_CHAR_HOOK resolves this.

e.g.,

MapEditor/UI/MapCanvas.cpp:147:	Bind(wxEVT_CHAR_HOOK, &MapCanvas::onKeyDown, this);

**Comment by sirjuddington** [comment]
Does this one still happen with the latest macos build updates? If so feel free to reopen it
