### ISSUE TITLE
Slade Crashes in Seconds before i can do anything

### ISSUE THREAD

**Issue by LanternJoe** [sirjuddington/SLADE#911]
**SLADE Version**: (v3.1.2 Beta 5)
**Operating System**: (Windows 10)

**Issue Details**:
Everytime i Open Slade from the Rar., It Immediately Crashes after a few seconds.

**Comment by LanternJoe** [comment]
It doesn't even show anything after crashing, it just closes out.

**Comment by Gaerzi** [comment]
What do you mean by "from the Rar"? SLADE isn't distributed in RAR files.

But regardless of format, you cannot run it from inside an archive. It needs to be able to access its support data (slade.pk3), and it requires a few third-party libraries to be available. So you need to extract all the files in a directory, and then run SLADE from there. Not from a zip or rar or whatever.

**Comment by DoomKrawa** [comment]
If your installation of Slade3 is correct, but it keeps crashing immediately, you can try to reset your settings (but be careful):
- Enter Explorer link: %appdata%
- It leads you to C:\Users\\\<your user name>\AppData\Roaming
- All settings of Slade3 are in directory SLADE3
- Rename that directory (so you have a safety copy of it) and start Slade3
- Slade3 starts now with default settings and creates default SLADE3 directory

**Comment by sirjuddington** [comment]
Closing this, if it still happens in the latest version feel free to reopen the issue
