### ISSUE TITLE
Bad ZScript code can cause parser crash

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#914]
See [https://forum.zdoom.org/viewtopic.php?p=1075665#p1075665](https://forum.zdoom.org/viewtopic.php?p=1075665#p1075665).

**Comment by Gaerzi** [comment]
The pastebin was set to delete itself after a day, so to be able to investigate it at leisure, here's a copy that won't expire.
[https://pastebin.com/Aq4apGP4](https://pastebin.com/Aq4apGP4)

**Comment by sirjuddington** [comment]
This was an issue in 3.1.2 beta 5 but is fixed in master
