### ISSUE TITLE
SLADE fails to recognize multiple comment types.

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#915]
SLADE fails to recognize comments in a Lua script correctly. It recognizes // as a comment line, and not --. Same with comment blocks, /* and */ are recgonized, but not --[[ and ]].

**Comment by crisisinaptica** [comment]
I've just built Slade from master on Linux.

Here it recognizes the lua single line comment `--`, but the multiline `--[[ ]]` does not work.

**Comment by SteelTitanium** [comment]
Sorry for having to reopen this, but finally got around to testing it, as of dev build 2260844 that was uploaded to the site., the issue isn't fixed and it still has issues with certain comment types.
