### ISSUE TITLE
[Feature request] Map Editor 2D Sector / Line / Points Rotation

### ISSUE THREAD

**Issue by franksouza183** [sirjuddington/SLADE#916]
Well, as the title says, it would be interesting and extremely useful to rotate lines, sectors and points (when more than 1 is selected, of course), perhaps using the same logic when setting the direction of Things with the "D" key.

**Comment by crisisinaptica** [comment]
Select a sector, press E (Shortcut to edit objects), while pressing ctrl, grab to rotate.

**Comment by franksouza183** [comment]
Thank you! Is this information in the documentation / wiki? I searched a lot and did not find anything related, nor in the keybindings page.

**Comment by crisisinaptica** [comment]
Hey @franksouza183 , that operation is in the toolbar.

![rotate](https://user-images.githubusercontent.com/21117400/47111632-56ca8980-d254-11e8-9765-2fb303002aee.jpg)

I recommend you to also check the keyboard shortcuts for the editor. There are some functions only accessible by key presses. There is more than meets the eye.
