### ISSUE TITLE
SLADE has a tendency to crash when saving while map editor is open

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#918]
**SLADE Version**: Since commit 6029370
**Operating System**: Linux

**Issue Details**:
Saving while the map editor is open has a high chance of causing SLADE to crash. The crash dialog is completely blank (doesn't draw), so I can't give a trace.

**Comment by crisisinaptica** [comment]
@OrdinaryMagician Do you mean saving the archive that the map is in, or saving the map itself?
Can you reproduce #929?

**Comment by OrdinaryMagician** [comment]
Any kind of saving while the map editor is open.

I also can see that bug if it does NOT crash.
