### ISSUE TITLE
Music Systems (probably) shut down

### ISSUE THREAD

**Issue by NARbluebear** [sirjuddington/SLADE#932]
**SLADE Version**: v3.1.2 Beta 5
**Operating System**: Windows 7

**Issue Details**:
I am trying to insert music into a custom wad, but whenever I do so, it seems as if the music does not play. I have double checked, and it seemed to occur with MIDIs first, then OGGs, which is a huge problem because what I am doing requires OGGs. No, it does not crash, but I just can't play back music. In case you are wondering, I am using this for a custom **[Sonic Robo Blast 2](https://srb2.org)** stage with music. For example, I try to play O_MAPAKM.ogg (corresponds to a level not yet implemented, but plays a MIDI of Europe's "The Final Countdown"), nothing happens. And as of the time of writing this, I am confirming that it is not my earbuds due to the fact that I can hear the music I want to import playing from an open tab.

**Comment by sirjuddington** [comment]
Closing this issue since it's fairly old now - does it still happen in 3.2.0 beta? If so feel free to reopen the issue
