### ISSUE TITLE
64 Grid disappears when opening thing properties

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#941]
**SLADE Version**: v3.1.2 Beta 5
**Operating System**: Linux

**Issue Details**:
Whenever I open the properties of a thing in the map editor, the 64 grid simply disappears. It fixes itself if I go into 3D view and back, though.

**Comment by crisisinaptica** [comment]
I can't reproduce this in current master.

**Comment by OrdinaryMagician** [comment]
Ah, I've updated and it's no longer happening.
