### ISSUE TITLE
Eevee's 3dFloor branch building on current master.

### ISSUE THREAD

**Issue by crisisinaptica** [sirjuddington/SLADE#955]
I have merged all the commits of @eevee 's   [render-3d-floor branch](https://github.com/eevee/SLADE/tree/render-3d-floors) to a [new branch based on current master](https://github.com/crisisinaptica/SLADE/tree/eevee_3d_floors).

I have cherry picked commit by commit, integrating the old patches over the new source.
After each merge I tried to build SLADE.
If it failed, I went over the code fixing things here and there to to make it play nice with the current code base. Then tried again and checked if the commit makes what's supposed to do, just a quick look, I did not test extensively.

The majority of these minor changes have been made amending the original commit.
If you encounter something that does not work, blame me and not eevee.
For the most part everything looks OK, but It's very possible I have messed something along the way... :hurtrealbad:

I was curious to see If this could be made to work again, after building eevee's old branch and seeing how well his efforts were going.

It would be great if eevee could finish this one some day. :pray: 

I don't think I'm the best option to work on this (I have no clue about opengl or graphics programming) but I hope that having this code working again can contribute somehow to finish this feature.

I'll try to rebase the branch onto master frequently.

![3dfloors master_opt](https://user-images.githubusercontent.com/21117400/48647998-0169cf80-e9ee-11e8-82ea-543d02675daf.jpg)

**Comment by OrdinaryMagician** [comment]
Actually, @usernameak maintains a fork of SLADE that has all of this merged in, plus many fixes.

**Comment by crisisinaptica** [comment]
Damn, that's cool.
Didn't know! Thanks for letting me know.
So, a PR to include all these change to SLADE is something bound to happen?
I would like that to happen, let me know if there's something I can help with.

**Comment by crisisinaptica** [comment]
I clicked too far to the left because of excitement.

**Comment by crisisinaptica** [comment]
After taking a close look on this, I think the code is high level enough for me to manage right now (The words 'renderer' and '3d Window' made me think of dealing with opengl...)
I've added to my branch some of @usernameak 's improvements, and some fixes I have made myself.
I'm going to pound this one until it's done & polished.
