### ISSUE TITLE
Cannot modify images

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#958]
**SLADE Version**: latest
**Operating System**: Linux

**Issue Details**:
Converting an image, doing any sort of change whatsoever and then trying to save gives me a dialog with the message "Cannot save changes to image: Writing unsupported for format".

**Comment by OrdinaryMagician** [comment]
New discovery: I can actually modify images fine, but once I try to convert a Doom patch to PNG, any and all modifications to any image anywhere will fail to save.

**Comment by Talon1024** [comment]
Likewise, I cannot convert PNGs to Doom graphics.

**Comment by Talon1024** [comment]
It's fixed now. Thanks!
