### ISSUE TITLE
Draw pixel tool not working

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#975]
I remember during one of the betas, it used to work correctly. But on latest stable, it no longer works and draws anything.

**Comment by sirjuddington** [comment]
Hmm, are you on windows or linux? I don't think it has ever worked for me on linux (need to look at that) but it's working fine for me on windows currently

**Comment by SteelTitanium** [comment]
Windows

**Comment by crisisinaptica** [comment]
Does not work properly on Linux.

**Comment by DoomKrawa** [comment]
By default there is no brush selected. Could that be the problem?

**Comment by sirjuddington** [comment]
This will be fixed in the next beta release (see https://github.com/sirjuddington/SLADE/commit/94e11ff7077883d92af6681fb716cb615fa2d02d)
