### ISSUE TITLE
Allow to override wx-config name

### ISSUE THREAD

**Issue by danfe** [sirjuddington/SLADE#976]
**SLADE Version**: (3.1.2)
**Operating System**: (Linux/FreeBSD)

**Issue Details**:
In `src/CMakeLists.txt`, it is assumed that `wx-config` is always called like that, while it is not necessarily true (e.g., it can contain version).  Consider this little patch, which would allow to pass correct name on the command line if needed:
```patch
--- src/CMakeLists.txt.orig
+++ src/CMakeLists.txt
@@ -13,7 +13,9 @@ if (WITH_WXPATH)
 endif()
 unset(WITH_WXPATH CACHE)

+if (NOT CL_WX_CONFIG)
 set( CL_WX_CONFIG wx-config )
+endif()
```

**Comment by Johnnynator** [comment]
https://github.com/sirjuddington/SLADE/commit/16765263204d8b93f414f0b06580700d503067c8
You can overwrite `wxWidgets_CONFIG_EXECUTABLE` which will also be picked up by the wxWidgets cmake script.

**Comment by danfe** [comment]
Thanks, I've applied the patch and my custom `wxWidgets_CONFIG_EXECUTABLE` is picked up correctly.
