### ISSUE TITLE
Map Checks window can be initially unusable when floating

### ISSUE THREAD

**Issue by Jjp137** [sirjuddington/SLADE#978]
**SLADE Version**: 3.1.2
**Operating System**: Linux

**Issue Details**:
For some reason, when floating, the UI of the Map Checks window initially looks like this:

![map checks](https://user-images.githubusercontent.com/1811645/49492289-889bad80-f80c-11e8-9efa-8e0fddcf19a6.png)

This is the case with both GTK2 and GTK3. The above screenshot uses GTK3. Resizing the window does not change the size of the UI elements.

However, once the Map Checks window has been dragged to the side in order to turn it into a sidebar or top/bottom pane and then turned into a floating window again, it works properly until SLADE is closed. If the Map Checks window was previously closed while floating when SLADE is closed, the problem will occur again the next time the Map Checks window is opened. No issues occur if the Map Checks window was attached to one side of the map editor window when SLADE is closed.

**Comment by sirjuddington** [comment]
This should be fixed with 0c4a4b2
