### ISSUE TITLE
Wrong endianness handling for FreeBSD

### ISSUE THREAD

**Issue by danfe** [sirjuddington/SLADE#988]
Just as for OpenBSD, it is sufficient to simply `#include <sys/endian.h>` which already defines all needed macros and/or functions.  SLADE won't build as is on FreeBSD right now, because of this line:
https://github.com/sirjuddington/SLADE/blob/beab73bdec74bf2dcca52882fdaff048dd9fc249/src/External/zreaders/portable_endian.h#L55
I'm not sure about NetBSD and DragonFly, didn't bother to check or test (sorry), but at least FreeBSD should be removed from this list and put together with OpenBSD check here:
https://github.com/sirjuddington/SLADE/blob/beab73bdec74bf2dcca52882fdaff048dd9fc249/src/External/zreaders/portable_endian.h#L51

**Comment by michaelbaeuerle** [comment]
It does not work for NetBSD too (tested with version 9).
Looks like at least FreeBSD and NetBSD should be treated like OpenBSD here (removed from line 55 and added to line 51).

I don't use DragonflyBSD, but recent versions seem to have the header "sys/endian.h" (with the required macros inside) too:
[https://gitweb.dragonflybsd.org/dragonfly.git/blob_plain/HEAD:/sys/sys/endian.h]

**Comment by danfe** [comment]
> It does not work for NetBSD too (tested with version 9).

Hmm, I really forgot that I've filed this issue back in 2018, so I didn't close it when #1263 had been merged.  I guess I'll leave open in case Simon would want to handle NetBSD case.
