### ISSUE TITLE
Sounds/Music don't preview at all

### ISSUE THREAD

**Issue by DarkPulse** [sirjuddington/SLADE#990]
**SLADE Version**: 3.1.3
**Operating System**: Windows

**Issue Details**:
No matter what I do, music and sounds do not play in SLADE at all. They used to, but stopped at some point - don't know when.

I've got a soundfont properly set up, but even sound effects won't play. All the DLLs are in the right folder (along SLADE.exe), and I even tried the installer version - no luck.

Tried deleting the config so it could create a clean one. No luck.

Logfile/console shows no obvious sound errors.

The only thing I can think of - and this is a hell of a stretch - is that I'm using a USB headset, but somehow I doubt that that's the problem. Literally everything else on my PC plays sound just fine.

**Comment by DarkPulse** [comment]
**UPDATE:** At Gez's suggestion, I tried older versions of SLADE. 3.1.2 works fine for previewing sound, so some change between then and 3.1.3 broke it for me.

**Comment by sirjuddington** [comment]
Did you mean you tried 3.1.2 (release) or 3.1.2 beta 5? There isn't any difference in audio or libraries used between 3.1.2 (release) and 3.1.3.

**Comment by DarkPulse** [comment]
The Help>About menu is reporting 3.1.2. I'm assuming 3.1.2 (release) since the date on its EXE is November 26th, 2018.

**Comment by sirjuddington** [comment]
Ok, that is really strange then. What if you keep all the dll files from 3.1.2, install 3.1.3 and put the dlls there from 3.1.2?

**Comment by DarkPulse** [comment]
Seemed to produce no effect - stuff was still silent. That said, only three of the DLLs got replaced:

- FreeImage.dll
- openal32.dll
- libfluidsynth.dll

The OpenAL and libfluidsynth DLLs were the same (right down to the hash), so it's definitely not a corrupt DLL. (So is FreeImage, but that has nothing to do with sound.)

libsndfile-1.dll wasn't present in the 3.1.2 install, or at least, not in the 7z I got of it about a month ago.

**Comment by sirjuddington** [comment]
libsndfile-1.dll shouldn't be there I don't think, what happens with/without it?

**Comment by DarkPulse** [comment]
Nothing. Sounds still don't play.

And for what it's worth, [the SLADE documentation still claims it needs it.](http://slade.mancubus.net/index.php?page=wiki&wikipage=Installation)

**Comment by sirjuddington** [comment]
Unfortunately I have no idea what could be going on. One last thing to try - if you try to play an ogg/audio file, exit SLADE, then open the `slade3.log` file (should be in `%APPDATA%\SLADE3`), are there any error messages in there from SFML?

**Comment by DarkPulse** [comment]
Nothing that I can see.

> 19:16:32: SLADE - It's a Doom Editor
19:16:32: Version 3.1.3
19:16:32: Written by Simon Judd, 2008-2018
19:16:32: Compiled with wxWidgets 3.1.1 and SFML 2.5.1
19:16:32: --------------------------------
19:16:32: Loading configuration
19:16:32: Loading resources
19:16:32: Loading icons
19:16:33: Loading entry types
19:16:33: Loading text languages
19:16:33: Loading text style sets
19:16:33: Loading colour configuration
19:16:33: Loading base resource
19:16:34: Base resource loaded
19:16:34: Loading game configurations
19:16:34: Read game configuration "doom2" + ""
19:16:34: SLADE Initialisation OK
19:16:34: Checking for updates...
19:16:34: Latest stable release: v3.1.3
19:16:34: Latest beta release: v3.1.2 beta 5
19:16:34: Already up-to-date
19:16:43: Opening archive C:/GZDoom/PWADs/kickdm2.wad
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 4.6 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 4.6 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 4.6 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 4.6 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
19:16:46: Opening took 2795 ms
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 4.6 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
19:16:58: wxWebView Error: INET_E_RESOURCE_NOT_FOUND
19:16:58: wxWebView Error: INET_E_RESOURCE_NOT_FOUND

**Comment by DarkPulse** [comment]
Of note, this seems to still be present as of 3.1.7.

**Comment by DarkPulse** [comment]
This is fixed as of 3.2.0 Beta 2. Closing accordingly.
