### ISSUE TITLE
All button icon/images missing

### ISSUE THREAD

**Issue by WMcb** [sirjuddington/SLADE#996]
**SLADE Version**: (3.1.4)
**Operating System**: (Windows 10 64bit)

**Issue Details**:
Just updated, all button icons missing, they still work, but I wouldn't know they were there by looks alone.
![bandicam 2018-12-27 03-41-43-812](https://user-images.githubusercontent.com/46187711/50473132-c7470280-0989-11e9-979f-2fffa975f63b.png)

**Comment by Gaerzi** [comment]
Typically caused by SLADE not having write access to its temp directory. Check your console log (Ctrl-2).
